- etl/command.py
This change refactors the command module into Step classes which are able to determine if they are "dirty", i.e. if they are missing or if their ingredients have changed since they were last built.
The dirty checks are all based on checksums, rather than timestamps, so they only care about consistency.
The checksums for data steps include the Python or Jupyter notebook files containing the code to generate the step, so the step will rebuild if those files change.
Skipped steps are still listed in the ETL, but they are marked as "cached".
> feat: Only rebuild datasets that have changed

- .github/workflows/python-package.yml
- etl/frames.py
- tests/test_frames.py
Today, our largest feather file is 269MB, and consists only of integers and floats, both 64 bits wide by default.
This PR improves packing of integers and floats into smaller types, e.g. `int8` and `float32`, making them much more compact on disk.
> enhance: Repack dataframes into smaller types

- etl/steps/open_numbers.py
Open Numbers ships large datasets in file fragments, whereas we combine them into single megafiles.
Our previous combination method was to load frames, then join them in memory. But this was quite expensive and slow.
This change instead concatenates fragments into a CSV megafile, then loads that megafile directly. This approach is much faster. It's not yet clear whether it also uses less memory.
> enhance: Speed up large open numbers dataset loading

- etl/steps/data/garden/explorers/2021/food_explorer.ipynb
This PR fixes several bugs when it comes to region data:
- It converts _per-capita_ metrics into absolute metrics: `food_available_for_consumption__fat_g_per_day_per_capita`, `food_available_for_consumption__kcal_per_day_per_capita`, `food_available_for_consumption__kg_per_capita_per_year` and `food_available_for_consumption__protein_g_per_day_per_capita`
- Re-calculates metric `yield__tonnes_per_ha` for regions as `production__tonnes/area_harvested__ha` (previous computed values did not make sense)
- Metric `yield__kg_per_animal` left blank for regions.
- Fix of other minor bugs
Major changes happened in section 9. of the notebook.
> fix(food_explorer): region metrics

- etl/steps/data/garden/explorers/2021/food_explorer.ipynb
- etl/steps/data/garden/explorers/2021/food_explorer.items.std.csv
- etl/steps/data/garden/faostat/2021-04-09/faostat_fbsc.ipynb
- etl/steps/data/meadow/faostat/2017-12-11/faostat_fbsh.ipynb
_UPDATES_
- Add new products: 
- `Total`: Only available for FBSC metrics. 
- `Potatoes`: Include QCL metrics (FBSC were already included).
_FIXES_
- `NaN` values for regions: For some years, all countries within a region (continent, income group) have missing data for some metrics. In such cases, the corresponding regions should report `NaN` (missing values), instead of `0` (currently)
- Temporary fix for FBSC product names (new metadata release was published by FAO)*
---
*Currently, metadata coming from FAO API is being ingested at the _meadow_ stage and not in Walden. This prevents us from having a complete snapshot of the source data. Also, it may lead to _out of sync_ scenarios where data and metadata are not aligned. In the near future, we want to move this (API calls) to Walden …
> FIX: Fix data reports for regions, temporary fix FBSC and add new products

- etl/steps/data/garden/explorers/2021/food_explorer.elements.std.csv
- etl/steps/data/garden/explorers/2021/food_explorer.ipynb
- etl/steps/data/garden/explorers/2021/food_explorer.items.std.csv
- Add FBSC's metrics for `Meat, beef`, `Fish and seafood`
- Remove products `Meat, other birds`, `Meat, cattle`, `Meat, other camelids`, `Meat, other rodents`
- Redefine product `Chillies and peppers`
- Add metric `Producing or slaughtered animals`
- Rename metric `Waste -> Waste in supply chain`
- Remove values when `food_available_for_consumption__fat_g_per_day` shows irregularities
> Fix(food_explorer): Team feedback

- .pre-commit-config.yaml
Fix CI and make sure `make format` runs as a pre-commit hook to avoid these styling bugs in the future. (linting and isort could be added as a pre-commit hook too)
> style(black): format code as pre-commit hook

- etl/steps/__init__.py
Resolves #95.
When you decide if data from Walden has changed, consider not only the data file but the metadata itself. This way, if you change the dataset name or description, it will ripple through the ETL and be copied as necessary to downstream datasets.
> fix: include walden metadata in data freshness check

- etl/harmonize.py
I changed the displayed message in `harmonize`, since I found "(n) skip (s) suggest" sometimes a bit confusing.
> style(harmonize): correct typos and change displayed messages

- etl/steps/data/garden/owid/latest/key_indicators/table_land_area.py
- etl/steps/data/garden/owid/latest/key_indicators/table_population.py
- etl/steps/data/garden/owid/latest/population_density/__init__.py
I wrote a simple script for "backporting" metadata from grapher to ETL structure. First I find a chart like https://ourworldindata.org/grapher/population-density and then by its slug find variable, dataset and source. Then I structure them to fit `etl` Dataset - Table - Variable framework.
As you can see, grapher is not very consistent and for instance sources are all over the place. Couple of questions / ideas:
1. `Table` does not have `sources` field, but to me it seems like a better place than keeping sources on variable (maybe we could have sources for all `Dataset` - `Table` - `Variable` and always choose a common denominator)
2. Perhaps `annotations.yaml` would be a better place for metadata? [like this one](https://github.com/owid/etl/blob/master/etl/steps/grapher/who/2021-07-01/ann …
> enhance(population): add metadata to population, land area and population density

- dag.yml
- etl/grapher_helpers.py
- etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.meta.yml
- etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.py
- etl/steps/grapher/ggdc/2020-10-01/ggdc_maddison.py
Import Maddison dataset from ETL into grapher. This was done in way to have metadata parity with the old version of Maddison. Here's the [old one](https://staging.owid.cloud/admin/datasets/5219) on staging vs the [new one](https://staging.owid.cloud/admin/datasets/5566) for comparison.
There's one "trick" where we map `Dataset.description` to `Source[0].description` to make it work with the grapher model. It's explicit in the code, but we may decide to make it implicit. Metadata is loaded from YAML file using helper methods, but that one might be also improved in the future.
(There's still [one part](https://github.com/owid/etl/pull/144/files#diff-066f8606fbd0d1ebf10c166179474f38f8c508d55ecdb232b1c81b9530fa13f5R28) I need to improve, but that shouldn't prevent review)
> data(maddison): Production export of the Maddison dataset data

- etl/command.py
- etl/steps/__init__.py
- tests/test_steps.py
After computing the subgraph, include their dependencies as well. This needed a couple of performance improvements to make this reasonably fast - caching walden catalog and checking steps dirtiness in parallel (requests from `GithubStep` were slowing it down).
> enhance(dag): include all dependencies of the planned subgraph

- etl/db_utils.py
- etl/grapher_import.py
- etl/steps/__init__.py
- etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.meta.yml
Running `etl grapher://... --grapher` automatically creates all objects in grapher. Variables and sources are upserted to grapher by matching on their `name`. So if you rename a variable, `etl` will create a new one and leave the old one in the DB 
(with the same datasetId). We should delete old renamed variables.
Another issue is that grapher data model needs exactly one source per variable, so we need to make sure we're not inserting multiple sources per variable.
Cleanup ghost variables and sources after every `GrapherStep`. We just need to be careful not to remove variables that are already used in charts.
1. `Dataset` can also have a single source, but does it make sense to insert it grapher? AFAIK it's not used by anything (or is it?) so I don't see a point inserting it there. We …
> enhance(grapher): improve upserts to grapher, do not leave ghost variables and sources

- etl/publish.py
- etl/reindex.py
Core PR in [owid-catalog-py](https://github.com/owid/owid-catalog-py/pull/35)
Split our catalog into multiple channels to make finding garden datasets easier and more efficient. By default we only read `garden` channel which is really small (17 datasets with ~30kb index). Other channels like `open_numbers` or `backport` have much larger indexes (>MBs) and take longer time to reindex & publish.
> feature(catalog): split catalog into channels

- etl/publish.py
* md5 check should be on 32 characters, not 40
* parallelize s3 uploads to speed up open_numbers and faostat
> 177 publishing large number of tables in dataset is slow

- poetry.lock
- pyproject.toml
Upgrade datautils package to version 0.4.0, and update poetry.lock file. This version provides a faster method to map series (required when harmonizing country names).
> chore(poetry): update datautils version and dependencies

- Makefile
Currently running `make test` ends up with an error and needs to be run again to make it work
```
==> Initialising submodules
git submodule update --init
Submodule 'vendor/owid-catalog-py' (https://github.com/owid/owid-catalog-py) registered for path 'vendor/owid-catalog-py'
Submodule 'vendor/walden' (https://github.com/owid/walden) registered for path 'vendor/walden'
Cloning into '/Users/mojmir/projects/etl4/vendor/owid-catalog-py'...
Cloning into '/Users/mojmir/projects/etl4/vendor/walden'...
Submodule path 'vendor/owid-catalog-py': checked out '8801c7b19f37d0429bb05441a4961098620aec76'
Submodule path 'vendor/walden': checked out 'e8c88db79b2ac8e3f49aaa95a6802a5b4b3849f3'
touch .submodule-init
make: *** No rule to make target `vendor/owid-catalog-py/*', needed by `.venv'.  Stop.
```
I'm …
> fix(makefile): make test should work on the first run

- Makefile
- README.md
- backport/backport.py
- backport/bulk_backport.py
- dag.yml
- etl/backport_helpers.py
- etl/command.py
- etl/grapher_model.py
- etl/publish.py
- etl/steps/__init__.py
- etl/steps/data/backport/owid/latest/political_regimes.py
- etl/steps/data/backport/owid/latest/wdi_world_bank.py
- poetry.lock
- pyproject.toml
Add command `bulk_backport` that calls `backport` for backporting all datasets that are used in at least one chart and are not private to Walden. Next, flag `--backport` creates `Backport` steps for all backported datasets found in Walden. That step aligns grapher metadata with ETL metadata and yields a wide-table (~~or long-table in rare cases~~) with all columns from the backported dataset.
I've tested it on two cases - creating World Bank Indicators from backported data and for getting SDG indicators into ETL catalog.
Datasets & tables are currently named like `dataset_5438_global_health_observatory__world_health_organization__2021_12`. We have [an issue](https://github.com/owid/etl/issues/167) for making them prettier.
~~The initial plan was to convert every dataset to a wide `Table`, …
> feature(backport): Perform a once-off bulk backport of the full dataset

- backport/backport.py
- etl/backport_helpers.py
Add `entity_id` and `entity_code` to index for backported datasets. This will be useful for the API.
Alternatives are:
* keep it as column instead of having it in multiindex
* keeping the `entity_name -> entity_id` mapping in metadata
* `entity_name` as categorical variable with category codes being entity ids
Keeping it all in multiindex is probably the best though.
> enhance(backport): add entity_id and entity_code to dataframe index

- backport/backport.py
- backport/bulk_backport.py
- dag.yml
- etl/command.py
- etl/steps/__init__.py
- etl/steps/data/examples/jupytext/jupytext_example.py
- etl/steps/data/examples/private/2022-03-08/private_example.py
- etl/steps/data/examples/script/script_example.py
- etl/steps/data/examples/vs_code_cells/vs_code_cells_example.py
Previously only public datasets were backported. This PR adds support for private datasets that are uploaded without public visibility to Walden and then processed in ETL and uploaded as private to our catalog.
> feature(backport): full backport of private data

- etl/steps/__init__.py
It seems `load_dag()` does not work because sub-dag files inside `dag_files` are not found. This should solve the issue.
> fix: load dag including sub-dags

- etl/steps/__init__.py
- tests/test_steps.py
`after_run` method for labelling datasets private wasn't called for backported data, this fixes that and adds test. (Note: we didn't publish any private backported datasets since `--private` flag is not yet turned on our [analytics server](https://github.com/owid/analytics/pull/44))
> fix(backport): use correct flag for private datasets

- etl/db_utils.py
- etl/grapher_import.py
- etl/steps/__init__.py
#94 
When a dataset is loaded into grapher, write the source checksum. This allows us to compare with the checksums in ETL to determine whether grapher is out-of-date.
Prerequisite:
> Write source checksum to new db column

- etl/grapher_import.py
- etl/steps/__init__.py
#94 
With https://github.com/owid/etl/pull/208, we began writing the latest input checksum to grapher db. Now, we use that checksum to verify if the grapher db data is up-to-date, by implementing `GrapherStep#is_dirty`.
> Implement is_dirty check for GrapherStep

- etl/steps/data/explorer/owid/latest/food_explorer.py
- etl/steps/data/garden/faostat/2022-05-17/faostat_metadata.py
- etl/steps/data/garden/faostat/2022-05-17/shared.py
`tqdm` writes to stderr by default which is then displayed in our `#analytics-errors` channel as error. Make it write to stdout instead
> tqdm should write to stdout

- .env.example
The file is only required if you are doing trial exports to grapher in your local dev environment. It's designed to match .env settings in dev grapher.
> doc: add an example .env file

- README.md
- backport/backport.py
- backport/fasttrack.py
- etl/backport_helpers.py
- etl/command.py
- etl/publish.py
- etl/reindex.py
- etl/steps/__init__.py
- pyproject.toml
Fastrack script is meant to backport updated datasets as soon as possible. It listens to grapher DB for updates and when it detects a change it will:
1. Run `backport` to get the backported dataset to **local** Walden catalog (without uploading to S3)
2. Run ETL on the backported dataset
3. Publish new ETL catalog to S3
All these steps have been optimized to run in a few seconds (except of huge datasets) and make them available through [data-api](https://github.com/owid/data-api).
> feature(fasttrack): automatically trigger backport on updates in DB

- dag.yml
- etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.py
- etl/steps/data/garden/owid/latest/key_indicators/table_population.meta.yml
- etl/steps/data/garden/owid/latest/key_indicators/table_population.py
- etl/steps/data/garden/owid/latest/population_density/__init__.py
- etl/steps/data/garden/owid/latest/population_density/population_density.meta.yml
- etl/steps/grapher/ggdc/2020-10-01/ggdc_maddison.py
- etl/steps/grapher/owid/latest/population_density.py
Export population density dataset to grapher. This is not currently used in production by any other datasets, but it simplifies metadata for population with YAML files and it could be useful in the future. (And I could finally close the [original issue](https://github.com/owid/etl/issues/141))
> data(population): population to grapher

- backport/backport.py
- backport/bulk_backport.py
- backport/utils.py
If dataset is archived or deleted from DB, it will still be saved in walden index (local index) and walden S3 bucket. This PR adds `bulk_backport --prune` command that deletes those datasets. This is meant to be run from production server and commited to walden as soon as the backport finishes (so that catalog in S3 and walden commits are out-of-sync as short time as possible).
> enhance(backport): prune inactive datasets from walden

- backport/backport.py
- backport/bulk_backport.py
- backport/fasttrack.py
- backport/utils.py
- etl/grapher_model.py
Fastrack is backporting datasets only locally and does not upload them to Walden, hence the missing `owid_data_url`. Periodic backport runs need to find those datasets and upload them before commiting to Walden.
> fix(backport): fix missing owid_data_url in backported datasets

- etl/command.py
- poetry.lock
Now, `etl asdf` throws an error (since there are no matching steps), instead of saying `All datasets are up to date!`
> Raise error when no steps are found for a given input

- etl/steps/__init__.py
- etl/steps/data/examples/examples/latest/jupytext_example.py
- etl/steps/data/examples/examples/latest/notebook_example.ipynb
Previously we weren't able to import modules from the same directory as notebook (e.g. `from shared import ...`). This sets working directory correctly.
> fix(steps): run notebook with proper working directory

- etl/steps/open_numbers.py
Several open_numbers datasets are large, and importing them can take a long time when done table by table.
This PR parallelises each open_numbers dataset import, whilst leaving the overall process serial.
On a 10-core M1 Max, running `rm -f data/open_numbers; etl open_numbers`
Before: `2352.86s user 130.22s system 99% cpu 41:35.25 total`
After: `4143.78s user 554.04s system 654% cpu 11:57.23 total` (3.5x faster)
> enhance(open_numbers): parallelise table imports

- etl/steps/data/garden/bp/2022-07-14/statistical_review.py
I put back some lines that were removed from the garden step of the BP statistical review dataset. In theory they are not necessary, but in practice they are (maybe not all of them?). For example, if I don't add `table.metadata.dataset = dataset.metadata`, the `table.metadata.dataset` is incomplete, and this is needed in the grapher step, because it contains the description that appears in the SOURCES tab for a particular variable.
> fix(bp): Fix metadata in BP statistical review

- backport/bulk_backport.py
- dag.yml
- etl/steps/data/garden/sdg/latest/generate_sdg_mapping.ipynb
This problem breaks ETL and started happening after we added checksum to WDI dataset which then stopped being imported.
It's a bit of a hotfix before we [do it properly](https://github.com/owid/etl/issues/329).
> fix(sdg): backport WDI dataset that comes originally from ETL

- etl/helpers.py
- etl/run_python_step.py
- etl/steps/__init__.py
- pyproject.toml
- tests/test_helpers.py
Fixes #333
Remove the module import hacking, and instead use a separate process when running a python module.
> fix: isolate python steps by running them in a separate process

- etl/compare.py
- etl/tempcompare.py
- poetry.lock
- pyproject.toml
This PR implements the first version of a compare CLI that allows easy comparison of either arbitrary dataframes (feather, csv, parquet) or etl files (in that case against the version currently uploaded in the production catalog). Much of the logic for the diffing lives in the data-utils-py repo and is managed in this PR: https://github.com/owid/data-utils-py/pull/29 . 
This PR currently includes a temporary copy of the new HighlevelDiff class for development. It will be removed here and imported from data-utils-py when the PR over there is merged.
> Add compare tool

- etl/harmonize.py
- etl/publish.py
- etl/scripts/countries-regions/08-metadata.ipynb
- etl/scripts/sex/01-create-table.ipynb
- etl/steps/data/explorers/owid/2021/food_explorer.py
- etl/steps/data/explorers/owid/latest/food_explorer.py
Fixes #332
This change enables support for co-publishing in `feather` and `parquet` formats. The `parquet` format includes the full table metadata inside the Parquet schema. At this time, `csv` was disabled by default since it would 50x the catalog size.
The motivation for this was to support quick (or even, lazy) DuckDB indexing for the API.
- Code forcing an output format is updated, in particular `reference/countries_regions` and `**/food_explorer` (`ds.add(t, format='csv') --> ds.add(t, formats=['csv'])`).
- Channels are reindexed in parquet as well as feather
- Publishing co-publishes parquet indexes
This PR only causes newly rebuilt datasets will get published this way. A full forced rebuild of the ETL is recommended to generate the first batch of `parquet` files.
> Multi-format support including parquet

- etl/db_utils.py
- etl/grapher_import.py
- etl/steps/data/garden/owid/latest/population_density/population_density.meta.yml
- etl/steps/grapher/ggdc/2020-10-01/ggdc_maddison.py
- etl/steps/grapher/owid/latest/population_density.py
- etl/steps/grapher/who/2021-07-01/annotations.yml
- etl/steps/grapher/who/2021-07-01/ghe.py
Issue https://github.com/owid/etl/issues/314
[Grapher DB migration](https://github.com/owid/owid-grapher/pull/1566)
Sync attributes
* `Dataset.short_name` -> `datasets.shortName`
* `Dataset.title` -> `datasets.name`
* `Dataset.version` -> `datasets.version`
Migration adds unique constraints on `(dataset, shortName, version)` and updates `shortName` and `version` of existing datasets. That means rerunning grapher steps won't create new datasets, but only update `dataset.name` with `Dataset.title`
Sync attributes
* `VariableMeta.short_name` -> `variables.shortName`
* `VariableMeta.title` -> `variables.name`
Migration adds unique constraints on `(dataset, shortName)`, but there's also an existing `(dataset, name)` constraint. So running grapher steps would only update `variables.shortName` …
> feature(grapher): update grapher export and backports to use new short name and version fields

- etl/steps/data/garden/faostat/2022-05-17/faostat_food_explorer.py
Fixes #363
A typo in the table metadata for the `faostat_food_explorer` dataset caused the entire multi-index to be serialised into the metadata, instead of just the names of the columns.
Fixing the primary key field for this dataset to just store the names of the columns reduces the parquet file's size from 187M to 61M, much closer to the feather file.
The feather file was not affected since it follows a different code path.
> fix: massive parquet file for faostat_food_explorer

- Makefile
The deploy command does a full ETL run on production using the analytics script `ops/scripts/etl-prod.sh`. The script helpfully acquires a global lock, so you don't have to worry about any race conditions with production runs.
> chore: add "make deploy" helper command

- etl/grapher_import.py
`GrapherStep.is_dirty` didn't work because it was fetching datasets by `name` which changed to `shortName` recently.
> fix(grapher): get dataset checksum by shortName instead of name

- etl/grapher_helpers.py
- etl/steps/grapher/who/2021-07-01/ghe.py
- tests/test_grapher_helpers.py
Helper functions for yielding tables for grapher don't work well with dimensions. They don't support titles and had bugs in creating short names.
This PR adds the following functionality:
* Title (= variable name in grapher) is now created automatically from the original title and dimensions. For instance variable `deaths` with dimensions `age group` and `sex` would be converted into `deaths - age group: 10-18 - sex: male`. It also supports new argument `dim_titles` for custom dimension naming, e.g. `Deaths - Age group: 10-18 - Sex: male` in this case
* Short names are created similarly to title, though they're not used for anything in grapher yet
* Adds test coverage for yielding wide and long tables (see unit tests for toy examples)
`yield_long_table` groups table by variable and then …
> fix(grapher): fix dimensions when yielding long or wide table to grapher

- README.md
I ran into this and someone else did too – when setting up for the first time, we need to init the submodules before attempting to install all dependencies with poetry.
I'm not sure if this should instead point to a `make` step, since that initializes submodules:
https://github.com/owid/etl/blob/a9e96f2b6f5d0f97c1b054a69aa9525b79d4d024/Makefile#L38-L41
> docs: init submodule before installing packages

- poetry.lock
- pyproject.toml
Update datautils version. This PR should be merged only after [this one](https://github.com/owid/walden/pull/66) in walden. Otherwise there will be an incompatibility in the dependencies.
> chore: Update datautils version

- etl/command.py
- etl/grapher_helpers.py
- etl/grapher_import.py
- etl/steps/__init__.py
- poetry.lock
- pyproject.toml
Inserts to `data_values` (and deletion of data values for variable id!) are way too slow. Doing it in parallel with threads speeds it up considerably (`faostat_fbsc` takes ~2500s and `faostat_qcl` takes ~180s, if there are existing variable ids then this takes longer).
I've tried loading the data from csv with `LOAD LOCAL INFILE` and various other approaches, but inserts with pandas `to_sql` were the fastest (it uses `executemany` under the hood just like we did, but for some reason it's a bit faster) and the most stable (no deadlock errors with threads).
Note that this is just a temporary solution, we hope to move from `data_values` to a new data architecture asap.
> enhance(grapher): parallelize upserts to data_values with threads

- etl/db.py
- etl/match_variables_from_two_versions_of_a_dataset.py
- pyproject.toml
Improvements on the match variables script
- Prettify the menu with variable options (using `click` and colouring)
- Changed `argparse` for `click` to manage executable
- Created command `etl-match-variables` to run the script
- Removed unused code
- Moved database-specific functions to `etl.db`
- Added argument `--max-suggestions`, to select an arbitrary number of new variables to be displayed
**Test the code**
1. Install the library: `poetry install`
2. Run `etl-match-variables --help`
The library might need a patch upgrade (0.1.1)
> enhance: match_variables command

- etl/match_variables_from_two_versions_of_a_dataset.py
Correct description for `max-suggestions` argument of command `etl-match-variables` (introduced in #386)
> docs(match_variables): fix arg description

- etl/db_utils.py
- etl/grapher_helpers.py
- etl/grapher_import.py
- etl/steps/__init__.py
- pyproject.toml
* there is a bug that labels grapher step as complete if inserts into DB fail
* fix performance bottleneck in `yield_wide_table`
* lower default grapher connections to 10
* run variable deletion in parallel
> fix(grapher): fix grapher inserts

- etl/chart_revision_suggester.py
- poetry.lock
- pyproject.toml
The code to submit the chart revisions to Grapher was using the wrong library (native `json` instead of 3rd party `simplejson`).
In particular, argument `ignore_nan` from function `json.dumps` was not recognised and led to an error during execution time.
> fix(json): use simplejson

- etl/command.py
- etl/config.py
- etl/run_python_step.py
- etl/steps/__init__.py
This non-essential flag makes it easier to check where something is going wrong. If you run the `etl` command but add `--ipdb`, it will enter the debugger on failure, regardless of whether you are in normal ETL code or within a Python ETL step.
- Adds a global variable to `etl.config` indicating whether the debugger should be triggered on exceptions
- Adds `--ipdb` options to both the `etl` command and the `run_python_step` command
> chore: add --ipdb option to enter debugger on failure

- .gitignore
- etl/config.py
Currently when I run grapher steps on staging on production I change my envs in `.env` file and then change it back. This could be dangerous if I forget to do so and then test against production envs in `.env`. Running `ENV=.env.production etl ...` instead is much more flagrant.
(I don't think that `dotenv` supports setting env file from environment or does it?)
> enhance(.env): allow custom .env file

- etl/grapher_import.py
Fix https://github.com/owid/etl/issues/432. There was a missing commit and opening new connection within an existing connection was a dumb idea. Add missing commits and only use single connection.
> fix(grapher_import): commit dataset after upsert to unfreeze sources

- etl/steps/data/garden/faostat/2022-05-17/faostat_metadata.py
In datasets `faostat_ek`, `faostat_qv`, and `faostat_sdgb`, some units were empty. This led to variables in the flattened dataset (and therefore variables in grapher) having names like `item | item code || element | element code || `.
But in all cases, when unit was missing, unit short name was given. So I have filled unit names with unit short names in those cases.
> fix(faostat): Fill missing FAOSTAT unit names with unit short names

- etl/steps/data/garden/faostat/2022-05-17/faostat_metadata.py
Silly bug: I was filling missing short units with "fao_unit_short_names" instead of the actual value of the unit short names.
> fix(faostat): Fix wrong use of fillna with fao unit short name

- etl/steps/data/garden/smil/2017-01-01/global_primary_energy.meta.yml
- etl/steps/data/garden/smil/2017-01-01/global_primary_energy.py
The source for Smil data was duplicated in the `smil/2017-01-01/global_primary_energy` dataset. I have solved in manually with a temporary solution.
@Marigold if you want feel free to create an issue about this (I guess you understand better than me what the root issue is).
> fix(smil): Fix duplicated sources in metadata

- dag.yml
- etl/steps/data/garden/owid/latest/key_indicators/table_population.meta.yml
- etl/steps/data/garden/owid/latest/key_indicators/table_population.py
Switch to UN WPP 2022 revision population for data starting from 1950:
New countries (only UN data, i.e. > 1950 year):
- Kosovo
- Guernsey
- Jersey
Deleted:
- Channel Islands (now Guernsey and Jersey)
- Melanesia, Polynesia (not countries)
> enhance(population): use un wpp 2022

- etl/steps/__init__.py
- etl/steps/grapher/bp/2022-07-14/energy_mix.py
- etl/steps/grapher/bp/2022-07-14/statistical_review.py
Compare modified date of dataset `index.json` files to detect whether `.save()` was called and raise warning if not. This is not foolproof because `Dataset.create_empty` saves the dataset too (any changes to metadata after that won't be reflected and you won't get a warning).
> enhance(datastep): raise warning if .save was not called

- poetry.lock
- pyproject.toml
To open `xls` files it seems we need `xlrd` package installed (I think `openpyxl` can only handle `xlsx` files).
> chore: Add xlrd to dependencies

- etl/grapher_helpers.py
- etl/grapher_model.py
- tests/test_grapher_helpers.py
If table contains variable with multiple sources, combine them into a single source ready for upsert to grapher.
I've also slightly refactored `combine_metadata_sources` as `adapt_*` methods will be soon applied to all datasets by default. I haven't changed the original logic, but to be honest I find it quite confusing how we make description fallbacks to dataset description or table description. I couldn't think of a better solution though.
@pabloarosado are you fine with the existing fallback logic? If yes then I'd say we go ahead and keep it like that until we either find it problematic or design a better schema for sources.
> enhance(grapher_helpers): combine sources of variables

- etl/grapher_helpers.py
- etl/grapher_model.py
- pyproject.toml
- tests/test_grapher_helpers.py
Fixes https://github.com/owid/etl/issues/487#issuecomment-1252863212
Previously we were `slugify`-ing variable short names before upserting to grapher. This converted double underscore to a single underscore which led to unintended effects. In this PR we don't transform column names (since they are already underscored), only dimension names if necessary.
To avoid collisions when doing upserts, we match variables on either short name or short name with single underscore. This should eventually fix (i.e. put back original double underscore) all variables in grapher.
(I could also re-upsert all grapher datasets into grapher. Would it be perhaps safer?)
> fix(grapher): use original column names in grapher upsert

- etl/chart_revision_suggester.py
- pyproject.toml
Command tool to submit the new variable mapping to Grapher to generate the appropriate chart revisions.
Its usage is:
```
~ etl-chart-suggester --help
Usage: etl-chart-suggester [OPTIONS]
Using the <mapping-file> JSON file mapping variable IDs from an old dataset
to a new dataset, it creates a bunch of suggested chart revisions in
Grapher.
It connects to Grapher based on the environment file found in the project's
root directory `path/to/etl/.env`.
Options:
-f, --mapping-file TEXT  Path to variable mapping json file.  [required]
-n, --namespace TEXT     Namespace of the dataset.  [required]
-v, --version TEXT       Version of the dataset.  [required]
-d, --dataset-name TEXT  Name of the dataset.  [required]
--help                   Show this message and exit.
```
Currently, it is using a …
> feature: new command tool

- etl/command.py
- etl/config.py
- etl/steps/__init__.py
Partial fix for https://github.com/owid/etl/issues/466
If you make any changes to `shared.py` (e.g. in `faostat/`), its checksum won't change and running `etl faostat_fs` is gonna tell you `All datasets up to date!` even though its recipe has changed.
Locally you can get around this by using `--force --only`, but once you push it to production, etl on our server won't rebuild the dataset.
ETL only looks for changes in `[dataset].py` or if you use directory `[dataset]/*` it looks for all changes in that directory (this would be best, but it would mean creating many redundant directories e.g. for faostat).
In addition to files above, look for changes in all `shared*` files (`shared.py`).
We could also got with directories and have symlinks for shared files, but that might be an overkill …
> enhance(steps): add shared modules to checksum

- etl/steps/open_numbers.py
Added function `fast_table_clean` to `etl.steps.open_numbers` module.
This function resets the indices, maps Open Number's codes to OWID country names, checks columns and standardizes their names.
The idea is that does some minor data transformations that can come in handy when loading Open Number's tables (e.g. to combine with other tables).
```python
>>> from owid.catalog import Dataset
>>> from etl.paths import DATA_DIR
>>> from etl.steps.open_numbers import fast_table_clean
>>> d = Dataset(DATA_DIR / "open_numbers/open_numbers/latest/open_numbers__world_development_indicators")
>>> d["it_net_user_zs"].head()  # uncleaned
it_net_user_zs
geo time                
abw 1990             0.0
1991             0.0
1992             0.0
1993             0.0
1994             0.0
>>> df = …
```
> feature(open-numbers): fast table loading and cleaning

- etl/files.py
- tests/test_files.py
Fix for https://github.com/owid/etl/issues/527
There was a bug that didn't ignore `__pycache__` which is why our checksums were different on different machines. `files.walk` is being used for [calculating checksums](https://github.com/owid/etl/blob/master/etl/steps/__init__.py#L361).
> fix(files): ignore __pycache__ when walking files

- etl/variable_mapping_translate.py
There was an unnecessary call to `pd.Series.squeeze`. 
Most of the time, it would squeeze a Series of length > 1, and would not complain (as it leaves the object unchanged). However, if the Series was from length 1, it would return a scalar, and subsequent operations would fail. An example of this is #534.
> fix(cmd): unnecessary squeeze (solves #534)

- etl/grapher_helpers.py
- etl/steps/grapher/un/2022-07-11/un_wpp.py
- etl/steps/grapher/un_sdg/2022-07-07/un_sdg.py
- etl/steps/grapher/who/2021-07-01/ghe.py
- tests/test_grapher_helpers.py
Grapher steps should work without MySQL, since `country_to_entity_id` is trying to create entities in MySQL, we have to get rid of it in grapher steps and leave just country there.
> fix(grapher): move country_to_entity_id from grapher steps and keep only country column

- etl/steps/data/explorers/un/2022/un_wpp.py
The connection was unused, but meant that the explorer build failed for the general public due to missing credentials.
Discovered in a full rebuild: https://buildkite.com/our-world-in-data/etl-nightly-public-build-from-scratch/builds/2#01838dde-2288-4cbe-affa-d8e34aa2a1b5
> fix(un_wpp): remove unused s3 connection from un_wpp explorer

- Makefile
Fixes #483
When using `make` to set up the virtual environment, refuse to do if the wrong Python interpreter has been used in Windows.
> fix: force Windows users onto WSL python

- README.md
- etl/grapher_import.py
Stop upserting to `data_values` table now that data in admin is loaded directly from parquet files in grapher channel.
Adding `CATALOG_PATH=/path/to/etl/data` to `owid-grapher/.env` is needed for local development (see README).
> feature(grapher): stop upserting to data_values table

- etl/command.py
- etl/files.py
- etl/steps/__init__.py
Fix for https://github.com/owid/etl/issues/552
[PR in walden](https://github.com/owid/walden/pull/91)
`WaldenStep` should also compare checksums before using file from cache. However, this is computationally expensive so we use runtime cache with filename as a key. (Using mtime of files plus filename would be also possible, but is it necessary over one run of ETL?)
> fix(WaldenStep): compare checksums in is_dirty

- etl/grapher_import.py
- scripts/typecheck_steps.sh
Bring back upserts to `data_values` table. We're having issues with parquet files in production, so we want to keep upserting to `data_values` for the time being. I've manually run `etl --grapher` for datasets without existing data_values.
We'll remove it once again as we resolve these issues.
> fix(grapher_import): rollback data_values upserts

- etl/steps/data/garden/un/2022-07-11/un_wpp/deaths.py
@fiona asked if we could have the 100+ year group for [this chart](https://ourworldindata.org/grapher/deaths-by-age-group?country=~OWID_WRL). So the ‘Deaths - Sex: all - Age: 100+ - Variant: estimates’ variable.
Issue tracked in https://github.com/owid/owid-issues/issues/648
> feat(un_wpp): add 100+ age group for `deaths`

- etl/metadata_export.py
- etl/steps/data/converters.py
- etl/steps/data/meadow/dummy/2020-01-01/dummy.py
- pyproject.toml
- walkthrough/cli.py
- walkthrough/garden.py
- walkthrough/grapher.py
- walkthrough/meadow.py
- walkthrough/meadow_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
- walkthrough/walden.py
- walkthrough/walden_cookiecutter/cookiecutter.json
Implemented some ideas from https://github.com/owid/etl/issues/294
* CLI `etl-metadata-export` that creates a `*.meta.yml` file from a dataset, this is recommended in walkthrough, but could be used outside it too (@pabloarosado is this helpful? Any ideas how to make it more useful?)
* Add `version` field to walden
* Rearrange fields to be in order `namespace-version-short name`
* Ingestion scripts generated in `institution/version` folder
Does it make sense to generate `*.meta.yml` for meadow or should we only encourage to do it on garden level?
> enhance(walkthrough): various improvements

- pyproject.toml
Ignore `.ipynb_checkpoints`, otherwise `make test` fails.
> chore: Ignore .ipynb_checkpoints in pyright

- etl/command.py
- etl/steps/__init__.py
- tests/test_command.py
Enable pushing to grapher from private datasets. This supports DAGs such as
```
grapher://grapher/gcp/2022-11-11/global_carbon_budget
- data-private://grapher/gcp/2022-11-11/global_carbon_budget
```
that are run with `etl ... --private --grapher`. It shouldn't raise validation error any more. `grapher-private://` step got also removed as it didn't make any sense (grapher database is always _private_).
@pabloarosado can you merge it yourself if you approve it?
> fix(steps): proper private dependencies for grapher

- etl/config.py
- etl/steps/__init__.py
Use `prlimit` on Linux to limit steps to 16G of virtual memory.
We want the ETL to run correctly on machines with 16GB of memory, of which not all can be dedicated to the ETL. We also want to be able to potentially parallelise steps in future.
By setting this limit, we force expensive steps to break predictably on Linux rather than have them sometimes work and sometimes not depending on other factors.
16GB is a memory size that's increasingly the default for data work on laptops and reasonably priced cloud servers, so that's the default we choose here.
Conveniently, all our current work fits into 16GB of memory, so merging this constraint will only cause future memory-intensive work to fail rather than existing work.
> chore: limit steps to 16G of memory on Linux

- poetry.lock
Currently, BuildKite full rebuilds are failing because `ipdb` won't install during the `poetry install` step.
After debugging a ton of stuff, it appears to be necessary to manually add `setuptools` to get the virtualenv to build.
> fix: problem installing ipdb due to missing setuptools

- dag.yml
- etl/steps/data/explorers/emdat/2022-12-07/natural_disasters.py
Add natural disasters explorer step, which simply takes the annual/decadal tables from garden, and exports two tables with the same columns as those needed in the explorer.
> feat(emdat): Add natural disasters explorer step

- dag.yml
- etl/grapher_import.py
In order to remove variable from `variables`, we first have to remove it from `country_latest_data` to prevent foreign key error.
> fix(grapher_import): remove ghost variables from `country_latest_data`

- etl/run_python_step.py
- etl/steps/data/garden/andrew/2019-12-03/co2_mitigation_curves.py
- etl/steps/data/garden/dummy/2020-01-01/dummy.py
- etl/steps/data/garden/emdat/2022-11-24/natural_disasters.py
- etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.py
- etl/steps/data/garden/hmd/2022-11-04/life_tables.py
- etl/steps/data/garden/rff/2022-09-14/world_carbon_pricing.py
- etl/steps/data/grapher/dummy/2020-01-01/dummy.py
- etl/steps/data/grapher/ihme_gbd/2020-12-19/child_mortality.py
- etl/steps/data/grapher/malnutrition/2022-10-18/malnutrition.py
- etl/steps/data/grapher/postnatal_care/2022-09-19/postnatal_care.py
- etl/steps/data/meadow/aviation_safety_network/2022-10-12/aviation_statistics.py
- etl/steps/data/meadow/aviation_safety_network/2022-10-14/aviation_statistics.py
- etl/steps/data/meadow/dummy/2020-01-01/dummy.py
- etl/steps/data/meadow/emdat/2022-11-24/natural_disasters.py
- pyproject.toml
- snapshots/dummy/2020-01-01/dummy.py
- snapshots/dummy/2020-01-01/dummy.xlsx.dvc
- walkthrough/garden.py
- walkthrough/garden_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
- walkthrough/grapher.py
- walkthrough/grapher_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
- walkthrough/meadow_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
The purpose of this change is to make working with datasets & tables & metadata more ergonomic. Currently we have something like this
```python
ds = Dataset.create_empty(dest_dir, metadata=convert_snapshot_metadata(snap.metadata))
ds.metadata = convert_snapshot_metadata(snap.metadata)
ds.metadata.version = "2020-01-01"
table_metadata = TableMeta(
short_name=snap.metadata.short_name,
title=snap.metadata.name,
description=snap.metadata.description,
)
tb = Table(df, metadata=table_metadata)
tb = underscore_table(tb)
ds.metadata.update_from_yaml(N.metadata_path, if_source_exists="replace")
tb.update_metadata_from_yaml(N.metadata_path, "dummy")
```
which is terrifying... especially those `update_from_yaml` pieces. This now changes to
```python
ds = Dataset.create_empty(dest_dir, …
```
> feature(etl): improve metadata ergonomics

- .dvc/config
- etl/snapshot.py
- etl/steps/__init__.py
ETL users without AWS config (any config, not necessarily ours) couldn't pull snapshots and got weird DVC error. Make DVC pull public files from https://catalog.ourworldindata.org/snapshots instead of S3. Using CDN also speeds up access and reduce bandwidth costs.
> enhance(snapshots): use Cloudflare cdn for accessing public snapshots

- etl/files.py
- etl/metadata_export.py
- etl/snapshot.py
- fasttrack/yaml_meta.py
- tests/test_files.py
Dumping strings to YAML were sometimes producing weird single-line strings full of `\n` newline characters. Turned out it was caused by non-stripped lines in multi-line strings. This PR fixes that and creates consistent function for dumping dictionaries to YAML format.
> enhance(yaml): add yaml_dump for proper writing of multi-line strings

- walkthrough/charts.py
If no logs are produced when creating chart revisions, do not show a dedicated scrollable field area for the logs.
> enhance(walkthrough): do not show logs if no logs

- snapshots/aviation_safety_network/2022-10-14/aviation_statistics.py
- snapshots/dummy/2020-01-01/dummy.py
- snapshots/ggdc/2020-10-01/ggdc_maddison.py
- snapshots/hmd/2022-12-07/hmd.py
- snapshots/hyde/2017/baseline.py
- snapshots/hyde/2017/general_files.py
- snapshots/un/2022-11-29/undp_hdr.py
- walkthrough/garden_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
- walkthrough/snapshot_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
This PR solves a typo in `walkthrough meadow` step, which wrongly had the help text as "Upload dataset to Walden" instead of "Upload dataset to Snapshot".
Also, changed python script template for Garden, so it uses `etl.data_helpers.geo` instead of `owid.datautils.geo`.
> enhance(walkthrough): typos, use data_helpers

- dag_files/dag_faostat.yml
Every now and then we have issues with some of the old FAOSTAT steps, which used to be necessary for the global food explorer, but now they are not used anywhere.
This PR removes those old steps from the dag.
> refactor: Remove old, unnecessary FAOSTAT steps from dag

- etl/steps/data/grapher/un_sdg/2022-07-07/un_sdg.py
Fixes #726, where the name of exploded dimensional variables is unstable for the SDG grapher dataset.
> fix: explode dimensions in deterministic order

- etl/compare.py
- etl/datadiff.py
- etl/metadata_export.py
- etl/steps/data/garden/emdat/2022-11-24/natural_disasters.py
- poetry.lock
- pyproject.toml
- tests/test_datadiff.py
Find differences between two catalogs (either two local catalogs or local and remote) and summarise them in a pretty format. It can be run locally, but it's gonna be used primarily in Buildkite as a separate pipeline to let us know what has changed.
I'm using `source_checksum` to find candidates for comparison. This works ok in most cases, but it's not gonna catch cases where ETL core code or dependencies (like new pandas version) changed. (This could be solved by adding ETL version to checksum calculation and increment whenever we do non-step change that we need to check... like pandas upgrade).
This originally leveraged `compare` tool that we have for comparing two datasets, but I've changed it to simple summary because the output was too long and messy in our CI. Devs can run `compare` …
> feature(datadiff): CLI for checking differences between two catalogs

- etl/steps/data/garden/faostat/2022-05-17/faostat_metadata.py
Pandas 1.5.2 raises warning `FloatingPointError: invalid value encountered in cast` when converting categories to str with `.astype(str)`. Changing it to `.astype("string")` runs without warning and should be more effective.
I plan to merge this only after `datadiff` has been merged and we have an automatic verification that datasets haven't changed by using `.astype("string")`.
> fix(faostat): fix warnings resulting from .astype(str)

- etl/helpers.py
- tests/test_helpers.py
`PathFinder` wasn't working for steps that were using `version/short_name/` directory instead of `version/short_name.py` module. This fixes it and adds some tests.
> fix(helpers): fix paths in PathFinder

- etl/grapher_helpers.py
Fix for https://github.com/owid/etl/issues/733. Could be related to pandas 1.5.1 -> 1.5.2 upgrade, `Series.map` now maps `Category` to `Category` natively.
> fix(grapher): fix issue with country_to_entity_id

- .github/workflows/python-package.yml
- dag/main.yml
- etl/datadiff.py
- etl/steps/data/meadow/un/2022-07-11/un_wpp.py
- etl/tempcompare.py
- snapshots/un/2022-07-11/un_wpp.zip.dvc
* stop running `walden tests` now that we use snapshots (takes ~1.5min in CI)
* migrate `un/2022-07-11/un_wpp` to snapshot (speeds up certain `etl` runs by the factor of 10x)
(better to wait for `datadiff` to make sure un_wpp hasn't changed)
> enhance(etl): improve ETL performance

- etl/steps/__init__.py
- tests/test_steps.py
This PR includes the Pandas version in the checksum for any dataset that gets created.
If the Pandas version gets updated for the ETL, then it will force CI to rebuild the datasets, giving us an opportunity to notice build problems and also data differences.
> Include pandas version in checksum

- etl/steps/data/meadow/papers/2022-11-04/riley_2005/__init__.py
Fixes #750 
Updates `data://meadow/papers/2022-11-04/riley_2005` step to use the new PyPDF interface as recommended.
✓ Checked that this change does not change the data output in any way
> fix: update Riley 2005 paper to new PDF parser API

- etl/steps/__init__.py
Currently, you get two exceptions when a step fails:
1. The real exception, the reason for failure
2. A `CalledProcessError` from `subprocess`
This PR removes the second one, which is not very helpful, so that you can focus on the first one.
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/Users/lars/Documents/owid/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File …
```
> enhance: make exceptions clearer when a step fails

- etl/match_variables.py
- etl/scripts/countries-regions/init.py
- etl/steps/data/garden/emdat/2022-11-24/shared.py
- poetry.lock
- pyproject.toml
- Removes dependency on `fuzzywuzzy`:
- This library is no longer maintained and has been replaced by `thefuzz`. See https://github.com/seatgeek/fuzzywuzzy for more details.
- We were already using `thefuzz` in some instances.
-  Pins `python-Levenstein` to a specific version. Otherwise, `thefuzz` usage will fail, because of a known bug: See https://github.com/seatgeek/thefuzz/issues/43, https://github.com/maxbachmann/python-Levenshtein/issues/1, https://github.com/seatgeek/thefuzz/pull/10, 
I noticed this error when trying to run `walkthrough charts`. It would not work, because it relies on `thefuzz`.
> chore(fuzzywuzzy): use thefuzz, fix levenshtein

- snapshots/conflicts/2023-01-09/bouthoul_carrere_1978.csv.dvc
- snapshots/conflicts/2023-01-09/bouthoul_carrere_1978.py
- snapshots/conflicts/2023-01-09/clodfelter_2017.csv.dvc
- snapshots/conflicts/2023-01-09/clodfelter_2017.py
- snapshots/conflicts/2023-01-09/dunnigan_martel_1987.csv.dvc
- snapshots/conflicts/2023-01-09/dunnigan_martel_1987.py
- snapshots/conflicts/2023-01-09/eckhardt_1991.csv.dvc
- snapshots/conflicts/2023-01-09/eckhardt_1991.py
- snapshots/conflicts/2023-01-09/orae_1985.csv.dvc
- snapshots/conflicts/2023-01-09/orae_1985.py
- snapshots/conflicts/2023-01-09/sorokin_1937.csv.dvc
- snapshots/conflicts/2023-01-09/sorokin_1937.py
- snapshots/conflicts/2023-01-09/sutton_1971.csv.dvc
- snapshots/conflicts/2023-01-09/sutton_1971.py
This PR adds several conflict datasets to Snapshot. To this end, I have created a new namespace: `conflicts`.
These datasets were previously manipulated and saved in [Google Drive](https://docs.google.com/spreadsheets/d/1lh4Ra3TaLt10ZRL4-C16--X1Zu4atofQO5iLwSBuOEY/edit#gid=1175422923). Here, we download these files from Google Drive and port them to Snapshots.
I have added [technical notes](https://docs.google.com/document/d/1aoBrW5UXkFNCZVM18teD9nYWcQH82_y5-uqeEH9c30E/edit#) to the corresponding dataset metadata.
> data(snapshot): add conflict datasets from spreadsheets

- etl/steps/data/garden/homicide/2023-01-03/homicide_long_run_omm.meta.yml
Adding in some white space to the bullet points on source tab.
> format(homicide): fixing homicide long run metadata

- backport/backport.py
- backport/bulk_backport.py
There's an option to set workers, but it wasn't applied in `ThreadPool` and backporting was using maximum number of workers.
> fix(backport): add missing number of workers to backport

- poetry.lock
- pyproject.toml
Frictionless got recently upgraded to 5.x.x version which broke nightly build. Pinning it to 4.x.x for now (it's not clear whether it's a bug in 5.x.x or if data format of open numbers supports only 4.x.x)
> fix(requirements): pin frictionless to 4.x.x version

- dag/demography.yml
- dag/emissions.yml
- dag/main.yml
- etl/data_helpers/geo.py
- etl/steps/data/garden/demography/2022-12-08/population/__init__.py
Merging [geo refactoring](https://github.com/owid/etl/pull/761#issuecomment-1378946768) introduced circular dependency of population dataset on itself. Step `data://garden/demography/2022-12-08/population` calls function `add_region_aggregates` calls  `list_countries_in_region_that_must_have_data` which tries to load population table from `data://garden/owid/latest/key_indicators` (that doesn't exist yet). Since we know population in `demography/2022-12-08/population`, the easiest fix is to pass it explicitly as a parameter for region calculation.
There might be a better solution, this is just a hotfix. @pabloarosado feel free to suggest a better one.
In addition, I've also added `data://garden/owid/latest/key_indicators` as dependencies to steps that use `geo.add_population_to_dataframe` …
> fix(geo): fix circular dependency of population dataset

- etl/harmonize.py
- etl/match_variables.py
- poetry.lock
- pyproject.toml
[thefuzz](https://github.com/seatgeek/thefuzz) seems not to be very active in maintenance.
Motivated by this https://github.com/seatgeek/thefuzz/pull/10#issuecomment-1381844400, I have changed this dependency to [RapidFuzz](https://github.com/maxbachmann/RapidFuzz).
This also gets rid of the version-pin of `python-Levenshtein` (see https://github.com/owid/etl/pull/747).
> chore(fuzz): thefuzz → rapidfuzz

- dag/main.yml
- etl/steps/data/garden/met_office_hadley_centre/2023-01-17/near_surface_temperature.meta.yml
- etl/steps/data/garden/met_office_hadley_centre/2023-01-17/near_surface_temperature.py
- etl/steps/data/grapher/met_office_hadley_centre/2023-01-17/near_surface_temperature.py
- etl/steps/data/meadow/met_office_hadley_centre/2023-01-17/near_surface_temperature.py
- snapshots/met_office_hadley_centre/2023-01-17/near_surface_temperature.py
- snapshots/met_office_hadley_centre/2023-01-17/near_surface_temperature_global.csv.dvc
- snapshots/met_office_hadley_centre/2023-01-17/near_surface_temperature_northern_hemisphere.csv.dvc
- snapshots/met_office_hadley_centre/2023-01-17/near_surface_temperature_southern_hemisphere.csv.dvc
I updated this dataset (which didn't really need an update) just to adapt it to the new walkthrough workflow and to see if everything works well. Nothing has changed with respect to the previous steps, so there's no need to review the steps.
Everything went well, except for one small issue: Initially, in the garden metadata, I only had:
```yaml
dataset:
title: Near-surface temperature anomaly (Met Office Hadley Centre, 2022b)
```
Given that all metadata was well defined since the snapshot step. However, on grapher admin I saw that the datset description (which shows in the SOURCES tab) was duplicated. That's why I had to include `description: ""`. I think this happens because, when transferring the ETL grapher step to grapher, the sources' description are appended to the dataset …
> 884 data update near surface temperature met office hadley centre

- walkthrough/garden.py
Sometimes, a garden dataset might rely on a meadow dataset with a different version, e.g.
```yaml
data://garden/namespace/2022-11-25/short_name:
- data://meadow/namespace/2022-11-30/short_name
```
Therefore, I have added an extra field if we want to specify the Meadow version separately.
> enhance(walkthrough-garden): accept different meadow version

- etl/data_helpers/geo.py
- etl/datadiff.py
- etl/steps/data/garden/dummy/2020-01-01/dummy.py
- tests/data_helpers/test_geo.py
- walkthrough/garden_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
* Generalize `etl.data_helpers.harmonize_countries` so that it can ingest a path to a file of excluded country names.
* Change tests to load `geo` from `etl.data_helpers` instead of `owid.datautils`.
* Add new tests for `harmonize_countries`.
* Simplify walkthrough garden to use the new `harmonize_countries`.
* Reformat garden dummy step.
> Improve harmonize countries

- etl/datadiff.py
- etl/files.py
- etl/steps/__init__.py
- etl/steps/data/garden/country_profile/2022/overview.py
- etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.meta.yml
- etl/steps/data/garden/hmd/2022-11-04/life_tables.py
- etl/tempcompare.py
- tests/test_steps.py
* improve performance of `datadiff` so that running `etl-datadiff REMOTE data/ --include "garden" --verbose` runs in reasonable time (it could still take an hour or so if your bandwidth is slow)
* avoid recomputing dependencies checksums by caching them, this speeds up `etl garden` by 3x or so
* save country profiles as other formats to make them available in the catalog
> enhance(datadiff): improve performance

- etl/chart_revision/cli.py
- etl/chart_revision/deprecated.py
- walkthrough/charts.py
By default, `walkthrough charts` and `etl-chart-suggester` will now use the new backend version. Previously, new version was optional (see #776).
To use old (legacy) version, use:
```
etl-chart-suggester MAPPING.json -o
```
or in walkthrough check "Use old version":
---
Good enough review would be to test `walkthrough charts` for some datasets locally and see that it makes sense.
> enhance(wt-charts): use new backend version by default

- etl/files.py
- etl/metadata_export.py
- tests/test_files.py
@paarriagadap the problem was in tabs, so I replaced every tab by two spaces to be able to render it as nice multiline string. This is how the description looks now.
```yaml
dataset:
namespace: wid
short_name: world_inequality_database
title: World Inequality Database (WID, 2022)
description: |-
The World Inequality Database (WID) is an extensive database on the distribution of income and wealth, both between and within countries. It is primarily maintained by the World Inequality Lab (WIL), located at the Paris School of Economics (PSE). But it is fundamentally the result of a coordinated, collaborative effort involving hundreds of researchers throughout the world over the past twenty years.
In recent years, the WIL has been leading efforts in creating “distributional national accounts” …
```
> fix(etl-metadata-export): remove channel property and keep strings in literal format

- pyproject.toml
For some reason I forgot to change the function called in the `etl-chart-suggester` command tool. The web app client is already using the new backend version
> enhance(wt-charts): use new backend version

- dag/main.yml
- etl/steps/data/explorers/lis/2023-01-18/luxembourg_income_study.py
Create explorer step for Luxembourg Income Study. It follows the same structure as [WID](https://github.com/owid/etl/blob/master/etl/steps/data/explorers/wid/2023-01-27/world_inequality_database.py).
> Create explorer step for Luxembourg Income Study

- etl/steps/data/garden/dummy/2020-01-01/dummy.meta.yml
- etl/steps/data/meadow/dummy/2020-01-01/dummy.meta.yml
- walkthrough/garden.py
Before this `walkthrough grapher --dummy-data` generated grapher dataset that was raising error about missing properties like title. This PR adds missing metadata when we use flag `--dummy-data`.
(I could have fixed just the dummy dataset, but someone would have overwritten it soon anyway, so it's better to fix it when being generated)
> fix(walkthrough): add some fields to metaata to make dummy dataset from walkthrough work

- etl/compare.py
- etl/grapher_import.py
- etl/steps/__init__.py
- etl/steps/data/garden/un_sdg/2022-07-07/un_sdg.py
- etl/steps/data/grapher/energy/2022-07-29/primary_energy_consumption.py
Couple of minor fixes needed to run `etl grapher --grapher` successfully on staging / live. This is a prerequisite to automated deploys.
It also fixes bug with excessive number of open connections (by using shared engine).
In addition to changes in this PR, I'll have to run the following SQLs against live DB (should be harmless)
```
update datasets set shortName = 'global_carbon_budget_additional'
where name = 'Global Carbon Budget (Global Carbon Project, v2021b)' and shortName = 'global_carbon_budget_global';
update datasets set name = 'United Nations Office on Drugs and Crime - Intentional Homicides'
where name = 'United Nations Office on Drugs and Crime - Intentional Homicides (2022)' and version = '2023-01-04';
```
> fix(data): fix failing grapher upsert steps

- etl/paths.py
Steps archival works pretty well in my opinion. I think it's time to start excluding archived steps by default.
(I thought we were excluding them already which bit me recently)
> enhance(etl): use non-archive DAG file by default

- etl/steps/data/garden/country_profile/2022/overview.py
Our nightly full build was failing because of outdated dependency. We've updated life expectancy dataset, but forgot to update it country profiles code. Switching to `PathFinder` should fix it.
> fix(data): fix wrong dependency version for country_profile

- backport/datasync/data_metadata.py
- backport/datasync/datasync.py
- etl/config.py
- etl/grapher_import.py
- etl/grapher_model.py
When running `etl --grapher`, push to S3 in addition to upserting to `data_values`. Stop syncing datasets from ETL in `datasync` service. After we make sure loading data from S3 works well, we can remove upserting to data_values and prune all ETL datasets from there. That should make `data_values` significantly smaller and give us better visibility into what's writing there and still needs to be migrated.
Running `ENV=.env.prod etl ... --grapher` now does the following:
1. Upsert to `data_values`
2. Upload data to https://catalog.ourworldindata.org/baked-variables/live_grapher/data/[variable_id].json (and metadata)
3. Set `dataPath` and `metadataPath` of all upserted variables
4. (Skip `datasync`)
Grapher admin will fetch data and metadata from S3 instead of data_values.
Note that we're …
> enhance(grapher_import): upsert to S3 in addition to data_values

- backport/datasync/datasync.py
There was an unnecessary session created which name collided with another session. Removing it fixes some `sqlalchemy.exc.InvalidRequestError` errors.
> fix(datasync): variable name collision

- backport/datasync/data_metadata.py
- tests/backport/datasync/test_data_metadata.py
Grapher data JSON files uses mixed types, but datasync uses consistent type, i.e. grapher values
```
{"values: {1, 2.5, "NA"}}
```
get incorrectly converted to strings by datasync as
```
{"values: {"1", "2.5", "NA"}}
```
This causes issues in plotting charts. Once we merge this change, we'll have to datasync all datasets with wrong types. I have a local comparison script that detects those datasets and eventually ensures 1:1 match between S3 and baked data files.
> fix(datasync): fix datasync types

- scripts/data_parity.py
Small script for comparing data files in S3 and baked files on live. They should be identical to safely merge [this grapher PR](https://github.com/owid/owid-grapher/pull/1997). You don't have to try it on your local, just check the code for any obvious errors, please.
They're identical except of variable 468301 used in [this chart of road traffic deaths](https://ourworldindata.org/grapher/road-traffic-deaths-to-alcohol). If you check the data with `select * from data_values where variableId = 468301;` you'll see that it contains non-numeric values (e.g. `13 (GB), 23 (NI)`)
```
"value","year","entityId","variableId"
"13 (GB), 23 (NI)",2017,1,468301
"38.5",2017,2,468301
"29",2017,3,468301
"11 - 24",2017,5,468301
"7",2017,6,468301
"13",2017,7,468301
"20 - 25",2017,8,468301
"17 Males, 6.7 …
```
> feature(scripts): script for comparing data parity

- etl/steps/data/explorers/poverty_inequality/2023-03-01/poverty_inequality.py
- etl/steps/data/garden/lis/2023-01-18/luxembourg_income_study.meta.yml
- etl/steps/data/meadow/wid/2023-01-27/world_inequality_database.py
- snapshots/lis/2023-01-18/lis_abs_poverty.csv.dvc
- snapshots/lis/2023-01-18/lis_distribution.csv.dvc
- snapshots/lis/2023-01-18/lis_keyvars.csv.dvc
I have introduced a temporal update for the `poverty_inequality` `explorers` step: As the World Bank Poverty and Inequality Platform (PIP) dataset is currently outside the ETL we decided to merge the current version of the exported dataset (in the notebooks repo) to both LIS and WID explorers datasets to create a [comparison data explorer](https://github.com/owid/owid-issues/issues/983).
This is a temporary solution because I plan to move PIP to the ETL [in May](https://github.com/owid/data-research-roadmap/#pablo-a-gantt-chart)
There is also a [2023 LIS update](https://www.lisdatacenter.org/news-and-events/2023-spring-data-splash/) that I include
> Add Poverty and Inequality Platform to explorer (+ LIS update)

- snapshots/who/latest/fluid.csv.dvc
- snapshots/who/latest/fluid.py
- snapshots/who/latest/flunet.py
Make sure we're not updating snapshots that are not working. This should hotfix https://github.com/owid/etl/issues/925 until we either decide what to do or until provider fixes their data. It also rolls back fluid to the latest working file.
It has also checks on CSV size since sometimes we're getting valid files which are [however much smaller](https://github.com/owid/etl/issues/925#issuecomment-1470365608).
> fix(flu): raise an error when creating snapshot if CSV cannot be parsed

- backport/datasync/datasync.py
Datasync was using `sourceChecksum` to detect which datasets are from ETL. This didn't work well because `sourceChecksum` is set after all variables are upserted. Column `shortName` doesn't have this problem.
> fix(datasync): dont sync ETL datasets

- backport/datasync/datasync.py
- scripts/data_parity.py
Compare metadata in `data_parity.py` script in addition to data. There's one [inconsistency](https://github.com/owid/owid-grapher/issues/1927), but we're not using that field so it's not a blocker. I've also found that `datasync` can't rely just on `dataEditedAt` and `metadataEditedAt` in case someone changes variable metadata. This PR also fixes that.
> feature(data_parity): compare metadata

- etl/steps/data/garden/nasa/2023-03-06/ozone_hole_area.meta.yml
- etl/steps/data/garden/unep/2023-03-17/consumption_controlled_substances.meta.yml
- etl/steps/data/garden/unep/2023-03-17/consumption_controlled_substances.py
This PR:
- Improves metadata for datasets:
- [Ozone hole area and concentration (NASA, 2023)](https://owid.cloud/admin/datasets/5912)
- [Consumption of controlled substances (UNEP, 2023)](https://owid.cloud/admin/datasets/5925)
- Adds a new variable, `consumption_rel_1986`, which normalizes the variable `consumption` value so that it equals 100 for the year 1986. This should allow us to update this chart: https://ourworldindata.org/grapher/ozone-depleting-substances-index
> fix(ozone): metadata

- backport/datasync/data_metadata.py
- backport/datasync/datasync.py
- etl/chart_revision/deprecated.py
- etl/chart_revision/variables.py
- etl/compare.py
- etl/config.py
- etl/datadiff.py
- etl/grapher_import.py
- etl/grapher_model.py
- etl/steps/__init__.py
- tests/backport/datasync/test_data_metadata.py
- walkthrough/grapher.md
Stop upserting values to `data_values` table. Adapt `compare` and `etl-chart-suggester` to fetch data from S3 instead of `data_values`. `data_values` remains only in datasync and backporting now (we won't need them once all data go through ETL).
> refactor(etl): replace data_values table with values from S3

- fasttrack/cli.py
- fasttrack/sheets.py
Add field `data_url` to Google Sheets. If it's not empty, use it to fetch data instead of fetching them from Google Sheets. This is especially useful for large datasets which lets us host data on S3 and metadata in Sheets.
> enhance(fasttrack): add data URL as an alternative to data sheet

- etl/chart_revision/cli.py
- etl/chart_revision/revision.py
- Improves a slightly confusing error message.
- Simplifies the submission of chart revisions with the new function `create_and_submit_charts_revisions`. This aims to improve the experience of users that want to submit chart revisions programmatically. In such cases, users have a dictionary mapping old to new variable IDs and want to use this to create and submit the necessary chart revisions.
> enhance(chart_revision): error message, simplified API

- etl/steps/data/garden/wid/2023-01-27/shared.py
- etl/steps/data/garden/wid/2023-01-27/world_inequality_database.meta.yml
- snapshots/wid/2023-01-27/wid_indices.do
- snapshots/wid/2023-01-27/world_inequality_database.csv.dvc
Although the median is included among the WID variables (as a `p50p60_thr` variable), when I create explorers I need a median variable and a 5th percentile threshold with different names to be shown in comparisons with PIP and LIS. See more information about the explorers [here](https://github.com/owid/owid-issues/issues/983).
This is a minor change; it only adds four new variables and their metadata.
> feat(wid): Add median data as a separate variable

- walkthrough/grapher.py
- walkthrough/grapher_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
Only affects Grapher step:
- Minor bug in Grapher template: `ds_garden` was used instead of `ds_grapher` when running sanity checks.
- It was assumed that Garden dataset version was the same as Grapher's. I have added an extra field to allow users to define different versions for each step. We are currently doing this in the Garden step for Meadow/Garden.
> enhance(walkthrough): fix bug, add field in Grapher step

- etl/steps/data/grapher/demography/2023-03-31/population.py
This will add a new variable, which provides the source name for each data point in the dataset.
By creating a chart with this variable, we can point users in our article [What are the sources for Our World in Data's population estimates?](https://ourworldindata.org/population-sources) to a table with the source at (country, year)-level.
This actually makes me think that this is a (hacky) way to surface annotations at datapoint level.
> enhance(population): add variable "sources"

- walkthrough/garden.py
- walkthrough/meadow.py
- walkthrough/utils.py
Previously, `walkthrough` allowed users to add our population and reference datasets as dependencies to our DAG _only_ in the meadow step. However, these datasets should not be listed as dependencies in any meadow step. Instead, they should be used in Garden.
This PR:
- Allows users to add population and reference datasets as dependencies in a Garden step from `walkthrough` interface. It removes these options from the Meadow step, as these should not be used there.
- Updates the population dataset used by default to the latest available one: `data://garden/demography/2023-03-31/population`
---
related to https://github.com/owid/etl/issues/1003
tagged you both, @pabloarosado @paarriagadap ー but one review should suffice I think.
> fix(walkthrough): load population and reference datasets in garden step

- dag/faostat.yml
- etl/steps/data/garden/faostat/2023-02-22/additional_variables.meta.yml
- etl/steps/data/garden/faostat/2023-02-22/additional_variables.py
- etl/steps/data/grapher/faostat/2023-02-22/additional_variables.py
In [the fertilizers' data explorer](https://ourworldindata.org/explorers/fertilizers), the data for total fertilizers per area of cropland was inconsistent with the data for each of the individual fertilizers per area of cropland. The reason is that, for the former, "cropland" meant "arable land", whereas for the latter, "cropland" meant "arable land plus permanent crops".
To fix the inconsistency, I added a new variable for all fertilizers per area of cropland (meaning arable land plus permanent crops). Additionally, I added variables for total use of each of the fertilizers (which were not included in the explorer and may now be included, if we find them useful).
This PR fixes https://github.com/owid/owid-issues/issues/996
> Add fertilizers data

- dag/demography.yml
- etl/steps/data/garden/demography/2023-03-31/population/meta.yml
- etl/steps/data/garden/demography/2023-04-14/population_density.meta.yml
- etl/steps/data/garden/demography/2023-04-14/population_density.py
- etl/steps/data/grapher/demography/2023-04-14/population_density.py
- Creates garden and grapher datasets for our `population density` OMM.
- We estimate it as `population / land area`, where
- `population`: from our OMM dataset.
- `land area`: from FAOSTAT RL dataset.
- Minor metadata adjustments to `population` OMM: Add licenses.
- Metadata for `population density` is mostly inherited from `population`.
This PR makes `key_indicators` no longer required:
- population metrics can be found in the population OMM dataset.
- population density metrics can be found in the population density OMM dataset.
- land area metric can be found in FAOSTAT RL dataset.
I sanity-checked, and differences with `key_indicators` are neglectable.
<details>
<summary>Show sanity check code</summary>
```python
import pandas as pd
from owid.catalog import Dataset
from etl.paths …
```
> data(population-density): add OMM dataset

- fasttrack/cli.py
- fasttrack/instructions_large_csv.md
- fasttrack/sheets.py
Add instructions for importing large CSVs to fast-track and make it work with Google Drive URLs. We are already using this feature, but the documentation was not available.
> enhance(fasttrack): add instructions for importing large CSVs

- etl/harmonize.py
- tests/test_harmonize.py
In addition to `countries_regions.csv`, save aliases also to `regions.yml` file that contains metadata about our new regions dataset.
It uses regexes to find `aliases` and replace them, which is not great, but works... I've tried using ruamel.yaml, but keeping formatting of `regions.yml` unchanged was surprisingly hard. We'd have convert it to a more standardised format first to be able to effectively use ruamel.yaml.
> enhance(harmonize): save aliases to regions.yml file

- etl/grapher_helpers.py
- etl/steps/data/garden/health/2023-04-18/wgm_mental_health.py
In grapher we assemble **source** description (which is shown in admin as dataset description 🤦 dataset description is not shown anywhere in grapher) from **dataset description + source description** if and only if they're different. However, if someone appends something to e.g. source description, we'd have duplicate paragraphs in the output. Change it so that it uses both descriptions only if one is not subset of another.
Also remove `ds_garden.update_metadata(paths.metadata_path)` which is already part of `create_dataset`.
> data(health): fix description of Wellcome Global Monitor 2020

- docs/overrides/404.html
- docs/tutorials/adding-data/manual.md
- docs/tutorials/adding-data/walkthrough.md
The following pages had the wrong URL embedded in the "Getting started" reference. This was first raised in https://github.com/owid/etl/issues/1046.
- https://docs.owid.io/projects/etl/en/latest/tutorials/adding-data/walkthrough/
- https://docs.owid.io/projects/etl/en/latest/tutorials/adding-data/manual/
> fix(docs): wrong url

- etl/steps/data/garden/faostat/2023-02-22/additional_variables.meta.yml
- etl/steps/data/garden/faostat/2023-02-22/additional_variables.py
- etl/steps/data/grapher/faostat/2023-02-22/additional_variables.py
Add table to dataset of FAOSTAT additional variables with data for cereal allocation (e.g. the share of cereals that are allocated to human food).
> Add cereal allocation data

- etl/steps/data/garden/regions/2023-01-01/regions.yml
`regions.yml` with East Timor is inconsistent with `countries_regions.csv` with Timor. That prevents us from region [centralisation in grapher](https://github.com/owid/owid-grapher/pull/2135). We have a migration prepared that would rename Timor -> East Timor, but that might take time and we want to unblock the grapher PR first.
> data(regions): rename East Timor back to Timor to stay consistent with ETL & grapher

- etl/steps/data/garden/un/2022-07-11/un_wpp/__init__.py
- etl/steps/data/garden/un/2022-07-11/un_wpp/population.py
We were trying to filter Sint Maarten before but using the ISO code. Instead, we should be using the complete country name.
TODO: review "natural_disasters" pipeline, seems to sanity check the countries in un_wpp. Now that Sint Maarten is missing, it fails.
> :bug: un: remove sint maarten inaccurate estimates

- etl/grapher_model.py
Following dicussion from https://github.com/owid/etl/pull/1106#discussion_r1197624562, I'm adding some methods to class `Chart` in our `etl.grapher_model` ORM.
What do you think, @Marigold? I was unsure if we wanted a `load_chart` or a `load_charts`. Or if one could use the logic of the other without making unnecessary calls to the table.
> :sparkles: grapher_model: new methods for Class

- etl/data_helpers/geo.py
- etl/harmonize.py
- etl/paths.py
- etl/steps/data/garden/owid/latest/key_indicators/__init__.py
- etl/steps/data/garden/owid/latest/key_indicators/table_land_area.py
- etl/steps/data/garden/owid/latest/key_indicators/utils.py
Key indicators were still using `from owid.datautils import geo` instead of `from etl.data_helpers import geo` which caused problems for nightly build. Fix this dependency by passing population directly.
@pabloarosado is this the right time to remove `geo` module from `datautils` package? Or do we want to keep it there for some reason?
> :bug: switch key_indicators from datautils.geo to data_helpers.geo

- etl/steps/data/garden/lgbt_rights/2023-04-27/lgbti_policy_index.meta.yml
- etl/steps/data/garden/lgbt_rights/2023-04-27/lgbti_policy_index.py
I have modified metadata to create clearer binary charts on Grapher. I have also fixed binary variables representing regressive policies: in those cases partial implementation of the law should be together with "yes".
I have temporarirly deactivated `set_index` to make the process work. See https://github.com/owid/etl/pull/1154
> Change metadata and vars in LGBT+ Policy dataset

- dag/agriculture.yml
- etl/steps/data/garden/agriculture/2023-04-20/long_term_wheat_yields.meta.yml
- etl/steps/data/garden/agriculture/2023-04-20/long_term_wheat_yields.py
Restrict long-term wheat yields dataset to European countries (since otherwise data for all other countries is redundant with FAOSTAT QCL).
> Restrict long-term wheat yields dataset to European countries

- etl/chart_revision/v2/schema.py
- etl/chart_revision/v2/updaters/variable_update.py
Corrects the case when either `properties.timelineMaxTime` or `properties.timelineMinTime` is set to `None` by removing the field.
> ✨ fix errors in chart config

- etl/steps/data/garden/wid/2023-01-27/shared.py
- etl/steps/data/garden/wid/2023-01-27/world_inequality_database.meta.yml
- snapshots/wid/2023-01-27/wid_indices.do
- snapshots/wid/2023-01-27/world_inequality_database.csv.dvc
Minor edit: Include the income share between the 90th and 99th percentiles (to construct stacked area charts) and recalculate the share of the middle 40% (because their components have a wider time rage than the variable p50p90 for share).
This is for charts in the all charts block of the new [inequality topic page](https://github.com/owid/owid-issues/issues/784).
> Add new variables for World Inequality Database

- etl/publish.py
Deleting old dataset from remote S3 catalog could cause problems when incrementing version of a dataset (and archiving an old one). With this PR and turning off [pruning](https://github.com/owid/etl/blob/master/etl/prune.py) all previous versions will stay in the catalog and in S3.
> :sparkles: don't remove datasets from remote catalog

- .env.example
- backport/datasync/datasync.py
- etl/config.py
- etl/grapher_import.py
- etl/grapher_model.py
- etl/publish.py
When running --grapher step, upload data to R2 rather than to S3. Note that catalog is still published to S3 (R2 migration is likely planned at some point,  there's [even PR](https://github.com/owid/etl/pull/583) that supports publishing to R2).
After this change, everyone will have to setup extra .env variables
```
R2_ACCESS_KEY=xxx
R2_SECRET_KEY=xxx
R2_ENDPOINT_URL=https://078fcdfed9955087315dd86792e71a7e.r2.cloudflarestorage.com
```
It'd keep working if people still push to S3 because there's a fallback in Cloudflare worker, but the sooner we start pushing to R2 the better.
> :tada: upload data to R2 instead of S3

- Makefile
Add `make format-all` to Makefile.
Also, improve the output message for `make help` (sorted commands alphabetically, added some that were missing)
> ✨ makefile: add `make format-all`, improve `make help`

- etl/helpers.py
- lib/catalog/owid/catalog/utils.py
- lib/catalog/tests/test_utils.py
It is often the case that the source codes their fields using `camelCase`. In such instances, we want to preserve the token separation with a `_` instead of a "lower- to upper-case" change.
An example:
- Currently: `numberOfParticipants` → `numberofparticipants`
- New: `numberOfParticipants` → `number_of_participants`
To this end, I've slightly modified our function `underscore` to perform camelCase to snake_case formatting. This is only triggered if the argument `camel_to_snake` is True. By default, this argument is set to False so we don't break any of the pipelines (i.e. some metadata files might expect the older formatting).
> ✨ underscore: format camelCase fields as snake_case

- etl/helpers.py
- etl/snapshot.py
- etl/steps/__init__.py
- lib/catalog/owid/catalog/s3_utils.py
- lib/catalog/owid/catalog/tables.py
- lib/datautils/owid/datautils/dataframes.py
- lib/datautils/owid/datautils/decorators.py
- lib/datautils/owid/datautils/format/__init__.py
- lib/datautils/owid/datautils/format/numbers.py
- lib/datautils/owid/datautils/google/__init__.py
- lib/datautils/owid/datautils/google/api.py
- lib/datautils/owid/datautils/google/sheets.py
- lib/datautils/owid/datautils/io/__init__.py
- lib/datautils/owid/datautils/io/archive.py
- lib/datautils/owid/datautils/io/df.py
- lib/datautils/owid/datautils/s3.py
- lib/walden/owid/walden/owid_cache.py
Reduce by about 40% the import time for `etl.helpers`, which by convention we're importing on all new steps, by lazy loading modules that might not be used.
Changes:
- :honeybee: only lazy dvc and papermill on demand
- :honeybee: lazy load boto3
- :honeybee: lazy load requests and grapher helpers
Benchmark with `time etl data://grapher/fasttrack/ --force --only`:
- 10.2s before the change
- 7.8s with lazy loading (~25% faster)
> :honeybee: Reduce import overhead of etl.helpers

- etl/steps/data/garden/lis/2023-01-18/shared.py
Minor update: the calculations originally were done by calculating the median dhi and the change was not applied to the metadata.
> Fix relative poverty indicators' names and descriptions on Luxembourg Income Study

- etl/steps/data/garden/excess_mortality/latest/excess_mortality/__init__.py
- etl/steps/data/garden/excess_mortality/latest/excess_mortality/excess_mortality.meta.yml
- snapshots/excess_mortality/latest/hmd_stmf.csv.dvc
- snapshots/excess_mortality/latest/wmd.csv.dvc
Having fixed `date_accessed: "2023-04-24"` in YAML metadata was preventing updates of excess mortality in the covid repo. This is a hotfix that sets `date_accessed` of all sources to the latest one.
Proper fix would involve propagating sources from snapshots through channels instead of defining them in YAML metadata. It'd be better to wait for metadata updates we're working on though and @pabloarosado way of propagating metadata (this would be a good proof of concept).
> :bug: set latest date_accessed for excess mortality

- docs/assets/site-logo.svg
- docs/dev/docs.md
- mkdocs.yml
The motivation for these changes is the fact that we are now linking users from our site to this documentation. In particular, we use the button "Read about our data pipeline" in data pages to link users to https://docs.owid.io/projects/etl.
**Main changes**:
- Change the navigation menu colour.
- Change site name.
- Changed default logo; now use OWID's.
- Fix minor typos.
**Preview changes**
Run 
```
mkdocs serve
```
from the project top directory.
**Currently**:
**After changes**:
> 📜 docs: styiling improvements

- etl/steps/data/garden/lis/2023-01-18/luxembourg_income_study.meta.yml
- snapshots/lis/2023-01-18/lis_abs_poverty.csv.dvc
- snapshots/lis/2023-01-18/lis_distribution.csv.dvc
- snapshots/lis/2023-01-18/lis_keyvars.csv.dvc
Update of the LIS dataset, because of a correction on US data for 2021, which has [_a major impact on poverty and inequality indicators_](https://www.lisdatacenter.org/news-and-events/the-us21-dataset-has-been-corrected/).
Part of the [inequality topic page](https://github.com/owid/owid-issues/issues/784).
> Update Luxembourg Income Study dataset with correction to US data

- etl/steps/data/explorers/poverty_inequality/2023-03-01/poverty_inequality.py
This is a minor edit to include a PIP explorer dataset only for inequality, which deletes regional aggregation as they don't have data (only for poverty).
There will be a performance improvement in the main explorer, because it is currently using the full `poverty_inequality` dataset (LIS + PIP + WID)
This is a continuation of the temporal work from https://github.com/owid/etl/pull/923, which will be replaced on the second semester by PIP inside the ETL.
This PR is done to solve the problem described in https://github.com/owid/owid-issues/issues/1063
> Add inequality explorer dataset for World Bank's Poverty and Inequality Platform

- etl/config.py
- etl/steps/__init__.py
- lib/catalog/owid/catalog/datasets.py
- lib/catalog/tests/test_datasets.py
We would like to have an API with support for many formats, including Parquet.
Previously we took the approach that the `data/` folder had an identical folder structure to the API, so we co-generated Parquet files for every dataset. Now we would like a different approach where we build a more compact catalog, then have a bake step for the API that generates secondary formats.
This PR drops Parquet autogeneration from every step, which will speed them up and reduce the size of the `data-catalog` repo going forward. It also adds a new counter that you can increment to trigger a full ETL rebuild. The counter is turned off, but would be enabled to actually deploy this feature and prune parquet from the catalog.
> :hammer: Remove parquet autogeneration

- snapshots/oecd/2023-06-06/income_distribution_database.csv.dvc
Update the inequality data for the [OECD IDD](https://stats.oecd.org//Index.aspx?QueryId=123861#), which was updated from the source two days after [I ingested it into the ETL](https://github.com/owid/etl/pull/1190).
Dataset update issue [here](https://github.com/owid/owid-issues/issues/646).
> Update OECD Income Distribution Database

- etl/steps/data/garden/country_profile/2022/overview.py
- etl/steps/data/garden/excess_mortality/latest/excess_mortality_economist/__init__.py
- lib/catalog/owid/catalog/catalogs.py
Remove the residual places where Parquet gets generated in our catalog:
- :hammer: remove parquet generation for the catalog index
- :hammer: disable parquet support for specific datasets
> :hammer: Remove further parquet generation

- lib/catalog/owid/catalog/meta.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/variables.py
We work in notebooks often, but today metadata is horrific to view in notebooks.
This PR adds rich HTML display of metadata to make it easier to read, and also adds a title to make it easier to distinguish a `Table` from a `DataFrame` and a `Variable` from a `Series`.
Before and after comparison: https://gist.github.com/larsyencken/5c9aedaaacba4f593d1b18d797cc2c00
It uses a completely generic approach that doesn't know anything about the metadata fields, so it will work just as well when new fields become available.
> :lipstick: Give catalog objects rich html versions

- lib/catalog/owid/catalog/datasets.py
- lib/catalog/tests/test_datasets.py
This change causes a warning to happen any time you save a table without a primary key. It also allows a strict mode in which the warning becomes an exception.
We are trying to move more metadata to the indicator level. The dimensions an indicator has is a really important piece of metadata that is make or break for automatically collecting, indexing and reusing the indicators.
The Buildkite tasks that build production data and do the nightly full build will not be run in strict mode. However, PRs will be run in strict mode. This is to avoid any downtime for the ETL, whilst strongly encouraging future changes to have a primary key.
> :hammer: Support strict primary key enforcement

- etl/steps/data/meadow/democracy/2023-03-02/vdem.meta.yml
Add the text
> Many countries in recent years receive high scores even though they are far from equal participation because the index scores them relative to the historical average across countries.
That is in the footnote of the [chart about Women's Political Participation Index](https://owid.cloud/admin/charts/6379/edit)
We needed to do this before advertising the [Women's Rights topic page](https://github.com/owid/owid-issues/issues/1044)
> Add disclaimer to the Women's Political Participation Index indicator (V-Dem)

- etl/steps/data/meadow/democracy/2023-03-02/vdem.meta.yml
Add the text
> Many countries in recent years receive high scores even though they are far from equal participation because the index scores them relative to the historical average across countries.
That is in the footnote of the [chart about Women's Political Participation Index](https://owid.cloud/admin/charts/6379/edit)
We needed to do this before advertising the [Women's Rights topic page](https://github.com/owid/owid-issues/issues/1044)
> Add description to women political empowerment index

- lib/catalog/owid/catalog/datasets.py
- lib/catalog/tests/test_datasets.py
Usually when an index is not unique, you haven't properly specified the dimensions of the data or done roll-ups that you need to.
We would enforce this for new PRs only.
> :hammer: raise strict mode error for non-unique index

- etl/steps/data/garden/lis/2023-01-18/luxembourg_income_study.meta.yml
Another minor change, removing the acronym for LIS in the source name
> fix: change name of the source for LIS

- backport/backport.py
- etl/scripts/faostat/create_new_snapshots.py
- etl/snapshot.py
- etl/steps/data/converters.py
- fasttrack/cli.py
- lib/walden/ingests/un_sdg.py
- snapshots/excess_mortality/latest/hmd_stmf.py
- snapshots/un/2023-01-24/un_sdg.py
- snapshots/worldbank_wdi/2023-05-29/wdi.py
Fields in `SnapshotMeta` like `source_published_by` are just flattened Source and License. Working with Sources and Licenses directly makes further changes to metadata easier.
I've been initially thinking about editing all snapshot YAML files and adding `source:` and `license:` entries there, but that'd be probably too much. To avoid that I'm converting those YAML fields to Source object on load.
> :hammer: Replace snapshot fields by source and license

- etl/steps/data/garden/lis/2023-01-18/luxembourg_income_study.meta.yml
- snapshots/lis/2023-01-18/lis_abs_poverty.csv.dvc
- snapshots/lis/2023-01-18/lis_distribution.csv.dvc
- snapshots/lis/2023-01-18/lis_keyvars.csv.dvc
- snapshots/lis/2023-01-18/lissy_ineq_pov.do
[Joe realized](https://github.com/owid/owid-issues/issues/377#issuecomment-1615902423) there were differences in market income estimations between the dataset I obtained with my code and the one appearing on [LIS' DART](https://dart.lisdatacenter.org/). The problem is that the code didn't address when one of the components of market income was an entire column of zeros.
To solve this I have introduced a check that is similar to my estimation of total consumption.
> fix: Remove wrong market income calculations for LIS

- etl/command.py
- etl/config.py
- etl/steps/__init__.py
- lib/catalog/owid/catalog/datasets.py
- tests/test_etl.py
Enable strict mode by default for all `garden` and `grapher` datasets, where `version` is `latest` or after `2023-06-25`.
Strict mode for now means the following:
- Every table must have a primary key
- Every primary key must uniquely identify a row
If either of these criteria fail then the step will refuse to build.
When building the ETL manually, you can override the default setting by running `etl --strict` or `etl --no-strict`.
> :hammer: enforce strict mode for new datasets

- etl/data_helpers/population.py
Current behaviour: 
```
import pandas as pd
from etl.data_helpers.population import add_population
data = {'country': ['Chad', 'Chad', 'Canada', 'Canada', 'Germany', 'Germany'],
'year': [2019, 2020, 2019, 2020, 2019, 2020],
'value': [10, 15, 5, 8, 12, 18]}
df = pd.DataFrame(data)
add_population(df, country_col = 'country', year_col= 'year' )
```
Throws the following error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Untitled-1 in line 8
3 data = {'country': ['Chad', 'Chad', 'Canada', 'Canada', 'Germany', 'Germany'],
4         'year': [2019, 2020, 2019, 2020, 2019, 2020],
5         'value': [10, 15, 5, 8, 12, 18]}
7 df = pd.DataFrame(data)
----> 8 add_population(df, country_col = …
```
> 🐛  Allowing dataframes without age column to be used in data_helpers.population.add_population()

- etl/steps/data/garden/energy_institute/2023-06-26/statistical_review_of_world_energy.py
Fixed a small bug that prevented aggregate regions to be added to the main garden table.
> fix(energy_institute): Fix missing regions in Statistical Review

- etl/config.py
- lib/catalog/owid/catalog/variables.py
Improve way we combine units when propagating metadata, to avoid spurious warnings.
This change affects for example the step `data://meadow/energy_institute/2023-06-26/statistical_review_of_world_energy`. Before this PR, it would raise many warnings on a melt operation, and with this PR it doesn't.
NOTE: I increased ETL_EPOCH to see if datadiff shows any relevant difference with this change.
> Improve the way we combine units when propagating metadata

- lib/catalog/owid/catalog/tables.py
- tests/test_etl_step_code.py
Following the discussion on https://github.com/owid/etl/pull/1315, I've reverted the arguments of our new `read_csv` and `read_excel` functions to coincide with those in pandas. To avoid importing hidden pandas modules, I had to redefine some types.
I also fixed a test that was failing when finding hidden jupyter notebook files.
> Minor improvements on table functions

- etl/db_utils.py
Case from ETL might not be respected since we match on the lower cased name. This PR makes the matching case-sensitive.
Merging this and manually running `etl energy_institute/2023-06-26/statistical_review_of_world_energy --grapher` should fix the [following chart](https://owid.cloud/admin/charts/1369/edit).
> :sparkles: case sensitive matching of entities

- etl/command.py
- etl/grapher_helpers.py
- etl/grapher_import.py
- etl/steps/__init__.py
- lib/catalog/owid/catalog/tables.py
Grapher step for `un_sdg` takes almost two hours now. That's because we use thousands of tables and grapher upsert only runs in parallel within table. This PR moves the parallelism up so that multiple tables can be processed in parallel. This makes `un_sdg` run about 10x faster.
> :sparkles: parallel upserts to grapher on table level

- etl/grapher_model.py
- etl/steps/data/garden/ophi/2023-07-05/multidimensional_poverty_index.meta.yml
- schemas/dataset-schema.json
- snapshots/ophi/2023-07-05/multidimensional_poverty_index.csv.dvc
@Marigold I am experimenting with two things:
1. Call values to fill three different source definitions that share parameters (in `source_common`)
2. Call the `sources` structure for each indicator (like in `cme_mpi_national` or `cme_mpi_urban`)
Is it possible to make placeholders work for (1) and (2)?
For (1) I thought I was doing right, but I have YAML warnings (strangely not for `hot` (?)):
I tried to use placeholders for (2), but I couldn't. For now, I was trying to use anchors, as in [here](https://github.com/owid/etl/blob/master/etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.meta.yml), but we are trying to avoid that.
> Include different sources by variable in Multidimensional Poverty Index

- etl/steps/data/grapher/energy/2023-07-10/electricity_mix.py
Add note about grapher admin timeline restriction in a chart of electricity mix dataset.
> Add note about grapher admin timeline restriction in a chart of electricity mix dataset

- etl/grapher_import.py
We assume that different sources have different names and optimise MySQL upserts based on it. This does not need to be true.
Fix this by creating sources even if a source with the same name exists, but has different published by or description field.
> :hammer: fix source name collision

- dag/animal_welfare.yml
- etl/steps/data/garden/animal_welfare/2023-08-01/uk_egg_statistics.meta.yml
- etl/steps/data/garden/animal_welfare/2023-08-01/uk_egg_statistics.py
- etl/steps/data/grapher/animal_welfare/2023-08-01/uk_egg_statistics.py
- etl/steps/data/meadow/animal_welfare/2023-08-01/uk_egg_statistics.py
- poetry.lock
- pyproject.toml
- snapshots/animal_welfare/2023-08-01/uk_egg_statistics.ods.dvc
- snapshots/animal_welfare/2023-08-01/uk_egg_statistics.py
Add Defra data on UK egg statistics.
Additionally, install a library to be able to open .ods files.
> Add uk egg statistics

- etl/grapher_import.py
- lib/catalog/owid/catalog/meta.py
Make source upserts more efficient and ensure that [different sources](https://github.com/owid/etl/pull/1410) with the same name are upserted correctly.
> :sparkles: improve performance of source upserts

- etl/grapher_model.py
There's an issue if `additionalInfo` is empty string.
> :bug: fix source upsert

- etl/match_variables.py
Command line tool `etl-match-variables` has a required input argument `output-file`, which points to the file where the variable mapping will be saved. If this file is not `JSON`, the export will fail.
This is currently not being checked, hence if the user of the tool was to insert an invalid value for `output-file` they will only realise at the very end (after investing time in building the variable mapping).
Hence, this PR sanity checks the value of `output-file` at first.
First raised in #1403
> ✨ match-variables: check validity of output_file

- lib/catalog/owid/catalog/meta.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/test_tables.py
Make all metadata classes hashable (i.e. enable `hash(obj)`) to allow usage of `set` or `unique` on those objects.
> :sparkles: make all metadata classes hashable

- etl/steps/data/garden/war/2023-07-18/cow.py
- etl/steps/data/garden/war/2023-07-20/brecke.py
- Add suffix `(COW)` to region names in COW dataset.
- In COW data, set values to missing (instead of zero) accordingly. This is because each dataset covers different year periods. (also added several checks).
- Intra-state conflicts: All NaNs after 2014.
- Inter-state conflicts: All NaNs after 2003.
- Extra-state conflicts: All NaNs after 2007.
- Non-state conflicts: All NaNs after 2005.
- Simplify regions in Brecke:
- Asia
- Central Asia
- East Asia
- South Asia
- Southeast Asia
- Africa
- East & south Africa
- North Africa
- West & Central Africa
- Americas
- North America, Central America and Caribbean
- South America
- Europe
- Eastern Europe
- Western Europe
- Middle East
- Middle East
- Correct wrongly classified wars. These were automatically classified as `internal`, using the …
> ✨ war: minor improvements

- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
Concat along column axis isn't preserving metadata fields other than those in `combine_variables_metadata`. Also add an error if trying to concat along rows with indices (not working at the moment).
> :sparkles: improve tables.concat

- etl/chart_revision/v2/schema.py
- etl/chart_revision/v2/updaters/variable_update.py
Chart config field `map.variableId` was recently renamed to `map.columnSlug` and changed the type to string. All entries in MySQL have been migrated, so there's no `map.variableId`.
Update this in `etl-chart-suggester`. This was tested on the [IHME data](https://github.com/owid/etl/issues/1437#issue-1841475289) from the parent issue.
> :bug: use map.columnSlug rather than map.variableId

- .env.example
- backport/datasync/data_metadata.py
- backport/datasync/datasync.py
- etl/compare.py
- etl/config.py
- etl/grapher_import.py
- etl/grapher_model.py
- etl/steps/data/grapher/animal_welfare/2023-08-01/global_hen_inventory.py
- scripts/data_parity.py
- tests/backport/datasync/test_data_metadata.py
Should be merged at the same time as https://github.com/owid/owid-grapher/pull/2507
Original issue https://github.com/owid/owid-grapher/issues/2474#issue-1815448106
Columns `variables.dataPath` and `variables.metadataPath` were useful for transitioning to Data API, but they're just complicating things now that we have cloudflare workers with fallbacks.
This PR replaces it by new env `DATA_API_ENV` that is your laptop username by default (which raises warning) or can be set to `production` or staging server name for instance.
> :hammer: deprecate dataPath and metadataPath in favour of ENV paths

- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/test_tables.py
- lib/catalog/tests/test_variables.py
Various improvements on metadata propagation:
* Propagate metadata when doing operations like `tb[["a", "b"]].sum(axis=1)` (idem for `prod`).
* Idem for operations like `tb[["a", "b"]] *= 2` and other similar operations.
* Add tests.
> Improve metadata propagation

- .dvcignore
- etl/snapshot.py
Backports currently took around minute due to huge number of DVC files. Better targeting of exclude in .dvcignore cuts this into several seconds.
> :sparkles: improve backport performance by undvcignoring single file

- backport/backport.py
- etl/command.py
- etl/scripts/faostat/create_new_snapshots.py
- etl/snapshot.py
- snapshots/backport/latest/dataset_5592_covid_testing_time_series_data__vietnam_exemplar_config.json.dvc
- snapshots/backport/latest/dataset_5592_covid_testing_time_series_data__vietnam_exemplar_values.feather.dvc
Allow backporting archived datasets. This is not meant to be used by ETL, but we need to store the data as snapshots to get rid of `data_values`. Running `etl --backport` doesn't run archived datasets.
> :sparkles: support for archived backported datasets

- lib/catalog/owid/catalog/utils.py
- lib/catalog/tests/test_utils.py
Underscoring in meadow step assigns titles to variables even if the underscoring doesn't change anything. It's safer to keep it as None.
> :bug: keep title as None if underscoring didn't change anything

- lib/catalog/owid/catalog/meta.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/test_tables.py
- lib/catalog/tests/test_variables.py
Add `Variable.copy(deep=True)` method. This fixes https://github.com/owid/etl/issues/1454. The method can be reused for other dataclasses (we could even add it to all by default with a decator, similarly to `@pruned_json`).
@pabloarosado I've noticed you implemented `Table.copy_metadata` method. There's already `Table.copy_metadata_from` that I believe does the same (and doesn't use `copy.deepcopy` which is quite slow). Do you think it'd be possible to unify them?
> :sparkles: add .copy methods to Variable and VariableMeta

- etl/steps/data/garden/health/2023-08-09/unaids.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/variables.py
* In some cases we created `_fields` as dict, but it should have been defaultdict
* replace `copy.deepcopy` by existing `.copy` methods
> :bug: fix missing VariableMeta

- etl/steps/data/garden/ihme_gbd/2019/shared.py
- etl/steps/data/grapher/ihme_gbd/2019/gbd_risk.py
- etl/steps/data/meadow/ihme_gbd/2019/shared.py
- In response to the recent issue with GBD prevalence percentages being the % of total cases rather than % of the population, I added a function to convert the percent variables to be 1000x the rate per 100,000 (where the denominator is population). 
- However, this doesn't make sense for the `gbd_child_mortality`, `gbd_risk` or `gbd_cause` datasets, in these cases, the denominator was DALYs and deaths, which is what we want. 
- Fix is just only using the `add_share_population()` on the `gbd_prevalence` and `gbd_mental_health` datasets.
> 🐛 Fixing the share of deaths variables in IHME GBD

- etl/steps/data/garden/war/2023-06-22/ucdp.meta.yml
- etl/steps/data/garden/war/2023-07-07/mars.meta.yml
- etl/steps/data/garden/war/2023-07-07/mars.py
- etl/steps/data/garden/war/2023-07-18/cow.meta.yml
- etl/steps/data/garden/war/2023-07-18/cow.py
- etl/steps/data/garden/war/2023-07-20/brecke.py
- etl/steps/data/garden/war/2023-07-21/prio_v31.meta.yml
- etl/steps/data/garden/war/2023-07-21/prio_v31.py
- etl/steps/data/garden/war/2023-08-05/cow_mid.meta.yml
- etl/steps/data/garden/war/2023-08-05/cow_mid.py
- Fixes in dataset descriptions (metadata)
- Fix metrics in COW - MID: `number_ongoing_conflicts` and`number_new_conflicts`:
-  for `region="World"`, and disaggregated by `hostility_type`. Some conflicts were double-counted (in multiple regions, with different hostility levels).
- Fix metrics in PRIO v3.1
- The estimate on battle deaths is often missing. In such cases, replace the `NAs` with the value given by the low estimate on battle deaths (low and high estimates are never missing).
> ✨ war: fixes

- lib/catalog/owid/catalog/meta.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
* merge both functions into `copy_metadata`
* remove unused arguments from `copy_metadata` to keep it simple
* make shallow copy by default for performance reasons (shouldn't affect any existing use)
> :hammer: merge functions copy_metadata and copy_metadata_from

- etl/steps/data/garden/war/2023-08-05/cow_mid.meta.yml
- etl/steps/data/garden/war/2023-08-05/cow_mid.py
- etl/steps/data/garden/war/2023-08-15/mie.py
- etl/steps/data/grapher/war/2023-08-08/cow_mid.py
Simplify the COW MID dataset.
- Only report one metric: number of ongoing conflicts.
- Report disaggregated by `region` and `fatality`.
- `fatality` describes a range of fatalities (lower and upper bounds) over the complete lifetime of a dispute globally.
- We include an "unknown" category for `fatality`.
> 📊  war: change format of COW MID dataset

- etl/steps/data/garden/war/2023-08-05/cow_mid.meta.yml
- etl/steps/data/garden/war/2023-08-05/cow_mid.py
- etl/steps/data/grapher/war/2023-08-08/cow_mid.py
Add old metrics, which were wrongly removed in https://github.com/owid/etl/pull/1509.
These include `number of ongoing disputes` and `number of new disputes` broken down by hostility level.
> 📊 war: improve COW - MID dataset

- apps/metadata_playground/app.py
- dag/walkthrough.yml
- etl/steps/data/garden/dummy/2020-01-01/dummy_full.meta.yml
- etl/steps/data/garden/dummy/2020-01-01/dummy_full.py
- etl/steps/data/grapher/dummy/2020-01-01/dummy_full.py
- etl/steps/data/meadow/dummy/2020-01-01/dummy_full.py
- snapshots/dummy/2020-01-01/dummy_full.csv.dvc
- snapshots/dummy/2020-01-01/dummy_full.py
I let metaplay now use either `dummy` or `dummy_full`. The latter is a new dataset that includes (almost) all metadata fields with their names (when possible). I've also tried to express the fallback options, e.g.
```yaml
title: "[grapher-config.title > indicator.title]"
```
I'm not sure if all of them are true (in fact I know that `subtitle: "[grapher-config.subtitle > indicator.description-short]"` is not true, but I think it should be), but precisely for this reason I created this dataset, to be able to play around with the metadata fields and see how the resulting grapher chart/data page changes.
> Create dummy full dataset

- Makefile
- apps/metadata_playground/app.py
- apps/metadata_playground/cli.py
- etl/config.py
- etl/files.py
- etl/helpers.py
- etl/steps/__init__.py
- tests/test_helpers.py
* When running `DEBUG=1 etl ...` don't fork new processes, but keep it all in the same env. That subtracts about 2s from each ETL step
* Run `etl-metaplay` in DEBUG mode (rendering goes down from ~30s to ~5s)
* Check `apps` for linting errors
> :hammer: speed up ETL in DEBUG mode

- etl/snapshot.py
- etl/steps/data/converters.py
Propagate both sources and origins from snapshot. This makes incremental migration from sources to origins easier.
> :bug: allow both sources and origins

- etl/command.py
- etl/steps/data/meadow/dummy/2020-01-01/dummy.py
Buildkite [collapses sections](https://buildkite.com/docs/pipelines/managing-log-output#collapsing-output) prefixed with `---`. This should declutter outputs we get from ETL builds.
Example
> :lipstick: add sections for buildkite logs

- etl/steps/data/garden/un/2023-08-16/un_sdg.countries.json
The UN renamed [the Netherlands to the Kingdom of the Netherlands](https://unterm.un.org/unterm2/en/view/08960271-ea69-4614-8f58-7952a92c6e94). I originally kept this as a separate entity but I think now it is okay to move back to using the Netherlands.
> 🐛  Kingdom of the Netherlands -> Netherlands

- etl/steps/data/garden/war/2023-06-22/ucdp.meta.yml
- etl/steps/data/garden/war/2023-06-22/ucdp.py
- etl/steps/data/garden/war/2023-07-20/brecke.py
- etl/steps/data/garden/war/2023-07-21/prio_v31.meta.yml
- etl/steps/data/garden/war/2023-07-21/prio_v31.py
- Brecke dataset: Fixed region "America" → "Americas"
- UCDP and PRIO v3.1 datasets: Changed region "Asia" → "Asia and Oceania"
> 🐛 war: region names

- etl/steps/data/garden/wid/2023-08-24/shared.py
- etl/steps/data/garden/wid/2023-08-24/world_inequality_database.py
- snapshots/wid/2023-08-24/wid_indices.do
Add relative poverty measures (headcount ratio, 40, 50 and 60% of the median) by estimating 40, 50 and 60% of the median and checking that value against the closest thresholds in the newly created percentile file.
> Add relative poverty in WID

- etl/steps/data/garden/ggdc/2022-11-28/penn_world_table.meta.yml
- etl/steps/data/garden/ggdc/2022-11-28/penn_world_table.py
We have decided to modify Penn World Table to exclude datapoints considered outliers by the source, given that GDP in those cases is very low or very unstable.
See conversation [here](https://github.com/owid/owid-issues/issues/1060). OWID issue [here](https://github.com/owid/owid-issues/issues/1204).
This fix will be also implemented in the [PWT update](https://github.com/owid/owid-issues/issues/931).
> Filter out outlier values in Penn World Table

- etl/grapher_helpers.py
- etl/steps/data/garden/war/2023-06-22/ucdp.meta.yml
- etl/steps/data/garden/war/2023-07-07/mars.meta.yml
- etl/steps/data/garden/war/2023-07-18/cow.meta.yml
- etl/steps/data/garden/war/2023-07-20/brecke.meta.yml
- etl/steps/data/garden/war/2023-07-21/prio_v31.meta.yml
- etl/steps/data/garden/war/2023-08-05/cow_mid.meta.yml
- etl/steps/data/garden/war/2023-08-15/mie.meta.yml
- etl/steps/data/grapher/war/2023-06-26/ucdp.py
- etl/steps/data/grapher/war/2023-07-14/mars.py
- etl/steps/data/grapher/war/2023-07-20/brecke.py
- etl/steps/data/grapher/war/2023-07-21/prio_v31.py
- etl/steps/data/grapher/war/2023-07-26/cow.py
- etl/steps/data/grapher/war/2023-08-08/cow_mid.py
- etl/steps/data/grapher/war/2023-08-15/mie.py
Fix for https://github.com/owid/etl/issues/1548
This PR adds support for Jinja2 templating (using `<%` tags instead of standard `{{` because it would collide with `dynamic_yaml` that we use for placeholders). This is especially helpful for long tables where we want to construct titles or descriptions on the fly and the combinations grow exponentially (see [these descriptions](https://docs.google.com/spreadsheets/d/1Z3fWwUJhafUBc75YY2KsO0Cj8VW3XpzwA9P8tHqDfPA/edit#gid=0)).
Dimensions with values are passed to the template and we can use ifs & variables from Jinja2 to get what we want without repetition.
It's a bit annoying to get whitespaces right in Jinja. I recommend setting `DEBUG=1` flag to speed up ad-hoc etl builds and then check back and forth with grapher.
@lucasrodes I've …
> :tada: enable Jinja2 templating in metadata

- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
Make it possible to use
```
description_key_common: &description_key_common
- &text_1 Text 1
- &text_2 Text 2
tables:
test:
variables:
a:
description_key:
- *description_key_common
- *text_2
- Text 3
```
> :tada: flatten description key

- schemas/dataset-schema.json
- schemas/definitions.json
- schemas/snapshot-schema.json
Update metadata documentation in schemas.
> Update metadata documentation

- etl/command.py
- etl/config.py
- etl/files.py
- etl/grapher_import.py
- etl/helpers.py
- etl/steps/__init__.py
- schemas/snapshot-schema.json
- tests/test_files.py
* Add `etl --watch` that constantly scans for changes to files and rebuilds datasets
* Add `GRAPHER_FILTER` for filtering which indicators to upsert (useful when working on a single indicator from large dataset)
* Fix behaviour of `--only` flag to run ONLY the steps matching pattern and not their dependencies
* Improve performance of grapher upserts
* Fix indentation of saved YAML files
Let's say that you work on metadata for variable `ahdi` from dataset `ahdi/2023-09-08/augmented_hdi`. You open the data page on your staging server and run
```
GRAPHER_FILTER=ahdi ENV=.env.mojmir etl ahdi/2023-09-08/augmented_hdi --grapher --watch
```
which constantly watches changes you make and updates the data page in about 6s (you have to refresh it manually).
> :tada: ETL --watch mode

- lib/datautils/poetry.lock
- lib/walden/poetry.lock
- poetry.lock
- pyproject.toml
Updating dependencies to close some of the dependabot PRs.
Changes:
* update all packages
* remove `jupytext`
* move mkdocs to dev dependencies
* update `mkdocs`
Fixes https://github.com/owid/etl/issues/1580
> :honeybee: update dependencies

- etl/publish.py
We're occasionally getting [IncompleteRead errors](https://buildkite.com/our-world-in-data/etl-deploy-master/builds/2254#018aac86-0079-422d-97a0-7f5ab0014e35) when publishing. Try retrying them.
> :bug: retry IncompleteRead error when publishing

- apps/walkthrough/garden.py
- apps/wizard/templating/garden.py
- etl/grapher_model.py
- lib/catalog/owid/catalog/meta.py
- lib/catalog/owid/catalog/tables.py
- schemas/dataset-schema.json
- schemas/snapshot-schema.json
Don't raise a warning when `variable.licenses` is missing. Using `origin.license` is preferred. Also show linter error in YAML files when the field is present.
> :sparkles: discourage use of variable.licenses

- apps/wizard/templating/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.{{cookiecutter.file_extension}}.dvc
- apps/wizard/templating/snapshot.py
Remove `licenses` from `$.meta`.
This complements https://github.com/owid/etl/pull/1638, and fixes the wizard bug:
```
File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 548, in _run_script
self._session_state.on_script_will_rerun(rerun_data.widget_states)
File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 68, in on_script_will_rerun
self._state.on_script_will_rerun(latest_widget_states)
File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 486, in on_script_will_rerun
self._call_callbacks()
File "/home/lucas/repos/etl/.venv/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line …
```
> 🐛 wizard: remove licenses field

- apps/wizard/templating/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.{{cookiecutter.file_extension}}.dvc
- apps/wizard/templating/snapshot.py
This PR changes how the attribution field is field in Snapshot.
To test it, you can run
```
etl-wizard --dummy-data
```
Then, play with the input field `origin.attribution`. In particular, you can:
- Choose first format option: `origin.attribution` will not be added to the metadata yaml file.
- Choose the second format option: `origin.attribution` with the desired format.
- Choose the custom option and input it yourself. This value will be added to `origin.attribution` in the metadata.
---
This PR includes the fix from https://github.com/owid/etl/pull/1640
> ✨ wizard: limit options of attribution

- apps/wizard/templating/garden.py
- etl/metadata_export.py
Generating YAML metadata with `etl-metadata-export ...` isn't needed anymore now that wizard generates reasonable YAML file and we don't have to repeat metadata in the garden step.
I removed the optional instruction to run `etl-metadata-export` and also fixed the function in case anyone uses it to prune fields like `origins` or `licenses` that aren't useful anymore.
> :hammer: remove etl-metadata-export from wizard instructions

- apps/wizard/templating/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.{{cookiecutter.file_extension}}.dvc
- schemas/definitions.json
- Use `|-` for `citation_full` in `origin` metadata template. This prevents weird errors (e.g. when citation full contains `:`).
- Accept numeric values for `version_producer`. Sometimes the version might just be a number (e.g. `3.2`) or a year (`2016`). Let's accept these and stop showing error messages when this is the case.
> ✨ wizard: minor enhancements

- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/test_variables.py
Avoid propagating metadata fields (titles, units and descriptions) of the denominator, when dividing two variables.
When dividing a variable by another, it only makes sense to keep the metadata values of the first variable. For example, if we have energy (without description) and population (with a description), when calculating energy per capita, the result shouldn't have the description of population. It should have no description.
This PR would fix for example [this chart](https://owid.cloud/admin/charts/4451/edit) of electricity per capita. The sources tab shows the description of population.
In a separate PR we can add similar logic to display and presentation.
> Avoid propagating metadata on division

- etl/grapher_helpers.py
- etl/grapher_model.py
- etl/helpers.py
- etl/steps/data/grapher/gcp/2023-07-10/global_carbon_budget.meta.yml
- etl/steps/data/grapher/gcp/2023-07-10/global_carbon_budget.py
- lib/catalog/owid/catalog/datasets.py
- lib/catalog/owid/catalog/meta.py
- lib/catalog/owid/catalog/tables.py
[JSON Data Page](https://ourworldindata.org/grapher/consumption-co2-per-capita)
[ETL Data Page](http://staging-site-mojmir/admin/datapage-preview/738081)
Command for "live" reloading of Data Page
```
ENV=.env.mojmir GRAPHER_FILTER=consumption_emissions_per_capita etl grapher/gcp/2023-07-10/global_carbon_budget --grapher --watch
```
- Topic tags links redirect to non-existing pages and they have different names than those on the data page (I took topic names from [datasette](http://datasette-private/owid?sql=SELECT+tags.%60name%60+from+tags+where+isTopic+%3D+1+ORDER+BY+tags.%60name%60%0D%0A))
- [FAQ GDoc](https://owid.cloud/admin/gdocs/1gGburArxglFdHXeTLotFW4TOOLoeRq5XW6UfAdKtaAw/preview) doesn't work well with staging server, since it only gets saved to live MySQL. I had to replicate it …
> :hammer: migrate JSON Data Page - Per capita consumption-based CO₂ emissions

- etl/steps/data/garden/wvs/2023-06-25/longitudinal_wvs.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
- lib/repack/README.md
- lib/repack/owid/repack/__init__.py
- lib/repack/pyproject.toml
- lib/repack/tests/test_repack.py
* Improve repack performance (speeds up `garden/faostat/2023-06-12/faostat_scl` by 10x)
* Fix groupby with `count` column
> :sparkles: Improve repack performance and fix groupby

- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
Fix for https://github.com/owid/etl/issues/1698. Thanks @lucasrodes, I didn't know `agg` accepts kwargs.
> :bug: add kwargs to Table.groupby.agg

- apps/backport/migrate/migrate.py
- dag/education.yml
- dag/migrated.yml
- etl/metadata_export.py
- etl/snapshot.py
- etl/steps/data/garden/education/2017-09-30/public_expenditure.meta.yml
- etl/steps/data/garden/education/2017-09-30/public_expenditure.py
- etl/steps/data/garden/education/2018-04-18/literacy_rates.meta.yml
- etl/steps/data/garden/education/2018-04-18/literacy_rates.py
- etl/steps/data/garden/wb/2023-07-10/education.py
- etl/steps/data/grapher/education/2017-09-30/public_expenditure.py
- etl/steps/data/grapher/education/2018-04-18/literacy_rates.py
- snapshots/backport/latest/dataset_242_public_expenditure_on_education_oecd__tanzi__and__schuknecht__2000_config.json.dvc
- snapshots/backport/latest/dataset_242_public_expenditure_on_education_oecd__tanzi__and__schuknecht__2000_values.feather.dvc
- snapshots/backport/latest/dataset_2762_cross_country_literacy_rates__world_bank__cia_world_factbook__and_other_sources_config.json.dvc
- snapshots/backport/latest/dataset_2762_cross_country_literacy_rates__world_bank__cia_world_factbook__and_other_sources_values.feather.dvc
- snapshots/education/2017-09-30/public_expenditure.feather.dvc
- snapshots/education/2017-09-30/public_expenditure.py
- snapshots/education/2018-04-18/literacy_rates.feather.dvc
- snapshots/education/2018-04-18/literacy_rates.py
Backport [literacy rates](https://owid.cloud/admin/datasets/2762) with
```
ENV=.env.prod backport-migrate --dataset-id 2762 --namespace education --version 2018-04-18 --short-name literacy_rates
```
Backport [public expenditure on education](https://owid.cloud/admin/datasets/242) with
```
ENV=.env.prod backport-migrate --dataset-id 242 --namespace education --version 2017-09-30 --short-name public_expenditure
```
Once these datasets are merged, we should run `ENV=.env.prod.write walkthrough charts` to migrate their charts and delete old datasets.
1. Markdown in `snapshots/education/2018-04-18/literacy_rates.feather.dvc` doesn't show list properly, not sure what am I doing wrong?
2. Source fields `Variable geographic coverage` and `Data publisher's source` are not available in ETL …
> :bar_chart: backport literacy rates and public expenditure on education to ETL

- etl/steps/data/meadow/who/latest/flunet.py
- lib/repack/owid/repack/__init__.py
`who/latest/flunet` step was failing because column `aother_subtype_details` contains mix of everything (floats, nans, strings, ...) and repack wasn't able to convert it to category. Converting it to string (while preserving nans) fixes it.
@spoonerf I'm gonna merge this now to fix ETL, but could you still take a look?
> :bug: fix aother_subtype_details column in flunet

- etl/grapher_import.py
- etl/grapher_model.py
We rarely end up with duplicate origins in the `origins` table. The current script assumes uniqueness, but that's tricky to do because having unique constraint on all columns is impossible and ensuring no race conditions is tricky too (honestly, I don't know how can we end up with duplicate origins. There are locks when upserting to `origins`). Anyway, having multiple origins is not such a big deal (especially since we might clean them up later).
This PR makes it robust to duplicate origins.
> :bug: fix duplicate origins

- dag/migrated.yml
- etl/steps/data/garden/agriculture/2023-10-04/share_of_agriculture_in_gdp.meta.yml
- etl/steps/data/garden/agriculture/2023-10-04/share_of_agriculture_in_gdp.py
- etl/steps/data/grapher/agriculture/2023-10-04/share_of_agriculture_in_gdp.py
- snapshots/agriculture/2023-10-04/share_of_agriculture_in_gdp.feather.dvc
- snapshots/agriculture/2023-10-04/share_of_agriculture_in_gdp.py
- snapshots/backport/latest/dataset_3009_share_of_agriculture_in_gdp_at_current_prices__herrendorf_et_al__and_ggdc_10_data__split_config.json.dvc
- snapshots/backport/latest/dataset_3009_share_of_agriculture_in_gdp_at_current_prices__herrendorf_et_al__and_ggdc_10_data__split_values.feather.dvc
Backported with
```
ENV=.env.prod backport-migrate --dataset-id 3009 --namespace agriculture --version 2017-03-08 --short-name share_of_agriculture_in_gdp
```
> :left_arrow: backport share of agriculture in GDP

- etl/run_python_step.py
- etl/steps/__init__.py
With this, you'll be able to import files without relative imports. Absolute imports let you use VSCode code interpreter.
> :bug: add proper path to pythonpath if step is a module

- .vscode/launch.json
- apps/wizard/templating/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.{{cookiecutter.file_extension}}.dvc
- apps/wizard/templating/snapshot.py
- schemas/definitions.json
- Fixes indentation in `origin.citation_full` (see #1752).
- Improves uploading message in snapshot step (see #1753).
- Update docs and schema to stop encouraging the usage of `date_published: latest`.
> 🐛 wizard: minor fixes

- etl/steps/data/garden/un/2023-08-16/igme.meta.yml
- etl/steps/data/garden/un/2023-08-16/igme.py
- etl/steps/data/garden/un/2023-08-29/long_run_child_mortality.py
- etl/steps/data/grapher/un/2023-08-16/igme.py
- snapshots/un/2023-08-16/igme.zip.dvc
Splitting the under fifteen mortality out into a different table, to make it easier to give it slightly amended metadata as it is a combination of two vintages of UN IGME.
> 🔧  Fixing UN IGME metadata

- schemas/dataset-schema.json
Update metadata guidelines, now that `description_key` should not include `description_short`.
There may be cases of recent datasets where `description_key` includes `description_short`, but this is not too bad (just a bit redundant). We can tackle them in the future as we see them.
> Update metadata guidelines

- lib/catalog/owid/catalog/tables.py
`Table.to_csv()` failed when passing `index=False`. This PR should fix that.
> Fix to_csv failing when having 'index' as an argument

- lib/catalog/README.md
- lib/catalog/pyproject.toml
Bump owid catalog version and update the changelong.
For context, I'm trying to use `catalog.find` in the `co2-data` repos, and it raises an error, which doesn't happen when using the same command from the current ETL. I haven't looked into it, but I suppose that upgrading `owid-catalog` should fix the issue.
> Bump owid catalog version

- lib/catalog/pyproject.toml
Instead of 0.4.0, use 0.3.7 (this avoid incompatibility issues with datautils).
> Fix owid-catalog version

- lib/catalog/README.md
- lib/catalog/poetry.lock
- lib/catalog/pyproject.toml
- poetry.lock
- pyproject.toml
Fix for https://github.com/owid/etl/issues/1789. The issue happens only in python3.9 and dataclasses-json versions >5.8. Let's pin it to 5.8 for now.
> :bug: Fix dataclasses-json error

- docs/architecture/index.md
- docs/architecture/metadata/faqs.md
- docs/architecture/metadata/index.md
- docs/architecture/metadata/propagation.md
- etl/docs.py
- mkdocs.yml
- schemas/dataset-schema.json
- schemas/definitions.json
Following our latest discussions and changes:
* Update metadata guidelines.
* Fix some small typos.
* Add section about indicator titles to the metadata documentation.
> 📜 Update metadata guidelines, fix typos, and add section about indicator titles

- dag/main.yml
- etl/steps/data/garden/countries/2023-09-25/gleditsch.countries.json
- etl/steps/data/garden/countries/2023-09-25/gleditsch.meta.yml
- etl/steps/data/garden/countries/2023-09-25/gleditsch.py
- etl/steps/data/garden/countries/2023-09-25/isd.meta.yml
- etl/steps/data/garden/countries/2023-09-25/isd.py
- etl/steps/data/garden/countries/2023-09-25/shared.py
- etl/steps/data/garden/countries/2023-09-29/cow_ssm.meta.yml
- etl/steps/data/garden/countries/2023-09-29/cow_ssm.py
- etl/steps/data/garden/war/2023-09-21/brecke.meta.yml
- etl/steps/data/garden/war/2023-09-21/brecke.py
- etl/steps/data/garden/war/2023-09-21/cow.meta.yml
- etl/steps/data/garden/war/2023-09-21/cow.py
- etl/steps/data/garden/war/2023-09-21/cow_mid.py
- etl/steps/data/garden/war/2023-09-21/mars.meta.yml
- etl/steps/data/garden/war/2023-09-21/mars.py
- etl/steps/data/garden/war/2023-09-21/mie.meta.yml
- etl/steps/data/garden/war/2023-09-21/mie.py
- etl/steps/data/garden/war/2023-09-21/prio_v31.meta.yml
- etl/steps/data/garden/war/2023-09-21/prio_v31.py
- etl/steps/data/garden/war/2023-09-21/shared.py
- etl/steps/data/garden/war/2023-09-21/ucdp.meta.yml
- etl/steps/data/garden/war/2023-09-21/ucdp.py
- Add population in each region in the 'states in region' datasets
- Add conflict mortality indicators to all war datasets. This is basically normalising the number of deaths by the region population.
> 📊 war: add conflict mortality indicators

- etl/steps/data/garden/demography/2023-10-09/life_expectancy.py
Adding age groups 10, 25 and 45 to our Life Expectancy OMM. This will be added to https://owid.cloud/admin/charts/7287/edit.
> 📊 demography: add age groups to omm

- etl/steps/data/grapher/wb/2022-10-03/world_bank_pip.meta.yml
- etl/steps/data/grapher/wid/2023-08-24/world_inequality_database.meta.yml
Migrate JSON-based Data pages to ETL-based Data page by adding metadata to its grapher step. I tried to match the original Data page as closely as possible, which means some metadata fields might not **adhere to our guidelines**. I moved [FAQs to its GDoc](https://docs.google.com/document/d/1gGburArxglFdHXeTLotFW4TOOLoeRq5XW6UfAdKtaAw/edit) and used official topic tags names.
@paarriagadap  could you please check the Data Page for any issues? You are also encouraged to update metadata in the YAML file according to guidelines. Commented lines are metadata from the ETL dataset, you should delete them if they're not helpful. **Add commits to this PR** as you wish!
- [Extreme poverty JSON](https://ourworldindata.org/grapher/share-of-population-in-extreme-poverty) -> [Extreme poverty …
> :bar_chart: migrate JSON data page for PIP indicators

- docs/architecture/metadata/faqs.md
- Change `grapher_config.title` to `presentation.grapher_config.title`
- The hierarchy for the title of the data page was wrong
- wrong: `presentation.title_public > grapher_config.title > display.name > indicator.title`
- correct: `presentation.title_public > presentation.grapher_config.title > indicator.title`
> 📜 fix hierarchy error in indicator name

- docs/architecture/metadata/faqs.md
Hierarchies were wrongly defined. They might be updated soon, watch out:
- https://github.com/owid/owid-grapher/issues/2756
> 📜 fix indicator name usage

- dag/open_numbers.yml
We only use two datasets from [Open numbers initiative](https://github.com/open-numbers), but we still download and republish all the other ones. Those unused datasets use up **almost 28gb** in `.owid/git/`, and they slow down all `etl` runs because we have to compare etags against their github repos.
Disabling these datasets would considerably improve performance of our nightly and full ETL runs as well as automated ETL servers. The only reason for keeping them here was if someone was using them through `owid-catalog`, but I don't think anyone does that.
> :hammer: disable unused open numbers datasets

- etl/steps/data/grapher/energy/2023-07-10/electricity_mix.py
Add sanity check to latest electricity mix grapher step.
This will not fix https://github.com/owid/owid-issues/issues/1256, but it will serve as a reminder of how to identify some of the affected rows in the data.
> Add sanity check to latest electricity mix grapher step

- dag/emissions.yml
- etl/steps/data/garden/emissions/2023-10-24/emission_factors.meta.yml
- etl/steps/data/garden/emissions/2023-10-24/emission_factors.py
- etl/steps/data/grapher/emissions/2023-10-24/emission_factors.py
- etl/steps/data/meadow/emissions/2023-10-24/emission_factors.py
- snapshots/emissions/2023-10-24/emission_factors.py
- snapshots/emissions/2023-10-24/emission_factors.xlsx.dvc
Add snapshots, meadow, garden and grapher steps for CO2 emission factors.
This is a very small dataset that we used to have [here](https://owid.cloud/admin/datasets/970). I thought we would find more updated emission factors, but the best data I've found from [the official source](https://www.ipcc-nggip.iges.or.jp/EFDB/) comes from the same document, from 2006. However, I think those factors are still used as reference values.
> 📊 Create IPCC CO2 emission factors dataset

- dag/demography.yml
- etl/steps/data/garden/demography/2023-10-20/broken_limits_le.py
Previously, we were including only countries present in HMD _**pre-1959**_. With this change, we consider all countries since they first appear in HMD dataset. E.g. if Ukrain starts being reported in HMD since 1959, we consider its values since 1959.
This is done even if we use UN WPP data post-1950.
> 🐛 demography: change countries included

- etl/steps/data/garden/worldbank_wdi/2023-05-29/wdi.meta.yml
Migrate [JSON-based Data page](https://ourworldindata.org/grapher/share-of-individuals-using-the-internet) to [ETL-based Data page](http://staging-site-mojmir/admin/datapage-preview/735493) by adding metadata to its grapher step. I tried to match the original Data page as closely as possible, which means some metadata fields might not **adhere to our guidelines**. I moved [FAQs to its GDoc](https://docs.google.com/document/d/1gGburArxglFdHXeTLotFW4TOOLoeRq5XW6UfAdKtaAw/edit) and used official topic tags names.
@danyx23 could you please check the Data Page for any issues? You are also encouraged to update metadata in the YAML file according to guidelines. Commented lines are metadata from the ETL dataset, you should delete them if they're not helpful. **Add commits to this PR** as you …
> :bar_chart: migrate JSON data page for internet usage

- apps/wizard/templating/cookiecutter/garden/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.meta.yml
- apps/wizard/templating/garden.py
- apps/wizard/utils.py
- etl/db.py
- etl/grapher_model.py
- schemas/definitions.json
Test it by using `etl-wizard garden`
> ✨ wizard: add tag field in garden, fix license options

- dag/war.yml
- etl/steps/data/garden/war/2023-09-21/ucdp.py
- etl/steps/data/garden/war/2023-09-21/ucdp_prio.meta.yml
- etl/steps/data/garden/war/2023-09-21/ucdp_prio.py
There is no data on the number of deaths from extrasystemic conflicts after 1989. We fill these with zeroes so charts on Grapher look nicer.
> 📊 war: fill with zeroes

- docs/architecture/metadata/structuring-yaml.md
- lib/catalog/owid/catalog/yaml_metadata.py
- schemas/dataset-schema.json
Enable writing table-specific common metadata like this
```
tables:
my_table:
common:
display:
numDecimalPlaces: 1
```
> :tada: tables.<table_name>.common section

- apps/wizard/charts/utils.py
- etl/grapher_model.py
Occasionally, we rename variables in a dataset, which disrupts the ETL process because some charts still reference the old variable names and cannot be deleted. The error appears as follows:
```
ValueError: Variables used in charts will not be deleted automatically:
chartId  variableId
0      3405      812319
1       714      812319
2      2328      812319
3      3446      812319
4      2724      812319
```
To resolve this, we must remap the old variables to the new ones and rerun the ETL process, which will remove those old variables. This can be particularly challenging if the dataset is extensive. In such cases, using `etl-wizard charts` can be very beneficial. However, there is an issue where the wizard maps "old" variables to themselves, causing the process to fail. This PR addresses …
> :sparkles: don't map onto same variables in wizard charts

- etl/config.py
This lets you use
```
STAGING=mojmir etl igme --grapher
```
which will load your `.env` and point environment variables to server `staging-site-mojmir`. You won't have to keep multiple `.env.*` files for staging servers anymore.
> :tada: add STAGING env for accessing staging-site-*

- dag/emissions.yml
- etl/steps/data/garden/emissions/2023-11-06/global_warming_potential_factors.meta.yml
- etl/steps/data/garden/emissions/2023-11-06/global_warming_potential_factors.py
- etl/steps/data/grapher/emissions/2023-11-06/global_warming_potential_factors.py
- etl/steps/data/meadow/emissions/2023-11-06/global_warming_potential_factors.py
- snapshots/emissions/2023-11-06/global_warming_potential_factors.csv.dvc
- snapshots/emissions/2023-11-06/global_warming_potential_factors.py
Create a very simple dataset with the GWP-100 factors for a list of greenhouse gases, from the IPCC AR6 (to replace [this dataset](https://owid.cloud/admin/datasets/860) based on AR5).
> Update global warming potential factors

- etl/steps/data/garden/emdat/2023-09-20/natural_disasters.meta.yml
- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/conftest.py
- lib/catalog/tests/test_variables.py
- snapshots/emdat/2023-09-20/natural_disasters.xlsx.dvc
* Propagate `description_key` when doing variable operations.
* Add tests.
* Some small improvements on natural disasters metadata (some require the propagation of `description_key` to show up in charts).
> Combine new metadata fields

- schemas/definitions.json
Ensure that we include the year in the full citation of an origin (as [suggested by Lars](https://owid.slack.com/archives/C064666EG8K/p1699357652810009)).
> Minor improvement in metadata documentation

- etl/steps/data/grapher/worldbank_wdi/2023-05-29/wdi.meta.yml
Migrate [JSON-based Data page](https://ourworldindata.org/grapher/share-of-children-younger-than-5-who-suffer-from-stunting) to [ETL-based Data page](http://staging-site-mojmir/admin/datapage-preview/735978) by adding metadata to its grapher step. I tried to match the original Data page as closely as possible, which means some metadata fields might not **adhere to our guidelines**. I moved [FAQs to its GDoc](https://docs.google.com/document/d/1gGburArxglFdHXeTLotFW4TOOLoeRq5XW6UfAdKtaAw/edit) and used official topic tags names.
@lucasrodes could you please check the Data Page for any issues? You are also encouraged to update metadata in the YAML file according to guidelines. Commented lines are metadata from the ETL dataset, you should delete them if they're not helpful. **Add commits to …
> :bar_chart: migrate JSON data page for children stunting

- etl/steps/data/garden/demography/2023-03-31/population/population.meta.yml
* I changed `description_key` -> `description_short` in all indicators in the population dataset.
* I also changed `·` with `-` in a list of bullet points (which should render properly as a list).
@lucasrodes @Marigold do you see any unintentional risks on these changes? And do you remember if there was any particular reason why we were using `description_key` for those short descriptions? Thanks.
**NOTE**: This PR should be merged at the end of the day, since it will trigger a big ETL run.
> Use description key as description short in population indicators

- etl/steps/data/grapher/worldbank_wdi/2023-05-29/wdi.meta.yml
Define origins only to the specific indicator that is used in a data page, and keep all other indicators with sources.
> Fix WDI origins

- apps/wizard/templating/garden.py
- docs/architecture/metadata/structuring-yaml.md
- etl/metadata_export.py
Some time ago, I removed `etl-metadata-export` for no good reason. It turned out people are still using it for pre-generating YAML files with indicators.
This PR puts a mention about it back to Wizard and adds some options to the tool like `--decimals` that automatically detect number of decimal places.
> :sparkles: Reintroduce `etl-metadata-export` and add more options

- etl/data_helpers/geo.py
- tests/data_helpers/test_geo.py
Speed up add_regions_aggregates by avoiding for loop over variables. This is very noticeable for datasets with 100+ variables.
Also add unit test to clarify what happens if mandatory country has NaN values (@pabloarosado  this is not a but, it works in the end)
> :sparkles: Speedup add_regions_aggregates

- etl/helpers.py
- etl/steps/data/meadow/rff/2023-10-19/emissions_weighted_carbon_price.py
- lib/catalog/owid/catalog/tables.py
The problem is in [these lines](https://github.com/owid/etl/blob/master/etl/steps/data/meadow/rff/2023-10-19/emissions_weighted_carbon_price.py#L40-L45)
```
tb_economy = pr.read_csv(z.open(DATA_PATH_ECONOMY), metadata=metadata, origin=origin)
tb_economy.metadata.short_name = "emissions_weighted_carbon_price_economy"
tb_coverage = pr.read_csv(z.open(DATA_PATH_COVERAGE), metadata=metadata, origin=origin)
tb_coverage.metadata.short_name = "emissions_weighted_carbon_price_coverage"
```
`metadata` refers to the same object and the second `tb_coverage.metadata.short_name` updates the short name of the first table, too. Function `create_dataset`, which accepts two tables, then overwrites the tables.
I've added a uniqueness check for table short names and also fixed this by copying `metadata` …
> :bug: fix overriding table's short name

- apps/staging_sync/cli.py
- docs/architecture/workflow/staging-servers.md
- etl/datadiff.py
- etl/files.py
- etl/grapher_model.py
- mkdocs.yml
* Match existing charts on chart id instead of slug (which can change)
* Don't use `chart.updatedAt` when comparing whether chart has been updated on live, but use staging server creation time
* Show metadata diff if a chart has been updated on live
* Improve CLI help
* Add docs
> 🔨  etl-staging-sync improvements

- etl/files.py
- tests/test_files.py
Fix for https://github.com/owid/etl/issues/1708. It's a bit hacky, but the alternatives are too complex.
> :sparkles: ignore region aliases when calculating checksums

- apps/metadata_migrate/cli.py
- etl/grapher_model.py
- schemas/dataset-schema.json
Column `tags.isTopic` was removed from MySQL. Reflect that in ETL.
@ikesau I'm not very familiar with how tags work on our site. Is there a way now to tell whether a tag is a topic tag? Topic tags had unique names, which was necessary to get their IDs in ETL. I don't they are unique any more. Any ideas how to filter them?
> :bug: remove isTopic from tags

- lib/catalog/owid/catalog/processing_log.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_processing_log.py
Adding `Table.amend_log` that modifies the latest entry in plog. It's a light version of the original implementation, as I couldn't find a good use case yet. I expect that we'll make it more powerful as we start using plog for real.
@pabloarosado comments from the [previous PR](https://github.com/owid/etl/pull/1574)
Thanks for working on this! I haven't looked deeply into the guts of the code, but I have tried a few things and it makes sense. I think it would be good to merge this as soon as possible to avoid it from stalling (provided that it doesn't affect any other ETL step unless `PROCESSING_LOG=1`). I just have a few comments/questions:
* I see that the `rename` operation is now omitted. I understand why this happens after other operations, but in general, if you explicitly want to …
> :sparkles: add amend_log to plog

- etl/command.py
- etl/snapshot.py
- etl/steps/__init__.py
- lib/catalog/owid/catalog/datasets.py
- lib/walden/owid/walden/files.py
Refactor DVC in steps and snapshots and simplify it a bit. It uses somehow magical combination of locks to make it work for nightly builds with multiple processes. When I have time I plan to replace `dvc.pull` [with something custom](https://github.com/owid/etl/pull/2058).
> :hammer: Refactor DVC and snapshots

- apps/wizard/charts/submission.py
- etl/chart_revision/v2/core.py
- etl/chart_revision/v2/schema.py
- etl/chart_revision/v2/updaters/variable_update.py
There were two issues with chart revisions:
1. Some charts don't have `config["id"]` - Hotfixed by creating it when loading the chart, but the plan is to fix all charts like that in MySQL
2. Some suggested revisions don't have `version` - this was caused by function that was deleting properties with default values (where `version = 1`) even though the property is required
I've tested it locally. If you run into an error that says chart revisions don't have a unique `chartId`, you'll have to delete that revision manually from DB (this happens because of previous failed attempts).
> :bug: fix chart revisions for edge cases

- etl/data_helpers/geo.py
Using `add_population_to_dataframe` should raise a warning, but using `add_population_to_table` should not.
Given that the latter uses the former, the warning was raised in both cases. This PR fixes that.
> Avoid unnecessary warning

- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
When filling with nans using another table, we should combine the metadata of the two tables.
This change will also make `datautils.dataframes.combine_two_overlapping_dataframes` automatically propagate metadata of the two tables.
`fillna` is a very common operation (although it's unusual to fill with entire tables), and `combine_two_overlapping_dataframes` is also fairly commonly used. So it would be very good to check if this PR alters the metadata of existing steps.
One possible issue I can imagine happening is that, when doing tb1.fillna(tb2), one may expect that the title and description of tb1 should be preserved. But, if tb1 and tb2 have different titles and descriptions, the combination will have no title/description (which also makes sense).
> Propagate metadata on fillna

- lib/catalog/owid/catalog/variables.py
Avoid a warning when dividing two variables with different units (which is very common, e.g. when computing per capita variables).
We may want to make this logic a bit more generic in the future, but for now this will significantly reduce the number of warnings.
> Avoid metadata warning on division

- etl/steps/data/garden/war/2023-09-21/ucdp.meta.yml
Only applies to indicator 'number_ongoing_conflicts' in UCDP dataset.
Fixes https://github.com/owid/owid-issues/issues/1308
> 📊 war: set default entities to 'World'

- dag/migrated.yml
- etl/steps/data/garden/gapminder/2019-05-25/fertility_rate.meta.yml
- etl/steps/data/garden/gapminder/2019-05-25/fertility_rate.py
- etl/steps/data/garden/wb/2017-04-16/world_gdp.meta.yml
- etl/steps/data/garden/wb/2017-04-16/world_gdp.py
- etl/steps/data/grapher/gapminder/2019-05-25/fertility_rate.py
- etl/steps/data/grapher/wb/2017-04-16/world_gdp.py
- snapshots/backport/latest/dataset_393_world_gdp_in_2011_int_dollar__owid_based_on_world_bank_plus_maddison__2017_config.json.dvc
- snapshots/backport/latest/dataset_393_world_gdp_in_2011_int_dollar__owid_based_on_world_bank_plus_maddison__2017_values.feather.dvc
- snapshots/backport/latest/dataset_4132_fertility_rate__selected_gapminder__v12__2017_config.json.dvc
- snapshots/backport/latest/dataset_4132_fertility_rate__selected_gapminder__v12__2017_values.feather.dvc
- snapshots/gapminder/2019-05-25/fertility_rate.feather.dvc
- snapshots/gapminder/2019-05-25/fertility_rate.py
- snapshots/wb/2017-04-16/world_gdp.feather.dvc
- snapshots/wb/2017-04-16/world_gdp.py
Migrated with
```
ENV=.env.prod backport-migrate --dataset-id 4132 --namespace gapminder --version 2019-05-25 --short-name fertility_rate
```
and
```
ENV=.env.prod backport-migrate --dataset-id 393 --namespace wb --version 2017-04-16 --short-name world_gdp
```
> :bar_chart: migrate fertility rate and GDP to ETL

- etl/steps/data/grapher/gapminder/2019-05-25/fertility_rate.meta.yml
- etl/steps/data/grapher/wb/2017-04-16/world_gdp.meta.yml
- snapshots/gapminder/2019-05-25/fertility_rate.feather.dvc
- snapshots/wb/2017-04-16/world_gdp.feather.dvc
I've taken all Lucas' grapher charts from our [data pages candidate list](https://docs.google.com/spreadsheets/d/1SyyRR_iaokoc-tkDVQ24F4gW7cf47mLRdEyr8ZSBYo0/edit#gid=0) and ran `etl-metadata-migrate` to pre-generate YAML files. This should hopefully ease the migration. Generated YAML files contain all metadata information we have about indicator (including everything from garden step). This means we might end up with duplicate information in garden & grapher YAML files. It's up to you whether you decide to refactor it and move everything to `garden` channel. I don't think it's necessary now (maybe with next update).
Work on this branch and commit back to it. For all data pages from the list:
1. Look up their YAML file from this PR
2. Fill in all TBD fields (update or remove), remove …
> 📊 Migrate grapher charts to Data Pages (Lucas)

- etl/steps/data/garden/war/2023-09-21/shared.py
Hey @Marigold this file has been showing up every time I do `make test` (because it had an unused import). And `make check` doesn't notice it. I just created this PR in case this is a potential issue of `make check` (maybe it ignores `shared.py` files).
> Improve format of war shared file

- etl/data_helpers/misc.py
- etl/steps/data/garden/energy/2023-12-12/electricity_mix.py
* Fixed spurious jumps in oil, gas (and therefore fossil) electricity generation in Oceania.
* Fixed issue with `combine_tables` plotting function, so that it doesn't fail on categorical columns.
> Fix electricity issues in oceania

- snapshots/wb/2017-04-16/world_gdp.feather.dvc
I have changed the attribution of the World GDP dataset, since [Max pointed out](https://owid.slack.com/archives/C03NV9Z3YSV/p1703764800168289) that it was wrong. But I'm not sure if this is the correct attribution (I haven't worked on this dataset), @lucasrodes feel free to change it if this is not correct.
> Fix attribution in World GDP dataset

- etl/steps/data/garden/ihme_gbd/2019/shared.py
We get huge number of warnings from `ihme_gbd` like this
```
2024-01-02 11:09:53 [warning  ] Column share_of_total_dalys_that_are_from_varicella_and_herpes_zoster__in_females_aged_7_27_days uses display.name but no presentation.title_public. Ensure the latter is also defined, otherwise display.name will be used as the indicator's title.
```
The `display.name` is the same as the indicator's title, so there's no point in keeping both.
> :hammer: stop using display.name to prevent warnings spam

- .dvc/config
- etl/files.py
- etl/snapshot.py
- tests/test_files.py
UPDATED 2024-01-02
DVC has become a bit annoying in some aspects:
1. DVC doesn't interact well with multiprocessing (we got around this by using various hacks, and we can only pull a single snapshot at a time).
2. DVC is slow with the large number of DVC files we have (the current workaround is to dynamically use `.dvcignore` for backported datasets... it works, but is prone to errors).
3. DVC is spamming our logs because of these workarounds.
4. The new major version of DVC doesn't support our file model (which involves having DVC YAML files next to data files).
5. We can't add comments to `*.dvc` files.
We only use a small fraction of DVC's capabilities (just storing files on remote S3 storage), so it's worth considering whether dealing with these issues is justifiable. Initially, we …
> :bug: Replace DVC pull with direct fetch

- dag/war.yml
- etl/steps/data/garden/war/2024-01-09/nuclear_weapons_inventories.countries.json
- etl/steps/data/garden/war/2024-01-09/nuclear_weapons_inventories.meta.yml
- etl/steps/data/garden/war/2024-01-09/nuclear_weapons_inventories.py
- etl/steps/data/garden/war/2024-01-09/status_of_world_nuclear_forces.countries.json
- etl/steps/data/garden/war/2024-01-09/status_of_world_nuclear_forces.meta.yml
- etl/steps/data/garden/war/2024-01-09/status_of_world_nuclear_forces.py
- etl/steps/data/grapher/war/2024-01-09/nuclear_weapons_inventories.py
- etl/steps/data/grapher/war/2024-01-09/status_of_world_nuclear_forces.py
- etl/steps/data/meadow/war/2024-01-09/nuclear_weapons_inventories.py
- etl/steps/data/meadow/war/2024-01-09/status_of_world_nuclear_forces.py
- snapshots/war/2024-01-09/nuclear_weapons_inventories.csv.dvc
- snapshots/war/2024-01-09/nuclear_weapons_inventories.py
- snapshots/war/2024-01-09/status_of_world_nuclear_forces.csv.dvc
- snapshots/war/2024-01-09/status_of_world_nuclear_forces.py
Add data from [the Federation of American Scientists](https://fas.org/initiative/status-world-nuclear-forces/), on stockpiles of nuclear weapons over time, and on 2023 inventories.
- [Old dataset](https://owid.cloud/admin/datasets/6203) -> [New dataset](http://staging-site-add-nuclear-warhead-inventories-data/admin/datasets/6347) (2 charts).
- [Old dataset](https://owid.cloud/admin/datasets/6204) -> [New dataset](http://staging-site-add-nuclear-warhead-inventories-data/admin/datasets/6346) (1 chart). Here, the old dataset used to have data for 2022 and 2023, whereas the new one only has data for 2023. This is because the 2022 data has been removed from their page. We will consider fetching it from somewhere else, if there is time (in a separate PR).
> Add nuclear warhead inventories data

- etl/steps/data/garden/gcp/2023-12-12/global_carbon_budget.meta.yml
- snapshots/gcp/2023-12-12/global_carbon_budget.py
- snapshots/gcp/2023-12-12/global_carbon_budget_fossil_co2_emissions.csv.dvc
- snapshots/gcp/2023-12-12/global_carbon_budget_global_emissions.xlsx.dvc
- snapshots/gcp/2023-12-12/global_carbon_budget_land_use_change_emissions.xlsx.dvc
- snapshots/gcp/2023-12-12/global_carbon_budget_national_emissions.xlsx.dvc
Add short attribution to Global Carbon Budget (as suggested by @JoeHasell in [this slack conversation](https://owid.slack.com/archives/C0193RW5E2J/p1705406898711349)).
> Add short attribution to Global Carbon Budget

- etl/steps/data/garden/excess_mortality/latest/wmd.py
We have hardcoded the year 2023 in excess mortality datasets. Change it to the current year.
> :bug: bump expected year in XM checks

- etl/steps/data/garden/energy/2023-12-12/electricity_mix.py
We currently calculate the share of electricity in primary energy consumption (shown in [this chart](https://ourworldindata.org/grapher/electricity-as-a-share-of-primary-energy)) as simply dividing the total electricity generation by primary energy consumption.
However, primary energy consumption (from the Statistical Review of World Energy) is defined in "input-equivalents" (what we usually call [the substitution method](https://ourworldindata.org/energy-substitution-method)). This means that non-fossil electricity sources (nuclear, hydro, solar, wind, bioenergy and other renewables) are inflated to mimic the inefficiencies of fossil fuels. To achieve that, the Statistical Review divides the electricity generation of non-fossil sources by an efficiency factor (which is roughly between …
> Improve calculation of the share of electricity in primary energy

- apps/wizard/charts/search_config.py
- apps/wizard/charts/utils.py
- apps/wizard/charts/variable_config.py
There were minor issues when updating indicators from the same dataset (i.e. having `old dataset = new dataset`).
Pablo surfaced this in https://github.com/owid/etl/issues/1563#issuecomment-1903700162.
**Some fixes/improvements include**:
- **Mapping identically named variables**
- By default, indicators with the same name were mapped automatically (with no edits allowed by the user) if there was a 100% name match. This option can be tweaked by the parameter "Mapped identically named variables". This flexible parameter is useful when old and new datasets differ. However, in this case, we prefer the default behaviour to be that no automatic mapping is done to allow for "variable migrations" (migrating a variable to a new one, which does not necessarily have the same name).
- Added a help …
> 🐛 wizard charts: fix and improve experience with same-dataset-updates

- apps/staging_sync/app.py
- apps/staging_sync/cli.py
- apps/staging_sync/instructions.md
- apps/utils.py
- apps/wizard/app.py
- apps/wizard/home.py
- pyproject.toml
UI for command `etl-staging-sync` for migrating charts from staging servers to production. 
It will be run on `owid@etl-prod-2` together with fast-track (on a different port), and there'll be a link to it from admin.
The current version needs **active staging server** to sync charts from there, and the branch **must be merged in ETL**. I've increased the time for killing staging servers from 1 day to **3 days after merging**.
Last time, we talked about snapshotting the staging server somewhere so that we can kill the server right away and reconstruct updated charts from the snapshot. I gave it a try, and it turned out to be unnecessarily complicated. Moreover, having an active staging server when syncing charts could be useful (e.g. if you realise you still have to make some chart edits …
> :tada: streamlit app for etl-staging-sync

- etl/steps/data/garden/energy/2023-12-12/electricity_mix.meta.yml
- etl/steps/data/garden/energy/2023-12-12/electricity_mix.py
In [my previous PR](https://github.com/owid/etl/pull/2196) I attempted to fix the calculation of the share of electricity in primary energy consumption (used in [this chart](https://ourworldindata.org/grapher/electricity-as-a-share-of-primary-energy)). However, I then realized that the calculation was still problematic, so I reverted it.
We should calculate the share of electricity in terms of direct primary energy consumption, instead of input-equivalent primary energy. This is not ideal, since we use the substitution method in most of our charts, but it's the best trade-off given the data we have.
Once this PR is merged, I'll change the subtitle of the chart, to mention that we use direct primary energy consumption, and not primary energy using the substitution method.
Comparison:
* …
> Fix calculation of the share of electricity in primary energy

- dag/archive/war.yml
- dag/war.yml
- etl/steps/data/garden/war/2024-01-25/nuclear_weapons_tests.countries.json
- etl/steps/data/garden/war/2024-01-25/nuclear_weapons_tests.meta.yml
- etl/steps/data/garden/war/2024-01-25/nuclear_weapons_tests.py
- etl/steps/data/grapher/war/2024-01-25/nuclear_weapons_tests.py
- etl/steps/data/meadow/war/2024-01-25/nuclear_weapons_tests.py
- snapshots/war/2024-01-25/nuclear_weapons_tests.csv.dvc
- snapshots/war/2024-01-25/nuclear_weapons_tests.py
Following our suggestion, the Arms Control Association updated the values in their table on the Nuclear Testing Tally (so that, instead of saying "2018-2019" now it says "2018-Present"). The only change in the data is that instead of 2019, the last informed year now is 2022.
* Update nuclear weapons tests dataset.
* Move steps of the previous version to archive dag.
> Update nuclear weapons tests dataset

- dag/archive/war.yml
- dag/war.yml
- snapshots/war/2024-01-30/strategic_nuclear_forces.py
- snapshots/war/2024-01-30/strategic_nuclear_forces.xlsx.dvc
- snapshots/war/2024-01-30/strategic_nuclear_forces_monadic.xlsx.dvc
Load strategic nuclear forces monadic data by Suh from a URL (now that the public link exists) instead of a local file, and update documentation.
> Load Strategic Nuclear Forces data from URL

- etl/steps/data/garden/un/2023-08-16/igme.meta.yml
- Previously the same metadata was used for death rate and absolute deaths
> 🐛  Fix metadata for under fifteen deaths

- dag/fasttrack.yml
Remove from the dag fasttrack steps whose code was already removed (on nuclear weapons data). They should have been removed from the dag when the steps were removed.
> Remove fasttrack steps that do not exist anymore

- dag/faostat.yml
After some experiments with the new version tracker, I noticed that the dataset on additional FAOSTAT variables was still using an old version of the data. This PR creates the corresponding new grapher dataset.
> Add missing faostat step to dag

- snapshots/ivs/2023-11-27/integrated_values_survey.csv.dvc
- snapshots/ivs/2023-11-27/ivs_create_file.do
In the Integrated Values Survey dataset, each observation has variables associated to the WVS/EVS wave (S002VS):
- 1981-1984 (EVS/WVS1)
- 1989-1993 (EVS/WVS2)
- 1994-1998 (WVS3)
- 1999-2004 (EVS3, WVS4)
- 2005-2010 (EVS4, WVS5)
- 2010-2014 (WVS6)
- 2017-2022 (EVS5, WVS7)
Strangely, there were many observations with this variable set as missing. All of them have a defined S002EVS value (EVS wave), so I initially assigned last year of these EVS waves as the year of these observations.
I communicated with WVS/EVS people to ask if I should assign EVS/WVS waves instead (or none) and they told me
> We published an erratum on this issue only on Tuesday. The problem relies on a mistaken spelling of S002VS in the EVS Trend File (s002vs instead of S002VS), resulting in missing values after merging …
> :bug: Fix years assigned to EVS data in Integrated Values Survey

- apps/wizard/pages/fasttrack/app.py
- apps/wizard/pages/fasttrack/process.py
We were having issues with fast-track. This splits `dataset_uri` into multiple keys and also keeps validation errors expanded.
> :bug: split dataset_uri into separate keys and fix them

- snapshots/climate/2023-12-20/surface_temperature.gz.dvc
- snapshots/education/2023-12-15/wittgenstein_center_data.csv.dvc
- snapshots/excess_mortality/latest/hmd_stmf.csv.dvc
- snapshots/oecd/2023-05-18/co2_air_transport.csv.dvc
- snapshots/terrorism/2023-07-20/global_terrorism_database.csv.dvc
- snapshots/un/2018/igme.csv.dvc
- snapshots/wb/2023-11-21/worldwide_bureaucracy_indicators.csv.dvc
- snapshots/who/latest/fluid.csv.dvc
- snapshots/who/latest/flunet.csv.dvc
- snapshots/wvs/2023-06-25/longitudinal_wvs.csv.dvc
The previous fuckup was caused by working with cached Cloudflare files from R2. These checksums and file sizes are taken directly from R2, not from custom domain that caches it.
> :bug: fix MD5 yet again

- etl/snapshot.py
- lib/walden/owid/walden/files.py
- lib/walden/pyproject.toml
- lib/walden/tests/test_files.py
- poetry.lock
I was unintentionally stripping Windows newlines from downloaded files, which then led to size mismatch errors. This PR doesn't update the downloaded file and also switches back to downloading from custom domain instead of R2 directly.
> :bug: don't modify downloaded file when updating MD5 with Windows newlines

- etl/steps/data/garden/ivs/2023-11-27/integrated_values_survey.py
Replace null answers by 0 in the Schwartz questionnaire when the main answer is not null. This is done to solve issues like the one shown below:
Due to tolerance, Grapher thinks it needs to fill out the null variable for another from a previous year.
I also clean the code by specifying the questions in list at the start of the code.
> :bug: ivs: Change null Schwartz answers to 0 when there is data for other ansers

- etl/steps/data/garden/ivs/2023-11-27/integrated_values_survey.meta.yml
- etl/steps/data/garden/ivs/2023-11-27/integrated_values_survey.py
- snapshots/ivs/2023-11-27/integrated_values_survey.csv.dvc
- snapshots/ivs/2023-11-27/ivs_create_file.do
The high incidence of missing values for some questions is due that I was including the categories
```
.c Not applicable
.d Not asked in survey
.e Missing: other
```
Among the missing variables. This PR replaces these variables by a "No answer" category (.b), which together with "Don't know" (.a) are the only classifications beyond the common answers I am keeping.
https://github.com/owid/owid-issues/issues/1374
> :bug: ivs: Fix high incidence of missing values in Integrated Values Surveys

- etl/config.py
- etl/grapher_helpers.py
- etl/grapher_import.py
- etl/helpers.py
- etl/steps/__init__.py
- lib/catalog/owid/catalog/datasets.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/utils.py
- tests/test_grapher_helpers.py
I had to do various improvements to core ETL to make Global Health Observatory dataset work in ETL. The plan is to merge this first and then rebase [GHO PR](https://github.com/owid/etl/pull/2172).
When working with a huge dataset like GHO or WDI, running a step can take minutes or more. In development, one typically focuses on a single indicator, debugs, fixes it, and pushes to grapher to see the output. To speed up this process, you can now load `SUBSET` from environment and filter your data by it (typically indicator name). With this, I can run GHO steps for indicator `sa_0000001547` in a few seconds
```
SUBSET=sa_0000001547 STAGING=gho etl run who/2024-01-03/gho --grapher
```
If you use `SUBSET`, ghost indicators are not removed from MySQL, hence you only add / edit that indicator …
> :sparkles: Various core ETL improvements needed for GHO dataset

- etl/steps/data/garden/ivs/2023-11-27/integrated_values_survey.meta.yml
- etl/steps/data/garden/ivs/2023-11-27/integrated_values_survey.py
- snapshots/ivs/2023-11-27/integrated_values_survey.csv.dvc
- snapshots/ivs/2023-11-27/ivs_create_file.do
Issue here: https://github.com/owid/owid-issues/issues/1400
- I have replicated the ["happy" indicator](https://owid.cloud/admin/variables/1704) (very happy + quite happy)
- I have also created new not happy (not very happy, not at all happy), very happy, quite happy, not very happy, not at all happy, don't know and no answer indicators. They are useful for further exploration (in stacked charts, for example).
- I have not created the [happy indicator for the first and last waves](https://owid.cloud/admin/variables/1765), because I thought it's too specific. Would you prefer to modify the text or actually create the variable, @spoonerf?
> 📊 ivs: Add happiness questions to Integrated Values Surveys

- docs/getting-started/building-datasets.md
This PR adds a small toggle note to the "First Steps" documentation. It explains how to activate the Poetry environment in order to use the CLI tool. If this isn't useful, feel free to give it a thumbs down and I can close/delete it, but I thought it might benefit some public users who aren't familiar with Poetry. Thank you!
> 📜 add additional troubleshooting info to first steps documentation

- apps/wizard/pages/dashboard.py
I noticed that the information in the operations list was incomplete.
To replicate the issue:
* Tick “Select only grapher...”.
* Select step “data://grapher/irena/2023-12-12/renewable\_power\_generation_costs”.
* Click on "Add selected steps to the Operations list".
* Click on "Add direct dependencies". A garden step is added to the operations list.
* Click on "Add direct dependencies" of the garden step. The corresponding meadow step should appear, but instead, nothing happens.
If you repeat this without ticking on "Select only grapher...", the problem is solved, and you do see meadow as well.
So to perform operations, we need the full steps_df, not just the filtered version that is displayed.
That's why, in this PR, I define steps_df (as all the original data, used in operations), and …
> Fix missing info in operations list of etl dashboard

- dag/archive/demography.yml
- dag/demography.yml
Move unused new (experimental) population steps to the archive dag, and comment them.
Given that this experimental dataset is currently not used, and we do not advise using for now, this PR moves the steps to the archive (and comments them). This way we avoid population to appear as outdated (hence making all datasets that use population be outdated too) in the ETL dashboard. We also avoid confusion and the risk of using this dataset by mistake.
Once we decide to use this dataset, we can just move the steps from the archive to the active dag (the steps code has not moved).
> Remove new unused population steps

- apps/wizard/config/config.yml
- apps/wizard/pages/dashboard.py
- apps/wizard/pages/owidle.py
This PR improves the ETL dashboard in the following ways:
* Instead of showing by default grapher steps with charts, show all grapher steps by default (plus explorer steps).
* Operations list now has a button to remove steps that we most likely don't want to update (e.g. regions or population).
* Operations list now has a button to replace steps in the list by their corresponding updated versions (useful for after updating).
* There is a button to run snapshots and ETL steps.
Feel free to play around with [the resulting new dashboard on staging](http://staging-site-improve-etl-dashboard/etl/wizard/ETL%20Dashboard).
> Improve etl dashboard

- etl/steps/data/grapher/fasttrack/latest/welfare_broiler_chickens.meta.yml
As pointed out by [a user](https://app.frontapp.com/open/msg_k8dvjb6?key=3ZBso5H5nsIqTTScyyZbVGDoiPbr6ClE), the number of waking hours of broiler chickens was said to be 17 hours in some places (including our main article), but 16 hours in the metadata of the chart. I've fixed the latter.
> Fix metadata of welfare broiler chickens data

- dag/fasttrack.yml
Grapher dataset [DRAFT vdem_women_executives](https://owid.cloud/admin/datasets/6397) was created to have draft grapher charts, to be able to create static charts. Therefore, none of the charts nor the dataset itself are public. So, since the grapher dataset is private, the corresponding ETL grapher step should also be private. This PR makes that step private.
> Make draft grapher step private

- etl/steps/data/garden/wb/2024-03-11/income_groups.meta.yml
- etl/steps/data/garden/wb/2024-03-11/income_groups.py
- etl/steps/data/grapher/wb/2024-03-11/income_groups.py
- etl/steps/data/meadow/wb/2024-03-11/income_groups.py
- snapshots/wb/2024-03-11/income_groups.py
- snapshots/wb/2024-03-11/income_groups.xlsx.dvc
Update World Bank income groups.
This PR will replace the old datasets:
* [Income Classification - World Bank (2021)](https://owid.cloud/admin/datasets/5741).
* [Income Classification - World Bank (2017)](https://owid.cloud/admin/datasets/944).
* [Income classifications (World Bank, 2022)](https://owid.cloud/admin/datasets/5997).
By the new [World Bank's historical income classification](http://staging-site-update-wb-income-groups/admin/datasets/6406).
For more context: https://github.com/owid/owid-issues/issues/1179
> Update World Bank income groups

- dag/demography.yml
- etl/steps/data/explorers/un/2022/un_wpp.py
- etl/steps/data/garden/un/2022-07-11/un_wpp/population.py
- etl/steps/data/garden/un/2024-03-14/un_wpp_most.meta.yml
- etl/steps/data/garden/un/2024-03-14/un_wpp_most.py
- etl/steps/data/grapher/un/2024-03-14/un_wpp_most.py
* Adding 5-year age-groups for population across the whole age range (0-100) - for [this chart](http://staging-site-five-year-pops/admin/charts/7691/edit)
* Removing the new 5-year age-groups from the explorer step, so the explorer is unchanged
* Adding an experimental dataset to show the populous age-group for each country-year - for[ this chart](http://staging-site-five-year-pops/admin/charts/7690/edit)
> 📊 UN WPP population five year age-groups for 0-100, instead of 0-20

- etl/helpers.py
- etl/steps/data/grapher/lis/2023-08-30/luxembourg_income_study.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/variables.py
- lib/catalog/owid/catalog/warnings.py
This was heavily inspired by https://github.com/owid/etl/pull/2388.
Warnings are sometimes unavoidable, or it's just more convenient to ignore them (especially when you are not the maintainer of the data and need to silence them to have readable logs).
Implement our own `warnings.py` module with custom warnings that can be selectively ignored. The module lets us use context manager to ignore warnings which is the cleanest way.
```python
from owid.catalog import warnings
with warnings.ignore_warnings([warnings.NoOriginsWarning, warnings.DisplayNameWarning]):
ds_garden = create_dataset(
dest_dir, tables=[tb_garden], check_variables_metadata=True, default_metadata=ds_garden.metadata
)
```
Warnings module also overwrites the formatting function so that warnings are printed by colourful …
> :tada: custom warnings module

- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
Pandas `fillna` _does not_ impose the usage of argument `value`. Therefore, `Table.fillna` should do the same.
Forcing it, makes calls to `.ffill` or `.fillna(how="ffill")` raise errors.
Example of error:
```python
tb = ...
tb.ffill()
```
leads to 
```
TypeError: Table.fillna() missing 1 required positional argument: 'value'
```
> 🐛 generalise fillna table method

- apps/staging_sync/app.py
- docs/guides/indicator-upgrade.md
As discussed [here](https://owid.slack.com/archives/C0193RW5E2J/p1711101052248769). Note that Mojmir had already added a comment in the instructions of the chart sync (but it was a bit hidden, so now that info is more evident).
> Add documentation about tags limitation of the chart sync tool

- etl/steps/data/garden/energy/2023-12-12/electricity_mix.meta.yml
Fix processing description in the metadata of the electricity mix, "electricity consumption" -> "electricity generation".
> Fix metadata of electricity mix

- apps/step_update/cli.py
- etl/version_tracker.py
In `StepUpdater`, the property `steps_df` should only contain active steps (since they are the only ones to be considered for update, and the only ones relevant for the ETL dashboard). Indeed, column `step` of `steps_df` (which is the main index) only contains active seps. However, other columns (e.g. `direct_usages`) do contain archive steps. This issue was mentioned in https://github.com/owid/etl/issues/2365
This raises an `IndexError` in the ETL dashboard, if, in the Operations list, you click on "Add direct usages" for steps that are used by archive steps.
This PR fixes that. Now `VersionTracker` (which is loaded by `StepUpdater`) can be initialized with the argument `ignore_archive=True`.
> Let VersionTracker optionally ignore archive steps

- apps/wizard/pages/dashboard.py
Buttons in the operations list were acting in quite unexpected ways.
1. Add the latest garden step of long_term_crop_yields to the Operations list.
2. In the Operations list, click on "Add direct dependencies" of long_term_crop_yields.
3. Click on "Add direct dependencies" of long_term_wheat_yields.
4. Click on "Add direct dependencies" of faostat_qcl.
An error appears: DuplicateWidgetID: There are multiple widgets with the same key='remove_data://garden/faostat/2024-03-14/faostat_qcl'. To fix this, please make sure that the key argument is unique for each widget you create.
1. Add the latest garden step of long_term_crop_yields to the Operations list.
2. In the Operations list, click on "Add direct dependencies" of long_term_crop_yields.
3. Click again on the same button.
You can see …
> Fix wrong behavior of buttons in operations list

- etl/steps/data/garden/covid/latest/variants.meta.yml
- etl/steps/data/garden/who/latest/fluid.meta.yml
- schemas/snapshot-schema.json
- snapshots/unep/2023-01-03/global_trends_in_renewable_energy_investment.pdf.dvc
- snapshots/who/latest/fluid.csv.dvc
- snapshots/who/latest/flunet.csv.dvc
- tests/test_metadata_schemas.py
Light implementation of https://github.com/owid/etl/issues/2238.
The original issue suggests to
> Add the $schema parameter and opt-in historical YAML files that are already compliant
In my opinion, adding a property to every YAML file would add too much boilerplate code. I'm not sure if we need such a granular approach. Similarly with versioning metadata schema. I don't think we have to check every metadata file at each point in time. If we always have a green CI, then bump the version in `VALIDATE_AFTER`, update schema and have green again, then it's sufficient. (Especially since we have linting enabled)
I fixed a couple of datasets, but added some to `EXCLUDE` list. I've also disabled checking for `description` as it is present in too many datasets (we still get linting error for it).
> :tada: strict YAML metadata schema validation

- etl/steps/data/garden/climate/latest/weekly_wildfires.meta.yml
- snapshots/climate/latest/weekly_wildfires.csv.dvc
- snapshots/climate/latest/weekly_wildfires.py
Adjustments needed to update wildfires automatically. The script will run `python snapshots/climate/latest/weekly_wildfires.py` and then run ETL to update wildfires dataset.
There are couple of minor differences to the current process:
- Data will be updated daily (nothing happens if there are no changes)
- Description short slightly changes its date format to `The 2024 data is incomplete and was last updated 2024-03-27.`
Is it safe to run it daily or does it have to be run once a week?
> :tada: automatic wildfires update

- dag/poverty_inequality.yml
- etl/steps/data/garden/ons/2024-03-20/hours_and_earnings_uk.countries.json
- etl/steps/data/garden/ons/2024-03-20/hours_and_earnings_uk.meta.yml
- etl/steps/data/garden/ons/2024-03-20/hours_and_earnings_uk.py
- etl/steps/data/meadow/ons/2024-03-20/hours_and_earnings_uk.py
- snapshots/ons/2024-03-20/hours_and_earnings_uk.py
- snapshots/ons/2024-03-20/hours_and_earnings_uk.xlsx.dvc
Issue here https://github.com/owid/owid-issues/issues/1441
Creates income ratios from weekly gross income for the UK. Data comes from the [UK's Office of National Statistics](https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/ashe1997to2015selectedestimates).
Data is for the Chartbook of Economic Inequality https://github.com/owid/owid-issues/issues/1177
I am not pushing this to Grapher, because this is for archival reasons, for the Chartbook only.
> 📊 ons: Create UK earnings dataset

- etl/data_helpers/geo.py
- etl/steps/data/garden/artificial_intelligence/2024-03-22/papers_with_code_math.py
- tests/test_helpers.py
This PR fixes https://github.com/owid/etl/issues/2474
(The changes in the other two files were created by `make test`, they are just formatting problems).
I checked that in the example you gave in the issue:
```python
import pandas as pd
from etl.data_helpers.geo import add_regions_to_table
from etl.paths import DATA_DIR
from owid.catalog import Dataset
df = pd.DataFrame({
"country": ["Germany", "East Germany", "East Germany"],
"year": [1950, 1950, 1951],
"indicator": [1, 2, 3]
})
df["country"] = df["country"].astype("category")
ds_regions = Dataset(DATA_DIR / "garden" / "regions" / "2023-01-01" / "regions")
add_regions_to_table(df, ds_regions)
```
now I see the expected warning:
```
2024-03-29 15:14:14 [warning  ] Either the list of accepted overlaps is not found in the data or there are …
```
> Fix detect region overlap

- dag/main.yml
- dag/survey.yml
- etl/steps/data/garden/survey/2024-04-01/dietary_choices_uk.meta.yml
- etl/steps/data/garden/survey/2024-04-01/dietary_choices_uk.py
- etl/steps/data/grapher/survey/2024-04-01/dietary_choices_uk.py
- etl/steps/data/meadow/survey/2024-04-01/dietary_choices_uk.py
- snapshots/survey/2024-04-01/dietary_choices_uk.py
- snapshots/survey/2024-04-01/dietary_choices_uk.xlsx.dvc
Add snapshot, meadow, garden, and grapher steps for YouGov data on the dietary choices of Brits.
- [Old dataset in live](https://owid.cloud/admin/datasets/5622).
- [New dataset on staging](http://staging-site-add-uk-diet-choices-data/admin/datasets/6450).
> Add YouGov data on dietary choices of Brits

- etl/helpers.py
- tests/test_helpers.py
When function `write_to_dag_file` writes to the dag, it removes the comment of a step that appears right after an updated step (mentioned in: https://github.com/owid/etl/issues/2365). This PR solves that issue.
> Improve function that writes to dag

- apps/backport/datasync/data_metadata.py
- etl/grapher_import.py
- etl/grapher_model.py
- etl/helpers.py
- etl/snapshot.py
- etl/steps/data/garden/wb/2024-03-11/income_groups.meta.yml
- lib/catalog/owid/catalog/meta.py
- schemas/dataset-schema.json
- tests/backport/datasync/test_data_metadata.py
Implementation of this [Notion proposal](https://www.notion.so/owid/2023-03-10-Add-type-information-to-variables-dd15d4b5fdb74292b9420923981b2a1c). Relevant issue https://github.com/owid/owid-grapher/issues/1690.
We currently recognise these types "float", "int", "mixed", "string" and save them as `type` field in JSON metadata. We'd like to add two new types - `categorical` and `ordinal` (which is especially useful for ordering and coloring charts). Furthermore, we'd like to start saving the `type` field to MySQL (that field currently only exists in JSON) and also the `sort` containing a list of categories for ordinal type.
- JSON on the staging server https://api-staging.owid.io/staging-site-ordinal-types/v1/indicators/830988.metadata.json
- Migration in owid-grapher repository …
> :tada: special ordinal type for indicators

- apps/cli/__init__.py
- apps/explorer_update/cli.py
- etl/db.py
Create a tool to automatically update explorer (tsv) files.
Currently, we have ways to check if grapher charts are outdated (using `VersionTracker`), but we have no way to check if explorers are outdated.
As far as I understand, explorers can be:
* Grapher-based: They directly show the content of grapher charts. These explorers do not need to be updated, as long as their grapher charts are updated (via, e.g. the chart-upgrader tool).
* File-based: They rely on a URL pointing to the data catalog. This URL may have an ETL version that needs to be manually updated if the dataset is updated.
* Indicator-based: They rely on variable ids. All those ids need to be manually updated if their dataset is updated.
* Mixed file-based and grapher-based.
This PR creates a new cli tool that lets you …
> 🎉 Create `etl explorer-update` tool to automatically update explorer `.tsv` files

- apps/wizard/pages/fasttrack/fast_import.py
- etl/grapher_model.py
If we swap titles of two indicators, but their `short_name` isn't swapped (e.g. when one makes a mistake in fast-track), we'd get an error from MySQL saying that `dataset-name` must be unique. Ideally, we wouldn't have this constraint, but as a hotfix we can check if such indicator exists and rename it temporarily.
> :bug: fix case with swapped titles

- .gitignore
- etl/command.py
- etl/paths.py
I thought it would be useful to have an estimate of how long steps take on each machine.
One way to do it is to have a hidden json file that keeps the last execution time for each step. Then, ETL prints the expected time when running that step. If that step is new, ETL prints the expected execution time of the previous version of the step. And, if there is no previous version, no expected execution time is printed.
I haven't put much thought into it. If you think there could be some unwanted side effects, we can close this and think of a better solution.
> Let ETL write execution times to hidden file, and print informative messages

- apps/backport/backport.py
- apps/backport/bulk_backport.py
- apps/metadata_migrate/cli.py
- etl/compare.py
- etl/data_helpers/population.py
- etl/datadiff.py
- etl/db.py
- etl/grapher_helpers.py
- etl/grapher_import.py
- etl/variable_mapping_translate.py
- lib/catalog/owid/catalog/variables.py
- lib/repack/owid/repack/__init__.py
- lib/repack/tests/test_repack.py
- tests/data_helpers/test_geo.py
- tests/test_datadiff.py
Improve datadiff based on my experience with migrating to pandas 2.x. I've simplified the output, improved performance and handled edge cases.
There's also some prep for pandas 2.x migration to make the subsequent review easier.
You can now use `etl diff dataset_path_a dataset_path_b` which use particularly useful for comparing versions. For instance
```
etl diff data/garden/climate/2024-01-31/sea_ice_index data/garden/climate/2024-03-11/sea_ice_index --verbose
```
The output has also changed. Instead of showing confusing "changed index" messages, I just show new/removed/updated values with a random sample of 5 values. For instance
```
= Table sea_ice_index
~ Dim location
+ New values: 4 / 1084 (0.37%)
date            location
2024-01-15 Northern Hemisphere
2024-02-15 Northern Hemisphere …
```
> :sparkles: Improve datadiff

- etl/steps/data/garden/artificial_intelligence/2024-04-02/dynabench.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-04-02/dynabench.py
Set the first year's performance to the baseline of –1 for each benchmark. This is to preserve a baseline for –1 for all benchmarks, even when a second, better performance is recorded in a later year.
> 🐛 set first year to baseline of –1 for all benchmarks

- etl/grapher_helpers.py
- etl/helpers.py
- etl/steps/__init__.py
- tests/test_helpers.py
`load_dag()` is relatively performance heavy. Cache it in memory and also lazy load it in PathFinder.
Reuse engine to avoid too many connections.
> :sparkles: speed up PathFinder

- apps/owidbot/etldiff.py
- etl/steps/__init__.py
- etl/steps/data/garden/nasa/2023-03-06/ozone_hole_area.meta.yml
- etl/steps/data/garden/war/2023-01-18/dunnigan_martel_1987.meta.yml
- etl/steps/data/garden/war/2023-01-18/eckhardt_1991.meta.yml
- etl/steps/data/garden/war/2023-01-18/kaye_1985.meta.yml
- etl/steps/data/garden/war/2023-01-18/sutton_1971.meta.yml
Implements https://github.com/owid/etl/issues/2497
The big drawback is that this will rebuild the entire ETL again.
- Only a bit (we still calculate checksums of snapshots on disk to make sure they match checksum in their `*.dvc` file)
- Yes! This is a major blocker for datadiff right now. It'd speed it up by a lot.
> :sparkles: compute checksums from ingredients only

- Makefile
Add command `sync.catalog` that fetches main channels from ETL catalog to local with `rclone`. The entire catalog has ~10gb, so this could be much faster than rebuilding it locally from scratch (~15 min for me). This is particularly useful when `ETL_EPOCH` is incremented or regions updated.
It assumes you already have `data/snapshots` locally (snapshots don't need to be updated after EPOCH increment). If not, it'd run the entire DAG anyway.
I plan to test it locally after today's regions update.
> :sparkles: add command sync.catalog for prefetching catalog from R2

- etl/steps/data/garden/wb/2024-03-27/world_bank_pip.countries.json
- etl/steps/data/garden/wb/2024-03-27/world_bank_pip.py
- snapshots/wb/2024-03-27/pip_api.py
- snapshots/wb/2024-03-27/world_bank_pip.csv.dvc
- snapshots/wb/2024-03-27/world_bank_pip_percentiles.csv.dvc
Issue: https://github.com/owid/owid-issues/issues/1506
> :sparkles: add World excluding China and India data for World Bank PIP

- apps/staging_sync/cli.py
- etl/grapher_model.py
Fix for https://github.com/owid/etl/issues/2533#issuecomment-2061210834
You can either exclude charts that have variables matching `--include`, e.g.
```
etl chart-sync .env update-natural-disasters-data --include natural --dry-run
```
or `--exclude`
```
etl chart-sync .env update-natural-disasters-data --exclude foo --dry-run
```
or simply ignore charts causing errors
```
etl chart-sync .env update-natural-disasters-data --errors warn --dry-run
```
@pabloarosado could you try merging this into your PR and testing it out? I've only tested it on a few simple cases.
> :sparkles: add --errors and --include/--exclude to chart-sync

- etl/steps/data/garden/un/2024-04-09/undp_hdr.meta.yml
Set default chart view for all indicators, so it looks OK in data pages.
> 📊  undp: default view on data page

- apps/backport/datasync/datasync.py
- etl/config.py
- etl/publish.py
- lib/catalog/owid/catalog/s3_utils.py
- scripts/audit_s3.py
- snapshots/wb/2024-01-17/pip_api.py
- snapshots/wb/2024-03-27/pip_api.py
Connecting to R2 now happens exclusively in `owid.catalog.s3_utils`. Credentials are taken either from `.env` file or from rclone config file.
Previously we were using different function for running snapshot and in ETL which caused problems and confusion.
> :hammer: unify access to R2

- apps/wizard/config/__init__.py
- apps/wizard/config/config.yml
- apps/wizard/pages/indicator_upgrade/dataset_selection.py
- We can now be more granular on choosing where to show an app. 
- Use `disable` keyword in the wizard `config.yml` file.
- Before, one could only choose to disable certain apps in remote (staging servers + production).
- Now, one can choose to disable the app in any of the three settings: staging servers, production and dev (or local).
- The data workflow should not be rendered in production
> 🐛 wizard: improve enable/disable of apps

- apps/cli/__init__.py
- apps/utils/map_datasets.py
This is a simple CLI that prints the old and new grapher dataset that should manually be passed to the chart upgrader tool, based on the changes you have commited to your current ETL branch.
To test it, go to any branch and run `etl d map-datasets`.
Note: This is a temporary solution before this logic is implemented in the indicator upgrader (or possibly also in chart diff).
> 🎉  Create CLI to print affected grapher datasets

- etl/version_tracker.py
~31% execution time reduction in `VersionTracker().steps_df`. 
**In my machine, it went from 6.6 s ± 56.8 ms → 4.5s ± 75.3 ms.** (mean ± std. dev. of 7 runs, 1 loop each)
This has been achieved by slightly optimising the execution time of `_add_columns_with_different_step_versions`. In this function, there is a loop iterating over all "identifiers" of datasets. We only need to iterate over those identifiers that have more than one dataset associated, since those with only one dataset will have deterministic values for columns `"same_steps_forward"`, `"same_steps_backward`, `"same_steps_all"` and `"same_steps_latest"`. Note that the majority of the identifiers only have >` dataset (~1500 vs ~300 with more than one dataset). Therefore the loop is way faster!
At the start of …
> ✨ VersionTracker.steps_df: ~30% reduction in execution time

- etl/snapshot.py
I ran into this when running full ETL rebuild. Sometimes the downloaded file is corrupted and has a different checksum. This PR raises a clear error when that happens. In the future, we can consider retrying.
> :sparkles: check md5 checksum of a snapshot after downloading

- apps/cli/__init__.py
- apps/owidbot/chart_diff.py
- apps/owidbot/cli.py
- apps/utils/scan_chart_diff.py
- apps/wizard/pages/chart_diff/app.py
- etl/paths.py
Script that iterates over all open PRs by OWID members and runs `owidbot --services chart-diff` against them. Can be invoked with
```
etl d scan-chart-diff --dry-run
```
This script will be run from `etl-prod-2` as a CRON job every 10 minutes (could be lower if needed). I was considering running a Buildkite scheduled job, but that'd be probably too heavy.
In addition to the script, there are a couple of improvements:
- `owidbot` doesn't update `Last edited` timestamp when body hasn't changed
- If `.env.prod` exists, we use it to connect to prod (otherwise we keep using `staging-site-master`). By the way, this is getting a bit messy, maybe we could wrap staging & prod info in an object similar to `OWIDEnv`?
> :tada: periodic runs of chart-diff against all open PRs

- apps/wizard/etl_steps/express.py
playground is being created by default in meadow and garden. we should disable this.
this comes from the fact that the notebook is part of the cookiecutter template. So actually we create it and then delete it under the hood.
> 🐝 express: avoid notebook creation

- apps/wizard/config/config.yml
- apps/wizard/pages/owid_datasette_oracle.py
- apps/wizard/pages/owid_datasette_oracle_prompt.py
This PR adds a tool called "Owid Datasette Oracle" that knows about our datasette schema and helps you write sql queries.
> ✨ first version of owid datasette oracle

- apps/owidbot/grapher.py
Adds commit links to the SVG tester summary. It's useful to have a direct link to the individual commit when there are many changes and GitHub freezes when opening the branch summary, which includes changes of all commits (it happens).
The script reads log files (`commit_{default,all}-views.log`) that contain commit IDs that have been added by the SVG tester Buildkite job.
> ✨ (owidbot) add svg tester commit links

- apps/staging_sync/admin_api.py
- apps/staging_sync/cli.py
Chart-sync was failing in production (see [this thread](https://owid.slack.com/archives/C46U9LXRR/p1714663753633919)). After some trial and error (thanks to [Daniel](https://owid.slack.com/archives/C46U9LXRR/p1715593275334989)) I figured that there was a wrong url for the production charts api.
> 🐛 Fix wrong url to production admin in chart-sync

- apps/backport/backport.py
- apps/staging_sync/admin_api.py
- apps/wizard/utils/env.py
- docs/architecture/workflow/index.md
- etl/config.py
Use Tailscale address http://owid-admin-prod.tail6e23.ts.net for AdminAPI instead of http://owid-admin-prod. The problem is that `owid-admin-prod` resolves to an address of the actual LXC container instead of going through the Tailscale. Using alias `owid-admin-prod.tail6e23.ts.net` fixes the problem.
> :bug: use proper Tailscale address for AdminAPI

- apps/staging_sync/cli.py
- apps/wizard/pages/chart_diff/app.py
This is useful for automation of the new `chart-diff`.
> :sparkles: allow commit sha in chart-sync

- dag/main.yml
- etl/steps/data/garden/growth/2024-05-16/gdp_historical.meta.yml
- etl/steps/data/garden/growth/2024-05-16/gdp_historical.py
- etl/steps/data/grapher/growth/2024-05-16/gdp_historical.py
Return to use World Bank's estimates from 1990 onwards instead of Maddison Project Database to recreate a Maddison + Maddison Project + World Bank series in 2017 prices. https://github.com/owid/owid-issues/issues/379
> :bug: Revert GDP in the long run, using WDI

- lib/catalog/Makefile
- lib/catalog/README.md
- lib/catalog/owid/catalog/charts.py
- lib/catalog/owid/catalog/internal.py
- lib/catalog/tests/test_charts.py
_Add a new draft charts-based API for data fetching._
We would like to offer simple code snippets that give you the data powering a chart, but we want to prototype what that could look like before committing to baking data in a special way or making a special worker.
The most likely outcome, if we like this code, is that we will later migrate it to a CloudFlare worker and serve the API from there.
```python
from owid.catalog import charts
slugs = charts.list_charts()
df = charts.get_data('life-expectancy')
```
- For `list_charts()`
- Scrape the [Charts and explorers](https://ourworldindata.org/charts) page for chart links: 
- For `get_data()`
- Scrape the JSON config from the chart page
- Fetch data and metadata for every indicator from the indicator-based data API
- Throw a …
> :tada: Add a new charts-based data API

- etl/steps/data/garden/emdat/2024-04-11/natural_disasters.py
Economic impact variables are given in thousands of dollars. We used to convert to dollars when creating additional variables. Therefore, one of the new tables on the impact of disasters (that was created prior to that conversion) was not properly selecting disasters with a large economic impact.
Now the conversion happens earlier in the pipeline (within `prepare_input_data`), and the table on the impact of disasters is corrected.
The effect of the bug, however, is very small, since only a small fraction of the economic impacts has coverage.
> 🐛 Fix economic impacts variables in natural disasters

- apps/owidbot/chart_diff.py
- apps/owidbot/cli.py
- apps/owidbot/github_utils.py
- etl/config.py
Update the GitHub check in owidbot's chart diff in addition to posting it as the owidbot user (owidbot's updates are run every 5 minutes). The check is updated through the GitHub App. This also refactors existing GitHub utility functions.
The check itself is pretty bare-bones since the information about unapproved charts is already shown in owidbot's comment. We can improve the title/summary later.
Example of a check:
Example of owidbot comment:
> :tada: update github check in owidbot's chart-diff

- etl/helpers.py
- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/test_variables.py
Fix for https://github.com/owid/etl/issues/2636
When working on this, I noticed that we don't combine `type` and `sort` (e.g. `dropna()` loses information about ordinal types). I fixed those fields (I haven't fixed all possible edge cases as it is rarely used and typically in a grapher step) and added unit test in case we add more fields to remind us about adding them.
> :bug: allow nans in ordinal types & add missing fields to `combine_variables_metadata`

- apps/wizard/pages/dashboard.py
Currently, updating and archiving is only allowed when working locally. But this means that, if you are working on staging (especially with the new workflow) you can't archive from staging.
This PR lets the dashboard user update and archive steps from local or staging environments (but not from production).
NOTE: I haven't tested it, so I'm not sure if `ENV == "production"` is the right condition (but I suppose it should be).
> ✨ Let dashboard update and archive on staging servers

- snapshots/ihme_gbd/2024-05-20/gbd_cause.csv.dvc
- snapshots/ihme_gbd/2024-05-20/gbd_cause.py
- snapshots/ihme_gbd/2024-05-20/gbd_prevalence.py
- snapshots/ihme_gbd/2024-05-20/shared.py
Running `python snapshots/ihme_gbd/2024-05-20/gbd_cause.py` took quite long and "froze" at the end when creating the snapshot. The "froze" was caused by uploading a pretty large file as snapshot.
This PR tries to save memory wherever possible. It avoids unzipping file to disk and instead loads it directly to memory as dataframe. Then it optimizes it with `repack_frame`.
Finally, we concatenate all dataframes using our `concatenate` function that efficiently handles categorical variables.
(The previous approach might have been ok - it's just that uploading took so long. Zipped file should have similar size as dataframe with optimal types. One advantage of working with dataframes is that we don't have to unzip them in meadow step.)
> :sparkles: GBD 2021 faster snapshot creation

- apps/owidbot/chart_diff.py
- apps/owidbot/cli.py
- apps/staging_sync/app.py
- apps/staging_sync/cli.py
- apps/wizard/pages/chart_diff/app.py
- apps/wizard/utils/__init__.py
- apps/wizard/utils/env.py
- etl/config.py
- tests/apps/wizard/utils/test_env.py
Managing various envs (live, staging, local, etc.) has become more scattered and everyone is reinventing the wheel with their own helper functions. This PR unifies env management under existing `OWIDEnv` class.
Leverage `OWIDEnv` object for managing settings and engines for various environments. Instead of using default `etl.config`, you can now pass arbitrary config. There are also helper functions for creating `OWIDEnv` for staging servers etc.
I also removed `staging` from `OWIDEnvType` since we no longer use them (@lucasrodes can I remove `remote-staging` to `staging`?). Should I maybe also remove mentions of `live` from everywhere and replace them by `production`?
Currently, we compare `chart-diff` against `staging-site-master` on staging servers. That's not optimal as we'd like to …
> :hammer: enable chart-diff to connect to production and clean up envs

- apps/owidbot/cli.py
- apps/step_update/cli.py
- apps/wizard/pages/chart_diff/app.py
- apps/wizard/utils/__init__.py
- apps/wizard/utils/env.py
- etl/chart_revision/v3/indicator_update.py
- etl/config.py
- etl/datadiff.py
- etl/steps/data/garden/neglected_tropical_diseases/2024-05-18/funding.py
Various improvements to `chart-diff` that I found to be useful when updating WDI dataset.
- Add pagination to charts in `chart-diff` with 10 charts per page (WDI has 500+ charts...). We can try removing it when expander lazy loads its content (it's on their roadmap for August 2024)
- Add option to use `STAGING=1` env which assigns your current branch to `STAGING`. This lets you put `STAGING=1` in your `.env` and always run ETL against the correct staging database
- Move `Refresh` button next to `Approve / Pending`
- Fix minor bugs in indicators upgrader encountered when updating WDI
> :sparkles: chart-diff improvements

- etl/steps/data/garden/oecd/2024-04-30/affordable_housing_database.countries.json
- etl/steps/data/garden/oecd/2024-04-30/affordable_housing_database.meta.yml
- etl/steps/data/garden/oecd/2024-04-30/affordable_housing_database.py
- snapshots/oecd/2024-04-30/affordable_housing_database_homelessness.xlsx.dvc
From issue https://github.com/owid/owid-issues/issues/791
OECD removed Belgium from their dataset, so I have uploaded the new snapshot version and added metadata.
> ✨  oecd: update changes in snapshot

- apps/wizard/pages/charts/utils.py
- apps/wizard/pages/indicator_upgrade/utils.py
- apps/wizard/utils/__init__.py
- etl/chart_revision/v1/deprecated.py
- etl/chart_revision/v1/revision.py
- etl/db.py
- etl/grapher_helpers.py
- etl/scripts/faostat/archive_old_datasets.py
- etl/scripts/faostat/create_chart_revisions.py
- etl/variable_mapping_translate.py
- poetry.lock
- pyproject.toml
We've been enduring a lot of pain from Mysqlclient and `libmysql.*.dylib` libraries such as this one
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/mojmir/projects/etl2/.venv/lib/python3.10/site-packages/MySQLdb/__init__.py", line 17, in <module>
from . import _mysql
ImportError: dlopen(/Users/mojmir/projects/etl2/.venv/lib/python3.10/site-packages/MySQLdb/_mysql.cpython-310-darwin.so, 0x0002): Library not loaded: '/usr/local/opt/mysql/lib/libmysqlclient.22.dylib'
Referenced from: '/Users/mojmir/projects/etl2/.venv/lib/python3.10/site-packages/MySQLdb/_mysql.cpython-310-darwin.so'
Reason: tried: '/usr/local/opt/mysql/lib/libmysqlclient.22.dylib' (no such file), '/usr/local/lib/libmysqlclient.22.dylib' (no such file), …
```
> :hammer: migrate from mysqlclient to pymysql

- apps/owidbot/grapher.py
Adds ✅ (no differences) or ❌ (differences found) to the SVG tester's bot comment. Also refactors the code a bit.
> ✨ (svg tester) add status icons

- apps/chart_sync/cli.py
- apps/owidbot/chart_diff.py
- apps/owidbot/cli.py
- apps/wizard/utils/env.py
- etl/config.py
- tests/apps/wizard/utils/test_env.py
- tests/test_config.py
Fix `STAGING=fix/wizard-3 etlr ...` and `STAGING=1` with branch names containing `/` and other unusual characters.
> :bug: get proper container name when using weird branch names

- apps/utils/scan_chart_diff.py
- etl/config.py
Don't override system environment variables by those from `.env` file. We've [enabled it](https://github.com/owid/etl/pull/2272) some time ago for reasons no one remembers. It's unintuitive behaviour. Imagine I use `STAGING=mojmir` in my `.env` file and I run `STAGING=other etlr ...`. I'm expecting that the env variable in front of the command has higher priority, but it gets overwritten.
(I want to have `STAGING=1` in my `.env` and optionally set `STAGING=mojmir` to override it.)
> :hammer: set override=False when loading env

- apps/wizard/pages/owidle.py
- dag/education.yml
- dag/emissions.yml
- dag/health.yml
- dag/main.yml
- dag/natural_disasters.yml
- dag/poverty_inequality.yml
- etl/data_helpers/misc.py
- etl/steps/data/garden/education/2023-07-17/education_lee_lee.py
- etl/steps/data/garden/emdat/2023-09-20/natural_disasters.py
- etl/steps/data/garden/emdat/2024-04-11/natural_disasters.py
- etl/steps/data/garden/emissions/2023-10-06/gdp_and_co2_decoupling.py
- etl/steps/data/garden/emissions/2024-02-26/gdp_and_co2_decoupling.py
- etl/steps/data/garden/worldbank_wdi/2024-05-20/wdi.py
- etl/steps/data/meadow/worldbank_wdi/2024-05-20/wdi.py
- snapshots/worldbank_wdi/2024-05-20/wdi.zip.dvc
Remove misc function `add_origins_to_wdi` and update dependency `garden/worldbank_wdi/2023-05-29/wdi` to `garden/worldbank_wdi/2024-05-20/wdi` in all steps. I used ChatGPT-generated `wdi.sources.json` to get a producer (previously `source.name`) for a source from WDI metadata. Initially, I wanted to avoid ChatGPT and just dump the full source name as producer, but it was too messy and longer than 255 characters. If we wanted to polish it even further, we could use ChatGPT to create a full origin from given source name (not sure if it's worth it though).
Here is an example of an [old chart](https://admin.owid.io/admin/charts/317/edit) and a [new chart](http://staging-site-wdi-sources-to-origins/admin/charts/317/edit). It's almost identical except for indicator's description, which has been …
> :bar_chart: switch WDI from sources to origins

- apps/cli/__init__.py
This PR doesn't fix https://github.com/owid/etl/issues/2735
but for now it simply skips the load of metagpt, to be able to keep using `etl --help`.
> Skip metagpt on etl cli, to avoid error

- apps/explorer_update/cli.py
`etl explorer-update` was failing for one of the explorers. I haven't looked into why that's happening, but in this PR I simply raised a log error when such a case occurs.
> 🐛 Fix explorer-update cli, to avoid it from failing in odd cases

- apps/step_update/cli.py
- apps/wizard/app_pages/dashboard.py
- etl/version_tracker.py
- tests/test_version_tracker.py
* Ensure that steps that affect any step in the `external` channel are not archivable.
* Move the logic of the update status of steps from StepUpdater to VersionTracker, and ensure the archiving logic of StepUpdater and VersionTracker are aligned.
* Include the update statuses "Archived" (for steps that have already been archived) and "Not yet used" (for steps that may be in their latest version, but not used in any charts or by any external channel).
* Move a few things around for consistency, and fix broken test.
NOTE: This will make VersionTracker a bit slower, but hopefully not too much. If so, we can figure out ways to speed some things up.
> 🎉 Ensure steps affecting `external` channel are not archivable

- apps/backport/datasync/data_metadata.py
- apps/backport/datasync/datasync.py
- etl/files.py
- etl/grapher_import.py
- etl/grapher_model.py
- tests/test_files.py
PR with MySQL migration https://github.com/owid/owid-grapher/pull/3690
Right before uploading data & metadata to R2 as JSON files, calculate checksums for data and metadata. If checksums are matching ones in MySQL, it means that the data is identical and there's no need to upload the same files.
Checksums will be added as we refresh datasets. We could also bump `ETL_EPOCH` and populate all datasets, but perhaps only after making sure this concept works.
For metadata, we exclude fields `updatedAt`, `dataChecksum`, `metadataChecksum` (otherwise we'd always get a different checksum).
Tested on two staging servers with command
```
time poetry run etlr grapher://grapher/ihme_gbd/2024-05-20/impairments --force --private --grapher --only
```
Calculating checksums doesn't take much time (I ran a …
> :tada: save checksums for indicators in MySQL

- apps/utils/draft_pull_request.py
Following [this discussion](https://owid.slack.com/archives/C014SGT6W9X/p1718024551640549), now you don't need to write `--new-branch` and you can simply pass the name of the new branch as an argument.
I haven't implemented the `--ready-to-review` idea, because we don't want to create a PR that is ready for review with a draft title. If we do that, then we also need an argument for the title. At this point, I think it's just easier and more transparent to do it from github. It feels safer if the tool just drafts things. What do you think?
> ✨ Improve `etl d draft-pr` tool

- apps/chart_sync/cli.py
- apps/wizard/app_pages/chart_diff/app.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
- apps/wizard/app_pages/chart_diff/show.py
- apps/wizard/utils/__init__.py
- etl/config.py
- etl/grapher_model.py
- etl/steps/data/garden/biodiversity/2024-01-25/cherry_blossom.meta.yml
- etl/steps/data/grapher/biodiversity/2024-01-25/cherry_blossom.py
Chart-diff currently only shows charts with changed config (due to updating variable ids by indicator upgrader). We'd like to have an option to show all charts with changes - either coming from change to the underlying data or metadata.
Use data and metadata checksums to optionally show chart differences, in addition to just changed chart configurations. This information is displayed as tags next to a chart slug. Currently, only charts with changed configurations are shown by default, and approving them is enough for owidbot to give you a ✅. However, if desired, you can enable the option to show data and metadata changes in the filters.
The new function `modified_charts_by_admin` assumes that all charts or datasets were created by an Admin user with ID=1. This is a temporary solution …
> :tada: show chart diffs with changed checksums

- apps/backport/datasync/data_metadata.py
- tests/backport/datasync/test_data_metadata.py
Function `variable_metadata` was including `dataChecksum` and `metadataChecksum` in its output. This output was then used to calculate `checksum_metadata` which was creating a feedback loop with ever changing checksums and inconsistencies.
This PR removes `dataChecksum` and `metadataChecksum` from there and doesn't include it in S3 JSON file.
> :bug: fix metadata checksum

- dag/health.yml
- etl/steps/data/garden/ihme_gbd/2024-05-20/shared.py
**Should be merged outside of working hours**
Hotfix missing origins in GBD. A proper fix would involve adding `pr.concat` function that works with categoricals (tracking it in this issue https://github.com/owid/etl/issues/2796)
> :bug: fix origins in leading causes of death

- dag/main.yml
- etl/steps/data/garden/lgbt_rights/2023-04-27/lgbti_policy_index.meta.yml
- etl/steps/data/garden/lgbt_rights/2023-04-27/lgbti_policy_index.py
- etl/steps/data/garden/lgbt_rights/2024-06-03/equaldex.py
- etl/steps/data/grapher/lgbt_rights/2023-04-27/lgbti_policy_index.py
- etl/steps/data/grapher/lgbt_rights/2024-06-03/equaldex.py
- etl/steps/data/meadow/lgbt_rights/2023-04-27/lgbti_policy_index.py
- snapshots/lgbt_rights/2023-04-27/lgbti_policy_index.xlsx.dvc
Add combined indicators for same-sex marriage, LGB in the military and age of consent. Also add aggregations for each of the status of these columns.
The rest of the code is the same, though it has been updated to reflect the latest metadata changes.
Main issue https://github.com/owid/owid-issues/issues/1556
> :bar_chart: Add combined variables for Velasco LGBT+ data

- etl/config.py
- lib/walden/tests/test_catalog.py
Fix circular import of `etl.config` and `etl.db`. I wasn't able to run `from etl.db import get_engine` without this fix.
> :bug: fix circular imports of get_engine

- etl/config.py
`OWID_ENV` was set to local by default during this [refactoring](https://github.com/owid/etl/commit/2c6b6938bcdc1a4674a7ba1411bda851c51cc4f0#diff-65c3044b26e69b8a41f84a5c6dd8fe22ceb6f6c91b7b1815186968c2177dc5c5R479). Wizard then uses it as a default env in function [get_staging_creation_time](https://github.com/owid/etl/blob/5be4b4dbf1bc403d26a6ce6398e5c9420e9b1928/apps/wizard/utils/__init__.py#L711). Since local MySQL doesn't exist in production, wizard fails when trying to connect to it with
```
Access denied for user 'owid'@'etl-prod-2.owid.org.github.beta.tailscale.net
```
This PR doesn't load local by default, but from env by default.
> :bug: load .env by default instead of loading local

- etl/config.py
Using `STAGING=branch` updates variables like `config.DB_HOST`, but it wasn't reflected in `OWID_ENV` object, which was using variables from `.env` file (irrespective of staging).
This is a hotfix, unit tests coming up in a next PR.
> :bug: fix default env

- etl/config.py
Create `OWID_ENV` from `etl.config` so that they always match. It'd be nice to DRY it so that we don't have MySQL credentials duplicated in `OWID_ENV` and in `etl.config.DB_*`.
@lucasrodes will this work for production & staging servers? Is there a situation where we'd need `load_from_local`?
> :bug: Always make OWID_ENV match etl.config

- apps/utils/draft_pull_request.py
- `--category` (or `-c`): PR category based on [our etiquette](https://www.notion.so/owid/Git-GitHub-etiquette-68e824bed1a747e1a01f2b771c695bf7). Will be used to add an emoji to the start of the PR title.
- `--scope` (or `-s`): brief summary of the PR scope (e.g. 'wizard')
`etl d draft-pr <branch-name> -c data -t "Update VDEM data"` →  **:bar_chart: Update VDEM data**
`etl d draft-pr <branch-name> -c data -s vdem -t "update"` →  **:bar_chart: vdem: update**
`etl d draft-pr <branch-name> "Update VDEM data"` →  **Update VDEM data**
`etl d draft-pr <branch-name> -c enhance -s vdem` →  **🚧 Draft PR for branch <branch-name>** (i.e. no title is given, will ignore prefixes and use default title)
- This brings us closer to harmonizing PR titles. It also encourages us to define the scope of our …
> ✨ draft-pr: add options

- etl/grapher_model.py
> chart-sync ran on my latest merged [PR here](https://github.com/owid/etl/pull/2834). In it, I rejected all the chart-diffs, yet one of them was migrated to PROD. You can see I rejected all of them here: http://staging-site-news/etl/wizard/chart-diff.
@lucasrodes this is the fix. I noticed that in MySQL that chart was first rejected and then approved
```
mysql> select * from chart_diff_approvals;
+----+---------+---------------------+-----------------+---------------------+----------+
| id | chartId | sourceUpdatedAt     | targetUpdatedAt | updatedAt           | status   |
+----+---------+---------------------+-----------------+---------------------+----------+
|  1 |    7906 | 2024-06-18 20:34:20 | NULL            | 2024-06-19 12:47:50 | rejected |
|  2 |    7906 | 2024-06-18 20:34:20 | …
```
>  :bug: Use latest approval for chart-diff

- etl/steps/data/meadow/climate/2023-12-20/surface_temperature.py
Use smaller type float32 to reduce memory footprint. Check out data-diff below for differences (it's on the sixth decimal place). If this doesn't work, I guess we can just move the entire `_load_data_array` to snapshot.
>  :bar_chart: Reduce memory footprint of surface temperature

- apps/wizard/app_pages/chart_diff/app.py
- apps/wizard/app_pages/chart_diff/chart_diff_show.py
- apps/wizard/utils/__init__.py
- pyproject.toml
- Increase iframe height: footer buttons were hidden in some display settings. Changed from 500px to 600px.
- Changed pagination mode. Before arrows were used to change page; now a number input.
- remove `etlci` command alias, since it is not used. Instead, we use `etl` which is equivalent.
- improve presentation of icon in expander from chart-diff
- `chart_html`: Reduce the HTML code for the chart. Try to keep just the bare minimum to render the chart.
- use `st.experimental_fragment` for the chartdiff blocks, so that if the user interacts with one box, only code within the box is re-executed. I.e. avoids long re-runs of complete page.
> ✨ chart-diff: performance, ux/ui

- etl/steps/data/garden/energy/2024-06-20/electricity_mix.py
Fix spurious jumps in energy data for aggregate regions. The full explanation is in the code.
> 📊 Fix spurious jumps in energy data for aggregate regions

- apps/wizard/app_pages/indicator_upgrade/app.py
- apps/wizard/app_pages/indicator_upgrade/indicator_mapping.py
> 🐛 indicator-upgrader: team feedback

- apps/wizard/app_pages/map_brackets.py
The main motivation for these improvements is to have the chart shown more prominently so that the user doesn't have to constantly scroll down.
Actions taken:
- Move description and limitations to a `popover` (labeled as "Learn about it") so that it doesn't take much vertical space.
- Don't show the different 'use cases' radio buttons, since only one is supported. Signal this in the `Learn about it` popover.
- Put dataset and indicator selection in a container with border so it is easily found.
- Sidebar is shown by default. It was set to `collapsed`; I thought there we don't necessarily need to hide it this time since the page doesn't need much width. 
- Move configuration parameters to the side bar.
- Move export config button to the side bar, so that it is always visible.
There are …
> ✨ mab bracketer: ux/ui

- snapshots/wb/2024-03-27/pip_api.py
- snapshots/wb/2024-03-27/world_bank_pip_percentiles.csv.dvc
The file provided from the World Bank now includes an empty column that propagated through all percentile steps. I corrected the extraction code to drop that column and updated the snapshot.
> :bug: fix index column left in percentile file

- apps/backport/datasync/data_metadata.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
- tests/backport/datasync/test_data_metadata.py
Field `dimensions` is excluded from metadata checksum calculation. This means that adding new countries won't refresh the metadata file, which is wrong.
This PR will change `metadataChecksum` for new / refreshed indicators, but **won't update checksums** for existing ones (that would require incrementing ETL epoch). We have two options now - either keep `metadataChecksum` as it is and show all metadata as modified, or we set `metadataChecksum` in MySQL to NULL and don't show any metadata modifications (until checksum is refreshed). @lucasrodes what do you think? Or is the metadata config so used that we should go for the full rebuild?
>  :bug: Don't exclude dimensions from metadata checksum calculation

- apps/wizard/app_pages/indicator_upgrade/explore_mode.py
Tabs were being shown even they were not supposed to. 
It seems like streamlit doesn't behave as expected when generating a variable name of tabs.
Example:
- Explore mode for first indicator had 3 tabs
- Explore mode for first indicator had 2 tabs
HOWEVER, in the second explore mode three tabs are shown.
SOLUTION: show always the same number of tabs. If some tab is empty, just show it as empty.
> ✨ explore_mode: fix tabs

- apps/wizard/app_pages/indicator_upgrade/explore_mode.py
Add dataframe with overview of country data.
Quick comparison of the timeseries of the old and new indicators for each country. Uses `st.column_config` to show line charts in a dataframe ([see docs](https://docs.streamlit.io/develop/api-reference/data/st.column_config/st.column_config.linechartcolumn)).
> ✨ indicator upgrader: explore mode

- etl/data_helpers/geo.py
- etl/data_helpers/population.py
- lib/catalog/owid/catalog/datasets.py
- lib/catalog/owid/catalog/tables.py
Reading tables from disk is fast (<1s). What is slow is setting a primary key with `set_index` (>6s). Some steps using population through helper functions could be speeded up by avoiding setting & resetting the index.
This PR adds `read_table` method as an alternative to `ds[table_name]` that lets you optimize the reading.
> :hammer: add read_table method to read table without setting primary_key

- apps/wizard/app_pages/indicator_upgrade/indicator_mapping.py
A properties in `st.session_state` was being set within a function with decorator `@st.cache_data`.
This was preventing this set operation to be executed correctly on staging. That's because the code on staging had been ran in the past already, and values had been cached, which means that the function (and ultimately the set operation) were not being executed.
This error was not detected earlier because it was not a problem when working locally (but accessing remote resources).
> 🐛 indicator upgrader: session state not correctly set due to cache

- apps/wizard/app_pages/indicator_upgrade/explore_mode.py
In explore mode, several dataframes are shown. These, do not need to have the default numerical dataframe index shown, as it does not add any value. This PR removes the index column in the display.
> ✨ explore mode: remove index in dfs

- Makefile
- lib/catalog/owid/catalog/utils.py
- pyproject.toml
- tests/apps/wizard/app_pages/test_apps.py
Proof of concept for streamlit integration tests. These tests run streamlit app and connect to the staging MySQL (tests should be therefore read-only).
I've added a new Buildkite step for running integration tests. These are **not run by default** when you run `make test`, but with `make test-integration` (and connect to DB from your `.env`).
There are basic tests for chart-diff, fasttrack and indicator-upgrade. Nothing fancy, just making sure those apps start without errors and that you can click some buttons. We could of course make them more complex, but that would add additional friction to development. The main point of these tests is to prevent basic errors like circular imports.
There's an artificial `raise Exception` in chart-diff to test it out. If you click on `Details` of …
>  :hammer: Streamlit integration tests

- dag/demography.yml
- etl/steps/data/garden/demography/2024-07-12/un_wpp_historical.meta.yml
- etl/steps/data/garden/demography/2024-07-12/un_wpp_historical.py
- etl/steps/data/grapher/demography/2024-07-12/un_wpp_historical.py
- snapshots/fasttrack/latest/un_wpp_historical.csv.dvc
[Tracking issue](https://github.com/owid/owid-issues/issues/1561)
- Migrate Grapher dataset to ETL
- Import historical WPP data via Fast-Track, using the data we had manually transcribed in the past.
- I've added more data from revisions we hadn't transcribed. These are available from WPP's site: https://population.un.org/wpp/Download/Archive/Standard/. We now have data for all revisions since 1990.
- Add data from recent reviews 2022 and 2024 via ETL (from Garden datasets)
- Update the chart with a gradient color scheme, and add two samples for 2002 and 2012 (to avoid large time gaps).
> 📊 population: update historical dataset

- etl/steps/data/garden/un/2024-07-12/un_wpp.py
There was a bug when adding population density to the `population` table, which prevented the estimates on this indicator (pre 2024) to be added.
> 🐛 population density

- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/test_tables.py
I was finding very strange metadata issues, and it took me a while to find the culprit.
When pivoting a table, we are copying metadata from one variable to another. But this copy is shallow, so, when modifying the metadata of one variable, it affects others.
For example: 
```
from owid.catalog import Table, VariablePresentationMeta
import pandas as pd
tb = Table(pd.DataFrame({"year": [2020, 2021, 2022], "group": ["g1", "g1", "g1"], "subgroup": ["s1", "s1", "s2"], "value": [1, 2, 3]}))
tb["value"].m.presentation = VariablePresentationMeta(title_public="Value")
tb_p = tb.pivot(index="year", columns=["group", "subgroup"], values="value", join_column_levels_with="_")
tb_p["g1_s1"].m.presentation.title_public = "Group 1, Subgroup 1"
print(tb_p["g1_s2"].m.presentation.title_public)  # This …
```
> 🐛 Fix issue with metadata after pivot operations

- etl/steps/data/garden/demography/2024-07-15/population.meta.yml
- etl/steps/data/garden/demography/2024-07-15/population.py
Adding smoothed version of population growth rate as per [suggestion](https://github.com/owid/owid-issues/issues/1393#issuecomment-2238916350) from Hannah.
> 📊 population growth: add smoothing pre-1900

- snapshots/demography/2023-10-10/zijdeman_et_al_2015.xlsx.dvc
Description for Zijdeman snapshot was wrong, leading to wrong markdown rendering.
See https://ourworldindata.org/grapher/life-expectancy
- Fix links in snapshot file.
- Re-run snapshot step: `python snapshots/demography/2023-10-10/zijdeman_et_al_2015.py`
---
Fixes https://owid.slack.com/archives/C03NV9Z3YSV/p1721221808426329, raised by @rakyi
> 🐛 le: markdown rendering

- apps/wizard/app_pages/chart_diff/chart_diff.py
- etl/grapher_model.py
Fix for https://github.com/owid/etl/pull/2995
This PR reduces false positives from data & metadata changes (all are described in code in detail)
- Exclude certain datasets like COVID and AI Epoch from `METADATA CHANGE` in chart-diff (fixing the root cause turned out to be too challenging)
- Use `catalogPath` instead of `variableId` when comparing data & metadata checksums
- Remove data & metadata checksums change when variable is updated by indicator upgrader
If you want to test it, you can check that running it against `cset-ai` shows only relevant config changes
```
STAGING=cset-ai streamlit run apps/wizard/app_pages/chart_diff/app.py
```
> :sparkles: exclude certain datasets from metadata changes

- lib/repack/owid/repack/__init__.py
- lib/repack/tests/test_repack.py
Fix https://github.com/owid/etl/pull/2974#discussion_r1691003507
`"string"` type should be handled in the same way as `object` (`str`) by `repack`.
> :sparkles: Refactor repack_series function to handle string dtype

- lib/catalog/owid/catalog/processing.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
Trivial implementation of `keep_metadata` decorator from https://github.com/owid/etl/issues/3009. It is used for `pr.to_numeric` function.
>  :sparkles: Add decorator keep_metadata

- apps/wizard/app_pages/chart_diff/chart_diff_show.py
- apps/wizard/app_pages/chart_diff/conflict_resolver.py
I saw errors from chart-diff on this [staging server](http://staging-site-yougob/etl/wizard/chart-diff?change_type=new&change_type=config) about `DuplicateWidgetID`. Adding suffix `chart_id` to all those widgets fixed them, but I'm not sure if there could be any side effects.
>  :bug: Make widget keys unique in chart-diff

- etl/steps/data/garden/covid/latest/cases_deaths.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/test_tables.py
- lib/catalog/tests/test_variables.py
Related to #3009
Implement the `rolling` method for `VariableGroupBy` and `TableGroupBy` classes to support rolling window functions and preserve metadata.
* **lib/catalog/owid/catalog/tables.py**
- Implement the `rolling` method in the `VariableGroupBy` class.
- Implement the `rolling` method in the `TableGroupBy` class.
- Ensure metadata preservation in the `rolling` method for both `VariableGroupBy` and `TableGroupBy`.
* **lib/catalog/tests/test_tables.py**
- Add unit tests for the `rolling` method in `VariableGroupBy`.
- Add unit tests for the `rolling` method in `TableGroupBy`.
- Verify that the `rolling` method works without errors and preserves metadata in both classes.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/owid/etl/issue …
> :sparkles: Fix rolling methods in VariableGroupBy and TableGroupBy

- dag/education.yml
- dag/excess_mortality.yml
- dag/main.yml
- etl/data_helpers/geo.py
- etl/steps/data/garden/demography/2023-02-03/life_expectancy.py
- etl/steps/data/garden/education/2023-07-17/education_barro_lee_projections.py
- etl/steps/data/garden/education/2023-07-17/education_lee_lee.py
- etl/steps/data/garden/education/2023-07-17/shared.py
- etl/steps/data/garden/excess_mortality/latest/excess_mortality/process.py
- etl/steps/data/garden/faostat/2022-05-17/shared.py
- etl/steps/data/garden/faostat/2023-02-22/shared.py
- etl/steps/data/garden/faostat/2023-06-12/faostat_food_explorer.py
- etl/steps/data/garden/faostat/2023-06-12/shared.py
- etl/steps/data/garden/faostat/2024-03-14/shared.py
- etl/steps/data/garden/health/2023-08-16/deaths_karlinsky.py
- etl/steps/data/garden/oecd/2023-05-19/co2_air_transport.py
- etl/steps/data/garden/tourism/2023-05-05/unwto.py
- etl/steps/data/garden/un/2023-08-02/comtrade_pandemics.py
- etl/steps/data/garden/un/2023-10-09/plastic_waste.py
- tests/data_helpers/test_geo.py
We had an error in nightly build about `garden/health/2023-08-16/deaths_karlinsky` not having `garden/owid/latest/key_indicators` as dependency, despite having `data://garden/demography/2023-03-31/population` as dependency.
It turned out that it even though we were expecting version `2023-03-31/population` in dependencies, function `geo.add_population_to_dataframe` for adding population is using `key_indicators` by default (instead of population dataset) and **key_indicators use outdated `2022-12-08/population`**.
There are a couple of options how to fix it:
- Replace deprecated `geo.add_population_to_dataframe` function by `geo.add_population_to_table` everywhere
- Make `key_indicators` use the latest `2023-03-31/population` population dataset
Perhaps we could do both?
This PR fixes only …
>  :bug: Helper function `geo.add_population_to_dataframe` uses old version of population dataset

- lib/catalog/owid/catalog/tables.py
I've recently moved `.copy` from `pr.merge` method to a different place which possibly broke metadata propagation.
>  :bug: Fix metadata propagation in pr.merge

- etl/explorer_helpers.py
Raise error if not all items in the `yVariableIds` column of the graphers dataframe are lists.
> ✨ Avoid unexpected behaviour from `Explorer` when writing to tsv files

- apps/backport/datasync/data_metadata.py
- apps/chart_sync/admin_api.py
- apps/wizard/app_pages/expert/prompts.py
- etl/grapher_import.py
- etl/grapher_model.py
- etl/steps/__init__.py
- tests/backport/datasync/test_data_metadata.py
ETL part of https://github.com/owid/owid-grapher/pull/3793.
`grapherConfig` can't be directly saved to MySQL, because there are side effects to it (it updates all relevant chart configs). Instead of duplicating the side effect logic in ETL, we'll rather call Admin endpoints that handle all that:
```
PUT /variables/:variableId/grapherConfigETL
DELETE /variables/:variableId/grapherConfigETL
```
It works fairly well. I haven't optimized it much, since only a handful of indicators use `grapher_config`.
- `grapherConfigETL` is no longer in `*.metadata.json`, is that ok?
- This will change checksum of a lot of indicators, we might have to trigger a full ETL rebuild with new epoch
> :sparkles: Post grapherConfigETL update to Admin API

- lib/catalog/owid/catalog/s3_utils.py
> 🐛  log.info() only takes a single string argument

- apps/step_update/cli.py
- apps/utils/draft_pull_request.py
Automate PR creation after updating step in ETL dashboard (see our docs on [Updating data](https://docs.owid.io/projects/etl/guides/data-work/update-data/)).
We update a step with ETL dashboard, but then have to manually create a PR and potentially reference branch or a link to Github diff that excludes copying steps. This PR automates it a bit, while keeping it flexible enough.
After you update your step, StepUpdater CLI will show you a command:
```
Create PR automatically with:
etl d draft-pr update-{short_name} --title ":bar_chart: Update {short_name}" --step-update
```
An extra flag `--step-update` will commit the updated steps and post a link to view diff without copied steps (we used to use reference branch for this). See https://github.com/owid/etl/pull/3044 for example.
If this …
>  :sparkles: Add --step-update to draft-pr command

- etl/steps/data/garden/un/2024-07-08/maternal_mortality.py
Fix scaling of indicator: "percentage of maternal deaths indirectly related to HIV"
> 🐛 : maternal mortality hiv percentage fix

- docs/guides/data-work/update-data.md
Update documentation for section "Updating data" that doesn't use reference branch and recommends using `etl d draft-pr --step-update` for creating PR.
Check out [new docs](http://staging-site-docs-updating-data/etl/docs/guides/data-work/update-data/#4-approve-chart-differences) on staging server.
@pabloarosado I'm the only one who is using the new workflow. It'd make sense to first try it out a few times and only then overwrite the existing docs.
>  :honeybee: Docs for Updating data

- dag/minerals.yml
- etl/steps/data/explorers/minerals/latest/minerals.py
- etl/steps/data/garden/bgs/2024-07-09/world_mineral_statistics.py
- etl/steps/data/garden/minerals/2024-07-15/minerals.py
- etl/steps/data/garden/usgs/2024-07-15/historical_statistics_for_mineral_and_material_commodities.meta.yml
- etl/steps/data/garden/usgs/2024-07-15/historical_statistics_for_mineral_and_material_commodities.py
- etl/steps/data/garden/usgs/2024-07-15/mineral_commodity_summaries.py
- snapshots/bgs/2024-07-09/world_mineral_statistics.zip.dvc
- snapshots/usgs/2024-07-15/historical_statistics_for_mineral_and_material_commodities.zip.dvc
- snapshots/usgs/2024-07-15/mineral_commodity_summaries_2022.zip.dvc
- snapshots/usgs/2024-07-15/mineral_commodity_summaries_2023.zip.dvc
- snapshots/usgs/2024-07-15/mineral_commodity_summaries_2024.zip.dvc
* Combine BGS and USGS data only where they coincide (allow for shares up to 110% of USGS' World).
* Remove non-critical minerals, and other combinations with sparse or confusing data (mostly BGS).
* Implement all suggestions from the minerals bug bash.
* Fix various data issues.
* Improve metadata.
> 📊 Improve minerals explorer (different way of combining BGS and USGS)

- etl/steps/data/explorers/covid/latest/covid.config.yml
- etl/steps/data/explorers/covid/latest/covid.py
- etl/steps/data/garden/covid/latest/cases_deaths.meta.yml
- etl/steps/data/garden/excess_mortality/latest/excess_mortality_economist/excess_mortality_economist.meta.yml
- Have excess deaths (relative) as the default view, as a map.
- Improve display colours for XM data and confirmed deaths
> ✨ covid: add map as default view

- apps/cli/__init__.py
- apps/step_update/cli.py
- docs/guides/data-work/update-data.md
This amends https://github.com/owid/etl/pull/3152 to replace `etl d pr` with `etl pr.` Also, it updates the documentation accordingly.
`etl d draft-pr` is left for backwards compatibility. Might remove it once the team adopts `etl pr`.
> ✨ cli: etl pr

- etl/steps/data/garden/demography/2024-07-15/population.meta.yml
- etl/steps/data/garden/demography/2024-07-15/population.py
[tracking issue](https://github.com/owid/owid-issues/issues/1393)
Estimates pre-1900 should be estimated every 50 years, as Max did in his initial static chart. Otherwise, data artifacts appear.
> 📊 population growth

- apps/step_update/cli.py
- etl/steps/__init__.py
I noticed that `to_dependency_order(dag=dag, includes=STEPS, only=True)` was returning a list of steps that was larger than STEPS. But if I understand correctly, `only` should avoid that, right?
This PR may fix it (but I'm not sure if that behaviour was as expected, and I'm misinterpreting the meaning of `only`).
As an example:
```
from etl.steps import load_dag, to_dependency_order
STEPS = ['data://grapher/war/2023-09-21/ucdp', 'data://garden/war/2023-09-21/ucdp']
steps = to_dependency_order(
dag=load_dag(),
includes=STEPS,
excludes=[],
downstream=False,
only=True,
)
```
as far as I understand, should return `['data://garden/war/2023-09-21/ucdp', 'data://grapher/war/2023-09-21/ucdp']`, but instead it was returning `['data://garden/war/2023-09-21/ucdp', …
> 🐛 Fix `filter_to_subgraph` when passing the `only` argument

- etl/command.py
- etl/steps/__init__.py
- tests/test_etl.py
Following the discussion in https://github.com/owid/etl/pull/3197 I think we should have an `exact-match` option in `etlr`, to run steps that happen to be substrings of other steps (e.g. `data://grapher/war/2023-09-21/ucdp`,  substring of `data://garden/war/2023-09-21/ucdp_prio`).
Currently `etlr data://garden/war/2023-09-21/ucdp --only --dry-run --force`:
```
--- Would run 2 steps:
1. data://garden/war/2023-09-21/ucdp
2. data://garden/war/2023-09-21/ucdp_prio
```
And if you want to run only the desired step you need to do `etlr data://garden/war/2023-09-21/ucdp$ --only --dry-run --force`, which is a bit of a hack. To avoid such unexpected executions, users not only need to remember this hack, but also know that there are other steps that will be matched to the given argument.
Instead, …
> Add exact-match to etlr options

- etl/steps/data/garden/energy/2024-06-20/electricity_mix.py
As [pointed out by a user](https://app.frontapp.com/open/msg_m22n0zm?key=keI6IIXFC5xF8wnTFSikLPYcC_q7YoBh) (and [discussed](https://owid.slack.com/archives/C3RAU3BJ9/p1723646495890999?thread_ts=1723619090.242089&cid=C3RAU3BJ9)), Switzerland was missing in [this chart](https://ourworldindata.org/grapher/electricity-prod-source-stacked). The reason is that Ember's Yearly Electricity Review does not have data for Switzerland's coal electricity production. But instead of missing, it should simply be zero (at least since 2000, where the data starts). I've set those nans to zero.
> 📊 Fix missing Switzerland electricity data

- apps/utils/draft_pull_request.py
Currently, if you use `etl pr` with a branch name that does not exist locally, but does exist remotely, an error is raised, but after the local branch has been created.
With this PR, an error is raised and no local branch is created.
I have also changed `origin.fetch()` to `origin.fetch(prune=True)`, because often the script was raising an error, claiming that the proposed new branch already existed in remote, when it was actually removed there. If you think this can have unwanted side effects, we can do `origin.fetch(prune=prune)` and add `---prune` as an optional boolean flag (but I think there is no danger setting it to True).
> ✨ Raise error in etl pr if branch already exists locally or remotely

- etl/datadiff.py
- etl/helpers.py
- etl/steps/data/garden/artificial_intelligence/2024-06-03/epoch_aggregates_affiliation.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-08-05/epoch_aggregates_affiliation.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-08-05/epoch_aggregates_affiliation.py
- etl/steps/data/meadow/oecd/2016-06-01/regional_wellbeing.py
- lib/catalog/owid/catalog/datasets.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/yaml_metadata.py
Allow passing `yaml_params` dictionary to `create_dataset` function that makes them available in YAML template. This is especially useful as a replacement for `{TODAY}` "hack" that is causing spurious diffs.
Instead of
```
desc_update: The 2024 data is incomplete and was last updated {TODAY}.
```
we can now write
```
desc_update: The 2024 data is incomplete and was last updated {date_accessed}.
```
with
```
ds_garden = create_dataset(
dest_dir, tables=[tb_agg], yaml_params={"date_accessed": tb_agg.yearly_count.m.origins[0].date_accessed}
)
```
I'll start removing `{TODAY}` from recipes in a future PR.
>  :hammer: Allow passing parameters to YAML file

- etl/steps/data/garden/energy/2024-06-20/electricity_mix.meta.yml
- etl/steps/data/garden/energy/2024-06-20/electricity_mix.py
Add per capita electricity demand to electricity mix dataset.
For more context, per capita demand existed in the `yearly_electricity` dataset, but was not used. Now, in the `electricity_mix` dataset, it is calculated again, together with the rest of per capita variables (by dividing by population).
> 📊 Add electricity demand per capita

- apps/backport/datasync/data_metadata.py
- apps/chart_sync/admin_api.py
- apps/wizard/app_pages/expert/prompts.py
- etl/grapher_import.py
- etl/grapher_model.py
- etl/steps/__init__.py
- tests/backport/datasync/test_data_metadata.py
REOPENED https://github.com/owid/etl/pull/3049
ETL part of https://github.com/owid/owid-grapher/pull/3793.
`grapherConfig` can't be directly saved to MySQL, because there are side effects to it (it updates all relevant chart configs). Instead of duplicating the side effect logic in ETL, we'll rather call Admin endpoints that handle all that:
```
PUT /variables/:variableId/grapherConfigETL
DELETE /variables/:variableId/grapherConfigETL
```
It works fairly well. I haven't optimized it much, since only a handful of indicators use `grapher_config`.
- `grapherConfigETL` is no longer in `*.metadata.json`, is that ok?
- This will change checksum of a lot of indicators, we might have to trigger a full ETL rebuild with new epoch
> ✨ Post grapherConfigETL update to Admin API

- etl/grapher_import.py
- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_risk.py
- etl/steps/data/garden/ihme_gbd/2024-05-20/shared.py
Percentages from `gbd_risk` dataset such as [this one](https://admin.owid.io/admin/variables/937511) got removed by [this commit](https://github.com/owid/etl/commit/93e92ce428abd88a98bd08b819064cbf335fec88). Because of that, ETL tries to rebuild `gbd_risk` every time it runs and then throws a warning.
This PR adds `run_percent=True` argument to regional aggregates to put them back. It also raises an error on staging servers when there are variables that cannot be deleted automatically.
>  :bug: gbd-risk: Add missing percentages

- apps/wizard/app_pages/chart_diff/conflict_resolver.py
- apps/wizard/app_pages/indicator_upgrade/app.py
- apps/wizard/app_pages/indicator_upgrade/charts_update.py
- apps/wizard/app_pages/indicator_upgrade/utils.py
- apps/wizard/utils/__init__.py
- etl/grapher_model.py
- etl/indicator_upgrade/indicator_update.py
- etl/indicator_upgrade/schema.py
- tests/test_grapher_model.py
Couple of bugfixes for `chart-sync`
- Don't use default grapher schema `004`, but always load the schema specified in `config["$schema"]` (otherwise we get errors in chart-diff)
- Remap variableId of `sortColumnSlug`, this was previously left out (also try mapping new unknown fields)
> :bug: Improve chart-sync

- etl/grapher_model.py
This catches up the ETL side data model with a recently added column on the chart_configs table
> 🔨 engineering: add field definition for new generated md5 column on chart_configs

- etl/steps/data/garden/health/2024-09-05/seattle_pathogens.meta.yml
- etl/steps/data/garden/health/2024-09-05/seattle_pathogens.py
- etl/steps/data/grapher/health/2024-09-05/seattle_pathogens.py
Address https://github.com/owid/owid-issues/issues/1653#issuecomment-2355981837
> 📊 covid: merge categories

- etl/steps/data/garden/un/2024-07-16/migrant_stock.meta.yml
- etl/steps/export/explorers/migration/2024-08-05/migration_config_dict.py
Minor migration typos fixed in etl
> Migration typos

- apps/wizard/app_pages/datainsight_robot.py
- apps/wizard/app_pages/insights.py
The insighter has one mode at the moment which uses a chart view.
This PR adds a second, where it attempts to capture all the trends in a raw dataset.
> :tada: Add data explaining capability to Insighter

- snapshots/health/latest/global_health_mpox.py
The update should fail if Global.health adds 2023 data to their dataset; we currently add this manually, so this is to prevent double-counting.
> ✨ Mpox safety 

- lib/catalog/README.md
- lib/catalog/owid/catalog/charts.py
- lib/catalog/owid/catalog/internal.py
- lib/catalog/tests/test_charts.py
With the introduction of data catalog, we no longer have a way to get a list of slugs for all charts. This was used in `charts.list_charts()` function in data catalog.
I don't know how often was this function used. If we want to keep it, we'd have to add an endpoint that would return all charts slugs or call public Datasette.
>  :bug: Deprecate charts.list_charts

- etl/steps/data/garden/energy_institute/2024-06-20/statistical_review_of_world_energy.py
We found inconsistencies in wind consumption for Saudi Arabia in the latest release of the Statistical Review. For that reason, data for 2022 and 2023 was removed. However, other indicators (not affected by this issue) could still be safely used. I have brought back that data, and kept only wind consumption as missing.
> 📊 energy: Fix missing energy data for Saudi Arabia

- etl/steps/data/garden/energy_institute/2024-06-20/statistical_review_of_world_energy.py
- etl/steps/data/garden/irena/2023-12-12/renewable_electricity_capacity.py
IRENA's wind capacity for Saudi Arabia has changed for 2022 from 3MW to 403MW. Until we update this data, the given capacity is physically incompatible with the latest Statistical Review's value of wind generation. So, for now, I'll simply remove the 2022 value of capacity (which was an estimate by IRENA).
> Fix inconsistencies in Saudi Arabia's wind generation and capacity

- apps/wizard/app_pages/chart_diff/chart_diff_show.py
- apps/wizard/app_pages/expert/prompts.py
- Update datasette links. Fixes https://github.com/owid/etl/issues/3316
- Adds back the chart-type labels. Fixes https://github.com/owid/etl/issues/3127
> ✨ wizard: expert

- snapshots/who/2022-09-30/ghe.py
- snapshots/who/2024-07-30/ghe.py
- snapshots/who/latest/fluid.csv.dvc
- snapshots/who/latest/flunet.csv.dvc
- snapshots/who/latest/monkeypox.csv.dvc
WHO changed their API endpoint from https://frontdoor-l4uikgap6gz3m.azurefd.net to https://xmart-api-public.who.int. Update all snapshots that use it.
>  :honeybee: Update WHO API endpoint

- apps/wizard/app_pages/chart_diff/chart_diff.py
Charts were mistakingly using the previous WDI version instead of the 2024 update. Here I am just migrating the indicators.
> :bug: correct charts in old WDI

- apps/wizard/app_pages/indicator_upgrade/app.py
- apps/wizard/app_pages/indicator_upgrade/dataset_selection.py
- apps/wizard/app_pages/indicator_upgrade/utils.py
- etl/db.py
Pablo Arriagada reported that he could not view archived datasets in Indicator Upgrader (as part of his work in https://github.com/owid/etl/pull/3343).
To overcome this, he unarchived a dataset.
This PR solves this by allowing the user to show archived datasets if they click the 'show all datasets' option.
> ✨ wizard: option to show archived datasets

- etl/steps/data/grapher/worldbank_wdi/2024-05-20/wdi.meta.yml
Adding full data page metadata for the modeled estimates version of this indicator. We currently display the survey estimates version, but I think the modeled estimates version has been adjusted for sampling error and has greater data completeness. Additionally, values that cross-over between survey estimates and modeled estimates are very similar.
> ✨  Add data page for stunting (modeled estimates) 

- etl/steps/data/garden/oecd/2024-08-21/official_development_assistance.py
Discussed here: https://github.com/owid/owid-issues/issues/1620#issuecomment-2394180654
> :sparkles: Add Foreign aid as share of GNI

- etl/grapher_io.py
- etl/version_tracker.py
Some archived grapher datasets were missing in `VersionTracker.steps_df`. The reason was that, when extracting the relevant info from the database, steps were assign either `data://` or `data-private://` prefixes based on `isPrivate`. But there were grapher datasets that were manually archived (by setting `isArchived` and `isPrivate` to 1) which came from non-private ETL steps.
This PR fixes the issue, and those archived grapher datasets now appear in `steps_df`.
> Fix missing archived grapher datasets in version tracker

- etl/grapher_io.py
Cache indicator data from S3 to disk along with its ETag. When fetching it again, first compare its checksum to the cached version, and if they match, load it from disk instead. This should improve data loading speed in Anomalist.
>  :hammer: Cache indicator data from S3

- apps/anomalist/cli.py
- etl/grapher_io.py
Let anomalist CLI ingest dataset ids, variable ids, and a mapping.
> 🎉 anomalist: Improve anomalist CLI

- apps/anomalist/anomalist_api.py
- apps/anomalist/cli.py
- apps/anomalist/detectors.py
- apps/wizard/app_pages/anomalist/app.py
- etl/grapher_model.py
Various improvements on anomalist backend.
> 🎉 anomalist: Improve Anomalist backend

- apps/anomalist/cli.py
- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/app_pages/anomalist/utils.py
- apps/wizard/utils/chart_config.py
- apps/wizard/utils/components.py
- etl/grapher_model.py
- Better organization of streamlit app code.
- Add entity selector in each anomaly box
- Enable 're-estimate anomalies' buttons
- Cosmetic improvements to streamlit custom components.
- Decouple custom grapher chart component from grapher chart config generation.
- Add support for upgrade-anomalies in charts.
- Missing point anomalies.
- Fix minor bugs.
> ✨ wizard: improve app flow

- apps/anomalist/anomalist_api.py
Anomalist was failing when executed for multiple datasets (because variable ids from one dataset were not found in the data of another dataset).
> 🐛 anomalist: Fix unknown variable ids

- apps/anomalist/anomalist_api.py
- apps/anomalist/detectors.py
- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/app_pages/anomalist/utils.py
- etl/grapher_model.py
- Add `dfReduced`: This avoids loading `dfScore` in memory, and instead `dfReduced`, which is significantly lighter.
- Abstract logic to generate a single dataframe into one function.
- Support Gaussian Processes
> ✨ anomalist: GP support, refactor functions, add dfReduced

- apps/anomalist/anomalist_api.py
- apps/anomalist/detectors.py
- apps/anomalist/gp_detector.py
- Stop detecting anomalies after `max_time` in GP. They are processed in random order, but with probability proportional to country population (entities without population are given mean probability). It's **not being used yet**, but will be useful when we start detecting anomalies in production
- Add `n_jobs` for multiprocessing. This works poorly on my shitty laptop, but might provide speed up on our beefy server
- Return long format from GP detector and handle it in anomalist_api
>  :sparkles: Add max_time and n_jobs to GP

- apps/anomalist/anomalist_api.py
- apps/anomalist/detectors.py
- apps/anomalist/gp_detector.py
- apps/wizard/app_pages/anomalist/app.py
- etl/grapher_model.py
- Normalize gp_outlier to (0, 1)
- Let detectors own anomaly text instead of having it in the app
- Fix a couple of bugs I found during testing
>  :bug: Fix anomalist bugs

- apps/anomalist/anomalist_api.py
- apps/anomalist/gp_detector.py
* Stop storing `dfScore`, since the load of anomalies from DB takes much longer than when only storing `dfReduced`, and we are currently not using `dfScore` anywhere.
* GP detector was searching for anomalies in all indicators in the incoming `df`. However, by construction, `df` includes data for both new and old indicators (and detecting anomalies in the old indicators is unnecessary). This was causing anomalist to raise an error. Now the detection takes half of the time for datasets for which there is an old version.
> 🐛 anomalist: Fix bug with unknown indicators and long loading time

- apps/anomalist/anomalist_api.py
- apps/owidbot/cli.py
- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/app_pages/anomalist/utils.py
- apps/wizard/utils/__init__.py
- apps/wizard/utils/db.py
- etl/grapher_model.py
- Persist selected datasets and filter values in the URL
- Display anomalies from DB at startup (don't wait for a click on "Detect anomalies")
- A couple of small performance optimizations
> :sparkles: Persist filter values in the URL for Anomalist

- apps/chart_sync/admin_api.py
- apps/chart_sync/cli.py
- apps/owidbot/chart_diff.py
- apps/wizard/app_pages/chart_diff/app.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
- apps/wizard/app_pages/chart_diff/chart_diff_show.py
Add field `error` to `ChartDiff` object. It's used for errors that cannot be automatically fixed. We just had a case when someone replaced a chart by a different one in production (with different chart id) and kept the same slug. chart-sync tried to create a new chart, but Admin API rejected it because the slug was already taken.
This PRs shows error in chart-sync UI and in owidbot summary if chart-sync would create a new chart, but the slug is already taken.
Other changes:
- Show error messages from AdminAPI
- Enable bugsnag for chart-sync
- Skip charts that were already synced
This is how it looks
>  :sparkles: Add errors to chart-sync

- apps/anomalist/cli.py
- apps/anomalist/gp_detector.py
- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/app_pages/anomalist/utils.py
- docs/guides/sharing-external.md
- pyproject.toml
- uv.lock
- Convert z-score to p-value adjusted for multiple hypothesis testing instead of ad-hoc `min(z, 3) / 3`
- This significantly lowers GP scores
- Whether to adjust p-value is a question... time series with a lot of points (e.g. cherry blossom) give more reasonable scores, but it could be too low overall
- Prettify table with scores and add columns for all anomalies
> :sparkles: Prettify Anomalist scores table

- apps/chart_sync/admin_api.py
- apps/chart_sync/cli.py
- apps/owidbot/chart_diff.py
- apps/wizard/app_pages/chart_diff/app.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
- apps/wizard/app_pages/chart_diff/conflict_resolver.py
- apps/wizard/app_pages/indicator_upgrade/charts_update.py
- etl/helpers.py
- etl/steps/data/garden/biodiversity/2024-01-25/cherry_blossom.meta.yml
- etl/steps/data/garden/climate/latest/weekly_wildfires.meta.yml
- etl/steps/data/garden/climate/latest/weekly_wildfires.py
- etl/steps/data/grapher/climate/2023-12-20/surface_temperature_annual_average.meta.yml
- etl/steps/data/grapher/climate/2023-12-20/surface_temperature_annual_average.py
- etl/steps/data/grapher/climate/latest/wildfires_by_week_average.meta.yml
- etl/steps/data/grapher/climate/latest/wildfires_by_week_average.py
- lib/datautils/pyproject.toml
Goes together with https://github.com/owid/owid-grapher/pull/4083 that automatically logs Tailscale users to Admin. This means that going to http://staging-site-feature won't ask you to login as `admin` user and won't show an annoying popup about compromised password.
On ETL side, charts are created by logged user instead of ETL and synced correctly to production by chart-diff.
Datasets will still be created by ETL user, because they're created in production and there's no easy way how to know who created it. That is, unless we add `owner` to dataset metadata and start using it.
>  :sparkles: Use real users on staging servers

- apps/owidbot/cli.py
- docs/api/index.md
- docs/ignore/generate_dynamic_docs.py
This PR adds a first stab at describing how our new chart data api works. Feedback is welcome!
> 📜 add chart api documentation

- apps/owidbot/cli.py
- etl/harmonize.py
- tests/apps/wizard/app_pages/test_apps.py
Implements https://github.com/owid/etl/issues/3457
Add `exclude` option to harmonizer CLI and create an `*.excluded_countries.json` file at the end.
>  :sparkles: Add excluding countries to harmonizer

- apps/anomalist/cli.py
- etl/grapher_import.py
- etl/grapher_model.py
Implements https://github.com/owid/etl/issues/3423
Add columns `datasets.catalogPath` and `datasets.tables` and populate them when upserting datasets to MySQL. Only `catalogPath` is backfilled, `tables` are left as null (will be populated at next ETL_EPOCH increment).
>  :sparkles: Add catalogPath column to datasets table

- etl/harmonize.py
Implement suggestion from [this issue](https://github.com/owid/etl/issues/3457#issuecomment-2454993299) by @spoonerf 
> I think the ideal situation would be that it always asks about Asia, Europe, North America, South America and Oceania and that these are not automatically mapped. However, if this is tricky, I'd say it's a pretty minor pain point, so maybe not worth spending too much time on.
The Harmonizer CLI now consistently makes OWID continents ambiguous. It's best used in combination with `--institution WB` to prioritize `Asia (WB)` as the first choice.
@lucasrodes are you ok with this change as a harmonizer's father?
>  :sparkles: Make OWID continents ambiguous in harmonizer

- etl/steps/data/garden/un/2024-04-09/undp_hdr.meta.yml
- etl/steps/data/garden/un/2024-04-09/undp_hdr.py
@antea04 Just realized that https://github.com/owid/etl/pull/3425 aggregated all the indicators, regardless of rel_cols. I have fixed that. Take a look to see this is still what you were looking for.
> :bug: un: aggregate only columns I need in HDR dataset

- docs/architecture/workflow/index.md
- etl/explorer.py
- etl/files.py
Enable editing of explorers on staging servers.
- New staging servers create a branch in `owid-content`
- Explorer steps in ETL commits to that branch on the staging server (previously all changes were uncommitted) (e.g. `etlr explorers/minerals --export`)
- Editing Explorer TSV from Admin commits to the branch
- Merging the branch pushes the branch to `owid-content` repo. It doesn't automatically merge it with master, but one can create a PR from it and merge manually
>  :honeybee: engineering: enable explorers on staging servers

- apps/wizard/app_pages/indicator_upgrade/charts_update.py
- apps/wizard/utils/cached.py
- etl/grapher_model.py
When the indicator upgrader updates charts, the edits appear to be made by the last person who manually edited the chart, not by the person who ran the upgrade. This can cause confusion, especially when Slack notifications show updates attributed to users who haven’t interacted with the chart.
This PR addresses the issue by assigning updates to the user who runs the indicator upgrader. However, a drawback is that bulk upgrades (e.g., population or WDI) will be attributed to a single user, even if they are unrelated to the charts.
---
- Added a function to detect the user and their `id` in Streamlit.
- Updated the indicator upgrader to use the detected user when making chart updates (instead of attributing them to the last editor).
>  :hammer: indicator upgrader: use real users

- dag/archive/fasttrack.yml
- dag/archive/main.yml
- dag/archive/war.yml
- dag/fasttrack.yml
- dag/main.yml
- dag/war.yml
ref: https://github.com/owid/owid-issues/issues/1740
Archive datasets no longer in use:
- `fasttrack/2023-06-19/world_population_comparison`
- `countries/2023-10-01/gleditsch`
- `fasttrack/latest/democracy_lexical_index`
> 🔨 archive datasets (lucas)

- apps/utils/scan_chart_diff.py
- apps/wizard/utils/__init__.py
I encountered a nasty bug causing `owidbot` to post "No charts for review," even when there were actual charts for review. The issue was that `scan-chart-diff` iterates over all staging servers, but `get_staging_creation_time` was using a cached value from the key `staging_creation_time`. This resulted in `staging_creation_time` being fetched for only the first staging server and reused for the others.
This PR resolves the issue by clearing the cache with `st.session_state.clear()` before processing each staging server and by using a unique key for caching `staging_creation_time` based on the engine in use.
>  :bug: Fix caching of staging creation time

- etl/harmonize.py
Fixes https://github.com/owid/etl/issues/3559
I encountered the same issue and patched it quickly, I haven't looked thoroughly into it, but it worked for my case.
> 🐛 harmonize: Fix harmonize ipython when used on already harmonized datasets

- apps/wizard/etl_steps/cookiecutter/grapher/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
Setting ds_garden.read(reset_index = False) as default.
Maybe I misunderstand, but I find that the grapher step fails unless I set an index in the grapher step. 
I _think_ it makes sense not to reset the index when reading in the table, but I'm sure I'm missing something!
> 🐝  Update {{cookiecutter.short_name}}.py

- etl/steps/data/garden/homicide/2024-10-30/unodc.meta.yml
Hey @lucasrodes,
This is very much not urgent. I'm trying to figure out why I'm getting missing spaces after the {definitions.metric} field in the titles of [this dataset](http://staging-site-jinja-unodc/admin/datasets/6788).
I think it's a Jinja issue, I saw you made [these recent changes to Jinja formatting](https://github.com/owid/etl/commit/9e4a2a6ba28c0ac369dc1c37f08fb5372f093b0a), I think to solve a similar issue? 
Any idea what could be going on in this dataset? I tried to copy what you did but the space is still missing.
> 🐝 metadata: Improve UNODC metadata and fix issue with missing spaces in Jinja

- dag/main.yml
- etl/steps/data/garden/homicide/2024-10-30/unodc.meta.yml
- etl/steps/data/garden/homicide/2024-10-30/unodc.py
Currently UNODC provides data for England, Wales, Scotland and N.Ireland separately. In this PR I combined them for the count variables and calculate the rates using the UK population from UN WPP for the rate variables.
> 📊  homicides: adding uk data to UNODC dataset

- apps/wizard/app_pages/anomalist/app.py
Based on https://github.com/owid/etl/issues/3436#issuecomment-2489144642
Adding features to Anomalist:
- Export list of anomalies as a list.
- Enable faceting option in charts. This is useful for comparing indicators when multiple entities are shown.
/schedule
> ✨ wizard: anomalist

- etl/steps/data/garden/war/2024-11-22/ucdp_preview.py
Assign conflict type of conflicts in 2024 based on the latest available categorization. This is the case when the conflict was going on in the year before CED data (i.e. before 2024).
/schedule
> 📊 war: ucdp check on type=unknown

- apps/wizard/etl_steps/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.py
- apps/wizard/etl_steps/snapshot.py
- etl/scripts/archive/run_all_snapshots/run_all_snapshots.py
When creating default Snapshot steps with manual imports, we add the argument `path_to_file` to ingest local files.
```py
@click.option("--path-to-file", prompt=True, type=str, help="Path to local data file.")
def main(upload: bool, path_to_file: str) -> None:
...
```
This is needed, and we should continue with this default. However, we could have an alternative and shorter argument name, e.g. `-f`, e.g.
```py
@click.option("--path-to-file",  "-f", prompt=True, type=str, help="Path to local data file.")
def main(upload: bool, path_to_file: str) -> None:
...
```
> ✨ shorter version for path-to-file in snapshot

- etl/steps/data/garden/hmd/2024-11-19/hfd.meta.yml
Minor edit to metadata titles.
- There was an error in `Cohort parity progression ratios` indicators. Instead of `n to n+1 birth` it should be `n-1 to n birth`.
- Instead of using `5p` in titles, let's use `≥5`.
> 📊 hfd: fix indicator title

- apps/wizard/app_pages/map_brackets.py
- apps/wizard/utils/chart_config.py
- apps/wizard/utils/components.py
- etl/config.py
- etl/grapher_model.py
- etl/helpers.py
- etl/indicator_upgrade/schema.py
- etl/steps/data/garden/animal_welfare/2023-09-05/bullfighting_laws.meta.yml
- etl/steps/data/garden/animal_welfare/2024-06-04/bullfighting_laws.meta.yml
- etl/steps/data/garden/harvard/2023-09-18/colonial_dates_dataset.meta.yml
- etl/steps/data/garden/wb/2024-01-17/world_bank_pip.meta.yml
- etl/steps/data/garden/wb/2024-03-27/world_bank_pip.meta.yml
- etl/steps/data/garden/wb/2024-10-07/world_bank_pip.meta.yml
- etl/steps/data/grapher/wb/2022-10-03/extreme_poverty_by_region.meta.yml
- etl/steps/export/explorers/covid/latest/covid.config.yml
- etl/steps/export/explorers/minerals/latest/minerals_supply_and_demand_prospects.py
- etl/steps/export/multidim/covid/latest/covid.cases_tests.yml
- etl/steps/export/multidim/covid/latest/covid.covax.yml
- etl/steps/export/multidim/covid/latest/covid.vax_breakdowns.yml
- etl/steps/export/multidim/energy/latest/energy.yml
- schemas/dataset-schema.json
- schemas/multidim-schema.json
Sibling PR to https://github.com/owid/owid-grapher/pull/4159 that makes changes to the database and chart config schema.
Changes include:
- Added derived column `chart_configs.chartType`
- For chart configs:
- Removed field `type` that is replaced by `chartTypes`
- `type` used to refer to a single chart type, like `"LineChart"`
- `chartTypes` refers to a list of chart types, like `["LineChart", "SlopeChart"]`
- For now, the only valid chart type combination is `["LineChart", "SlopeChart"]`. We might add support for more chart type combinations in the future, but that will be a slow process. A lot of words to say: It is usually safe to assume the first element in `chartTypes` is the "type" of the chart
- Removed field `hasChartTab`. If you want to know whether a Grapher has a chart tab, …
> 🔨 update grapher schema to latest version

- apps/wizard/app_pages/chart_animation.py
- docs/guides/upgrade-python-version.md
- mkdocs.yml
Builds on https://github.com/owid/etl/pull/3627/files
- Add square format support.
- Change use of `st.container` to `st.expander`. This way the user can collapse these.
- Improve presentation of output settings:
- Add help message to most widgets.
- Add dedicated section for "frame settings"
- Change duration of last frame to be in `ms` (instead of number of frames)
- Change "Remove duplicate frames" to "Allow duplicate frames". By default this is not checked.
- Change label "Year range open" to "Show only current year". I found the previous label a bit confusing.
- Other changes to improve script readability
> ✨ chart animation: add square-format support

- etl/steps/data/garden/covid/latest/vaccinations_us.meta.yml
- etl/steps/data/grapher/covid/latest/vaccinations_us.py
Remove `zeroDay` from the data, there is no need.
In this particular case, for VAX in the US, there was actually a typo in the `zeroDay`, which lead to wrong time-axis (see [chart](https://ourworldindata.org/grapher/us-total-covid-19-vaccine-doses-administered))!
> 🐛 covid: vax data

- apps/cli/__init__.py
- apps/pr/categories.py
- apps/pr/cli.py
- apps/step_update/cli.py
- apps/utils/draft_pull_request.py
- docs/guides/data-work/add-data.md
- docs/guides/data-work/update-data.md
- pyproject.toml
In the past, the only field that was mandatory when calling the `etl pr` command was the name of the branch. The name of the branch is not that important, given that it will not live for long. Instead, what we should be forcing users to care about is the PR title and category, which should help us organize PRs better.
From now on, the title and category are mandatory, but if the user doesn't type them in, the command will prompt them with available options.
- The temporary branch's name is auto-generated to ensure no collisions. Its structure is `{username}-{category}-{summary_of_the_title}-{hash}. E.g., `lucasrodes-data-ucdp-update-sdf09`. While long, this is still readable and doesn't force users to type in a name for a branch that will not long live. Optionally, the user can still use …
> 📊 improve etl pr command

- etl/steps/data/garden/ophi/2024-10-28/multidimensional_poverty_index.meta.yml
Following https://github.com/owid/owid-issues/issues/1707#issuecomment-2500742377
> :lipstick: Add dynamic links in MPI data pages

- etl/steps/data/garden/who/2024-07-30/ghe.meta.yml
There were missing spaces in many of the variable titles and description_shorts, this fixes that. 
I'm a bit worried that changing the titles is going to dissociate the indicators from their charts, but it looks like it will be okay on staging, do you think it will be okay? 
/schedule 2024-11-28T20:00:00.000Z
> 🐝 ghe: getting spaces in jinja

- apps/owidbot/cli.py
- apps/owidbot/github_utils.py
- etl/steps/export/github/co2_data/latest/owid_co2.py
Implements https://github.com/owid/etl/issues/3584
- Running `etlr github/co2_data --export` creates a branch with the same name as working ETL branch and commits updated files there.
- If the branch exists, push a new commit. (@pabloarosado's suggestion was to fail, but I think it's pretty safe to add a commit given that we don't overwrite existing ones and we create a PR at the end)
- Prefer `GITHUB_TOKEN` over `OWIDBOT_ACCESS_TOKEN` (in the future, we should clean it up and use only a single env)
- Show a link to create a PR from our branch
>  :sparkles: Automatically create a branch if it does not exist

- snapshots/covid/latest/cases_deaths.csv.dvc
- snapshots/covid/latest/cases_deaths.py
Link https://covid19.who.int/WHO-COVID-19-global-data.csv for updating COVID cases & deaths stopped working. It redirects to a dashboard now.
**Solution**
WHO has changed the file links.
So far we had been using their file with weekly reports. Now, they started occasionally reporting daily values in a new file. I've switched to this file.
/schedule
> 🐛 covid cases and deaths

- etl/steps/data/garden/antibiotics/2024-11-12/antimicrobial_usage.meta.yml
- etl/steps/data/garden/antibiotics/2024-11-12/antimicrobial_usage.py
- etl/steps/data/grapher/antibiotics/2024-11-12/antimicrobial_usage.py
Having some issues nicely formatting the `description_processing` any ideas of how to improve it would be v welcome!
> 📊  antibiotics: adding aggregated antimicrobial use data by class

- apps/pr/cli.py
- apps/wizard/app_pages/anomalist/app.py
- Minor tweak to `etl pr` to avoid some redundancy in branch names
- Remove buttons from chart iframe that are not used in the context of indicators (e.g. 'share', 'explore more data')
> ✨ etl pr, anomalist

- docs/architecture/metadata/structuring-yaml.md
- etl/grapher_helpers.py
- etl/steps/data/garden/covid/latest/sequence.meta.yml
- etl/steps/data/garden/covid/latest/yougov.meta.yml
A couple of improvements to alleviate some pain from https://github.com/owid/etl/issues/3654.
- Added instructions how to preview metadata with dimensions in a notebook to avoid long build-wait-check cycles
- Strip whitespaces from Jinja blocks
- Improve ETL docs
Note that this is still not perfect and doesn't solve `\n.` problem from the issue (we still need to use `<%- elif` to get rid of it). Ideally, we should never have to use `-` and have the Jinja templates as intuitive as possible. To do this properly, we should:
1. Replace `dynamic-yaml` by something simpler and unify saving & loading of metadata files (while keeping it **fast**, there were tons of performance optimizations)
2. Move `jinja` functionality to `owid-catalog` and add method …
> :sparkles: Jinja whitespaces and newlines

- etl/steps/data/garden/hmd/2024-12-01/hmd.meta.yml
- etl/steps/data/garden/hmd/2024-12-01/hmd.py
- etl/steps/data/garden/hmd/2024-12-03/hmd_country.py
- etl/steps/data/grapher/hmd/2024-12-01/hmd.py
The birth rate in HMD was miss-calculated, leading to an underestimate of 3x.
> 🐛 birth rate in HMD

- etl/steps/data/garden/hmd/2024-12-03/hmd_country.meta.yml
- etl/steps/data/garden/hmd/2024-12-03/hmd_country.py
- Improve metadata: names, descriptions.
- Add values for -9 months. Trying to estimate months of conception that lead to peak birth rate in a given year.
- Fixed `merge` operation that was leading to data loss (due to using INNER join)
- minor code readability improvements
/schedule
> ✨ birth rate monthly improvements

- apps/wizard/app_pages/chart_diff/chart_diff.py
- apps/wizard/utils/io.py
- Fixed a bug that displayed `Config change` for unrelated charts.
- Filtered data and metadata changes by checking which files were modified on the staging server.
I intended to use the function `get_datasets_from_version_tracker`, but calling `vt.steps_df` was too slow. Instead, I added a new function, `get_all_changed_catalog_paths`, which identifies the paths of changed steps along with their downstream dependencies. Let me know if a faster function for this purpose already exists.
Parsing catalog paths over and over again with `.split("/")` is tedious and prone to errors. I wanted to create a special object `StepPath` in this PR https://github.com/owid/etl/pull/3165, but wasn't fully satisfied with it and didn't end up merging. It'd be nice to refactor it all at one point.
> ✨ Better filtering of data & metadata in chart-diff

- etl/steps/data/garden/wb/2024-12-03/poverty_projections.meta.yml
- etl/steps/data/garden/wb/2024-12-03/poverty_projections.py
- snapshots/wb/2024-12-03/reproducibility_package_poverty_prosperity_planet.zip.dvc
Add a series with the historical + current forecast + historical growth data for extreme poverty.
Main issue https://github.com/owid/owid-issues/issues/1705
> 📊 wb: add series connecting estimates and projections of poverty from World Bank

- etl/grapher_import.py
There's an error that [sometimes comes up](https://owid.slack.com/archives/C46U9LXRR/p1733928261018389) on staging servers
```
ValueError: Variables used in charts will not be deleted automatically:
```
This issue occurs when someone renames the short names of indicators and updates some charts in production. If you then merge the master branch to the staging server, which is still using old charts from the time it was created, you'll encounter this error.
This PR adds a check that converts the error into a warning if the changes on the staging server are unrelated to the charts. The error disappears in production after the merge.
> 🐛 Raise warning on staging server when we cannot delete variables used in charts

- apps/wizard/app_pages/harmonizer/app.py
A bug was introduced into Harmonizer (likely in https://github.com/owid/etl/pull/3718)
/schedule
> 🐛 harmonizer import

- etl/config.py
Fix for https://github.com/owid/owid-grapher/issues/4308
Truncate branch names after 28 characters instead of 50. (Existing branches over 28 characters are excluded)
> ✨ Limit container names to 28 characters

- etl/steps/data/garden/un/2024-07-12/un_wpp.meta.yml
WPP metadata presented several unexpected white spaces. This PR solves this and ensures there is consistency across metadata fields `title` and `description_short` for WPP dataset.
> 💄 edit metadata fields in hfd

- apps/wizard/utils/__init__.py
Error introduced in #3726 where `clean_dict_empty` was not returning a value when input type was not list or dictionary.
/schedule
> 🐛 clean dictionary function

- etl/steps/data/meadow/neglected_tropical_diseases/2024-05-02/soil_transmitted_helminthiases.py
- lib/catalog/owid/catalog/tables.py
Underscore keys in `tb.format(keys)` function to fix ETL.
> 🐛 Underscore keys in tb.format

- dag/climate.yml
- etl/steps/data/meadow/climate/2023-12-20/surface_temperature.py
- pyproject.toml
- snapshots/climate/2024-12-05/surface_temperature.py
- snapshots/climate/2024-12-05/surface_temperature.zip.dvc
- uv.lock
hi @Marigold - looks like they've started to only update the data in the grib format so I am making some changes to read the data in the new format - I know there were issues with this code in the past so thought it'd be good if you reviewed this!
> 📊 climate: era5 surface temperature data December 2024

- apps/wizard/app_pages/similar_charts/app.py
- apps/wizard/app_pages/similar_charts/data.py
- apps/wizard/app_pages/similar_charts/scoring.py
- apps/wizard/config/config.yml
A Streamlit prototype for finding similar charts to the selected one. Initially, it was searching for similar charts based solely on the semantic similarity of chart titles and subtitles, but later, many more "features" were added and combined into a similarity score. It was created to provide an intuition for how well automatic chart recommendations could work. However, the selection will likely evolve into a semi-automatic process (this app could then be leveraged for labeling).
It's not yet clear what "similar chart" means. Should we show very similar charts ("narrow"), a "wide" selection, or charts that are not so similar but perhaps more interesting?
Similarity is calculated as a weighted average of the following sub-scores (all between 0 and 1):
- **title**: semantic similarity of …
> 🎉 Similar charts

- apps/chart_animation/cli.py
- apps/wizard/app_pages/chart_animation.py
- apps/wizard/config/config.yml
- apps/wizard/utils/components.py
In streamlit, there is the [st.query_params](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.query_params) function, which allows you to query the app via the URL.
This can be useful to link users to specific app views from external apps (e.g. the admin).
App candidates where querying makes sense:
- Can link it from chart edit page
- Can use it for the _housekeeper_
> ✨ add URL-query support in some wizard apps

- dag/environment.yml
- etl/command.py
- etl/data_helpers/geo.py
- etl/steps/data/garden/demography/2023-03-31/population/__init__.py
- etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.py
- etl/steps/data/garden/owid/latest/key_indicators/utils.py
- etl/steps/data/garden/state_capacity/2023-10-19/state_capacity_dataset.py
- etl/steps/data/garden/un/2023-08-02/comtrade_pandemics.py
- etl/steps/data/garden/unep/2023-03-17/consumption_controlled_substances.py
- tests/data_helpers/test_geo.py
We've recently deprecated `key_indicators` dataset, but the function `_load_population` was still using them. I removed it and updated `geo.*` functions accordingly. (Some steps were breaking our nightly build)
> 🐛 Cleanup _load_population

- dag/archive/health.yml
renamed a step in previous PR and did not use new name in the (archive) dag:
`data://garden/who/2023-06-29/guinea_worm -> data://garden/who/2023-06-29/guinea_worm_certification`
> :bug: step named wrongly in archive dag

- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/app_pages/similar_charts/app.py
- apps/wizard/utils/components.py
- tests/apps/wizard/utils/test_components.py
`url_persist` is great, but it was completely unreadable (even after modifications by Lucas). This refactors the whole thing to make it more understandable and adds some unit tests.
> 🔨 Refactor url_persist

- etl/snapshot.py
Reading multiple files from an archive is currently quite inefficient since we are unarchiving the file several times.
Instead, with this PR, we can now unarchive the main file just once:
```python
snap = Snapshot(...)
with snap.open_archive():
table1 = snap.read_from_archive("filename1.csv")
table2 = snap.read_from_archive("filename2.csv")
```
/schedule
> ✨ read multiple files from archive efficiently

- apps/chart_sync/admin_api.py
- apps/wizard/app_pages/indicator_upgrade/charts_update.py
- apps/wizard/utils/cached.py
- etl/config.py
- etl/grapher/model.py
There was a bug when working with indicator upgrader locally that used Admin grapher user id instead of the one defined in `.env`. This was caused by overwriting `GRAPHER_USER_ID` when working on a staging server. This PR adds new variable `ENV_GRAPHER_USER_ID` that doesn't get overwritten.
In addition to that, it slightly refactors function for getting grapher user id from Tailscale IP.
> 🐛 Use correct GRAPHER_USER_ID from env when working locally

- api/README.md
- api/main.py
- apps/backport/backport.py
- apps/backport/datasync/datasync.py
- apps/backport/migrate/migrate.py
- apps/chart_sync/cli.py
- apps/utils/scan_chart_diff.py
- apps/wizard/app.py
- apps/wizard/app_pages/fasttrack/app.py
- apps/wizard/utils/__init__.py
- etl/command.py
- etl/config.py
- etl/prune.py
- etl/publish.py
- etl/reindex.py
- pyproject.toml
- uv.lock
Implements https://github.com/owid/etl/issues/3881
- Switch from Bugsnag to Sentry
- Fix function `enable_sentry_for_streamlit` that's forwarding exceptions from streamlit to Sentry
- Run `enable_sentry_for_streamlit` when importing `apps.wizard.utils` to enable it for all our apps (running it in utils module looks fishy, but I couldn't find a better way. It doesn't work when run from `apps/wizard/app.py`)
> ✨ Switch from bugsnag to sentry

- apps/wizard/app_pages/chart_diff/app.py
- apps/wizard/app_pages/chart_diff/utils.py
- etl/grapher/model.py
- Add filtering by used indicator to chart-diff
- Fix `Variable.from_id` when `columns` are used (previously it returned only the first number in a row, now it returns Row object that is not `Variable`, but `Row` object that has the same fields)
> ✨ Add indicator filter to chart-diff

- etl/grapher/model.py
Fixes https://github.com/owid/etl/issues/3902
It removes hacky logic when upserting variables. Now it uses only `catalogPath` which should simplify things and prevent bugs like [this](https://github.com/owid/etl/issues/3902).
> 🐛 Fix inconsistency between MySQL and JSONs in R2

- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.meta.override.yml
- etl/steps/data/grapher/worldbank_wdi/2025-01-24/wdi.meta.yml
- snapshots/worldbank_wdi/2025-01-24/wdi.zip.dvc
Fixes https://github.com/owid/etl/issues/3609
- DRY origins in WDI and use only the one from snapshot
- Remove "attribution" from origin so that charts don't show "Multiple sources compiled by World Bank" and instead show real source from WB metadata
- Raw names from WB and shortened "name" we use in origins are stored in [wdi.sources.json](https://github.com/owid/etl/blob/master/etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.sources.json)
Check out some charts with changed metadata from [chart-diff](http://staging-site-wdi-fix-origins/etl/wizard/chart-diff?show_all=). `Data source:` in the footer should be more meaningful.
> 📊 WDI - use origins from WB metadata instead of 'Multiple sources compiled by WB'

- etl/steps/data/garden/ggdc/2024-04-26/maddison_project_database.meta.yml
- etl/steps/data/garden/growth/2024-05-16/gdp_historical.meta.yml
- etl/steps/data/garden/un/2024-04-09/undp_hdr.meta.yml
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.meta.override.yml
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.meta.yml
- etl/steps/data/grapher/ggdc/2022-11-28/penn_world_table.meta.yml
There are no changes in code, just in metadata.
Issue https://github.com/owid/owid-issues/issues/1836
> ✨ Improve metadata in GDP data pages

- etl/steps/data/garden/who/2024-01-03/gho.countries.json
- etl/steps/data/garden/who/2024-01-03/gho.excluded_countries.json
- etl/steps/data/garden/who/2024-01-03/gho.py
Some odd-looking entities were still being included in the data, so just removing those. 
We also had cases where regions from five different sources were being used, so now we just take the top two of ["World Bank", "WHO", "UNICEF", "UN", "UN SDG"], if there are more than two sources of regions being provided for a particular indicator.
> 🐛 fix entities in GHO

- dag/health.yml
- etl/command.py
Let the `--export` flag execute the corresponding `grapher://grapher` steps to all `data://grapher` dependencies. This allow us to remove `grapher://grapher` dependencies, and instead have the corresponding `data://grapher` ones.
NOTE: I'm not totally sure if this will work with mdims that depend on private steps (like `export://multidim/health/latest/causes_of_death`). For now, I omitted it from the dag.
> 🎉 Let export steps execute implicit grapher://grapher steps

- snapshots/covid/latest/cases_deaths.csv.dvc
> 🐛 fix covid mdim pipeline

- dag/health.yml
- etl/helpers.py
- etl/multidim.py
- etl/steps/export/multidim/health/latest/causes_of_death.py
- etl/steps/export/multidim/health/latest/causes_of_death.yml
- Remove `expand_views_with_access_db` function, move the grouping of indicators into lists to `group_views`
- Fix some type issues with DAG
- Enable mdim for causes of death again
Here's the [mdim page](http://staging-site-mdim-causes-of-deaths/admin/grapher/mdd-causes-of-death?cause=All+causes&age=All+ages&metric=Number) on a staging server.
> 🔨 Refactor causes of death mdim and remove expand_views_with_access_db

- etl/steps/data/garden/un/2024-09-11/igme.py
- etl/steps/data/garden/un/2024-09-16/long_run_child_mortality.py
Fix for [this issue](https://owid.slack.com/archives/C03NV9Z3YSV/p1738774206362549), where regional aggregates for child mortality rates fluctuate strongly. This is caused by new countries being added to regional aggregates over time, influencing the overall rate.
I have now changed the regional aggregates to only be calculated if data was available for >80% of the population. This smoothes out the lines and removes most data before ca 1965 (different for different regions).
There are two charts I had issues with:
- [Life satisfaction vs. child mortality](http://staging-site-bug-child-mortality-anomalie/admin/charts/250/edit) - For some reason the Cantril ladder score does not pull the latest year into the scatter plot (it is stuck on 2015). I assume it has something to do with [this …
> 🐛 child mortality anomalies

- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/utils.py
Inspired by [this comment](https://owid.slack.com/archives/C3RAU3BJ9/p1739981330767749?thread_ts=1739975692.480529&cid=C3RAU3BJ9), I thought it would be useful to have a `.to_excel()` method on our `Table` that by default exports a table with a "data" and a "metadata" sheet.
The metadata sheet contains for now very limited info (colum name, title, short description, and producers with urls). I haven't put much thought on what exactly this metadata should look like, but I suppose there's no harm in adding it as-is for now, and we can improve it in the future (unless `.to_excel()` is being used elsewhere).
> 🎉 catalog: Create tables method to export excel with metadata

- apps/housekeeper/charts.py
- apps/housekeeper/utils.py
Update housekeeper to ignore charts that have had their slug renamed in the last year.
> ✨ tweak housekeeper to ignore recent slug renames

- etl/multidim.py
- pyproject.toml
- uv.lock
jsonschema is extremely slow, especially in our case, when we use references to an external file (it apparently doesn't cache remote schemas!)
```
"$ref": "https://files.ourworldindata.org/schemas/grapher-schema.006.json#/properties/subtitle"
```
Switching to `fastjsonschema` speeds up validation for energy pricees from 10s to 10ms.
(I checked other places where we do schema validation. One happens when running `data://grapher`, but that takes only about 1ms, so there's nothing to gain there.)
> 🔨 Speedup mdim validation

- etl/steps/export/explorers/emissions/latest/air_pollution.py
When moving the air pollution explorer to an ETL indicator-based explorer, we lost the toggle for linear-log scale. This PR brings it back.
> 📊 emissions: Bring log scale control back to air pollution explorer

- etl/steps/data/garden/lazard/2025-02-25/levelized_cost_of_energy.meta.yml
Add footnote clarifying unsubsidized costs, and re-sync charts after [failure in master build](https://owid.slack.com/archives/C46U9LXRR/p1740735581655409).
> 📊 energy: Minor improvements to LCOE data

- apps/wizard/etl_steps/cookiecutter/garden/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- apps/wizard/etl_steps/cookiecutter/grapher/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- apps/wizard/etl_steps/cookiecutter/meadow/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- etl/helpers.py
I think by now we can safely use `check_variables_metadata=True` by default (in `create_dataset`), and remove it from wizard data step templates (which takes a lot of room).
Note that, as far as I can tell, there's little risk in setting this as `True` by default (maybe we'll see some additional warnings in old steps that didn't have this flag defined explicitly).
> ✨ Check variables metadata by default

- etl/slack_helpers.py
The return object from a function was wrong. Fixing it should resume chart-previews from being shared in the daily housekeeper slack message.
/schedule
> 🐛 housekeeper: messages not showing chart preview

- apps/wizard/etl_steps/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.py
Edit the wizard template for snapshot scripts, to write `run()` instead of `main()`. This would let us develop snapshot steps more easily with the new `run-until-cursor` extension (see https://github.com/owid/etl/pull/4058 ).
> ✨ Change 'main()' to 'run()' in snapshot templates

- etl/collections/multidim.py
- etl/steps/export/multidim/health/latest/vaccination_coverage.py
`expand_config` was only working to expand a single indicator in a table. This PR now adds support for expanding multiple-dimensional indicators.
This was earlier implemented in #4073
> ✨ MDIMs: apply expand_config to multiple indicators in table

- etl/run_python_step.py
- etl/steps/__init__.py
Decide whether to pass `dest_dir` or not by inspecting function arguments rather than catching TypeError. The latter has the disadvantage of being included in the traceback when step fails.
> 🔨 Refactor run(dest_dir)

- docs/architecture/metadata/structuring-yaml.md
- etl/grapher/helpers.py
- etl/steps/data/garden/emissions/2024-11-21/owid_co2.py
- lib/catalog/owid/catalog/datasets.py
- lib/catalog/owid/catalog/jinja.py
- lib/catalog/owid/catalog/meta.py
- lib/catalog/pyproject.toml
- lib/catalog/tests/test_jinja.py
- lib/catalog/tests/test_meta.py
- lib/catalog/uv.lock
- tests/test_grapher_helpers.py
- uv.lock
Replace function for rendering metadata with Jinja templates
```
import etl.grapher.helpers as gh
gh.render_variable_meta(tb.emissions.m, dim_dict={'pollutant': 'CO', 'sector': 'Transport'})
```
by
```
tb.emissions.m.render({'pollutant': 'CO', 'sector': 'Transport'})
```
As part of this, I also did:
- Move Jinja functions to owid-catalog
- Refactor dimension rendering in grapher:// step
The other function `render_yaml_file` for rendering Jinja from YAML file will be also moved in the future (to the new "YAMLMeta" object).
One disadvantage of `.render(...)` is that you need to build the garden dataset & load it to render it. It's often easier to work solely with the YAML file and use `render_yaml_file`.
> ✨ Add .render method to render Jinja templates

- docs/guides/data-work/export-data.md
- etl/collections/explorers.py
- etl/collections/model.py
- etl/collections/multidim.py
- etl/helpers.py
- etl/steps/export/explorers/covid/latest/covid.py
- etl/steps/export/multidim/covid/latest/covid.py
- etl/steps/export/multidim/emissions/latest/air_pollution.py
- etl/steps/export/multidim/energy/latest/energy_prices.py
- etl/steps/export/multidim/health/latest/causes_of_death.py
- etl/steps/export/multidim/health/latest/vaccination_coverage.py
Add `paths.create_mdim` and `Multidim.save` methods to align the structure of MDIM scripts with that of data scripts.
```python
def run(dest_dir: str) -> None:
#
#
ds_grapher = paths.load_dataset("energy_prices")
tb_annual = ds_grapher.read("energy_prices_annual")
tb_monthly = ds_grapher.read("energy_prices_monthly")
#
#
config = paths.load_mdim_config()
config["views"] = multidim.expand_config(
tb_annual,
dimensions=["frequency", "source", "unit"],
additional_config={"chartTypes": ["LineChart"], "hasMapTab": True, "tab": "map"},
)
#
#
mdim = paths.create_mdim(config=config)
mdim.save()
```
At the moment, `paths.create_mdim` is rather simple. It creates a `Multidim` object from a given `config`. In the future, we could change this to accept arguments like `yaml_file` (or `yaml_config`), …
> 🔨 MDIMs: `create_mdim` and `.save` (alignment with data steps)

- .vscode/settings.json
- Makefile
- pyproject.toml
- scripts/exclude_archived_steps.py
- uv.lock
Searching in VSCode can be frustrating when we keep old, archived versions of code in the repository. Quite frequently, I find myself yelling at my computer, only to realize that I was editing the wrong dataset (found through VSCode quick search). This problem has already been addressed by the [find-latest-step](https://github.com/owid/etl/tree/master/vscode_extensions/find-latest-etl-step) extension, although it lacks some capabilities of the native VSCode quick search. I don't personally use the `find-latest-etl-step` extension because it's slow on my laptop and I prefer the fuzzy matching in quick search (although other people use it).
Identify all inactive steps and exclude them from the VSCode search toolbar and file explorer by adding them to `"files.exclude"` and `"search.exclude"` …
> ✨ Exclude archived steps from VSCode search

- etl/steps/data/garden/war/2023-09-21/cow.py
The number of deaths in wars in the [Conflicts](https://ourworldindata.org/explorers/conflict-data) and [Conflicts Data Source](https://ourworldindata.org/explorers/conflict-data-source) explorers is zero between 2004 and 2007 (see [discussion](https://owid.slack.com/archives/C03NV9Z3YSV/p1742583191931629)). These zeros seem to be spurious.
I think these spurious zeros are created at some point when combining different tables. I have removed those zeros, so that the data ends in 2003 (minimum year for which all tables have data).
You can compare the old and new (corrected) Conflicts Data Source explorer [here](http://staging-site-data-fix-war/etl/wizard/explorer-diff?explorer=conflict-data-source&conflict-data-source_Measure=Conflict+deaths&conflict-data-source_Data+source=Correlates+of+Wa …
> 📊 war: Fix issue in war data

- etl/steps/data/external/owid_grapher/latest/regions.py
Following [this conversation](https://owid.slack.com/archives/C0193RW5E2J/p1742917803787839), we decided to keep `defined_by` field in the external `regions` dataset, which used to be unnecessary (since its only value was `owid`), but now that it has multiple options it has become useful.
> 📊 regions: Keep 'defined_by' field in external regions dataset

- snapshots/excess_mortality/latest/hmd_stmf.csv.dvc
- snapshots/excess_mortality/latest/hmd_stmf.py
Snapshot stopped working because the site now requires login. This PR updates the script to log in first, get auth token and use it to download the data.
> 🐛 Fix snapshot for excess mortality

- dag/health.yml
I noticed this missing dependency when I was running a full ETL rebuild, and it was failing because of this.
> 🐛 gbd: add missing dependency on `un_wpp`

- etl/steps/data/garden/faostat/2025-03-17/additional_variables.meta.yml
- etl/steps/data/garden/faostat/2025-03-17/additional_variables.py
- etl/steps/data/grapher/faostat/2025-03-17/additional_variables.py
FAOSTAT QCL used to have yield for milk (i.e. milk per animal, used in [this chart](https://ourworldindata.org/grapher/milk-yields-per-animal)), but it was removed at some point: that combination of item and element is empty in the 2025 release.
Numerically, it seems that their old milk yield indicator coincides reasonably well with production / animals, so I used that as an estimate. For some countries, however, the new data seems to be significantly larger (see e.g. Saudi Arabia or Mexico in [chart diff](http://staging-site-data-milk-yield-fix/etl/wizard/chart-diff)).
I have changed the subtitle to clarify that this is an estimate, and how it's calculated.
> 📊 agriculture: Fix missing milk yield indicator

- etl/steps/data/garden/faostat/2025-03-17/additional_variables.meta.yml
- etl/steps/data/garden/faostat/2025-03-17/additional_variables.py
- etl/steps/data/garden/faostat/2025-03-17/detected_anomalies.py
- etl/steps/data/garden/faostat/2025-03-17/faostat_metadata.py
- etl/steps/data/grapher/faostat/2025-03-17/additional_variables.py
* Fix issue with the number of live turkeys in EU, Europe, and HIC.
* Fix chart on the hypothetical meat demand per person (which was based on production, but it makes more sense to base it on consumption). Note that this means that the data changes significantly, and also the latest point is 2022 instead of 2023.
* Also, fix wrong attribution (see [discussion](https://owid.slack.com/archives/C46U9LXRR/p1744109863123159)).
* Create data for a new chart on the hypothetical number of land animals slaughtered if all countries had the same per-capita meat production.
> 📊 agriculture: FAOSTAT fixes and improvements

- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_risk.meta.yml
They are currently in the wrong order, e.g. "Ambient ozone pollution from all causes attributed to deaths among individuals aged 70+ years" should be "Deaths from all causes attributed to ambient ozone pollution among individuals aged 70+ years"
> 🐛 GBD risk: fix variable titles

- etl/collections/explorer_migration.py
- etl/steps/export/explorers/who/latest/migrate_influenza.ipynb
- tests/collections/test_explorer_migration.py
TSV parsing into a structured format has been moved to the Admin API. Remove the code for parsing TSV files from the explorer migration and simply load the data from the database instead.
> 🔨 Refactor explorer migration

- etl/steps/data/garden/un/2024-07-12/un_wpp.py
To avoid confusion, World net migration should be zero.
In [UN's methodology report](https://population.un.org/wpp/assets/Files/WPP2024_Methodology-Report_Final.pdf#page=33.67), they briefly talk about “international net migration” (see page 25), not sure it explains this ーwill have another read.
It seems that the world values are there just to compensate the sum of all individual country values
> Finally, net migration balancing was carried out to ensure that at the global level, the sum of all net
international migration flows equaled zero for each year of the estimation period. Balance was achieved by
applying small adjustments to net international migration estimates for countries where such estimates were
highly uncertain.
More context: [Slack …
> 📊 un wpp migration of world

- etl/db.py
Sometimes when I open a wizard on a staging server, I get the following error. It disappears after a refresh or two, but it's still annoying. It's hard to replicate, so this fix is a shot in the dark, but it could help (and shouldn't break anything)
> 🐛 Silence sqlalchemy.exc.PendingRollbackError

- etl/collections/beta.py
- etl/collections/common.py
- etl/collections/explorer.py
- etl/collections/model.py
- etl/collections/multidim.py
- etl/steps/export/explorers/un/latest/utils.py
- Abstract some methods in `Explorer` and `Multidim`: `process_views`, `create_*`.
- Change some class attributes for clarity.
- Other minor cosmetic changes.
Future:
I am considering moving classes `Explorer` and `Multidim` to module `etl.collections.model`. Having both classes in one single place could help us. Also, we could then simplify all the logic from `etl.collections.multidim`, `etl.collections.explorer` and ``etl.collections.common`... maybe just have one module instead of three.
/schedule
> ✨ adjust mdim api

- apps/wizard/app_pages/chart_diff/app.py
- apps/wizard/app_pages/chart_diff/utils.py
There's an assertion in `chart_diff/utils.py` that validates that environment isn't production (to avoid syncing from prod to prod). 
```
assert OWID_ENV.env_remote != "production", "Your .env points to production DB, please use a staging environment."
```
This raises an error in owidbot, because it imports chart-diff (but use custom environments). This PR hotfixes it by moving it to `get_engines`.
> 🐛 Fix owidbot and import from chart-diff

- apps/owidbot/data_diff.py
- etl/datadiff.py
- etl/git_helpers.py
When `chart-diff` detects changes, it uses both checksums and whether a dataset is a downstream dependency of any step changed in Git. This helps reduce noise when a branch isn't up to date with `master`.
This PR adds the same functionality to `data-diff` via the `--changed` flag. It also speeds up `get_changed_files` by making the `fetch` optional—saving about 2 seconds, which will benefit `chart-diff` as well.
> ✨ Diff only files changed in git

- lib/catalog/owid/catalog/tables.py
I added a `fill_dimensions` argument to the `pivot` function. By default, it's `True`, to make it compatible with the status quo.
Sometimes you may not want to create dimensions while in the middle of a processing pipeline (see [Pablo's issue](https://owid.slack.com/archives/C46U9LXRR/p1746695093710119)). In his case, pivoting add dimensions, which causes problems down the line. With the changes in this PR, he could use `fill_dimensions=False`.
> 🐛 Add `fill_dimensions` argument to pivot

- apps/autoupdate/cli.py
- scripts/update-wildfires.sh
- snapshots/climate/latest/weekly_wildfires.csv.dvc
- snapshots/climate/latest/weekly_wildfires.py
Replace automatic wildfires updates by `autoupdate:` that creates a PR which needs to be approved and merged.
Updating wildfires have always been tricky, their API isn't very stable and we sometimes get incomplete data. I'm leaving the original script in etl in case we want to roll back.
> 📊 Autoupdate wildfires

- dag/archive/faostat.yml
Remove old faostat food explorer from archive dag to avoid error in version tracker.
> 🐝 Remove old step from the archive dag

- etl/collection/model/core.py
There is an issue with `group_views`, where new views use the same `Indicator` instance as those used to create it. The problem is that a user changes anything on an indicator in a new view will also affect the "old" views.
This PR ensures that the new views reinstantiate the `Indicator` class.
This was detected in a view, where the legends didn't make sense
/schedule
> 🐛 fix `Collection.group_views` indicator instance

- etl/analytics.py
Fix `analytics` module after [recent changes](https://github.com/owid/owid-grapher/commit/44aa99ba7b8efa0495717150e822cd95c994ae5e) in grapher DB. The change in table name `chart_views` -> `narrative_charts` was causing chart diff to break when fetching analytics.
Additionally, changed `chart-view` to `narrative-chart` link type.
> 🐛 Rename narrative charts table

- etl/steps/data/external/owid_grapher/latest/regions.py
- etl/steps/data/garden/un/2023-10-30/un_members.py
- etl/steps/data/grapher/regions/latest/regions.py
Add Antarctica ("ATA") to the list of grapher mappable regions.
NOTE: The garden `regions` dataset is not affected, only the grapher regions is. I noticed that `MAPPABLE_COUNTRIES` is also hardcoded in the garden `un_members` step. This is only used as a dependency by `nuclear_weapons_treaties`. But note that adding "ATA" to that list un `un_members`doesn't make a difference, because `un_members` step only cares about mappable **countries** (with `region_type="country"`), while Antarctica has region type `other`.
> 📊 regions: Add Antarctica to mappable grapher regions

- etl/collection/model/core.py
- etl/steps/export/multidim/war/latest/mars.config.yml
Add a feature in Collections to set a default set of dimensions. This is done with the field `default_dimensions`.
It can either be set in the YAML file, as a top-level property, or via code using `c.default_dimensions = {...}`.
This field should be a dictionary, mapping dimension slugs to choice slugs, e.g.
```yaml
default_dimensions:
sex: female
age: 0
```
/schedule
> 🎉 default view in mdims

- etl/collection/core/create.py
Choice renaming was only being applied to MDIMs, because of an early `return` statement. It should also be applied to Explorers!
/schedule
> 🐛 explorers: choice renaming

- etl/collection/exceptions.py
- etl/collection/model/core.py
- etl/collection/utils.py
- etl/steps/export/multidim/war/latest/mars.py
- etl/steps/export/multidim/war/latest/ucdp.py
- etl/steps/export/multidim/war/latest/ucdp_prio.py
Improvements to `Collection.group_views`, inspired by the use case in #4407.
- If `choices` is None, group _all_ dimension choices!
- Change argument name `params` to `groups`, for clarity.
- Change argument name `config_new` to `view_config`, for clarity.
- Support setting metadata for the grouped views via `view_metadata`.
- Support dynamically setting the config (and metadata!) of the new views. For instance, if we want to set the title based on the view dimension "age", one can now do the following:
```python
c.group_views(
groups=[
{
"dimension": "sex",
"view_config": {
"title": "Population of people aged {age}",
}
"view_params": {
"age": lambda view: view.dimensions["age"],
},
}
]
)
```
/schedule
> ✨ improve Collection group_views

- etl/steps/data/garden/animal_welfare/2025-03-26/animals_used_for_food.py
Remove bees from animal welfare explorer (where metadata is wrong), as a temporary solution (see [conversation](https://owid.slack.com/archives/C03NV9Z3YSV/p1747746954674539)).
> 📊 animal-welfare: Fix animal-welfare explorer issues

- etl/steps/data/garden/itopf/2025-05-05/oil_spills.py
- etl/steps/data/garden/unesco/2025-05-01/education_opri.py
- etl/steps/data/garden/unesco/2025-05-01/education_sdgs.py
- etl/steps/data/grapher/itopf/2025-05-05/oil_spills.py
- etl/steps/data/grapher/un/2025-04-25/long_run_child_mortality.py
- etl/steps/data/grapher/unesco/2025-05-01/education_opri.py
- etl/steps/data/grapher/unesco/2025-05-01/education_sdgs.py
- etl/steps/data/grapher/unodc/2025-05-12/corruption.py
- etl/steps/data/grapher/unodc/2025-05-12/justice.py
- etl/steps/data/meadow/itopf/2025-05-05/oil_spills.py
- etl/steps/data/meadow/unesco/2025-05-01/education_opri.py
- etl/steps/data/meadow/unesco/2025-05-01/education_sdgs.py
Some recently added steps still use `dest_dir`. I've replaced these instances, to use `paths.create_dataset` approach instead.
/schedule
> 🔨 remove dest_dir from recent steps

- docs/guides/harmonize-countries.md
- fix typo in harmonize-countries guide
- `make test` *(fails: EHOSTUNREACH while installing npm package)*
> Fix typo in harmonize countries guide

- docs/architecture/metadata/data_pages_workflow.md
- etl/command.py
- etl/config.py
- etl/grapher/to_db.py
- etl/steps/__init__.py
- etl/steps/data/garden/biodiversity/2025-04-07/cherry_blossom.meta.yml
See the problem in https://github.com/owid/etl/issues/4333.
Instant metadata updates can be turned on with `INSTANT=1 etlr ...`. If on, instead of recalculating the garden step, it'll **load the existing garden dataset**, apply metadata YAML file and save it again. Then we detect what indicators have changed and save them in `INSTANT_METADATA_DIFF`. This dictionary will be then used in the `grapher://grapher` step to filter indicators that need to be updated.
- It's not bulletproof, and it's always recommended to do the final run **without** `INSTANT=1` (it'll be done by the staging server)
- `data://grapher` is always run (so is `long -> wide` flattening) - if that is a bottleneck, we can try to further optimize it (though it could get tricky) with `INSTANT_METADATA_DIFF` (especially …
> 🎉 Instant metadata updates

- etl/collection/model/core.py
Ensure that all slugs (choices & dimensions) are snake case. 
- Only lowercase characters, numbers and underscores are allowed
- Name should at least contain an alphanumeric character.
- Names should start with a character or underscore + anything, i.e., they can't start with a number
Examples:
- Valid ✅: `test`, `test_1`, `_1`
- Invalid ❌: `2020`, `_`
/schedule
> 🔨 force snake_case in collection slugs

- etl/steps/export/explorers/emissions/latest/ipcc_scenarios.config.yml
- etl/steps/export/explorers/emissions/latest/ipcc_scenarios.py
Empty slug for choice or dimension is not allowed.
> 🐛 fix underscoring of slugs in ipcc explorer

- etl/collection/model/core.py
- etl/steps/export/explorers/faostat/latest/global_food.py
- Map empty slugs `""` to `"na"` when exporting.
- We were snake-casing dimension and choice slugs, but forgetting about `choice[].presentation.choice_slug_true`, if existant.
/schedule
> 🐛 fix slugs in collections

- etl/steps/export/explorers/biodiversity/latest/habitat_loss.config.yml
- etl/steps/export/explorers/migration/2024-08-05/migration.py
- etl/steps/export/explorers/migration/latest/migration_flows.py
- etl/steps/export/explorers/wash/latest/water_and_sanitation.py
- schemas/dataset-schema.json
- scripts/poverty-inequality-explorers/common_parameters.py
- scripts/poverty-inequality-explorers/lis/lis_expanded_poverty_explorer.py
- scripts/poverty-inequality-explorers/lis/lis_incomes_across_distribution_explorer.py
- scripts/poverty-inequality-explorers/lis/lis_inequality_explorer.py
- scripts/poverty-inequality-explorers/multisource/incomes_across_distribution_explorer_comparison.py
- scripts/poverty-inequality-explorers/multisource/inequality_explorer.py
- scripts/poverty-inequality-explorers/multisource/inequality_explorer_comparison.py
- scripts/poverty-inequality-explorers/multisource/poverty_explorer_comparison.py
- scripts/poverty-inequality-explorers/wbpip/pip_expanded_poverty_explorer.py
- scripts/poverty-inequality-explorers/wbpip/pip_incomes_across_distribution_explorer.py
- scripts/poverty-inequality-explorers/wbpip/pip_inequality_explorer.py
- scripts/poverty-inequality-explorers/wbpip/pip_poverty_explorer.py
- scripts/poverty-inequality-explorers/wbpip/pip_ppp_comparison_explorer.py
- scripts/poverty-inequality-explorers/wid/wid_incomes_across_distribution_explorer.py
- scripts/poverty-inequality-explorers/wid/wid_inequality_explorer.py
We're getting rid of this setting on the grapher side of things, and it was _always_ set to `true` for a long time now anyhow.
There's not a single instance where it wasn't set to true, so...
> cleanup: remove `colorScaleEqualSizeBins`

- apps/chart_sync/admin_api.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
- etl/grapher/model.py
Issue https://github.com/owid/etl/issues/1563#issuecomment-2925684371
Chart config inheritance wasn't detected in `chart-sync` because it's not part of chart config, but a separate column in `variables` table. As a workaround, we artificially add it to chart `config` and then remove right before sending the config to Admin API. I don't know whether I've found all places where we use `configs_are_equal` and so added a couple of asserts as guardrails.
Check out [chart-diff for this server](http://staging-site-fix-inheritance-sync/etl/wizard/chart-diff). You should see one chart with enabled inheritance. (It's not shown by owidbot because it runs on `master`)
> ✨ Support chart inheritance in chart-sync

- etl/steps/data/garden/energy/2025-05-12/electricity_mix.meta.yml
The field `presentation.attribution_short` is manually input, and it was misleading in some cases (e.g. [this chart](https://owid.slack.com/archives/C01GAN73R5W/p1748948670117129), where it was "Ember and Energy Institute" but the right attribution should have been "Ember"). For simplicity and safety, I decided to remove this field.
Alternatively, I could manually assign "Ember", or "Energy Institute" or "Various sources" (or the appropriate combination of them) from code. But I'm also worried about how the propagation of this field will affect other downstream dependencies (e.g. `owid-energy`). See [this related issue](https://github.com/owid/etl/issues/4241).
> 📊 energy: Fix short attribution of electricity mix

- etl/steps/data/garden/covid/latest/sequence.py
- snapshots/covid/latest/vaccinations_global_who.csv.dvc
covariants.org added more sublineages of `Omicron`. This PR adds these so that CI/CD stops failing in other servers.
TODO: Edit charts in admin.
/schedule
> add new omicron variants to covid data

- etl/steps/data/garden/energy/2025-05-12/electricity_mix.py
There was a sudden drop in the share of fossil generation in 2023 for low-income countries (and hence a sudden increase in the share of renewables). This may be due mostly to Syria and North Korea, that have the largest fossil generation among low-income countries, and are not informed in 2023.
This PR removes the aggregate of low-income countries in 2023 for all columns in the electricity mix dataset (since those countries seem to be missing in almost all columns).
[See discussion](https://owid.slack.com/archives/C08LZUSC737/p1749573637118339).
> 📊 energy: Fix missing data in electricity mix for low-income countries in 2023

- snapshots/rff/2025-06-02/emissions_weighted_carbon_price.zip.dvc
- snapshots/rff/2025-06-02/world_carbon_pricing.zip.dvc
* Ed noticed [a potential data issue](https://owid.slack.com/archives/C03N1V9KXB9/p1749108634648809?thread_ts=1748855799.031569&cid=C03N1V9KXB9) in carbon pricing data for Norway, and I contacted the data provider. They have looked into it and fixed it, so I have re-executed the snapshots.
* I have also changed the citation, to show the 2024 paper in some of the charts (while also keeping the 2022 paper in the full citation).
@Marigold there's not much to review, but I wanted to flag a few issues that happened along the way. This PR was meant to be trivial: I just wanted to re-run a snapshot and overwrite the data. However, a few odd issues occurred:
* While running the snapshot `snapshots/rff/2025-06-02/emissions_weighted_carbon_price.zip.dvc`, I got an error saying that …
> 📊 Auxiliary staging server

- etl/steps/export/multidim/health/latest/vaccination_coverage.py
Improvements for https://github.com/owid/etl/pull/4558: Less duplicate text, use of `params` when grouping views.
- `metadata.description_short` was the same as `config.subtitle`, no need to repeat it twice.
- `config.note` is the same across all dimensions, no need to repeat it three times.
- Instead of iterating over views after creating the grouped views, you can use `params` in `group_views` and condition the values.
> suggestions for fiona

- etl/steps/export/explorers/agriculture/latest/crop_yields.config.yml
This PR adds more crops, for which we have FAOSTAT data, to the crop yields explorer.
Simply visit [the new explorer](http://staging-site-data-crop-yields-explorer/admin/explorers/preview/crop-yields) and:
1. Please have a look at the choices in the dropdown, and let me know if some of them can be removed.
2. Please have a look at the titles and let me know if any of them is odd (e.g. "Chickpeas yield" instead of "Chickpea yield").
Fixes https://github.com/owid/owid-issues/issues/1100
> 📊 agriculture: Add items to crop yields explorer

- apps/wizard/utils/components.py
ChartDiff shows grapher charts by using the JS function `window.Grapher.renderSingleGrapherOnGrapherPage(jsonConfig)`. This function was moved and is now at `window.renderSingleGrapherOnGrapherPage(jsonConfig)`
> 🐛 adapt to new way of embedding a single grapher after state refactor

- apps/wizard/config/config.yml
- tests/apps/wizard/app_pages/test_apps.py
Hey @Marigold, insight search is causing a segmentation fault when trying to execute it locally, and its integration test is failing (e.g. [here](https://buildkite.com/our-world-in-data/etl-automated-staging-environment/builds/20512#01979be3-4c8a-4532-85f5-5aebb216fd3b), although, interestingly, the app does work [in production](https://etl.owid.io/wizard/insight_search)). I couldn't figure out what's going on, so I've removed the app and the test. If you have an idea of what could be happening, feel free to have a look. Otherwise, I think we can live without it (now that we have [the DI search in the admin](https://admin.owid.io/admin/data-insights)). thanks!
> 🐛 Fix or patch insight search

- etl/grapher/model.py
We should be using `createdAt`, not `updatedAt` when getting `chart_revisions`. It used to be identical, but recent migration have bumped `updatedAt` of all revisions and broke chart-diff.
> 🐛 Use createdAt in chart_revisions

- etl/collection/core/utils.py
- etl/collection/model/core.py
- etl/collection/model/view.py
- etl/steps/export/multidim/war/latest/ucdp.py
- lib/catalog/owid/catalog/meta.py
- tests/collections/test_collection_model.py
- tests/collections/test_model_dimension_view.py
- Use preliminary UCDP data only in default view
- Some views were missing (`conflict_type='all'` for other than `indicator='deaths'`
- FEATURE: `tb.m.uri` to get table URI
- FEATURE: `View.matches` to match specific set of dimensions
- FEATURE: Add check of indicators. They should come from dependencies.
/schedule
> 💄 yet even still more edits to war mdims

- etl/collection/core/combine.py
- etl/collection/core/utils.py
- etl/collection/model/core.py
- etl/steps/export/multidim/covid/latest/covid.py
- schemas/multidim-schema.json
- tests/collections/test_collection_model.py
Fix bug when saving collections.
There is a sanity check that validates that the indicators used in the collections have been specified as dependencies. However, this check was implemented wrongly and was leading to some unexpected errors when there were private dependencies (e.g., `data-private://`).
This PR solves this.
/schedule
> 🐛 fix dependency check in collections

- apps/chart_sync/cli.py
- apps/wizard/app_pages/chart_diff/app.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
This PR adds some features to chart-sync and chart-diff:
* Add `--ignore-conflicts` option to chart-sync.
* Add button to fix all conflicts in chart diff (accepting staging changes).
* Add button to approve all (non-conflicted) pending charts in chart diff.
These features are particularly useful for big data updates, when you have a baseline PR (merging duplicated steps to master) and a subbranch (merging adapted steps to the baseline branch). After doing all the code and chart work in the subbranch staging server and merging the PR, the workflow would be to:
* Run: `etl chart-sync staging-site-sub-branch staging-site-baseline-branch --ignore-conflicts`
* In the chart diff of the baseline branch server, press the button to fix all conflicts, and then press the button to approve all …
> 🎉 Various improvements on chart sync and chart diff

- etl/steps/data/garden/demography/2024-07-15/population.meta.yml
- etl/steps/data/garden/demography/2024-07-15/population.py
There is an issue with early population data, where we were inflating data for some continents. This was due to wrongly back-propagating in time data values for some countries (e.g. value for Serbia in 1950 would be assigned to all years pre 1950), which then made the regional aggregate estimation use wrong numbers.
I've now changed the strategy to just rely on HYDE values pre 1800 also for continents.
/schedule
> 🐛 fix population omm

- apps/wizard/utils/chart_config.py
- docs/guides/data-work/export-data.md
- docs/guides/data-work/mdims.md
- etl/collection/core/expand.py
- etl/steps/export/explorers/agriculture/latest/crop_yields.config.yml
- etl/steps/export/explorers/climate/latest/climate_change.config.yml
- etl/steps/export/explorers/migration/latest/migration_flows.py
- etl/steps/export/explorers/wash/latest/migrate_wash.ipynb
- etl/steps/export/explorers/wash/latest/water_and_sanitation.config.yml
- etl/steps/export/explorers/who/latest/influenza.config.yml
- etl/steps/export/explorers/who/latest/monkeypox.config.yml
- etl/steps/export/multidim/energy/latest/energy_prices.py
- etl/steps/export/multidim/health/latest/vaccination_coverage.py
- etl/steps/export/multidim/migration/latest/migration_flows.py
- etl/steps/export/multidim/wb/latest/world_bank_pip.config.yml
- schemas/dataset-schema.json
- schemas/explorer-schema.json
- tests/collections/test_core_create.py
- tests/collections/test_explorer_migration.py
- tests/test_explorer.py
For line charts to switch to discrete bar charts when both handles are on the same time, we now need to explicitly include the `DiscreteBar` chart tab in `chartTypes`. If `chartTypes` isn't provided, it defaults to `["LineChart", "DiscreteBar"]`.
In this PR, I’ve added `DiscreteBar` whenever `chartTypes` is set to `LineChart`, but another option would be to just remove the chartTypes field altogether and rely on the default. Let me know which you’d prefer!
> 🔨 refactor chart types

- etl/steps/data/garden/war/2025-06-13/ucdp.meta.yml
- etl/steps/data/garden/war/2025-06-16/ucdp_prio.meta.yml
- etl/steps/data/garden/war/latest/ucdp_preview.meta.yml
- etl/steps/export/multidim/war/latest/ucdp.py
- etl/steps/export/multidim/war/latest/ucdp_prio.py
Replaced single quotes with escaped double quotes around "best" death estimates in metadata and export scripts for consistency in UCDP and PRIO references.
> 🐝  Standardize quotes for "best" death estimates

- etl/steps/data/garden/faostat/2025-03-17/faostat_metadata.py
- etl/steps/data/garden/regions/2023-01-01/regions.yml
I noticed that the OWID African aggregate for some agriculture indicators was a little below the original "Africa (FAO)"; this caught my attention, as our definition of Africa is the same as FAO's definition.
It seems that, even though we did have a "Sudan (former)" country defined in our regions file, this country was not added as a member of Africa. This PR includes it.
NOTE: Merge at the end of the day, as it will trigger a big run.
> 📊 regions: Add former Sudan to Africa region

- etl/steps/data/garden/ggdc/2024-04-26/maddison_project_database.meta.yml
- etl/steps/data/garden/wb/2025-08-07/world_bank_pip.meta.yml
- etl/steps/data/grapher/regions/2023-01-01/regions.meta.override.yml
- etl/steps/data/grapher/regions/2023-01-01/regions.py
Let's set the categorical indicators with region information (from OWID, WB, etc.) to be of type ordinal.
This way, we can define a sorting in the legends of charts in https://ourworldindata.org/world-region-map-definitions
/schedule
> 📊 try ordinals in un regions

- dag/main.yml
- etl/steps/data/garden/homicide/2025-08-06/who_mort_db.py
`data://garden/homicide/2025-08-06/who_mort_db` has 2024 un_wpp in dependencies, but it's actually using 2022 version (which is silently loaded in `add_population`). This doesn't affect data at all. cc @spoonerf
> 🐛 Use correct UN dependency in WHO Mortality DB

- etl/steps/data/meadow/irena/2025-08-22/renewable_power_generation_costs.py
* Fix bug related to an unfortunate coincidence in sheet names after latest update (between hydropower and geothermal).
* Add sanity checks to avoid this in the future.
See [conversation](https://owid.slack.com/archives/C03N1V9KXB9/p1756370615202589?thread_ts=1756368751.412129&cid=C03N1V9KXB9) for more context.
> 📊 energy: Fix bug in extraction of IRENA costs

- etl/steps/data/garden/agriculture/2025-03-26/attainable_yields.meta.yml
- etl/steps/data/garden/agriculture/2025-03-26/long_term_crop_yields.meta.yml
- etl/steps/data/garden/faostat/2025-03-17/detected_anomalies.py
- etl/steps/data/garden/faostat/2025-03-17/faostat_qcl.meta.yml
- etl/steps/export/explorers/faostat/latest/global_food.py
Tea production data in FAOSTAT QCL increased abruptly from 1990 to 1991 for many different countries (including some of the main producers, like China and India). However, data from 1991 is flagged as 'Estimated value' (while data prior to 1991 is flagged as 'Official figure'). Therefore, we decided to remove all tea production data (as well as per-capita production and yield).
This PR will remove tea production, per capita production, and yield, from the QCL dataset, the long term crop yields dataset, the attainable yields datasets, the food explorer, and the crop yields explorer.
In production, I've redirected the charts on [tea production](https://ourworldindata.org/grapher/tea-production) and [tea production by region](https://ourworldindata.org/grapher/tea-production-by-region) to …
> 📊 agriculture: Fix issue with tea leaves production

- dag/energy.yml
- etl/steps/data/garden/irena/2025-08-22/renewable_power_generation_costs.meta.yml
- etl/steps/data/garden/irena/2025-08-22/renewable_power_generation_costs.py
Use each country's GDP deflator (linked series) to adjust IRENA's renewable power generation costs (to convert data in constant 2023 USD to constant 2024 USD).
> 📊 energy: Fix inflation adjustment in IRENAs data

- snapshots/papers/2023-12-12/smil_2017.csv.dvc
Replace [broken link](https://vaclavsmil.com/2016/12/14/energy-transitions-global-and-national-perspectives-second-expanded-and-updated-edition/) by [a new one](https://vaclavsmil.com/book/energy-transitions-global-and-national-perspectives-second-expanded-and-updated-edition/) (and remove [the old download link](https://vaclavsmil.com/wp-content/uploads/2017/01/ET2_Appendix_A.pdf); the pdf of the appendix seems to not be available online anymore).
> 📊 energy: Fix broken link to Vaclav Smil's Energy Transitions book

- dag/demography.yml
- etl/steps/data/external/demography/latest/un_wpp_subset.py
Hey @Marigold, in Cologne, my group is working on some visualisations using the UN WPP data. I wanted to make some different slices of it easily accessible, and thought using the `external` channel would be a good way to do it. Is that okay? We can always remove it after Cologne, or move the pipeline into the ETL if we end up using the outputs.
> 📊  UN WPP data for Cologne

- etl/steps/data/garden/ilostat/2023-09-19/employment.meta.yml
- etl/steps/data/garden/ilostat/2023-09-19/unemployment.meta.yml
A request from @bertharc to prune an econ tag: remove `Labor Supply & Employment`, setting them all to `Labor Force Participation & Employment`
We're also renaming `Labor & Employment` to `Work and Employment` - but that's not mentioned anywhere in this repo.
> 🐝 migrate Labor Supply & Employment tag

- apps/chart_sync/cli.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
Send notifications about deleted charts from staging to Slack. An example
```
⚠ *ETL chart-sync: 1 Deleted Chart Detected* from `notify-deleted-charts`
The following chart exist(s) in production but not in staging and may have been deleted:
• Chart 8511: `the-us-spends-far-more-on-health-than-any-other-g7-country` - <https://admin.owid.io/admin/charts/8511/edit|View on Production>
chart-sync doesn't delete charts. Make sure to delete them from production if this was intentional.
```
Let's start with this and see how often it comes up. In the future, we might decide to go all the way and automate deletion (see https://github.com/owid/etl/issues/5004).
> 🎉 Notify about deleted charts
