owid/etl

- dag.yml
- etl/command.py
- etl/steps/data/garden/owid/latest/key_indicators/__init__.py
- etl/steps/data/garden/owid/latest/key_indicators/table_population.mapping.csv
- etl/steps/data/garden/owid/latest/key_indicators/table_population.py
- etl/steps/data/meadow/gapminder/2019-12-10/population.py
- etl/steps/data/meadow/hyde/2017/baseline.ipynb
Adapt Ed's population stitched dataset from the `importers` repo.
> data: Add `owid/latest/key_indicators` with stitiched population

- etl/git.py
Currently when we need to check if a repo is current, we shell out twice using the `sh` module, once to check the current ref, once to do a dry-run of `git fetch`. Both of these are slow and mean it takes a long time to see when the repo is out of date, once it's built.
The net effect of this is that, once you've built everything, your next `.venv/bin/etl --dry-run` spends several minutes just trying to work out what's out of date.
This change switches to getting the local sha by just reading from disk, and doing a single HTTPS request using Git's smart HTTPS protocol to Github to get the latest remote sha.
Before:
```
In [3]: %timeit git.GithubRepo('open-numbers', 'ddf--ihme--global_burden_disease_etiology').is_up_to_date()
428 ms ± 8.22 ms per loop (mean ± std. dev. of 7 runs, 1 loop …
```
> enhance: Speed up github checks for open numbers

- etl/publish.py
Fixes #55.
⚠️ I haven't tried that this works at all, because I wouldn't even know how. But it _sounds_ reasonable.
> feat: delete files from remote in `sync_folder`

- .github/workflows/python-package.yml
- etl/steps/data/garden/living_planet/2020-09-10/lpd.ipynb
Resolves https://github.com/owid/etl/issues/75
> fix(github_ci): fix failing MySQL on Github CI

- data/reference/countries_regions.csv
- data/reference/countries_regions.meta.json
> feat(countries_regions): update countries regions

- etl/db_utils.py
- etl/grapher_helpers.py
- etl/grapher_import.py
- etl/steps/data/garden/wpp/2019/standard_projections.py
- etl/steps/grapher/who/2021-07-01/ghe.py
PR for owid-catalog-py https://github.com/owid/owid-catalog-py/pull/28
The mapping between ETL and grapher metadata is not obvious at all. The grapher data model is quite outdated with some things that are not making much sense such as:
1. Even though dataset can have multiple sources, only the first one is shown - as a workaround we join all sources to a single one before inserting to grapher (this happens for `population density`)
2. Admin UI for dataset weirdly maps fields, e.g. `source.additionalInfo` is displayed as `Dataset description` in the UI, `unit` and `shortUnit` of variables are not mapped at all, but instead we show `display.unit` and `display.shortUnit`, etc.
Nevertheless, once you get used to these it's straightforward to write a script that gets your data into grapher in …
> enhance(grapher): align metadata for grapher and ETL

- etl/command.py
- etl/steps/__init__.py
- tests/test_steps.py
Fix a bug that wrongly computed steps dirtiness.
> fix(steps): replace threading as_completed with map to maintain order of futures

- backport/backport.py
- etl/backport_helpers.py
Part of https://github.com/owid/owid-catalog-py/pull/40
> fix(backport): underscoring can cause collision

- poetry.lock
- pyproject.toml
Install latest owid-datautils version and update poetry lock file.
> chore: install latest owid-datautils version and update poetry lock

- etl/command.py
Dumb mistake which caused one particular dataset to fail.
> fix(backport): strip not replace _values suffix

- etl/steps/data/meadow/faostat/2021-06-17/faostat_rl.ipynb
Solve small issue with an old FAOSTAT step.
> fix(faostat): solve issue with old FAOSTAT step

- etl/steps/data/garden/faostat/2022-05-17/shared.py
Couple of minor updates that should improve performance of faostat_fbsc (and others). Should be used alongside [latest improvements in datautils](https://github.com/owid/data-utils-py/commit/abc747521d371693e04f4c81ea82da27a98eab45).
Current runtime of `data://garden/faostat/2022-05-17/faostat_fbsc` is 344s on my old mac.
> Improve performance of fsbc faostat

- poetry.lock
- pyproject.toml
Pytest was failing with python 3.10
> chore(packages): update pytest

- etl/steps/data/garden/faostat/2022-05-17/faostat_fbsc.py
- etl/steps/data/garden/faostat/2022-05-17/shared.py
- delete unused dataframes throughout code to save memory
- use `copy(deep=False)` for critical parts of code
- optimize `prepare_wide_table` (this part alone was taking >8gb memory before)
> Memory fix for prepare_wide_tables

- dag_files/dag_faostat.yml
- etl/steps/data/explorers/owid/latest/food_explorer.py
- etl/steps/data/garden/faostat/2022-05-17/faostat_fbsc.py
- etl/steps/data/garden/faostat/2022-05-17/faostat_food_explorer.py
- etl/steps/data/garden/faostat/2022-05-17/faostat_qcl.py
- etl/steps/data/garden/faostat/2022-05-17/shared.py
Add missing variable to explorer (yield, in tonnes per hectare).
> Add new faostat steps

- etl/steps/data/garden/sdg/latest/sdg.py
https://github.com/owid/etl/issues/241
Step data://garden/sdg/latest/sdg was taking a long time, and the bottleneck was reading dataset Table's from feather files. It turns out that most of the time, we've read the same table before, so caching helps a lot.
This takes the runtime of that step from ~21 mins to ~55 secs 🎉 After that, the bottleneck is still reading feather files, so it will be a bigger structural change to improve performance further if that is necessary.
> Cache `Table` reads in `sdg` step

- data/garden/reference/countries_regions.csv
- data/garden/reference/countries_regions.meta.json
Add new names for known countries.
> data(countries_regions): add new names for known countries

- etl/grapher_helpers.py
- etl/steps/data/garden/un/2022-07-11/un_wpp.meta.yml
- etl/steps/grapher/un/2022-07-11/un_wpp.py
Use `yield_long_table` method for inserting to grapher.
> data(un_wpp): insert to grapher with yield_long_table

- etl/steps/__init__.py
- etl/steps/data/converters.py
- walkthrough/meadow.py
@larsyencken let me know if you want detailed description.
> enhance(etl): minor improvements

- etl/helpers.py
- etl/steps/__init__.py
- tests/test_helpers.py
> fix(steps): run steps in isolated environment

- etl/match_variables_from_two_versions_of_a_dataset.py
A minor improvement for this script: define mandatory arguments.
> Improve script to match variables

- etl/command.py
Fixes #338
Increase the soft limit of open files to 5000, if it's less than that.
> fix: allow more open files by default

- etl/steps/data/garden/energy/2022-08-05/owid_energy.py
Remove rows that only have nan in energy dataset.
> fix(energy): Remove rows of nan in energy dataset

- etl/steps/data/garden/un_sdg/2022-07-07/un_sdg.py
- etl/steps/grapher/un_sdg/2022-07-07/un_sdg.py
I switched from using the variable name to the variable code which worked in most cases, there is still at least one v long dimension name so I use only the first 255 characters in the variable name.
> Shortening the table variable names as in some cases they were over 255 chars

- etl/helpers.py
- etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.py
- etl/steps/grapher/ggdc/2020-10-01/ggdc_maddison.py
@pabloarosado do you think such syntactic sugar could be useful or am I trying to simplify something that's already simple enough? I find writing paths to meadow dataset and other files quite annoying.
(This is not a final version, just want to get initial feedback)
> feature(helpers): add Naming object

- etl/steps/open_numbers.py
Fix failing column `age_group_1year` and make sure we raise an error instead of a warning that's hard to debug.
> fix(open_numbers): fix mixed type

- poetry.lock
- pyproject.toml
> chore: Update datautils

- scripts/typecheck_steps.sh
Typechecking steps serially takes ~42s. Running them all in parallel takes under 12s.
> enhance(mypy): typecheck steps in parallel

- etl/grapher_helpers.py
- etl/grapher_import.py
- etl/steps/grapher/un_sdg/2022-07-07/un_sdg.py
- tests/test_grapher_helpers.py
Silly mistake, this was causing assertion errors for categorical variables.
> fix(grapher_helper): fix inf check

- poetry.lock
- pyproject.toml
Update owid-datautils version.
> chore: Update datautils version

- .env.example
- backport/backport.py
- backport/bulk_backport.py
- backport/fasttrack.py
- etl/command.py
- etl/config.py
- etl/prune.py
- etl/publish.py
- etl/reindex.py
- poetry.lock
- pyproject.toml
Improvement over slacktee error tracking with better tracebacks and possibility to add metadata to exceptions. Bugsnag has additional features that could make our life easier.
> feature(errors): add bugsnag for error handling

- etl/variable_mapping_translate.py
Bug correction in command `etl-translate-varmap`. The variable mapping was wrong due to a sorting issue.
> fix(var-translate): correct variable order

- etl/steps/data/garden/sdg/latest/sdg.py
Fix for https://github.com/owid/etl/issues/437
> fix(sdg): fix multiindex misalignment

- etl/grapher_import.py
- etl/steps/data/garden/un_sdg/2022-07-07/un_sdg.py
Fix for https://github.com/owid/etl/issues/445
> Bug: SDG indicator 15.9.1 series ER_BDY_ABT2NP has duplicate values after conversion

- dag_files/dag_energy.yml
- etl/steps/data/garden/smil/2017-01-01/global_primary_energy.meta.yml
- etl/steps/data/garden/smil/2017-01-01/global_primary_energy.py
- etl/steps/data/meadow/smil/2017-01-01/global_primary_energy.py
Add meadow and garden steps for Smil global primary energy dataset.
> Add smil energy dataset

- etl/steps/grapher/un/2022-07-11/un_wpp.py
- etl/steps/grapher/un_sdg/2022-07-07/match_vars_crs.py
- etl/steps/grapher/un_sdg/2022-07-07/un_sdg.py
- etl/steps/grapher/worldbank_wdi/2022-05-26/wdi.py
- etl/steps/grapher/worldbank_wdi/2022-05-26/wdi_variable_replacements.py
- scripts/typecheck_steps.sh
Fix for https://github.com/owid/etl/issues/440
> fix(makefile): typecheck grapher steps too

- etl/chart_revision_suggester.py
- etl/compare.py
- etl/tempcompare.py
* Improve error messages when table is not found
* Add `--debug` flag for easier development
* Fix a couple of issues that popped up when running `compare etl-catalog garden faostat faostat_ek faostat_ek$ --show-values`
> enhance(compare): preview samples and fix minor bugs

- etl/steps/data/garden/energy/2022-09-09/global_primary_energy.py
Silly bug (that neither me nor PyCharm nor CI tests noticed).
> fix(energy): Fix wrong method to sort index

- etl/steps/data/garden/un/2019/un_wpp.mapping.json
- etl/steps/data/garden/un/2022-07-11/dtypes.py
- etl/steps/data/garden/un/2022-07-11/un_wpp.country_std.csv
- Alphabetical sorting of categorical variable `location`
- Fix country name standardisation ~`Saint Barthlemy`~ -> `Saint Barthelemy` (un WPP 2022, 2019)
> dataset(un_wpp): minor fixes

- etl/grapher_helpers.py
- etl/run_python_step.py
- etl/steps/__init__.py
- etl/steps/grapher/ggdc/2020-10-01/ggdc_maddison.py
- etl/steps/grapher/un/2022-07-11/un_wpp.py
- etl/steps/grapher/un_sdg/2022-07-07/un_sdg.py
- etl/steps/grapher/who/2021-07-01/ghe.py
- etl/steps/grapher/worldbank_wdi/2022-05-26/wdi.py
- etl/steps/grapher/worldbank_wdi/2022-05-26/wdi_variable_replacements.py
- walkthrough/grapher.py
Issue https://github.com/owid/etl/issues/456
This [migration ](https://github.com/owid/owid-grapher/pull/1651) needs to be applied first
> data(shortName): remove insitution and version from dataset short names

- etl/grapher_helpers.py
- etl/grapher_import.py
Minor improvements to grapher.
> enhance(grapher): skip empty variables, capitalize dimension names

- .github/workflows/project-automations.yml
Copied from owid-grapher repo. Is there way (is there a need?) to test it before merging?
> enhance(actions): add triage label to new issues

- dag_files/dag_energy.yml
- etl/steps/data/garden/bp/2022-09-19/fossil_fuel_reserves_production_ratio.meta.yml
- etl/steps/data/garden/bp/2022-09-19/fossil_fuel_reserves_production_ratio.py
- etl/steps/data/garden/bp/2022-09-19/shared.py
- etl/steps/grapher/bp/2022-09-19/fossil_fuel_reserves_production_ratio.py
- etl/steps/grapher/bp/2022-09-19/shared.py
Add garden and grapher steps for a dataset on fossil fuel reserves/production ratios.
> Add reserves production dataset

- etl/grapher_helpers.py
- tests/test_grapher_helpers.py
Fix for https://github.com/owid/etl/issues/499
> fix(combine_sources): do not modify original source

- etl/grapher_helpers.py
- etl/grapher_import.py
- etl/steps/data/garden/un/2022-07-11/un_wpp/deaths.py
- etl/steps/data/garden/un/2022-07-11/un_wpp/population.py
- scripts/typecheck_steps.sh
Couple minor fixes / improvements.
> fix(etl): minor improvements

- docs/overview.rst
Fix minor typo, simplify long sentence
> docs: minor changes

- dag.yml
- etl/data_helpers.py
- etl/steps/data/garden/technology/2022/internet/__init__.py
Adds continent data to the dataset.
some context: https://github.com/owid/owid-issues/issues/551#issuecomment-1265773009
> feat(internet): add continent data

- etl/grapher_import.py
Fix for https://github.com/owid/etl/pull/569#issuecomment-1279024061. @spoonerf after we merge this could you rebase your PR and try again? (it worked for me)
> fix(grapher_import): fix precision of float32 in data_values table

- etl/steps/data/explorers/owid/2021/food_explorer.py
- etl/steps/data/garden/ihme_gbd/2019/gbd_tools.py
- etl/steps/data/garden/who/2022-07-17/who_vaccination.py
- etl/steps/data/meadow/oecd/2016-06-01/regional_wellbeing.py
Fix some warnings that are popping up in #analytics-errors.
> fix: fix some ETL warnings

- .mypy.ini
- etl/command.py
- etl/prune.py
- etl/run_python_step.py
- poetry.lock
- pyproject.toml
- tests/test_steps.py
Fix for error `etl/steps/data/meadow/irena/2022-10-20/renewable_power_generation_costs.py:15: error: Module "shared" has no attribute "CURRENT_DIR"`
> fix(mypy): fix mypy error when importing shared.py module

- etl/data_helpers.py
- etl/steps/data/garden/owid/latest/key_indicators/table_population.py
- etl/steps/grapher/worldbank_wdi/2022-05-26/wdi.py
Add source to WDI dataset to fix push to grapher. Also fix some warnings.
> fix(wdi): add source to wdi dataset

- dag_files/dag_energy.yml
- etl/steps/data/garden/irena/2022-10-20/renewable_power_generation_costs.countries.json
- etl/steps/data/garden/irena/2022-10-20/renewable_power_generation_costs.meta.yml
- etl/steps/data/garden/irena/2022-10-20/renewable_power_generation_costs.py
- etl/steps/data/meadow/irena/2022-10-20/renewable_power_generation_costs.py
- etl/steps/grapher/irena/2022-10-20/renewable_power_generation_costs.py
Add meadow, garden and grapher steps for IRENA dataset on levelized costs of energy.
> Include additional irena costs

- etl/steps/data/garden/un/2022-07-11/un_wpp/un_wpp.meta.yml
> fix(unwpp): deaths short unit

- etl/steps/data/grapher/faostat/2022-05-17/shared.py
Fixes https://github.com/owid/etl/issues/606
> fix(faostat): Fix wrong path to grapher steps folder

- etl/steps/data/garden/emissions/2022-11-11/owid_co2.py
- etl/steps/data/garden/gcp/2022-11-11/global_carbon_budget.meta.yml
- etl/steps/data/garden/gcp/2022-11-11/global_carbon_budget.py
- etl/steps/data/grapher/gcp/2022-11-11/global_carbon_budget.py
Minor issues solved in the GCB dataset:
* Fixed wrong unit in variable metadata.
* Removed rows of spurious zeros (for example, in the original data, total emissions were zero when all individual sources of emissions were nan).
* Then, in the grapher step, ensured that all countries have data for all years (so that stacked area charts work well).
* Included original region aggregates that were given in the raw data files, for comparison.
* Added sanity checks.
> Improve emissions data

- walkthrough/garden.py
- walkthrough/grapher.py
- walkthrough/meadow.py
- walkthrough/meadow_cookiecutter/cookiecutter.json
- walkthrough/walden.py
- walkthrough/walden_cookiecutter/cookiecutter.json
- walkthrough/walden_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
Add support for private datasets in walkthrough by adding checkbox "Is private" to all steps and change instructions to basically reflect steps described by Pablo [here](https://github.com/owid/etl/issues/618).
> feature(walkthrough): support private datasets

- poetry.lock
- pyproject.toml
Fix rev/tag and update to datautils without setuptools.
> chore: update owid-datautils

- etl/steps/open_numbers.py
* repack open-numbers in-place to reduce memory footprint
* ~pyarrow engine for faster (5x) csv loading~ (was raising random errors)
> fix(open_numbers): repack in place to reduce memory footprint

- dag.yml
- dag_files/dag_demography.yml
- etl/steps/data/garden/country_profile/2022/overview.py
Just some small changes to the country profile namespace - mostly updating to include the new life expectancy OMM and replacing the backport.
> Feat(country_prof): updating country profiles to include new life expectancy OMM and fix to output only countries with data

- etl/command.py
- etl/snapshot.py
- etl/steps/__init__.py
- poetry.lock
- pyproject.toml
ETL runs were taking way more than needed (tens of seconds) which is annoying during development. I've optimised couple of parts which reduces ETL runtime to seconds for smaller subsets of DAG and to reasonable time when running full ETL.
> enhance(etl): improve ETL performance

- etl/compare.py
The `compare etl-catalog` tool does not accept a `version` argument, which makes it unusable if there is more than one version of the dataset you want to compare with.
This PR adds an optional `version` argument.
I've also created [this issue](https://github.com/owid/owid-catalog-py/issues/74), given that, ideally, we should use `find_latest` (which does not exist) instead of `find_one`, and assume we always want to compare with the latest version of a dataset.
> feat(compare): Let etl-compare specify version

- etl/steps/data/garden/faostat/2022-05-17/shared.py
- poetry.lock
- pyproject.toml
The problem with pathspec and DVC seems to be fixed. Unpin pathspec and upgrade DVC.
> fix(packaging): unpin pathspec and upgrade dvc

- etl/chart_revision_suggester.py
- walkthrough/charts.py
- walkthrough/grapher.py
- walkthrough/utils.py
Fixes navigation in `walkthrough charts` step when all (or some) variables are paired automatically.
This was surfaced by @paarriagadap, thanks!
> fix(walkthrough): nav if all variables auto paired

- etl/steps/data/garden/un/2022-11-29/undp_hdr.meta.yml
Remove unnecessary annotation.
> enhance(undp_hdr): remove annotation

- etl/chart_revision_suggester.py
- walkthrough/charts.py
* Fixes https://github.com/owid/etl/issues/721
* Uses `from rich_click.rich_command.RichCommand` in `etl-chart-suggester`.
* Slight improvement on modularity of `etl.chart_revision_suggester`. Now `walkthrough charts` displays a processing bar instead of a loading circle.
> enhance(walkthrough charts)

- dag.yml
- etl/compare.py
- etl/steps/data/grapher/fasttrack/2022-02-28/nuclear_warhead_inventories.meta.yml
- etl/steps/data/grapher/fasttrack/2022-11-29/ai_index.meta.yml
- fasttrack/cli.py
- fasttrack/instructions.md
- fasttrack/styles.css
- snapshots/fasttrack/2022-02-28/nuclear_warhead_inventories.csv.dvc
- snapshots/fasttrack/2022-11-29/ai_index.csv.dvc
The main feature is comparison against existing dataset (showing differences in data and metadata). It also contains couple of refactorings and small improvements.
Rather than reviewing code itself, it makes more sense to give it a try:
1. Copy this [Google spreadsheet](https://docs.google.com/spreadsheets/d/1ReTohcxpo-dRvnXFzYG4N0YT-HoXh3b6AbG-qIaGTLI/edit#gid=409110122)
2. Change some data point / points and **dataset title** in the sheet
3. Run `fasttrack`
4. Get url for CSV from the sheet (see Instructions in fasttrack) and submit form
5. Check out comparison with the existing dataset
6. When it asks "Do you want to continue and create the dataset in GrapherDB?", hit "Cancel"
> feature(fasttrack): compare with existing dataset

- etl/chart_revision_suggester.py
- walkthrough/charts.md
- walkthrough/charts.py
- walkthrough/charts.styles.css
Same functionality, just minor improvements:
- Improved intro text
- Added link with more information on text similarity functions.
- Preview affected charts before submitting revisions to Grapher.
- Add variable preview: This includes variable description, timespan, units, and coverage (when available). This is made available using `put_collapsable` from `pywebio`.
- Add CSS style file
> enhance(walkthrough-charts)

- etl/datadiff.py
- etl/grapher_helpers.py
- fasttrack/cli.py
- fasttrack/sheets.py
- poetry.lock
- pyproject.toml
* remove `deepdiff` from datadiff and replace it with `difflib`
* better error for missing sources in fast-track
> enhance(fast-track): minor updates

- dag/archive/main.yml
- dag/main.yml
Just a quick PR to check I am archiving correctly
> refactor(dag): moving old unodc homicide data to archive dag

- etl/helpers.py
Let `PathFinder` work for explorers steps.
> fix(helpers): Let PathFinder work for explorers steps

- dag/main.yml
- etl/steps/data/explorers/wid/2023-01-27/world_inequality_database.py
- etl/steps/data/garden/wid/2023-01-27/issues.py
- etl/steps/data/garden/wid/2023-01-27/shared.py
- etl/steps/data/garden/wid/2023-01-27/world_inequality_database.meta.yml
- etl/steps/data/garden/wid/2023-01-27/world_inequality_database.py
- etl/steps/data/grapher/wid/2023-01-27/world_inequality_database.py
- etl/steps/data/meadow/wid/2023-01-27/world_inequality_database.py
- snapshots/wid/2023-01-27/wid_indices.do
- snapshots/wid/2023-01-27/world_inequality_database.csv.dvc
- snapshots/wid/2023-01-27/world_inequality_database.py
Create World Inequality Database dataset from a file extracted from the `wid` command in Stata.
> Create World Inequality Database dataset

- etl/steps/data/grapher/who/2022-09-30/ghe.py
For our projection on the Suicide topic page, we need more granularity for the suicide rates. That is, we need the metric for different age groups.
This PR includes all age groups for metrics with `cause="Self-harm"`.
The Grapher step takes a while to run for this one. I am currently running it, and the dataset should be available soonish on [staging](https://staging.owid.cloud/admin/datasets/5790).
> enhance(ghe): dimensions for cause=self-harm

- etl/data_helpers/population.py
- etl/steps/data/garden/un/2022-07-11/un_wpp/__init__.py
- etl/steps/data/garden/un/2022-07-11/un_wpp/population.py
This PR adds a function `add_population` to module `etl.data_helpers.population` which helps add population estimates (medium variant) to a table with multiple dimensions.
It has population estimates by country, year, sex (all/m/f), age group (any can be formed).
> enhance(population): tools to add population by dimension

- etl/grapher_helpers.py
- etl/helpers.py
- etl/steps/data/garden/bp/2022-12-28/energy_mix.meta.yml
- etl/steps/data/garden/bp/2022-12-28/statistical_review.meta.yml
- etl/steps/data/garden/bp/2023-02-20/energy_mix.meta.yml
- etl/steps/data/garden/health/2022-12-28/deaths_karlinsky.meta.yml
- etl/steps/data/garden/lis/2023-01-18/luxembourg_income_study.meta.yml
- etl/steps/data/garden/owid/latest/key_indicators/key_indicators.meta.yml
- etl/steps/data/garden/papers/2023-01-04/nemet_2009.meta.yml
- etl/steps/data/grapher/bls/2023-03-10/us_consumer_prices.py
- etl/steps/data/grapher/technology/2023-03-06/mobile_money.py
- etl/steps/data/meadow/democracy/2023-03-02/vdem.meta.yml
- etl/steps/data/meadow/democracy/2023-03-02/vdem.py
- schemas/dataset-schema.json
- walkthrough/grapher_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
Minor improvements to ETL that accumulated this week.
> Metadata cleanup and other minor improvements

- dag/excess_mortality.yml
- etl/steps/data/garden/excess_mortality/latest/excess_mortality/excess_mortality.meta.yml
- etl/steps/data/garden/excess_mortality/latest/hmd_stmf.meta.yml
- etl/steps/data/garden/excess_mortality/latest/wmd.meta.yml
- etl/steps/data/garden/excess_mortality/latest/xm_karlinsky_kobak.meta.yml
- snapshots/excess_mortality/latest/hmd_stmf.csv.dvc
- snapshots/excess_mortality/latest/hmd_stmf.py
- snapshots/excess_mortality/latest/wmd.csv.dvc
- snapshots/excess_mortality/latest/wmd.py
- snapshots/excess_mortality/latest/xm_karlinsky_kobak.ages.csv.dvc
- snapshots/excess_mortality/latest/xm_karlinsky_kobak.csv.dvc
- snapshots/excess_mortality/latest/xm_karlinsky_kobak.py
Update Excess mortality data:
- New snapshot version: `latest` (no more versions will be created)
- Updated `version`, `date_accessed` and `publication_date` fields in snapshot and garden metadata.
> data(excess-mortality): update

- etl/steps/data/explorers/poverty_inequality/2023-03-01/poverty_inequality.py
- etl/steps/data/garden/wid/2023-01-27/world_inequality_database.meta.yml
- snapshots/wid/2023-01-27/world_inequality_database.csv.dvc
Minor addition, doesn't change steps. For [this article](https://github.com/owid/owid-issues/issues/983)
> Add bottom 50% from PIP and mod WID metadata

- etl/steps/data/garden/who/2023-03-09/gho_suicides.meta.yml
- etl/steps/data/garden/who/2023-03-09/gho_suicides.py
- etl/steps/data/grapher/who/2023-03-09/gho_suicides.py
Add the suicide death rate ratio between males and females, using WHO GHO data.
This dataset has data available since 2000 and 2019.
> enhance(gho): suicide death rate

- etl/chart_revision/revision.py
- etl/chart_revision/variables.py
This PR solves https://github.com/owid/etl/issues/867.
> fix(chart_revision): sorting in barcharts

- dag/demography.yml
- etl/steps/data/garden/demography/2022-12-08/population/__init__.py
- etl/steps/data/garden/demography/2022-12-08/population/meta.yml
- etl/steps/data/grapher/demography/2023-03-30/population.py
Add a step to generate Grapher dataset for our Population OMM.
- This dataset was already half-way there (it was already in Garden).
- Currently, in Grapher, we use the variables from the "Key Indicator" dataset. This is not ideal, as we may deprecate this dataset in the future.
- This new dataset focuses on population metrics.
> data(population): grapher dataset

- etl/steps/data/grapher/un/2022-07-11/un_wpp.py
> docs(population): change source name in WPP

- backport/datasync/data_metadata.py
Edge case of datasync for empty variables.
> fix(datasync): empty variables

- dag/agriculture.yml
- dag/main.yml
- dag/papers.yml
- etl/steps/data/garden/agriculture/2023-04-20/long_term_wheat_yields.meta.yml
- etl/steps/data/garden/agriculture/2023-04-20/long_term_wheat_yields.py
- etl/steps/data/garden/papers/2023-04-20/bayliss_smith_wanmali_1984.countries.json
- etl/steps/data/garden/papers/2023-04-20/bayliss_smith_wanmali_1984.meta.yml
- etl/steps/data/garden/papers/2023-04-20/bayliss_smith_wanmali_1984.py
- etl/steps/data/grapher/agriculture/2023-04-20/long_term_wheat_yields.py
- etl/steps/data/meadow/papers/2023-04-20/bayliss_smith_wanmali_1984.py
- snapshots/papers/2023-04-20/bayliss_smith_wanmali_1984.csv.dvc
- snapshots/papers/2023-04-20/bayliss_smith_wanmali_1984.py
Add data on long-term yields extracted from a book (added to the `papers` namespace) and combine it with FAOSTAT QCL data.
> Add long run wheat yield data

- etl/steps/data/garden/health/2023-04-18/wgm_mental_health.py
- etl/steps/data/garden/health/2023-04-25/wgm_2018.py
Improve variable names, so that they also contain the questionnaire identifier
> enhance(wgm): add questionnaire codes to variable names

- etl/steps/data/garden/demography/2023-03-31/population/meta.yml
Version in metadata was wrong.
> fix(population): version in metadata

- etl/steps/data/garden/health/2023-04-25/wgm_2018.py
> fix(wgm): assert

- dag/archive/emissions.yml
- dag/archive/energy.yml
- dag/archive/fasttrack.yml
- dag/archive/main.yml
- dag/emissions.yml
- dag/energy.yml
- dag/fasttrack.yml
- dag/main.yml
Update `country_profile` dependency on global carbon budget (to use the latest version), and archive unused steps.
> Archive unused steps and update country profile dependency

- poetry.lock
- pyproject.toml
Fixes https://github.com/owid/etl/issues/1091
> :honeybee: update pywebio

- docs/getting-started/working-environment.md
Updates to documentation from workshop
> 📜 add library dependency

- etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.meta.yml
- etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.py
Add one variable to the EPR dataset. Minor update.
> Add share not belonging to an ethnical group

- etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.meta.yml
- etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.py
Minor edit to an already reviewed dataset
> Add aggregations for binary vars (Ethnic Power Relations dataset)

- etl/datadiff.py
- etl/steps/data/garden/regions/2023-01-01/regions.py
- etl/tempcompare.py
- tests/test_tempcompare.py
* improve data-diff by printing info about differing columns
* fix iso2 for Namibia - `NA` was loaded as NaN by pandas
> :sparkles: Improve data-diff

- Makefile
- etl/to_graphviz.py
Wanted to show dependency graph so I fixed a few things to make it work and look nicer. Still could use some love.
> :sparkles: improve dependency graph

- etl/paths.py
- walkthrough/utils.py
The path for `REGIONS_LATEST_VERSION` was not correctly set. Maybe related to the recent countries_region.csv deprecation.
> 🐛 walkthrough: wrong regions path

- etl/steps/data/garden/ihme_gbd/2023-05-15/gbd_mental_health_prevalence_rate.meta.yml
Correct typos in IHME GBD mental health dataset.
> 📊 gbd-mental-health: fix metadata

- etl/chart_revision/v2/schema.py
- etl/chart_revision/v2/updaters/variable_update.py
minor tools to fix obvious schema invalid syntax
> 🐛 schema: correct obvious schema errors

- .gitignore
- .vscode/settings.json
Add more defaults that could be useful for new hires
* format on save
* isort on save
* enable linting
> :honeybee: set default VSCode settings

- etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.meta.yml
- etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.py
Minor add to the Ethnic Power Relations dataset
> Add population vars to Ethnic Power Relations dataset

- etl/steps/data/garden/eth/2023-03-15/ethnic_power_relations.py
There is currently a problem when I try to run the steps for `ethnic_power_relations`. It is related to creating and index for country and year, so for now I have this commented. Will uncomment when this is fixed.
> Comment `set_index` to make `ethnic_power_relations` work

- etl/steps/data/meadow/democracy/2023-03-02/vdem.meta.yml
> Change metadata on V-Dem vars

- dag/agriculture.yml
- etl/steps/data/explorers/agriculture/2023-05-26/crop_yields.py
- etl/steps/data/garden/agriculture/2023-05-26/attainable_yields.py
- etl/steps/data/garden/papers/2023-05-26/mueller_et_al_2012.countries.json
- etl/steps/data/garden/papers/2023-05-26/mueller_et_al_2012.py
- etl/steps/data/meadow/papers/2023-05-26/mueller_et_al_2012.py
Improve attainable yields step and create crop yields explorers step.
> Create crop yields explorers step

- etl/steps/data/garden/faostat/2023-02-22/detected_anomalies.py
Add new detected anomalies to FAOSTAT QCL.
Fixes https://github.com/owid/owid-issues/issues/1071
> Add new detected anomalies to FAOSTAT QCL

- etl/steps/data/explorers/owid/2021/food_explorer.py
- etl/steps/data/explorers/owid/2021/food_explorer.regions.json
- etl/steps/data/garden/faostat/2022-05-17/detected_outliers.json
- etl/steps/data/garden/faostat/2022-05-17/shared.py
- etl/steps/data/garden/faostat/2023-02-22/faostat_fbsc.py
- etl/steps/data/garden/faostat/2023-02-22/shared.py
- etl/steps/data/garden/owid/latest/key_indicators/table_population.py
- etl/steps/data/garden/regions/2023-01-01/migration.py
This is causing issues in grapher.
> :bug: rename Eritrea and Ethiopia to Ethiopia (former) in faostat

- etl/steps/data/garden/lis/2023-01-18/luxembourg_income_study.meta.yml
- etl/steps/data/garden/lis/2023-01-18/shared.py
- snapshots/lis/2023-01-18/lis_abs_poverty.csv.dvc
- snapshots/lis/2023-01-18/lis_distribution.csv.dvc
- snapshots/lis/2023-01-18/lis_keyvars.csv.dvc
- snapshots/lis/2023-01-18/lissy_ineq_pov.do
Minor modification, introducing the $2 and $5 poverty lines from the LISSY command in Stata. I extract the updated data and upload it to the ETL
> Add poverty lines for LIS

- etl/steps/data/garden/health/2023-04-18/wgm_mental_health.meta.yml
- etl/steps/data/garden/health/2023-04-25/wgm_2018.meta.yml
`short_unit` was missing. Reported it in https://github.com/owid/owid-issues/issues/1090
> 📊 wgm: add short_unit

- dag/main.yml
- dag/space.yml
- etl/steps/data/garden/space/2023-06-09/exoplanets.meta.yml
- etl/steps/data/garden/space/2023-06-09/exoplanets.py
- etl/steps/data/grapher/space/2023-06-09/exoplanets.py
- etl/steps/data/meadow/space/2023-06-09/exoplanets.py
- snapshots/space/2023-06-09/exoplanets.csv.dvc
- snapshots/space/2023-06-09/exoplanets.py
This migrates the [previous Python script](https://github.com/owid/notebooks/tree/main/EdouardMathieu/exoplanets) to the ETL, to import data from the NASA Exoplanet Archive.
> Add Exoplanets (NASA, 2023)

- etl/steps/data/garden/who/2022-09-30/ghe.py
Adding regional aggregates for the calculated age-groups
> fix(ghe): regional aggregates for new age-groups

- dag/agriculture.yml
- dag/archive/agriculture.yml
- dag/archive/main.yml
Create a new archive dag for agriculture steps, and move some old agriculture steps from the main dag to the archive.
> Archive old steps

- dag/space.yml
- etl/steps/data/garden/space/2023-06-09/space_track.meta.yml
- etl/steps/data/garden/space/2023-06-09/space_track.py
- etl/steps/data/grapher/space/2023-06-09/space_track.py
- etl/steps/data/meadow/space/2023-06-09/space_track.py
- snapshots/space/2023-06-09/space_track.csv.dvc
- snapshots/space/2023-06-09/space_track.py
This migrates the [previous Python script](https://github.com/owid/notebooks/tree/main/EdouardMathieu/space_track) to the ETL, to import data from Space-Track.org
> Add Number of objects in space (United States Space Force, 2023)

- etl/steps/data/garden/oecd/2023-05-19/co2_air_transport.meta.yml
sorry, need to fix this as I didn't realised it would show up in sources tab
> fixed descriptions

- etl/steps/data/garden/health/2023-04-18/wgm_mental_health.meta.yml
- etl/steps/data/garden/health/2023-04-25/wgm_2018.meta.yml
adds link to full questionnaire based on team feedback.
> 📊 wgm: add links to complete questionnaire

- etl/steps/data/garden/health/2023-04-18/wgm_mental_health.meta.yml
- etl/steps/data/garden/health/2023-04-25/wgm_2018.meta.yml
- etl/steps/data/garden/ihme_gbd/2023-05-15/gbd_mental_health_prevalence_rate.meta.yml
Minor improvements in the metadata of WGM and IHME datasets.
> 📊 mental-health: metadata tweaks

- dag/health.yml
- etl/steps/data/garden/ihme_gbd/2023-06-14/prevalence_dalys_world.meta.yml
- etl/steps/data/garden/ihme_gbd/2023-06-14/prevalence_dalys_world.py
- etl/steps/data/grapher/ihme_gbd/2023-06-14/prevalence_dalys_world.py
Adding a new custom dataset so we can create a specific chart where we show DALYs and prevalence for different diseases for the World.
more context here: https://owid.slack.com/archives/C04VBQ00HQR/p1686749360343129
> 📊 ihme: custom dataset for a chart (using causes as entities)

- etl/steps/data/garden/lis/2023-01-18/luxembourg_income_study.meta.yml
- snapshots/lis/2023-01-18/lis_abs_poverty.csv.dvc
- snapshots/lis/2023-01-18/lis_distribution.csv.dvc
- snapshots/lis/2023-01-18/lis_keyvars.csv.dvc
Quarterly update of Luxembourg Income Study. [Details here](https://www.lisdatacenter.org/news-and-events/2023-summer-data-splash/). 
For the [new inequality topic page](https://github.com/owid/owid-issues/issues/784)
> LIS 2023 Summer Data Splash update

- poetry.lock
- pyproject.toml
- tests/data_helpers/test_geo.py
This might help with some performance issues and kernel crashes.
> :honeybee: upgrade notebook to version 7

- etl/datadiff.py
- etl/steps/data/garden/war/2023-01-18/shared.py
- etl/steps/data/meadow/un/2022-07-11/un_wpp.py
* fix datasets that were producing non-determinstic output
* fix datadiff
> :bug: make datasets determinstic

- etl/steps/data/garden/dummy/2020-01-01/dummy.py
- etl/steps/data/meadow/dummy/2020-01-01/dummy.py
- snapshots/dummy/2020-01-01/dummy.csv.dvc
- walkthrough/garden_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
- walkthrough/meadow_cookiecutter/{{cookiecutter.directory_name}}/{{cookiecutter.short_name}}.py
I feel like no one's using it (and those wanting to use it know how to import it), so there's no point in having it in walkthrough. We print time taken for every step and when it started, so these logs are kinda useless.
> :hammer: remove logging from walkthrough

- etl/steps/data/garden/wid/2023-01-27/shared.py
Changed the decimal points for monetary values from 1 to 2
> fix: decimal places for monetary values on WID

- etl/steps/data/garden/tourism/2023-05-05/unwto.meta.yml
hi @Marigold ! sorry for so many pull requests but my build just [failed](https://buildkite.com/our-world-in-data/etl-deploy-master/builds/1696#01890cfa-1210-4177-8136-58f5b3d4bc95). I had an error where the variable names didn't correspond correctly and now it's throwing an error - I am adding population to all of them to see if this will fix it?
> trying a fix

- dag/main.yml
- etl/steps/data/explorers/wid/2023-01-27/world_inequality_database.py
- etl/steps/data/garden/wid/2023-01-27/shared.py
- etl/steps/data/garden/wid/2023-01-27/world_inequality_database.py
- etl/steps/data/meadow/wid/2023-01-27/world_inequality_database.py
- snapshots/wid/2023-01-27/wid_indices.do
- snapshots/wid/2023-01-27/world_inequality_database_with_extrapolations.csv.dvc
- snapshots/wid/2023-01-27/world_inequality_database_with_extrapolations.py
Include extrapolations to create shares using the Is projection option in Grapher, like:
As part of the [Economic inequality topic page](https://github.com/owid/owid-issues/issues/784)
> Include extrapolations on the World Inequality Database

- etl/steps/data/garden/energy_institute/2023-06-26/statistical_review_of_world_energy.py
Fixed another small bug affecting regions in the main Statistical Review garden table.
> fix(energy_institute): Fix table has no short name issue

- etl/steps/data/garden/energy_institute/2023-06-26/statistical_review_of_world_energy.meta.yml
- etl/steps/data/grapher/energy_institute/2023-06-26/statistical_review_of_world_energy.meta.yml
- etl/steps/data/grapher/energy_institute/2023-06-26/statistical_review_of_world_energy.py
Improve variable titles and units in the Statistical Review dataset, and remove zero_filled variables.
@paarriagadap would you mind checking the FASTT of these charts on fossil fuel prices?
* https://owid.cloud/admin/charts/851/edit
* https://owid.cloud/admin/charts/1369/edit
* https://owid.cloud/admin/charts/653/edit
* https://owid.cloud/admin/charts/1370/edit
* https://owid.cloud/admin/charts/652/edit
* https://owid.cloud/admin/charts/1368/edit
Thanks!
> Minor improvements on statistical review

- etl/steps/data/garden/energy_institute/2023-06-26/statistical_review_of_world_energy.py
Fix efficiency factors, that were accidentally also included when doing aggregates (this should not affect any data except for those factors).
> fix(energy_institute): Fix efficiency factors

- etl/steps/data/garden/artificial_intelligence/2023-06-14/ai_national_strategy.py
making sure it's NaN if a strategy has already been released
> National strategy on AI fix

- etl/steps/data/garden/war/2023-06-22/ucdp.meta.yml
- etl/steps/data/garden/war/2023-06-22/ucdp.py
Fixing bugs and issues in the UCDP dataset raised by Bastian:
- Improve metadata
- Add zeroes (instead of NaNs) where applicable
- Correct a bug that was miss-calculating the number of new conflicts by type.
> 🐛 ucdp: data fixes

- etl/steps/data/garden/energy/2023-07-10/uk_historical_electricity.py
- etl/steps/data/grapher/energy/2023-07-10/uk_historical_electricity.py
Remove zero-filled variables and fix missing sources in UK historical electricity dataset.
> Fix issues in UK historical electricity dataset

- lib/catalog/owid/catalog/variables.py
- lib/catalog/poetry.lock
- lib/catalog/pyproject.toml
- poetry.lock
- pyproject.toml
* sync etl and catalog libraries to fix type errors
* update poetry locks
> :honeybee: update dependencies of etl and catalog

- etl/steps/data/meadow/aviation_safety_network/2022-10-12/aviation_statistics.py
Fix the failing nightly ETL build.
> :bug: load aviation statistics from snapshot rather than from walden

- etl/steps/data/garden/wb/2023-07-24/food_prices_for_nutrition.meta.yml
- etl/steps/data/garden/wb/2023-07-24/food_prices_for_nutrition.py
Convert share variables into percentages, and other minor changes in variable descriptions.
> Minor improvements in metadata and units in food prices for nutrition dataset

- etl/steps/data/garden/wb/2023-07-24/food_prices_for_nutrition.meta.yml
- etl/steps/data/grapher/usda_ers/2023-06-07/food_expenditure.meta.yml
- etl/steps/data/grapher/usda_ers/2023-06-07/food_expenditure.py
- etl/steps/data/grapher/wb/2023-07-24/food_prices_for_nutrition.meta.yml
- snapshots/papers/2023-06-07/commodity_prices.xlsx.dvc
- snapshots/wb/2023-07-24/food_prices_for_nutrition.csv.dvc
Several minor improvements on metadata of datasets related to food prices and expenditures.
> Improve metadata on food prices datasets

- etl/steps/data/garden/wvs/2023-03-08/wvs_trust.meta.yml
- etl/steps/data/garden/wvs/2023-03-08/wvs_trust.py
- etl/steps/data/meadow/wvs/2023-03-08/wvs_trust.py
- snapshots/wvs/2023-03-08/wvs_trust.csv.dvc
- snapshots/wvs/2023-03-08/wvs_trust.do
This update includes all the confidence and trust variables available in the World Values Survey
> Include new trust variables from World Values Survey

- etl/steps/data/garden/war/2023-06-22/ucdp.py
- Improve and add docstrings
- Improve function names
- Add new function: `fix_extrasystemic_entries`, to help deal with `conflict_type=extrasystemic` conflicts after 1989 (prior to this PR values for these would be missing, with this PR we just zero-fill values after 1989(
> 🐛 war.ucdp: fix missing values

- etl/steps/data/garden/artificial_intelligence/2023-06-21/epoch.meta.yml
- etl/steps/data/garden/artificial_intelligence/2023-06-21/epoch_aggregates.meta.yml
- etl/steps/data/meadow/artificial_intelligence/2023-06-21/epoch.py
- snapshots/artificial_intelligence/2023-06-21/epoch.csv.dvc
- snapshots/artificial_intelligence/2023-06-21/epoch.py
changed to direct download, deleted some variables that no longer exist
> updating EPOCH dataset

- etl/steps/data/grapher/animal_welfare/2023-08-01/uk_egg_statistics.meta.yml
- snapshots/animal_welfare/2023-08-01/uk_egg_statistics.ods.dvc
Minor changes in metadata of UK egg statistics.
> Minor changes in metadata of UK egg statistics

- etl/steps/data/garden/artificial_intelligence/2023-06-21/epoch.meta.yml
- etl/steps/data/garden/terrorism/2023-07-20/global_terrorism_database.meta.yml
- etl/steps/data/garden/terrorism/2023-07-20/global_terrorism_database.py
per 100,000 people instead of per capita
> terrorism death rate

- etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.meta.yml
- snapshots/biodiversity/2023-01-11/cherry_blossom.csv.dvc
- snapshots/ggdc/2020-10-01/ggdc_maddison.xlsx.dvc
I made some small changes in the snapshot/garden metadata files for consistency.
> Minor changes to new metadata examples

- etl/steps/data/garden/aviation_safety_network/2022-10-14/aviation_statistics.py
- etl/steps/data/meadow/aviation_safety_network/2022-10-14/aviation_statistics.py
> :bug: fix aviation dataset

- etl/steps/data/garden/terrorism/2023-07-20/global_terrorism_database.meta.yml
- etl/steps/data/garden/terrorism/2023-07-20/global_terrorism_database.py
number of killed, wounded and attacks; got rid of casualties (not used)
> added regional data for terrorism 

- etl/steps/data/grapher/who/2023-08-04/icd_codes.py
Also trying to force it to run
> 🧹  Cleaning up ICD code

- etl/steps/data/garden/war/2023-07-18/cow.meta.yml
- etl/steps/data/garden/war/2023-07-20/brecke.meta.yml
- etl/steps/data/garden/war/2023-07-21/prio_v31.meta.yml
- etl/steps/data/garden/war/2023-08-05/cow_mid.meta.yml
- etl/steps/data/grapher/war/2023-06-26/ucdp.py
- etl/steps/data/grapher/war/2023-07-14/mars.py
- etl/steps/data/grapher/war/2023-07-20/brecke.py
- etl/steps/data/grapher/war/2023-07-21/prio_v31.py
- etl/steps/data/grapher/war/2023-07-26/cow.py
Minor tweaks. The primary thing is documenting the regions used by the source.
Also, for the sake of reducing noise in the explorer, I'll be removing the suffixes from regions (e.g. `(COW)` or `(UCDP)`). Leaving these in Garden though.
> ✨ war: improve metadata fields

- etl/steps/data/garden/excess_mortality/latest/excess_mortality_economist/__init__.py
- etl/steps/data/grapher/excess_mortality/latest/excess_mortality.py
- etl/steps/data/grapher/excess_mortality/latest/excess_mortality_economist.py
- etl/steps/data/meadow/excess_mortality/latest/excess_mortality_economist.py
Trying to fix https://buildkite.com/our-world-in-data/etl-deploy-master/builds/1998
> set indices in XM dataets

- backport/backport.py
- backport/datasync/data_metadata.py
- docs/old-readme.md
- etl/compare.py
- etl/grapher_import.py
- etl/grapher_model.py
- walkthrough/charts_v2/variable_config.py
Remove leftover use of `data_values` table from ETL. Should be merged after https://github.com/owid/owid-grapher/pull/1923.
> :hammer: deprecate data_values table

- dag/war.yml
- etl/steps/data/meadow/war/2023-06-07/cow.py
- snapshots/war/2023-03-14/cow.extra_state.csv.dvc
- snapshots/war/2023-03-14/cow.inter_state.csv.dvc
- snapshots/war/2023-03-14/cow.inter_state_dyadic.csv.dvc
- snapshots/war/2023-03-14/cow.inter_state_dyadic.zip.dvc
- snapshots/war/2023-03-14/cow.intra_state.zip.dvc
- snapshots/war/2023-03-14/cow.non_state.csv.dvc
- snapshots/war/2023-03-14/cow.py
Adding an extra table to a meadow dataset (only snapshot & meadow steps).
> 📊 war: add interstate dyadic

- etl/helpers.py
- etl/steps/data/garden/dummy/2020-01-01/dummy.py
- etl/steps/data/grapher/dummy/2020-01-01/dummy.py
- etl/steps/data/meadow/dummy/2020-01-01/dummy.py
- snapshots/dummy/2020-01-01/dummy.csv.dvc
- walkthrough/explorers_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- walkthrough/garden.py
- walkthrough/garden_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- walkthrough/grapher_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- walkthrough/meadow_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- walkthrough/snapshot.py
- walkthrough/utils.py
* Update walkthrough to use `check_variables_metadata=True` and `paths.load_dependency` and owid processing functions
> :hammer: update walkthrough to use latest best practices

- backport/datasync/data_metadata.py
- etl/grapher_import.py
- tests/backport/datasync/test_data_metadata.py
Speed up grapher upsert by about ~20%.
> :sparkles: improve grapher step performance

- schemas/dataset-schema.json
- schemas/definitions.json
- schemas/snapshot-schema.json
> :hammer: DRY schema definitions

- dag/education.yml
- dag/main.yml
- etl/steps/data/garden/artificial_intelligence/2023-07-25/cset.py
- etl/steps/data/garden/education/2023-07-17/education_lee_lee.meta.yml
- etl/steps/data/garden/education/2023-08-14/oecd_education.countries.json
- etl/steps/data/garden/education/2023-08-14/oecd_education.meta.yml
- etl/steps/data/garden/education/2023-08-14/oecd_education.py
- etl/steps/data/garden/wb/2023-07-10/education.py
- etl/steps/data/meadow/education/2023-08-14/oecd_education.py
- snapshots/education/2023-08-14/oecd_education.csv.dvc
- snapshots/education/2023-08-14/oecd_education.py
- snapshots/wb/2023-07-10/education.csv.dvc
moved historical education estimates from OECD to education dag; combined historical literacy and formal education with more recent data
> 🐛 combining historical data and more recent estimates - Education

- etl/steps/data/garden/dummy/2020-01-01/dummy.py
- etl/steps/data/grapher/dummy/2020-01-01/dummy.py
- etl/steps/data/meadow/dummy/2020-01-01/dummy.py
- snapshots/dummy/2020-01-01/dummy.csv.dvc
- walkthrough/explorers_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- walkthrough/garden_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- walkthrough/grapher_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- walkthrough/meadow_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- walkthrough/snapshot.py
- walkthrough/utils.py
* put back `default_metadata`
* use Sources in walkthrough by default (until next Tuesday)
> :hammer: put back default_metadata in walkthrough to propagate DatasetMeta

- apps/walkthrough/explorers.py
- apps/walkthrough/garden.py
- apps/walkthrough/grapher.py
- apps/walkthrough/meadow.py
Fixes https://github.com/owid/etl/issues/1552
> 🐛 walkthrough: add to dag path

- etl/steps/data/garden/education/2023-07-17/education_barro_lee_projections.meta.yml
- etl/steps/data/garden/education/2023-07-17/education_barro_lee_projections.py
- etl/steps/data/garden/education/2023-07-17/education_lee_lee.meta.yml
- etl/steps/data/garden/education/2023-07-17/education_lee_lee.py
- etl/steps/data/garden/education/2023-08-14/oecd_education.meta.yml
- etl/steps/data/garden/wb/2023-07-10/education.py
adding gender ratios for historical and combine enrolment and average years of schooling data
> 📊 Barro Lee datasets: new indicators for gender inequality in education

- apps/walkthrough/snapshot_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.py
- apps/walkthrough/snapshot_origins_cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.py
- apps/wizard/templating/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.py
Let walkthrough and wizard create a snapshot file using a path to a local file.
Fixes https://github.com/owid/etl/issues/1571
> Fix walkthrough and wizard local file issue

- etl/steps/data/garden/lis/2023-08-30/luxembourg_income_study.meta.yml
- etl/steps/data/garden/lis/2023-08-30/luxembourg_income_study.py
- etl/steps/data/grapher/lis/2023-08-30/luxembourg_income_study.py
- etl/steps/data/meadow/lis/2023-08-30/luxembourg_income_study.py
Luxembourg income dataset is missing units for the following columns
```
index_dhci_eq, index_dhci_eq_100, index_dhci_eq_1000, index_dhci_eq_200, index_dhci_eq_2000, index_dhci_eq_215, index_dhci_eq_3000, index_dhci_eq_365, index_dhci_eq_4000, index_dhci_eq_500, index_dhci_eq_685, index_dhci_pc, index_dhci_pc_100, index_dhci_pc_1000, index_dhci_pc_200, index_dhci_pc_2000, index_dhci_pc_215, index_dhci_pc_3000, index_dhci_pc_365, index_dhci_pc_4000, index_dhci_pc_500, index_dhci_pc_685, index_dhi_eq, index_dhi_eq_100, index_dhi_eq_1000, index_dhi_eq_200, index_dhi_eq_2000, index_dhi_eq_215, index_dhi_eq_3000, index_dhi_eq_365, index_dhi_eq_4000, index_dhi_eq_500, index_dhi_eq_685, index_dhi_pc, index_dhi_pc_100, index_dhi_pc_1000, index_dhi_pc_200, index_dhi_pc_2000, index_dhi_pc_215, …
```
> :bug: fix units of luxembourg income study

- apps/wizard/templating/snapshot.py
- schemas/dataset-schema.json
- schemas/definitions.json
- Fixed schema layout
- Display bad examples in help layover
- changed 'mandatory' →  'required'
> Metadata fixes

- apps/wizard/templating/snapshot.py
- schemas/dataset-schema.json
- schemas/definitions.json
_Central issue https://github.com/owid/etl/issues/1566_
Transfer metadata guidelines from [its temporary notion page](https://www.notion.so/owid/Metadata-guidelines-29ca6e19b6f1409ea6826a88dbb18bcc?pvs=4) to ETL.
> Create metadata guidelines

- etl/steps/data/grapher/war/2023-06-26/ucdp.py
- etl/steps/data/grapher/war/2023-07-14/mars.py
- etl/steps/data/grapher/war/2023-07-20/brecke.py
- etl/steps/data/grapher/war/2023-07-21/prio_v31.py
- etl/steps/data/grapher/war/2023-07-26/cow.py
- etl/steps/data/grapher/war/2023-08-08/cow_mid.py
- etl/steps/data/grapher/war/2023-08-15/mie.py
> 💄 tests: imports unused

- apps/wizard/templating/cookiecutter/garden/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.meta.yml
Raised in https://github.com/owid/etl/issues/1563#issuecomment-1713506422
> 🐛 wizard: missing field in metadata

- apps/wizard/templating/garden.py
- apps/wizard/templating/meadow.py
- dag/animal_welfare.yml
- etl/helpers.py
- etl/steps/data/garden/animal_welfare/2023-09-08/fur_laws.meta.yml
- etl/steps/data/garden/animal_welfare/2023-09-08/fur_laws.py
- etl/steps/data/grapher/animal_welfare/2023-09-08/fur_laws.py
- etl/steps/data/meadow/animal_welfare/2023-09-08/fur_laws.py
- snapshots/animal_welfare/2023-09-08/fur_laws.pdf.dvc
- snapshots/animal_welfare/2023-09-08/fur_laws.py
Add steps about data on laws banning fur farming and trading.
Additionally, I made some small changes in a function of etl.helpers, and fixed a bug in wizard.
> Add fur ban data

- apps/wizard/templating/cookiecutter/garden/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.meta.yml
Fixes https://github.com/owid/etl/issues/1563#issuecomment-1713801435
> 📜  fix minor wizard bugs

- apps/wizard/templating/snapshot.py
Fixes https://github.com/owid/etl/issues/1609
> 🐛 wizard: fix key name error

- schemas/dataset-schema.json
minor fixes to the documentation
- display of URL
> fix url display

- etl/steps/data/garden/un/2023-08-16/un_sdg.py
- snapshots/un/2023-08-16/un_sdg.feather.dvc
The UN have pushed some recent data updates, it would be good to have these reflected on OWID, particularly as they include some corrections e.g. for indicator 15.4.2. (Proportion of degraded mountain land (%))
> 📊 UN SDG update - data corrections

- snapshots/animal_welfare/2023-08-01/global_hen_inventory.csv.dvc
- snapshots/animal_welfare/2023-08-01/global_hen_inventory.py
Fixed sources for global hen inventory dataset (after confirming with the author of the dataset).
> fix(animal_welfare): Fix sources for global hen inventory dataset

- .gitignore
- apps/wizard/templating/cookiecutter/garden/{{cookiecutter.namespace}}/{{cookiecutter.version}}/playground.ipynb
- apps/wizard/templating/cookiecutter/garden/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.meta.yml
- apps/wizard/templating/cookiecutter/meadow/{{cookiecutter.namespace}}/{{cookiecutter.version}}/playground.ipynb
- apps/wizard/templating/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.{{cookiecutter.file_extension}}.dvc
- apps/wizard/templating/garden.py
- apps/wizard/templating/grapher.py
- apps/wizard/templating/meadow.py
- apps/wizard/templating/snapshot.py
- apps/wizard/utils.py
- fix links in metadata yaml files (comments)
- run snapshot step from wizard
- add functionality of `--dumy-data` option
- ensure notebooks are generated when "Generate playground notebook" is checked
> 🐛 wizard: fix some issues

- dag/animal_welfare.yml
- etl/steps/data/garden/animal_welfare/2023-08-14/number_of_farmed_fish.meta.yml
- etl/steps/data/garden/animal_welfare/2023-08-14/number_of_farmed_fish.py
- etl/steps/data/garden/animal_welfare/2023-08-15/number_of_farmed_decapod_crustaceans.meta.yml
- etl/steps/data/garden/animal_welfare/2023-08-15/number_of_farmed_decapod_crustaceans.py
- etl/steps/data/garden/animal_welfare/2023-08-16/number_of_wild_fish_killed_for_food.meta.yml
- etl/steps/data/garden/animal_welfare/2023-08-16/number_of_wild_fish_killed_for_food.py
Add per capita indicators to Fishcount datasets.
> Add per capita indicators to Fishcount data

- etl/steps/data/garden/wb/2023-07-10/education.py
- etl/steps/data/garden/wb/2023-07-10/shared.py
only for harmonized learning scores and learning adjusted years of schooling
> 🎉 adding regional aggregates population weighted means

- apps/wizard/app.py
- apps/wizard/templating/cookiecutter/snapshot/{{cookiecutter.namespace}}/{{cookiecutter.snapshot_version}}/{{cookiecutter.short_name}}.{{cookiecutter.file_extension}}.dvc
- apps/wizard/templating/snapshot.py
> 🐛 wizard: metadata in snapshot, add spinner, etl-wizard entry page

- etl/steps/data/garden/animal_welfare/2023-08-14/number_of_farmed_fish.meta.yml
- etl/steps/data/garden/animal_welfare/2023-08-15/number_of_farmed_decapod_crustaceans.meta.yml
- etl/steps/data/garden/animal_welfare/2023-08-16/number_of_wild_fish_killed_for_food.meta.yml
Improve subtitles and footnotes following the advice by Mood et al.
> Enhance(animal_welfare): Improve fishcount metadata

- etl/steps/data/garden/demography/2023-03-31/population/__init__.py
- etl/steps/data/garden/demography/2023-03-31/population/population.meta.yml
- etl/steps/data/garden/demography/2023-06-12/population_density.py
- etl/steps/data/grapher/demography/2023-03-31/population.py
> Improve population metadata

- etl/steps/data/grapher/animal_welfare/2023-09-01/chick_culling_laws.py
- snapshots/animal_welfare/2023-09-01/chick_culling_laws.csv.dvc
- snapshots/animal_welfare/2023-09-01/chick_culling_laws.py
Rephrase "Banned but not yet effective" -> "Banned but not yet in effect".
> enhance(animal_welfare): Rephrase chick culling laws labels

- lib/catalog/owid/catalog/variables.py
- lib/catalog/tests/test_variables.py
Improve the logic of display and presentation propagation on division operations.
I applied the analogous logic to other metadata fields (titles, descriptions and units). Given c = a / b:
* If a has no metadata, c has no metadata (regardless of b).
* If a has metadata and b has no metadata, c has metadata from a.
* If a and b have identical metadata, c has that metadata.
* If a and b have different metadata, c has no metadata.
I'm not totally sure about the last point. Alternatively, we could adopt "If a and b have different metadata, c has metadata from a". But I think the current logic is a bit safer.
> Improve the logic of display and presentation propagation on divisions

- etl/steps/data/garden/war/2023-09-27/peace_diehl.meta.yml
- etl/steps/data/garden/war/2023-09-27/peace_diehl.py
Rename category 'positive peace' to 'warm peace'
> positive peace -> warm peace

- lib/catalog/owid/catalog/tables.py
We should only raise a warning on groupby if observed is False.
> We should only raise a warning on groupby if observed is False

- etl/steps/data/garden/war/2023-09-21/cow_mid.py
Fix bug that prevents `number of new conflicts` to be correctly estimated. At the moment, it is an all-zero timeseries.
See this bug in the chart in the data page: https://owid.cloud/admin/datapage-preview/812693
Corrected version in staging: http://staging-site-lucas/admin/datapage-preview/816451
> 🐛 war: fix bug in number of new conflicts with hostility=all

- etl/steps/data/grapher/gcp/2023-07-10/global_carbon_budget.meta.yml
- lib/catalog/owid/catalog/tables.py
- lib/catalog/owid/catalog/utils.py
- lib/catalog/owid/catalog/yaml_metadata.py
- lib/catalog/tests/test_tables.py
- lib/catalog/tests/test_utils.py
- lib/catalog/tests/test_yaml_metadata.py
- schemas/dataset-schema.json
Implementation of https://github.com/owid/etl/issues/1733. Its behaviour is best seen on [unit tests](https://github.com/owid/etl/pull/1737/files#diff-2b4afe7f7246c478125031da2d141d6d30a6c20b0aa63d6384bf4c8daab7502fR31).
> ✨ add definitions.common to YAML metadata

- docs/architecture/metadata/reference/index.md
- docs/architecture/workflow/garden.md
- docs/css/extra.css
- docs/ignore/gen_metadata_reference.py
- mkdocs.yml
Addresses:
- #1761 
- #1762 
To preview the documentation, run:
```
mkdocs serve
```
and go to localhost:8000
> 📜 improve navigation

- etl/steps/data/garden/excess_mortality/latest/wmd.countries.json
- etl/steps/data/garden/excess_mortality/latest/wmd.py
- etl/steps/data/garden/excess_mortality/latest/xm_karlinsky_kobak.countries.json
Their recent update added Fiji and a few values for Fiji with year == 0 (dropping them).
> :bar_chart: add Fiji to excess mortality and remove years == 0

- etl/steps/data/meadow/un/2022-07-11/un_wpp.py
We weren't passing `Origin` from snapshot to dataset. This should add origins to `garden/un/2022-07-11/un_wpp` dataset.
> :bar_chart: add origin to UN WPP

- dag/wizard.yml
- etl/steps/data/garden/dummy/2023-10-12/dummy_monster.meta.yml
- etl/steps/data/garden/dummy/2023-10-12/dummy_monster.py
- etl/steps/data/grapher/dummy/2023-10-12/dummy_monster.py
This dataset is a playground to test how things look in the sources tab and in data pages. To play around with it we just need to add/edit/remove indicators in the YAML file of the garden step (no need to change any other file).
I added a few normal, interesting, and extreme cases. We can add more in the future.
> Create dummy monster dataset

- dag/archive/emissions.yml
- dag/emissions.yml
- dag/main.yml
- etl/data_helpers/misc.py
- etl/steps/data/garden/emissions/2023-09-28/owid_co2.py
- etl/steps/data/garden/gcp/2023-09-28/global_carbon_budget.py
- snapshots/gcp/2023-09-28/global_carbon_budget_fossil_co2_emissions.csv.dvc
- snapshots/gcp/2023-09-28/global_carbon_budget_global_emissions.xlsx.dvc
- snapshots/gcp/2023-09-28/global_carbon_budget_land_use_change_emissions.xlsx.dvc
- snapshots/gcp/2023-09-28/global_carbon_budget_national_emissions.xlsx.dvc
* Minor changes in GCB metadata.
* Fix ~issue with African consumption-based emissions, and~(this was handled in a previous PR) issue with Palau emissions.
* Update `owid_co2` dataset.
* Archive unused steps (and update `country_profiles` dependencies to use the latest GCB dataset).
> Update CO2 dataset

- apps/backport/datasync/data_metadata.py
- etl/grapher_model.py
Add new column `displayOrder` that controls order of FAQ entries in Data page.
> :bug: fix ordering of FAQs in Data Pages

- snapshots/cardiovascular_diseases/2023-10-10/esc.csv.dvc
- snapshots/cardiovascular_diseases/2023-10-10/esc.py
bug in extracting numbers from html
> 🐛 ECS dataset on cardiovascular diseases - bug fix

- apps/wizard/templating/snapshot.py
Improve error when snapshot is uploaded and fails.
> 🐛 error message when failing to upload to snapshot fails

- etl/steps/data/garden/demography/2023-10-03/life_tables.meta.yml
- etl/steps/data/garden/hmd/2023-09-19/hmd.meta.yml
- etl/steps/data/garden/un/2023-10-02/un_wpp_lt.meta.yml
_Central issue: https://github.com/owid/owid-issues/issues/1223?notification_referrer_id=NT_kwDOARQ0KbM3ODUyNzQwMTY3OjE4MTAxMjg5#issuecomment-1766457421_
> 📊 demography: metadata on LT indicators

- dag/main.yml
- etl/steps/data/garden/met_office_hadley_centre/2023-10-18/near_surface_temperature.meta.yml
- etl/steps/data/garden/met_office_hadley_centre/2023-10-18/near_surface_temperature.py
- etl/steps/data/grapher/met_office_hadley_centre/2023-10-18/near_surface_temperature.py
- etl/steps/data/meadow/met_office_hadley_centre/2023-10-18/near_surface_temperature.meta.yml
- etl/steps/data/meadow/met_office_hadley_centre/2023-10-18/near_surface_temperature.py
- snapshots/met_office_hadley_centre/2023-10-18/near_surface_temperature.py
- snapshots/met_office_hadley_centre/2023-10-18/near_surface_temperature_global.csv.dvc
- snapshots/met_office_hadley_centre/2023-10-18/near_surface_temperature_northern_hemisphere.csv.dvc
- snapshots/met_office_hadley_centre/2023-10-18/near_surface_temperature_southern_hemisphere.csv.dvc
Update near-surface temperature dataset by Met Office.
TODO: Archive unused steps in a separate PR.
> 📊 Update met office data

- etl/steps/data/garden/worldbank_wdi/2023-05-29/wdi.countries.json
hey @Marigold! I seem to remember you've updated this dataset. Pablo R suggested we change West Bank and Gaza to Palestine here. Let me know if you are happy with this :)
> 🐛 WDI: West Bank and Gaza --> Palestine

- etl/steps/data/garden/war/2023-09-21/cow_mid.meta.yml
- etl/steps/data/garden/war/2023-09-21/ucdp.meta.yml
> 🐛 war: units

- etl/steps/data/grapher/democracy/2023-03-02/vdem.meta.yml
Migrate [JSON-based Data page](https://ourworldindata.org/grapher/electoral-democracy-index) to [ETL-based Data page](http://staging-site-mojmir/admin/datapage-preview/419298) by adding metadata to its grapher step. I tried to match the original Data page as closely as possible, which means some metadata fields might not **adhere to our guidelines**. I moved [FAQs to its GDoc](https://docs.google.com/document/d/1gGburArxglFdHXeTLotFW4TOOLoeRq5XW6UfAdKtaAw/edit) and used official topic tags names.
@paarriagadap could you please check the Data Page for any issues? You are also encouraged to update metadata in the YAML file according to guidelines. Commented lines are metadata from the ETL dataset, you should delete them if they're not helpful. **Add commits to this PR** as you wish!
You can …
> :bar_chart: migrate JSON data page for V-dem index

- etl/grapher_import.py
Fixes https://github.com/owid/etl/issues/1829
> :bug: proper cleanup of relationships

- etl/steps/__init__.py
Cache DVC repository to speed up checks of dirty steps.
> :sparkles: improve performance of ETL dirty steps check

- etl/steps/data/garden/war/2023-09-27/peace_diehl.py
Figures on number of country-pairs without no relationship was wrong.
> 🐛 war: fix no relationship

- dag/main.yml
- etl/steps/data/garden/state_capacity/2023-10-19/state_capacity_dataset.meta.yml
- etl/steps/data/garden/state_capacity/2023-10-19/state_capacity_dataset.py
Also:
- Convert log indicators with the exponential function.
- Add corresponding metadata.
> 📊 state capacity: regional aggregations for main dataset

- etl/steps/data/garden/animal_welfare/2023-10-24/fur_laws.py
* Fix Montenegro status of active fur farms.
* Simplify code.
> 📊 Fix fur laws dataset

- dag/war.yml
- etl/steps/data/garden/war/2023-09-21/ucdp_prio.meta.yml
- etl/steps/data/garden/war/2023-09-21/ucdp_prio.py
> 📊 war: add indicator rates

- dag/main.yml
- etl/steps/data/garden/harvard/2023-09-18/colonial_dates_dataset.meta.yml
- etl/steps/data/garden/harvard/2023-09-18/colonial_dates_dataset.py
Discussed in https://github.com/owid/owid-issues/issues/925
> 📊 harvard: regional aggregations in the colonial_dates_dataset

- apps/wizard/templating/garden.py
- apps/wizard/utils.py
Data managers now have to select a tag for all indicators as a requirement.
As part of https://github.com/owid/etl/issues/1868
> ✨ wizard: add tags as a requirement

- etl/grapher_helpers.py
- etl/steps/data/grapher/energy/2023-07-10/electricity_mix.py
Thanks @spoonerf for your suggestions in https://github.com/owid/etl/pull/1877
I've changed the function so that the original columns are not affected (and did a minor change in the electricity mix step to trigger the changes in production).
> Fix function for multiindicator charts

- .github/workflows/merge-schedule.yml
Add action to schedule merges.
Uses: https://github.com/marketplace/actions/merge-schedule
> ✨ scheduling merges

- etl/steps/data/garden/worldbank_wdi/2023-05-29/wdi.meta.yml
Adds the topic tag "Economic Growth" to all GDP per capita indicators inside WDI
> :hammer: add topic tag to WDI GDP indicators

- etl/data_helpers/misc.py
- snapshots/energy_institute/2023-06-26/statistical_review_of_world_energy.csv.dvc
Minor change in the description of the Statistical Review of World Energy, as suggested [on Slack](https://owid.slack.com/archives/C064666EG8K/p1699290053352009).
> Minor changes to Statistical Review description

- etl/steps/data/garden/ember/2022-08-01/european_electricity_review.meta.yml
- etl/steps/data/garden/ember/2023-02-20/european_electricity_review.meta.yml
Minor fixes in metadata in Ember's datasets.
> Fix metadata in Ember's datasets

- etl/steps/__init__.py
- etl/steps/data/garden/un/2023-08-16/igme.py
@spoonerf just a heads up that this fixes empty `igme_under_fifteen_mortality` table
> :bug: filter igme with correct indicator name

- etl/steps/data/garden/emdat/2023-09-20/natural_disasters.meta.yml
Improve definition of extreme temperatures.
> Improve definition of extreme temperatures

- etl/snapshot.py
- etl/steps/__init__.py
Use `get_dvc()` with proper config taken from `.env` everywhere. Refactor how we create DVC repo a bit.
Fixes #1951
> :bug: Fix private snapshots

- etl/steps/data/garden/worldbank_wdi/2023-05-29/wdi.py
Fix data issue with Papua New Guinea electricity access in WDI (as discussed in [this thread](https://owid.slack.com/archives/C3RAU3BJ9/p1700475660830369)).
> Fix issue with Papua New Guinea electricity access in WDI

- dag/archive/emissions.yml
- dag/emissions.yml
- etl/steps/data/garden/emissions/2023-11-23/national_contributions.meta.yml
- etl/steps/data/garden/emissions/2023-11-23/national_contributions.py
- etl/steps/data/garden/emissions/2023-11-23/owid_co2.py
- etl/steps/data/grapher/emissions/2023-11-23/national_contributions.py
- etl/steps/data/meadow/emissions/2023-11-23/national_contributions.py
- etl/steps/data/tyffhunogn.py
- snapshots/emissions/2023-11-23/national_contributions.py
- snapshots/emissions/2023-11-23/national_contributions_annual_emissions.csv.dvc
- snapshots/emissions/2023-11-23/national_contributions_cumulative_emissions.csv.dvc
- snapshots/emissions/2023-11-23/national_contributions_temperature_response.csv.dvc
* Improve code and metadata of Jones et al. dataset on national contributions to climate change.
* Update owid_co2 dataset to fetch those changes in metadata.
Nothing substantial has changed in the code: I have simply adjusted it to the latest ETL conventions.
The main changes to be reviewed are in the metadata (snapshots and garden yaml file).
> Improve metadata of national contributions to climate change

- etl/steps/data/garden/emissions/2023-11-23/national_contributions.meta.yml
Add topic tags to Jones et al. dataset on national contributions to climate change.
> Add topic tags to Jones et al. dataset

- etl/steps/data/meadow/faostat/2023-06-12/faostat_metadata.py
Two tables `faostat_qi_item_group` and `faostat_qv_item_group` were represented twice in tables which threw an error (there's a new assertion about unique table short names). I think it's harmless.
> :bug: deduplicate tables in faostat

- snapshots/gcp/2023-12-05/global_carbon_budget.py
- snapshots/gcp/2023-12-05/global_carbon_budget_fossil_co2_emissions.csv.dvc
- snapshots/gcp/2023-12-05/global_carbon_budget_global_emissions.xlsx.dvc
- snapshots/gcp/2023-12-05/global_carbon_budget_land_use_change_emissions.xlsx.dvc
- snapshots/gcp/2023-12-05/global_carbon_budget_national_emissions.xlsx.dvc
Update citation of Global Carbon Budget.
> Update citation of Global Carbon Budget

- docs/architecture/metadata/faqs.md
- schemas/dataset-schema.json
- schemas/definitions.json
Update guidelines and ETL docs regarding `display.name`.
> Update guidelines and docs to discourage the use of `display.name`

- apps/backport/migrate/migrate.py
- dag/migrated.yml
- etl/steps/data/garden/iucn/2022-12-08/threatened_and_evaluated_species.meta.yml
- etl/steps/data/garden/iucn/2022-12-08/threatened_and_evaluated_species.py
- etl/steps/data/grapher/iucn/2022-12-08/threatened_and_evaluated_species.py
- snapshots/backport/latest/dataset_5282_threatened_and_evaluated_species__iucn_red_list_config.json.dvc
- snapshots/backport/latest/dataset_5282_threatened_and_evaluated_species__iucn_red_list_values.feather.dvc
- snapshots/iucn/2022-12-08/threatened_and_evaluated_species.feather.dvc
- snapshots/iucn/2022-12-08/threatened_and_evaluated_species.py
> :bar_chart: migrate Threatened and evaluated species (IUCN Red List) to ETL

- etl/data_helpers/geo.py
- etl/steps/data/garden/tuberculosis/2023-11-27/outcomes_disagg.py
The problem seems to happen because "country_col" is categorical, and it doesn't like using ".any()" when the column is empty.
> Fix issue in tuberculosis step

- etl/steps/data/garden/tuberculosis/2023-11-27/drug_resistance_surveillance.meta.yml
- etl/steps/data/garden/tuberculosis/2023-11-27/drug_resistance_surveillance.py
Also trying out the new `add_regions_to_table()` function
> 📊 Adding sum of TB antibiotic susceptible patients with disaggregated HIV status

- etl/steps/data/grapher/papers/2023-12-12/farmer_lafond_2016.py
Improve display name in chart about cost of different technologies.
> Improve display name in chart about cost of different technologies

- etl/steps/data/garden/war/2023-09-21/ucdp.meta.yml
- etl/steps/data/garden/war/2023-09-21/ucdp.py
- snapshots/countries/2023-09-22/cow_ssm_majors.csv.dvc
- snapshots/countries/2023-09-22/cow_ssm_states.csv.dvc
- snapshots/countries/2023-09-22/cow_ssm_system.csv.dvc
- snapshots/war/2023-09-21/cow_extra_state.csv.dvc
- snapshots/war/2023-09-21/cow_inter_state.csv.dvc
- snapshots/war/2023-09-21/cow_inter_state_dyadic.zip.dvc
- snapshots/war/2023-09-21/cow_intra_state.zip.dvc
- snapshots/war/2023-09-21/cow_mid.zip.dvc
- snapshots/war/2023-09-21/cow_non_state.csv.dvc
- snapshots/war/2023-09-21/mie.zip.dvc
- snapshots/war/2023-09-21/war_brecke.xlsx.dvc
- snapshots/war/2023-09-21/war_mars.xls.dvc
Addresses https://github.com/owid/owid-issues/issues/1306
> 📊 war: improve source names

- etl/steps/data/garden/war/2023-07-20/brecke.meta.yml
- etl/steps/data/garden/war/2023-09-21/brecke.meta.yml
- etl/steps/data/garden/war/2023-09-21/ucdp.meta.yml
addresses https://github.com/owid/owid-issues/issues/1307
> 📊 war: fix typos

- dag/energy.yml
- etl/steps/data/garden/irena/2023-12-12/renewable_energy_patents.countries.json
- etl/steps/data/garden/irena/2023-12-12/renewable_energy_patents.meta.yml
- etl/steps/data/garden/irena/2023-12-12/renewable_energy_patents.py
- etl/steps/data/grapher/irena/2023-12-12/renewable_energy_patents.py
- etl/steps/data/meadow/irena/2023-12-12/renewable_energy_patents.py
- snapshots/irena/2023-12-12/renewable_energy_patents.py
- snapshots/irena/2023-12-12/renewable_energy_patents.xlsx.dvc
Adapt renewable energy patents steps.
Good news: This was the only remaining snapshot from walden!
> Adapt renewable energy patents steps

- dag/energy.yml
- etl/steps/data/garden/irena/2023-12-12/renewable_electricity_capacity.meta.yml
- etl/steps/data/garden/irena/2023-12-12/renewable_electricity_capacity.py
- etl/steps/data/garden/irena/2023-12-12/renewable_power_generation_costs.countries.json
- etl/steps/data/garden/irena/2023-12-12/renewable_power_generation_costs.meta.yml
- etl/steps/data/garden/irena/2023-12-12/renewable_power_generation_costs.py
- etl/steps/data/grapher/irena/2023-12-12/renewable_electricity_capacity.py
- etl/steps/data/grapher/irena/2023-12-12/renewable_electricity_capacity_by_technology.py
- etl/steps/data/grapher/irena/2023-12-12/renewable_power_generation_costs.py
- etl/steps/data/meadow/irena/2023-12-12/renewable_electricity_capacity.py
- etl/steps/data/meadow/irena/2023-12-12/renewable_power_generation_costs.py
- snapshots/irena/2023-12-12/renewable_electricity_capacity_and_generation.py
- snapshots/irena/2023-12-12/renewable_electricity_capacity_and_generation.xlsm.dvc
- snapshots/irena/2023-12-12/renewable_power_generation_costs.py
- snapshots/irena/2023-12-12/renewable_power_generation_costs.xlsx.dvc
Adapt snapshot, meadow, garden and grapher steps to new IRENA data, and update metadata.
> Add remaining irena data

- etl/steps/data/garden/countries/2023-09-25/gleditsch.meta.yml
- etl/steps/data/garden/countries/2023-09-25/isd.meta.yml
- etl/steps/data/garden/countries/2023-09-29/cow_ssm.meta.yml
- etl/steps/data/grapher/countries/2023-09-29/cow_ssm.meta.yml
- etl/steps/data/grapher/countries/2023-09-29/cow_ssm.py
- etl/steps/data/grapher/countries/2023-10-01/gleditsch.meta.yml
- etl/steps/data/grapher/countries/2023-10-01/gleditsch.py
- etl/steps/data/grapher/countries/2023-10-01/isd.meta.yml
- etl/steps/data/grapher/countries/2023-10-01/isd.py
Improves metadata on state_capacity indicators:
- Add topic tags
- Better binary (flag) indicator desscription
- Add key information
> 📊  state_capacity: improve metadata mgm

- snapshots/energy_institute/2023-12-12/statistical_review_of_world_energy.py
Add note about known issue in Statistical Review data, reporting https://github.com/owid/owid-issues/issues/1267 .
> Add note about known issue in Statistical Review data

- etl/steps/data/garden/energy/2023-12-12/electricity_mix.py
Fix comment in electricity mix.
> Fix comment in electricity mix

- etl/steps/data/garden/covid/latest/cases_and_deaths_who.meta.yml
Based on https://github.com/owid/covid-19-data/issues/2824
> 📜 covid: update links

- dag/space.yml
- etl/steps/data/garden/space/2024-01-03/near_earth_asteroids.meta.yml
- etl/steps/data/garden/space/2024-01-03/near_earth_asteroids.py
- etl/steps/data/grapher/space/2024-01-03/near_earth_asteroids.py
- etl/steps/data/meadow/space/2024-01-03/near_earth_asteroids.py
- snapshots/space/2024-01-03/near_earth_asteroids.csv.dvc
- snapshots/space/2024-01-03/near_earth_asteroids.py
Updates the NASA CNEOS data on Near-Earth Asteroids up to the end of 2023.
- Issue: https://github.com/owid/owid-issues/issues/1326
- Chart: [Near-Earth asteroids discovered over time](https://owid.cloud/admin/datasets/5437)
> NASA CNEOS - Near-Earth Asteroids

- etl/steps/data/grapher/un/2023-08-16/un_sdg.py
Hotfix for https://github.com/owid/etl/issues/2154. 
I will work towards moving the metadata to snapshot and grabbing them from there, rather than doing http requests in the grapher step.
> 🐛 Hotfix for UN SDG Metadata issue

- etl/steps/data/garden/hyde/2024-01-02/all_indicators.meta.yml
- etl/steps/data/garden/hyde/2024-01-02/all_indicators.py
> 📊 population: improvements to HYDE 3.3 dataset

- dag/main.yml
- etl/steps/data/garden/ggdc/2022-12-23/maddison_database.meta.yml
- etl/steps/data/garden/ggdc/2022-12-23/maddison_database.py
- etl/steps/data/garden/growth/2024-01-04/gdp_historical.meta.yml
- etl/steps/data/garden/growth/2024-01-04/gdp_historical.py
- etl/steps/data/grapher/growth/2024-01-04/gdp_historical.py
- etl/steps/data/grapher/worldbank_wdi/2023-05-29/wdi.meta.yml
- etl/steps/data/meadow/ggdc/2022-12-23/maddison_database.py
- snapshots/ggdc/2020-10-01/ggdc_maddison.xlsx.dvc
- snapshots/ggdc/2022-12-23/maddison_database.py
- snapshots/ggdc/2022-12-23/maddison_database.xlsx.dvc
This is a continuation of the work described [here](https://github.com/owid/owid-issues/issues/379), but adding the new metadata structure.
> 📊 growth: Update historical GDP to use new metadata

- etl/steps/data/garden/energy/2023-12-12/electricity_mix.meta.yml
Specify carbon intensity of electricity **generation**.
> Specify carbon intensity of electricity generation

- etl/steps/data/garden/war/2024-01-11/nuclear_weapons_proliferation.meta.yml
Add title public to nuclear weapons proliferation.
> Add title public to nuclear weapons proliferation

- etl/steps/data/garden/war/2023-09-21/ucdp_prio.meta.yml
Fixes https://github.com/owid/owid-issues/issues/1348
> 📊 war: add clarification on processing

- etl/steps/data/garden/war/2024-01-08/strategic_nuclear_forces.meta.yml
Improve key descriptions, following Bastian's suggestions.
> Improve strategic nuclear forces metadata

- etl/steps/data/garden/energy/2023-12-12/electricity_mix.py
> Revert "Improve calculation of the share of electricity in primary energy"

- etl/steps/data/garden/war/2024-01-23/nuclear_weapons_treaties.meta.yml
Improve metadata on nuclear weapons treaties.
> Improve metadata on nuclear weapons treaties

- dag/war.yml
Remove unnecessary steps from dag.
> Remove unnecessary steps from dag

- etl/steps/data/garden/covid/latest/variants.meta.yml
> 🦠 data: covid variants update

- apps/wizard/pages/harmonizer.py
> 🐛 wizard: KeyError in dictionary access in Harmonizer

- dag/fasttrack.yml
- etl/steps/data/grapher/fasttrack/2023-08-07/animal_lives_per_kilogram.meta.yml
- etl/steps/data/grapher/fasttrack/2023-08-07/animal_lives_per_kilogram.py
- etl/steps/data/grapher/fasttrack/latest/baxter_2013_gbd_adult_coverage.meta.yml
- etl/steps/data/grapher/fasttrack/latest/baxter_2013_gbd_adult_coverage.py
- snapshots/fasttrack/2023-08-07/animal_lives_per_kilogram.csv.dvc
- snapshots/fasttrack/latest/baxter_2013_gbd_adult_coverage.csv.dvc
Two fast-track datasets that weren't committed to ETL.
> :bar_chart: add missing fasttrack datasets

- etl/version_tracker.py
Fix spurious warning in version tracker.
> Fix spurious warning in version tracker

- apps/wizard/pages/charts/variable_config.py
- etl/match_variables.py
ref: 
- https://github.com/owid/etl/issues/2315
> 🐛 chart-revision: limit number of variables to map

- dag/climate.yml
Hotfix until we fix the issue https://github.com/owid/etl/issues/2334
> :bar_chart: temporarily disable climate/2023-12-20/surface_temperature

- dag/emissions.yml
- etl/steps/data/garden/emissions/2024-02-26/gdp_and_co2_decoupling.meta.yml
- etl/steps/data/garden/emissions/2024-02-26/gdp_and_co2_decoupling.py
Add new ETL dataset for static chart on per capita GDP vs per capita emissions.
WARNING: Do not merge until we decide on the range of years to compare (to be discussed with @samizdatco).
The changes have been discussed and decided in: https://github.com/owid/owid-issues/issues/1062
> Add new ETL dataset for static chart on per capita GDP vs per capita emissions

- dag/main.yml
> :bug: Fix incorrect dependency for malnutrition

- dag/archive/climate.yml
- dag/climate.yml
- snapshots/met_office_hadley_centre/2024-03-04/near_surface_temperature_global.csv.dvc
- snapshots/met_office_hadley_centre/2024-03-04/near_surface_temperature_northern_hemisphere.csv.dvc
- snapshots/met_office_hadley_centre/2024-03-04/near_surface_temperature_southern_hemisphere.csv.dvc
Update [Near-surface temperature anomaly](https://owid.cloud/admin/datasets/6274).
NOTE: This will be the first update implemented using the ETL Dashboard and StepUpdater.
> Update near surface temperature dataset

- apps/wizard/pages/owidle.py
- poetry.lock
- pyproject.toml
- Distance estimation was not accurate
- Bearing estimations is now done using flat-earth model, which feels more intuitive.
> minor fixes

- etl/steps/data/garden/wb/2024-03-11/income_groups.meta.yml
Update parameter update_period_days in World Bank income groups dataset.
> Update parameter update_period_days in World Bank income groups dataset

- etl/steps/data/garden/climate/2024-02-19/monthly_burned_area.meta.yml
- etl/steps/data/garden/climate/2024-02-19/monthly_fire_emissions.meta.yml
- etl/steps/data/garden/climate/latest/weekly_wildfires.meta.yml
- etl/steps/data/grapher/climate/latest/wildfires_by_week.py
- snapshots/climate/latest/weekly_wildfires.csv.dvc
+ minor metadata changes based on Hannah's feedback
> 📊 weekly wildfires dataset update

- etl/helpers.py
- tests/test_helpers.py
Fix for https://github.com/owid/etl/issues/2064
> :sparkles: validate that description_key is a list of strings

- apps/staging_sync/cli.py
Fixes https://github.com/owid/etl/issues/2451, https://github.com/owid/etl/issues/2452 and possibly https://github.com/owid/etl/issues/2457.
> :bug: fix chart-sync issues

- etl/steps/data/garden/demography/2023-03-31/population/population.meta.yml
Change to 500 days, so it matches our regular updates of WPP.
> 🔨 increase update frequency field

- apps/wizard/pages/news.py
- apps/wizard/scripts/news.py
I've updated the system prompt so that the chat GPT summary has a better structure. 
We use an emoji for all PRs to denote their type. This information can be used by GPT to better structure their summary output.
> ✨ wizard-news: improve system prompt

- apps/wizard/pages/dashboard.py
- etl/version_tracker.py
Ed's suggestions:
* Remove column with the 7-day chart views.
* Rearrange column order.
> Improve ETL dashboard, following Ed's suggestions

- dag/health.yml
- etl/steps/data/garden/health/2024-04-02/organ_donation_and_transplantation.meta.yml
- etl/steps/data/garden/health/2024-04-02/organ_donation_and_transplantation.py
- snapshots/health/2024-04-02/organ_donation_and_transplantation.xlsx.dvc
Add indicators per million people.
> 📊 Add data on organ donors per million people

- docs/data/faostat.md
Add comment about description of anomalies to FAOSTAT documentation.
> 📜 Add comment about description of anomalies to FAOSTAT documentation

- etl/files.py
Attempting to fix the ruamel issue (#2499) I was having, it appears to work (snapshot now runs) but I am not really sure why :)
> 🔧  Attempting to fix ruamel issue

- apps/owidbot/etldiff.py
- etl/datadiff.py
- etl/steps/data/garden/dummy/2020-01-01/dummy.py
A couple of minor improvements. The biggest hurdle is still how checksums are computed https://github.com/owid/etl/pull/2514
> :sparkles: improve datadiff posted by owidbot

- etl/steps/data/garden/wb/2024-03-27/shared.py
- etl/steps/data/garden/wb/2024-03-27/world_bank_pip.py
Discussed from here: https://github.com/owid/owid-issues/issues/1475#issuecomment-2060058155
> :sparkles: Use new method for picking income or consumption data in World Bank PIP

- apps/wizard/config/config.yml
- apps/wizard/pages/chart_diff/app.py
- apps/wizard/utils/__init__.py
- approval buttons
- add new charts
- minor changes to code structure
- add timestamps
> ✨ improve approval tool

- apps/wizard/config/config.yml
- apps/wizard/pages/datainsight_robot.py
Add a new page to wizard that allows you to ask ChatGPT for a data insight from a chart
> Data-insights-robot

- etl/steps/data/garden/health/2024-04-12/polio_free_countries.py
Ensuring all who region countries are included in the the certification even if they don't have other polio data
> 📊 Updating polio status

- docs/getting-started/working-environment.md
- Add dependency `pkg-config`.
> 🔨 fixes from engineering session

- etl/data_helpers/geo.py
Adapt helper function that adds GDP to a table, after the update of the Maddison Project Database.
The function now should work both when the old and when the new dataset is used.
> 🐛 Adapt helper function that adds GDP to a table

- etl/steps/__init__.py
Fix for https://github.com/owid/etl/issues/2596 and https://github.com/owid/etl/issues/2584
Unit tests are coming in the next PR.
> :bug: calculate checksum from the entire snapshot metadata file

- etl/steps/data/grapher/regions/2023-01-01/regions.py
Small fix to ensure countries that belong to multiple regions (e.g New Zealand being part of both Oceania (with region type `continent`) and Polynesia (`aggregate`)) are assigned to the continent.
> 🐛 Fix New Zealand being assigned to Polynesia in new simplified grapher regions dataset

- apps/wizard/config/config.yml
It should be possible to use Wizard to create steps on staging servers. I'd find it convenient when working exclusively on stagings.
> :sparkles: enable creating steps in Wizard on staging

- etl/steps/data/external/owid_grapher/latest/regions.py
Just stumbled on an outdated comment while reading through the step.
> 💬 correct comment

- apps/staging_sync/app.py
- apps/staging_sync/cli.py
- apps/staging_sync/instructions.md
- apps/wizard/pages/chart_diff/app.py
- apps/wizard/pages/chart_diff/chart_diff.py
- apps/wizard/pages/fasttrack/process.py
- etl/datadiff.py
- etl/grapher_model.py
* Refactor chart sync
* Enable `--publish` by default - sync published charts as published and drafts as drafts
> :hammer: refactor chart-sync

- apps/staging_sync/cli.py
Refactor `chart-sync` tool and integrate it with the new `chart-diff` tool. This **replaces** the existing `chart-sync` tool... it might be better to do `v2` of chart-sync or simply make everyone use the old way of creating charts in production for a while.
- Replace status `rejected` by `unapproved`. In my head, "reject" is a stronger concept that might be introduced later. Rejected charts might not even be synced. Let me know if you disagree @lucasrodes
- Remove chart-sync app
- Leverage `ChartDiffModified` for working with two charts
- Simplified logic for creating / updating charts
- Ignore chart revisions
- Slack notification when syncing unapproved chart
> :tada: new chart-sync tool that supports chart-diff

- apps/wizard/config/__init__.py
- apps/wizard/config/config.yml
- apps/wizard/etl_steps/express.py
- apps/wizard/etl_steps/garden.py
- apps/wizard/etl_steps/markdown/express.md
- apps/wizard/home.py
- apps/wizard/utils/__init__.py
Meadow + Garden + Grapher = Express
> 🎉 wizard: express mode

- dag/main.yml
- etl/steps/data/garden/ivs/2023-11-27/integrated_values_survey.meta.yml
- etl/steps/data/garden/ivs/2023-11-27/integrated_values_survey.py
Issue https://github.com/owid/owid-issues/issues/1374
> 🐛 ivs: add aggregations for Integrated Values Survey

- etl/steps/data/garden/emdat/2024-04-11/natural_disasters.meta.yml
Improve natural disasters metadata
> Improve natural disasters metadata

- etl/steps/data/garden/who/2022-09-30/ghe.meta.yml
- etl/steps/data/garden/who/2022-09-30/ghe.py
- etl/steps/data/grapher/who/2022-09-30/ghe.py
- etl/steps/data/meadow/who/2022-09-30/ghe.py
- snapshots/who/2023-07-14/standard_age_distribution.csv.dvc
[Tracking issue](https://github.com/owid/owid-issues/issues/1547)
We want to migrate our charts from using GHO to GHE estimates.
To this end, we need to estimate new indicators in our GHE dataset:
- Age-standardized death rates from cause self-harm. I've estimated these rates for all causes.
- Male-to-female ratio of death-rate from self-harm. I've created a new table not to affect the main table.
> 📊 health: ghe age-std and m-f ratio

- etl/steps/data/garden/emdat/2024-04-11/natural_disasters.meta.yml
- etl/steps/data/grapher/emdat/2024-04-11/natural_disasters.py
Minor tweaks to improve titles in natural disasters datasets and new explorer.
> 📊 Improve natural disasters metadata to enhance new explorer

- etl/steps/data/garden/emdat/2024-04-11/natural_disasters.meta.yml
Improve natural disasters metadata.
> ✨ Improve natural disasters metadata

- etl/steps/data/grapher/health/2023-08-16/deaths_karlinsky.meta.yml
as per request from @saloni-nd
> 📊 death registration: change citation for karlinsky

- lib/catalog/owid/catalog/meta.py
Move all utility methods into a `Base` class.
> :hammer: refactor metadata classes

- .env.example
- docs/getting-started/working-environment.md
- docs/guides/environment.md
Some updates to our docs after onboarding Tuna.
> :scroll: improve docs for onboarding

- apps/wizard/utils/db.py
I saw some errors in BugSnag about raw queries not being wrapped in `text(...)` which is needed by SQLAlchemy. This PR fixes that and add proper type hints to get a warning in the future.
> :bug: wrap raw queries in text()

- docs/guides/environment.md
- etl/grapher_helpers.py
Couple of memory optimizations for upserting to MySQL.
> :sparkles: reduce memory usage in grapher:// step

- dag/archive/environment.yml
- dag/archive/main.yml
- dag/environment.yml
- etl/steps/data/garden/nasa/2024-05-31/ozone_hole_area.meta.yml
- etl/steps/data/garden/nasa/2024-05-31/ozone_hole_area.py
- etl/steps/data/grapher/nasa/2024-05-31/ozone_hole_area.py
- etl/steps/data/meadow/nasa/2024-05-31/ozone_hole_area.py
- snapshots/nasa/2024-05-31/ozone_hole_area.py
- snapshots/nasa/2024-05-31/ozone_hole_area_p1.txt.dvc
- snapshots/nasa/2024-05-31/ozone_hole_area_p2.txt.dvc
[Tracking issue](https://github.com/owid/owid-issues/issues/1411)
Adds a new datapoint for year 2023, and updates the step code to use the latest available.
> 📊 nasa: ozone layer

- etl/steps/data/garden/aviation_safety_network/2024-06-05/aviation_statistics.meta.yml
> Improve metadata of aviation safety network

- etl/steps/data/meadow/ihme_gbd/2024-05-20/shared.py
When running `make test` on a separate PR, this file was being edited. I'll improve its format here to avoid touching IHME files in the other PR.
NOTE: Merge at the end of the day (since it triggers a big ETL build).
> 💄 Improve format of random `ihme_gbd` file

- apps/explorer_update/cli.py
- docs/guides/index.md
- etl/reindex.py
- Markdown renderings
- `etl d reindex` was wrongly referenced with name `etl d d publish`
> 📜 further fixes

- apps/wizard/app_pages/chart_diff/conflict_resolver.py
> 🐛 fix import

- etl/steps/data/garden/artificial_intelligence/2024-06-03/epoch.py
- etl/steps/data/garden/artificial_intelligence/2024-06-03/epoch_aggregates_affiliation.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-06-03/epoch_aggregates_countries.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-06-03/epoch_aggregates_domain.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-06-03/epoch_aggregates_domain.py
- etl/steps/data/garden/artificial_intelligence/2024-06-03/epoch_aggregates_organizations.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-06-03/shared.py
- etl/steps/data/grapher/artificial_intelligence/2024-06-03/epoch_aggregates_countries.py
small changes to metadata + cleaning up domains with less than 20 systems to be "Other"
> AI Epoch dataset - small edits 💄 

- snapshots/lgbt_rights/2024-06-03/equaldex.csv.dvc
- snapshots/lgbt_rights/2024-06-03/equaldex_current.csv.dvc
- snapshots/lgbt_rights/2024-06-03/equaldex_indices.csv.dvc
After a conversation with the data source, duplicates between current and historical data have been corrected.
The PR updates snapshot and leaves code intact
https://github.com/owid/owid-issues/issues/1556
> :bug: Update Equaldex with corrections from source

- etl/db.py
Fix poorly constructed query used in indicator upgrader
> Fix poorly constructed query used in indicator upgrader

- apps/owidbot/github_utils.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
Fix for `sqlalchemy.exc.NoResultFound` errors in bugsnag.
> :bug: fix case with no changed charts

- etl/steps/data/garden/wb/2024-06-10/gender_statistics.py
As per Bastian's suggestion [here](https://github.com/owid/owid-issues/issues/1274)
> WB gender stats - add assumptions relating to parental leave indicators 💄

- apps/utils/draft_pull_request.py
Add optional `--title` to replace PR name and commit title. I'd find it very useful for hotfixes and small changes.
Also add PR link after it gets created.
> :sparkles: Add --title to draft-pr

- dag/main.yml
- etl/steps/data/garden/lgbt_rights/2024-06-03/equaldex.meta.yml
- etl/steps/data/garden/lgbt_rights/2024-06-03/equaldex.py
Main issue https://github.com/owid/owid-issues/issues/1556
> :lipstick: Restrict Equaldex and Mignot data to sovereign countries

- apps/utils/draft_pull_request.py
Fix wrong help message in draft-pr
> 🐛 Fix wrong help message in draft-pr

- apps/wizard/app_pages/chart_diff/conflict_resolver.py
Fixes [this issue](https://owid.slack.com/archives/C0716HYGXBP/p1719236355978929).
Chart config fields which were LISTS were not being properly typed.
> 🐛 chart-diff: failing when field value is list

- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_cause.meta.yml
- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_cause.py
- For cancers that cause fewer than 200,000 deaths annually
> 📊  Adding 'Other cancer' aggregate 

- etl/grapher_import.py
- etl/steps/__init__.py
Fix for https://github.com/owid/etl/issues/2871, see the description there.
I fixed it by changing the error to a warning and setting a different checksum so that those variables get cleaned on next ETL run. It means that the dataset will be rerun twice, but it's the easiest solution and this should happen rarely.
>  :bug: Cleanup variables after chart-sync

- etl/steps/data/garden/news/2024-05-08/guardian_mentions.py
- snapshots/news/2024-05-07/guardian_mentions.csv.dvc
- snapshots/news/2024-05-07/guardian_mentions.py
- snapshots/news/2024-05-07/guardian_mentions_raw.csv.dvc
> 🐛 news: get correct numerator

- etl/steps/data/grapher/climate/2023-12-20/surface_global_monthly_anomaly.py
previously stupidly set below/above 0 columns before doing the annual averages
> 🐛 fixing a bug in annual global temperature anomalies

- etl/steps/data/garden/faostat/2024-03-14/detected_anomalies.py
- etl/steps/data/garden/faostat/2024-03-14/faostat_fbsc.py
- etl/steps/data/garden/faostat/2024-03-14/faostat_qcl.py
Fix a few data issues found in FAOSTAT data. More details in https://github.com/owid/owid-issues/issues/1596
> 📊 Fix FAOSTAT issues

- etl/steps/data/garden/faostat/2024-03-14/faostat_qcl.meta.yml
Fix typo in poultry meat production
> Fix typo in poultry meat production

- apps/wizard/utils/__init__.py
Fix env_local -> env_remote in Wizard
> Fix env_local -> env_remote in Wizard

- snapshots/wb/2024-03-27/pip_api.py
- snapshots/wb/2024-03-27/world_bank_pip.csv.dvc
- snapshots/wb/2024-03-27/world_bank_pip_percentiles.csv.dvc
Main issue: https://github.com/owid/owid-issues/issues/1580
> :bar_chart: wb: Update percentiles in World Bank PIP

- dag/archive/artificial_intelligence.yml
- dag/artificial_intelligence.yml
- etl/steps/data/garden/artificial_intelligence/2024-06-28/ai_robots.countries.json
- etl/steps/data/garden/artificial_intelligence/2024-06-28/ai_robots.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-06-28/ai_robots.py
- etl/steps/data/grapher/artificial_intelligence/2024-06-28/ai_robots.py
- snapshots/artificial_intelligence/2024-06-28/ai_robots.csv.dvc
- snapshots/artificial_intelligence/2024-06-28/ai_robots.py
hi @paarriagadap! sorry for another review! I am going to have another couple of these but the code is mostly extremely straightforward and rarely changes in logic. no rush to review!
> 📊 AI index report - robots

- apps/wizard/app_pages/map_brackets.py
Add full list of color schemes to map bracketer, as suggested by Lucas during the data call.
> ✨  Add full list of color schemes to map bracketer

- snapshots/wid/2024-05-24/test.do
- snapshots/wid/2024-05-24/wid_indices.do
- snapshots/wid/2024-05-24/world_inequality_database.csv.dvc
- snapshots/wid/2024-05-24/world_inequality_database_distribution.csv.dvc
- snapshots/wid/2024-05-24/world_inequality_database_distribution_with_extrapolations.csv.dvc
- snapshots/wid/2024-05-24/world_inequality_database_with_extrapolations.csv.dvc
Fix the remaining problem with Cuba in WID data https://github.com/owid/owid-issues/issues/1577
> :bug: update WID and fix data in Cuba

- dag/archive/health.yml
- dag/health.yml
GBD Risk Factors has some unresolved charts - the death attributed to drug use data is spiky on years ending in 0 and 5.
> 🧹  Archiving GBD 2019 with the exception of GBD Risk Factors 

- dag/poverty_inequality.yml
- etl/steps/data/garden/cedlas/2024-03-08/sedlac.meta.yml
- etl/steps/data/garden/chartbook/2024-03-21/altimir_1986.countries.json
- etl/steps/data/garden/chartbook/2024-03-21/altimir_1986.meta.yml
- etl/steps/data/garden/chartbook/2024-03-21/altimir_1986.py
- etl/steps/data/meadow/chartbook/2024-03-21/altimir_1986.py
- snapshots/chartbook/2024-03-21/altimir_1986.csv.dvc
- snapshots/chartbook/2024-03-21/altimir_1986.py
Issue https://github.com/owid/owid-issues/issues/1444
Main Argentina issue https://github.com/owid/owid-issues/issues/1450
@lucasrodes This old PR is fairly simple, so there is not much code to check. I want to merge it to resume the chartbook clear of old PRs.
> 📊 chartbook: Create Altimir (1986) dataset for Argentina

- apps/wizard/app_pages/indicator_upgrade/explore_mode.py
Exception was not being properly caught.
> ✨ explore mode: fix exception catch

- etl/steps/data/garden/un/2024-07-12/un_wpp.py
Due to `left`-merge, this data was being lost.
> 📊 wpp: death_rate for low and high scenarios

- apps/wizard/app_pages/indicator_upgrade/indicator_mapping.py
- dag/demography.yml
- etl/steps/data/garden/demography/2024-07-12/un_wpp_historical.meta.yml
- etl/steps/data/garden/demography/2024-07-12/un_wpp_historical.py
- etl/steps/data/grapher/demography/2024-07-12/un_wpp_historical.py
- snapshots/fasttrack/latest/un_wpp_historical.csv.dvc
Improve on https://github.com/owid/etl/pull/2973
> 📊 population: minor improvements

- apps/wizard/app_pages/expert/prompts.py
- etl/grapher_model.py
We want to rename the `charts.is_indexable` column to `isIndexable` in Grapher (see https://github.com/owid/owid-grapher/pull/3773)
> 🐝 rename is_indexable -> isIndexable

- dag/main.yml
- etl/steps/data/garden/geography/2023-11-28/nat_earth_110.meta.yml
- etl/steps/data/garden/geography/2023-11-28/nat_earth_110.py
- etl/steps/data/grapher/geography/2024-07-18/latitude.py
- snapshots/geography/2023-11-28/nat_earth_110.zip.dvc
Hey @veronikasamborska1994! 
I thought it might be useful to add a latitude variable to Grapher; I thought it shows the hump-shape of temperature anomalies quite nicely around the equator, e.g. [here](http://staging-site-centroids/admin/charts/7942/edit). It could be useful for other environmental variables too e.g., there is a latitudinal diversity gradient with species numbers being much higher around the equator.
> 📊 Country latitude centroids

- apps/wizard/app_pages/indicator_upgrade/dataset_selection.py
- dag/demography.yml
- etl/steps/data/garden/demography/2024-07-18/population_doubling_times.meta.yml
- etl/steps/data/garden/demography/2024-07-18/population_doubling_times.py
- etl/steps/data/grapher/demography/2024-07-18/population_doubling_times.py
[Tracking issue](https://github.com/owid/owid-issues/issues/1541)
> 📊 population: doubling times

- dag/health.yml
- etl/steps/data/garden/who/2024-05-20/vehicles.py
Hot-fix for #3004 as it was causing staging server issues for me on another branch.
> 🔧  Vehicle recipe hot fix

- dag/archive/artificial_intelligence.yml
- dag/artificial_intelligence.yml
- etl/steps/data/garden/artificial_intelligence/2024-07-23/shared.py
- etl/steps/data/garden/artificial_intelligence/2024-07-23/yougov_job_automation.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-07-23/yougov_job_automation.py
- etl/steps/data/garden/artificial_intelligence/2024-07-23/yougov_robots.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-07-23/yougov_robots.py
- etl/steps/data/grapher/artificial_intelligence/2024-07-23/yougov_job_automation.py
- etl/steps/data/grapher/artificial_intelligence/2024-07-23/yougov_robots.py
- etl/steps/data/meadow/artificial_intelligence/2024-07-23/shared.py
- etl/steps/data/meadow/artificial_intelligence/2024-07-23/yougov_job_automation.py
- etl/steps/data/meadow/artificial_intelligence/2024-07-23/yougov_robots.py
- snapshots/artificial_intelligence/2024-07-23/yougov_job_automation.py
- snapshots/artificial_intelligence/2024-07-23/yougov_job_automation.xlsx.dvc
- snapshots/artificial_intelligence/2024-07-23/yougov_robots.py
- snapshots/artificial_intelligence/2024-07-23/yougov_robots.xlsx.dvc
hi @paarriagadap ! you've reviewed pretty much identical code right before I left for maternity leave. this is just an update with the more recent data :)
> 📊 ai: yougov survey updates

- dag/archive/artificial_intelligence.yml
- dag/artificial_intelligence.yml
- etl/steps/data/garden/artificial_intelligence/2024-06-28/ai_adoption.countries.json
- etl/steps/data/garden/artificial_intelligence/2024-06-28/ai_adoption.meta.yml
- etl/steps/data/garden/artificial_intelligence/2024-06-28/ai_adoption.py
- etl/steps/data/grapher/artificial_intelligence/2024-06-28/ai_adoption.py
- snapshots/artificial_intelligence/2024-06-28/ai_adoption.csv.dvc
- snapshots/artificial_intelligence/2024-06-28/ai_adoption.py
- snapshots/artificial_intelligence/2024-06-28/ai_adoption_2023.csv.dvc
- snapshots/artificial_intelligence/2024-06-28/ai_adoption_2023.py
hi @antea04 ! I am adding another dataset from the AI index report that I previously asked you to review. It's very simple and pretty short. no rush to review, just when you get a chance to take a look! thanks very much!
> 📊 ai: adoption by organizations (AI Index)

- dag/health.yml
- etl/steps/data/garden/cardiovascular_diseases/2023-11-01/deaths_from_cardiovascular_diseases_vs_other.meta.yml
- etl/steps/data/garden/cardiovascular_diseases/2023-11-01/deaths_from_cardiovascular_diseases_vs_other.py
HI @veronikasamborska1994, I just updated the WHO Mortality DB so thought I would update this too. Some bigger code changes as the format of the data changed a bit, but the [resulting chart looks all good](http://staging-site-who-mdb-cardio/grapher/share-of-deaths-from-underlying-causes).
> 📊  Updating CVD chart to latest WHO MDB data

- etl/steps/data/garden/biodiversity/2023-01-11/cherry_blossom.py
- etl/steps/data/garden/biodiversity/2024-01-25/cherry_blossom.py
- etl/steps/data/garden/climate/2024-01-31/ghg_concentration.py
- etl/steps/data/garden/climate/2024-01-31/ocean_ph_levels.py
- etl/steps/data/garden/climate/2024-01-31/snow_cover_extent.py
- etl/steps/data/garden/climate/2024-03-11/ghg_concentration.py
- etl/steps/data/garden/climate/2024-03-11/ocean_ph_levels.py
- etl/steps/data/garden/climate/2024-03-11/snow_cover_extent.py
- etl/steps/data/garden/climate/2024-04-17/ghg_concentration.py
- etl/steps/data/garden/climate/2024-04-17/ocean_ph_levels.py
- etl/steps/data/garden/climate/2024-04-17/snow_cover_extent.py
- etl/steps/data/garden/climate/2024-05-20/ghg_concentration.py
- etl/steps/data/garden/climate/2024-05-20/ocean_ph_levels.py
- etl/steps/data/garden/climate/2024-05-20/snow_cover_extent.py
- etl/steps/data/garden/climate/2024-07-23/ghg_concentration.py
- etl/steps/data/garden/climate/2024-07-23/ocean_ph_levels.py
- etl/steps/data/garden/climate/2024-07-23/snow_cover_extent.py
- etl/steps/data/garden/wb/2024-01-17/world_bank_pip.py
Recent PR that added metadata to rolling operations broke some steps.
> :bug: fix rolling operations and metadata

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-01/hancock_1971_australia.meta.yml
- etl/steps/data/garden/chartbook/2024-08-01/hancock_1971_australia.py
- etl/steps/data/meadow/chartbook/2024-08-01/hancock_1971_australia.py
- snapshots/chartbook/2024-04-22/concialdi.py
- snapshots/chartbook/2024-08-01/hancock_1971_australia.csv.dvc
- snapshots/chartbook/2024-08-01/hancock_1971_australia.py
Australia issue: https://github.com/owid/owid-issues/issues/1451
Main issue: https://github.com/owid/owid-issues/issues/1177
> :bar_chart: chartbook: Upload Australian data from Hancock (1971)

- dag/chartbook.yml
- etl/steps/data/garden/cedlas/2024-07-31/sedlac_poverty_2016.meta.yml
- etl/steps/data/garden/cedlas/2024-07-31/sedlac_poverty_2018.meta.yml
- etl/steps/data/garden/chartbook/2024-03-21/altimir_1986.meta.yml
- etl/steps/data/garden/chartbook/2024-04-22/concialdi.meta.yml
- etl/steps/data/garden/chartbook/2024-05-23/wealth_france.meta.yml
- etl/steps/data/garden/chartbook/2024-08-01/hancock_1971_australia.meta.yml
- etl/steps/data/garden/chartbook/2024-08-02/ingles_1981_australia.meta.yml
- etl/steps/data/garden/chartbook/2024-08-02/ingles_1981_australia.py
- etl/steps/data/garden/insee/2024-03-21/inequality_france_1999.meta.yml
- etl/steps/data/garden/insee/2024-04-05/inequality_france.meta.yml
- etl/steps/data/garden/insee/2024-04-25/insee_premiere_1875.meta.yml
- etl/steps/data/garden/insee/2024-04-26/relative_poverty_france.meta.yml
- etl/steps/data/garden/insee/2024-05-23/interdecile_ratio.meta.yml
- etl/steps/data/garden/insee/2024-05-23/interdecile_ratio_2022.meta.yml
- etl/steps/data/garden/ons/2024-03-20/hours_and_earnings_uk.meta.yml
- etl/steps/data/garden/unu_wider/2024-04-22/world_income_inequality_database.meta.yml
- etl/steps/data/meadow/chartbook/2024-08-02/ingles_1981_australia.py
- snapshots/chartbook/2024-08-01/hancock_1971_australia.csv.dvc
- snapshots/chartbook/2024-08-02/ingles_1981_australia.csv.dvc
- snapshots/chartbook/2024-08-02/ingles_1981_australia.py
Australia issue: https://github.com/owid/owid-issues/issues/1451
Main issue: https://github.com/owid/owid-issues/issues/1177
I also modified `presentation.title_public` and `presentation.title_variant` to extract them in the consolidation step of the Chartbook.
> :bar_chart: chartbook: Upload Australian data from Ingles (1981)

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-05/atkinson_2008_australia.meta.yml
- etl/steps/data/garden/chartbook/2024-08-05/atkinson_2008_australia.py
- etl/steps/data/meadow/chartbook/2024-08-05/atkinson_2008_australia.py
- snapshots/chartbook/2024-08-05/atkinson_2008_australia.py
- snapshots/chartbook/2024-08-05/atkinson_2008_australia.xls.dvc
Australia issue: https://github.com/owid/owid-issues/issues/1451
Main issue: https://github.com/owid/owid-issues/issues/1177
> :bar_chart: chartbook: Upload Australian data from Atkinson (2008)

- dag/main.yml
- etl/steps/data/garden/wb/2024-06-10/gender_statistics_country_counts.py
- etl/steps/data/grapher/wb/2024-06-10/gender_statistics_country_counts.meta.yml
- etl/steps/data/grapher/wb/2024-06-10/gender_statistics_country_counts.py
hi @paarriagadap! this code is largely based on your [LGBT+ rights code for charts on the total number of countries/population but for the indicators from the WBL gender stats](https://ourworldindata.org/grapher/countries-protecting-core-lgbt-rights). Bastian asked me to make these today and I'd like to get it on grapher before I am off for holidays on Thursday so let me know if you are too busy atm!
> 📊 women's rights: number of countries for important policies 

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-05/atkinson_2008_australia.meta.yml
- etl/steps/data/garden/chartbook/2024-08-05/katic_leigh_2015_australia.meta.yml
- etl/steps/data/garden/chartbook/2024-08-08/langoni_1972_brazil.meta.yml
- etl/steps/data/garden/chartbook/2024-08-08/langoni_1972_brazil.py
- etl/steps/data/meadow/chartbook/2024-08-08/langoni_1972_brazil.py
- snapshots/chartbook/2024-08-08/langoni_1972_brazil.csv.dvc
- snapshots/chartbook/2024-08-08/langoni_1972_brazil.py
Issue https://github.com/owid/owid-issues/issues/1452
> :bar_chart: chartbook: Add Brazilian data from Langoni (1972)

- dag/covid.yml
- etl/steps/data/garden/covid/latest/shared.py
- etl/steps/data/garden/covid/latest/vaccinations_us.meta.yml
- etl/steps/data/garden/covid/latest/vaccinations_us.py
- etl/steps/data/grapher/covid/latest/vaccinations_us.py
- etl/steps/data/meadow/covid/latest/vaccinations_us.py
- snapshots/covid/latest/vaccinations_us.csv.dvc
- snapshots/covid/latest/vaccinations_us.py
> 📊 covid: us vaccinations

- dag/chartbook.yml
- etl/steps/data/garden/oecd/2024-08-08/tackling_inequalities_brazil_2010.meta.yml
- etl/steps/data/garden/oecd/2024-08-08/tackling_inequalities_brazil_2010.py
- etl/steps/data/meadow/oecd/2024-08-08/tackling_inequalities_brazil_2010.py
- snapshots/chartbook/2024-08-08/langoni_1972_brazil.py
- snapshots/oecd/2024-08-08/tackling_inequalities_brazil_2010.csv.dvc
- snapshots/oecd/2024-08-08/tackling_inequalities_brazil_2010.py
Issue https://github.com/owid/owid-issues/issues/1452
> :bar_chart: chartbook: Upload Brazilian data from Neri (2010)

- docs/architecture/workflow/index.md
The link for the sample DVC file referenced in `https://docs.owid.io/projects/etl/architecture/workflow/#snapshot` was broken.
This PR updates both link and YAML code.
> updated link and sample YAML code for example DVC file on fur laws data

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-09/love_1979_canada.meta.yml
- etl/steps/data/garden/chartbook/2024-08-09/love_1979_canada.py
- etl/steps/data/meadow/chartbook/2024-08-09/love_1979_canada.py
- snapshots/chartbook/2024-08-09/love_1979_canada.csv.dvc
- snapshots/chartbook/2024-08-09/love_1979_canada.py
> :bar_chart: chartbook: Upload Canada data from Love (1979)

- docs/architecture/workflow/index.md
Follow-up on https://github.com/owid/etl/pull/3095. There was a minor rendering issue.
> 📜 fix rendering

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-09/wolfson_1986_canada.meta.yml
- etl/steps/data/garden/chartbook/2024-08-09/wolfson_1986_canada.py
- etl/steps/data/meadow/chartbook/2024-08-09/wolfson_1986_canada.py
- snapshots/chartbook/2024-08-09/wolfson_1986_canada.csv.dvc
- snapshots/chartbook/2024-08-09/wolfson_1986_canada.py
> :bar_chart: chartbook: Upload Canada data from Wolfson (1986)

- dag/archive/covid.yml
- dag/covid.yml
- etl/steps/data/garden/covid/latest/combined.meta.yml
- etl/steps/data/garden/covid/latest/combined.py
- etl/steps/data/grapher/covid/latest/combined.py
> 📊 covid: combined dataset

- etl/steps/data/garden/un/2024-07-12/un_wpp.meta.yml
Fixes https://owid.slack.com/archives/C01GAN73R5W/p1723466952732939
> 🐛 correct deaths title, aged -> ages

- dag/chartbook.yml
- etl/steps/data/garden/abs/2024-08-06/employee_earnings_and_hours_australia.meta.yml
- etl/steps/data/garden/abs/2024-08-06/employee_earnings_and_hours_australia.py
- etl/steps/data/garden/abs/2024-08-06/household_income_and_wealth_australia.meta.yml
- etl/steps/data/garden/abs/2024-08-06/household_income_and_wealth_australia.py
- etl/steps/data/garden/abs/2024-08-06/household_income_and_wealth_australia_2017_2018.meta.yml
- etl/steps/data/garden/abs/2024-08-06/household_income_and_wealth_australia_2017_2018.py
- etl/steps/data/meadow/abs/2024-08-06/employee_earnings_and_hours_australia.py
- etl/steps/data/meadow/abs/2024-08-06/household_income_and_wealth_australia.py
- etl/steps/data/meadow/abs/2024-08-06/household_income_and_wealth_australia_2017_2018.py
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia.py
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2006.csv.dvc
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2006.py
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2008.csv.dvc
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2008.py
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2010.xls.dvc
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2012.xls.dvc
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2014.xls.dvc
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2016.xls.dvc
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2018.xlsx.dvc
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2021.xlsx.dvc
- snapshots/abs/2024-08-06/employee_earnings_and_hours_australia_2023.xlsx.dvc
- snapshots/abs/2024-08-06/household_income_and_wealth_australia.py
- snapshots/abs/2024-08-06/household_income_and_wealth_australia.zip.dvc
- snapshots/abs/2024-08-06/household_income_and_wealth_australia_2017_2018.py
- snapshots/abs/2024-08-06/household_income_australia_2017_2018.xlsx.dvc
- snapshots/abs/2024-08-06/household_wealth_australia_2017_2018.xlsx.dvc
Australia issue: https://github.com/owid/owid-issues/issues/1451
Main issue: https://github.com/owid/owid-issues/issues/1177
This is another dataset for the Chartbook, with more processing than others, since I need previous versions of the datasets as well as the "live" versions of them.
> :bar_chart: chartbook: Upload Australian data from the Australian Bureau of Statistics

- dag/covid.yml
- etl/steps/data/garden/covid/latest/oxcgrt_policy.meta.yml
- etl/steps/data/garden/covid/latest/oxcgrt_policy.py
- etl/steps/data/meadow/covid/latest/oxcgrt_policy.py
- snapshots/covid/latest/oxcgrt_policy.py
- snapshots/covid/latest/oxcgrt_policy_national_2020.csv.dvc
- snapshots/covid/latest/oxcgrt_policy_national_2021.csv.dvc
- snapshots/covid/latest/oxcgrt_policy_national_2022.csv.dvc
> 📊 covid: stringency_index

- dag/chartbook.yml
- etl/steps/data/garden/lis/2024-06-13/luxembourg_income_study.meta.yml
- etl/steps/data/garden/statistics_canada/2024-08-09/gini_coefficients.meta.yml
- etl/steps/data/garden/statistics_canada/2024-08-09/gini_coefficients.py
- etl/steps/data/garden/statistics_canada/2024-08-09/relative_poverty.meta.yml
- etl/steps/data/garden/statistics_canada/2024-08-09/relative_poverty.py
- etl/steps/data/meadow/statistics_canada/2024-08-09/gini_coefficients.py
- etl/steps/data/meadow/statistics_canada/2024-08-09/relative_poverty.py
- snapshots/statistics_canada/2024-08-09/gini_coefficients.csv.dvc
- snapshots/statistics_canada/2024-08-09/gini_coefficients.py
- snapshots/statistics_canada/2024-08-09/relative_poverty.csv.dvc
- snapshots/statistics_canada/2024-08-09/relative_poverty.py
I also added the update frequency of LIS here :)
> :bar_chart: Upload Canada data from Statistics Canada

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-14/atkinson_2008_canada.meta.yml
- etl/steps/data/garden/chartbook/2024-08-14/atkinson_2008_canada.py
- etl/steps/data/meadow/chartbook/2024-08-14/atkinson_2008_canada.py
- snapshots/chartbook/2024-08-14/atkinson_2008_canada.py
- snapshots/chartbook/2024-08-14/atkinson_2008_canada.xls.dvc
> :bar_chart: chartbook: Upload Canada data from Atkinson (2008)

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-15/davies_di_matteo_2020_canada.meta.yml
- etl/steps/data/garden/chartbook/2024-08-15/davies_di_matteo_2020_canada.py
- etl/steps/data/meadow/chartbook/2024-08-15/davies_di_matteo_2020_canada.py
- snapshots/chartbook/2024-08-15/davies_di_matteo_2020_canada.csv.dvc
- snapshots/chartbook/2024-08-15/davies_di_matteo_2020_canada.py
- snapshots/chartbook/2024-08-15/table_extract.py
> :bar_chart: chartbook: Upload Canada data from Davies and Di Matteo (2020)

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-15/jantti_2010_finland.meta.yml
- etl/steps/data/garden/chartbook/2024-08-15/jantti_2010_finland.py
- etl/steps/data/meadow/chartbook/2024-08-15/jantti_2010_finland.py
- snapshots/chartbook/2024-08-15/jantti_2010_finland.csv.dvc
- snapshots/chartbook/2024-08-15/jantti_2010_finland.py
- snapshots/chartbook/2024-08-15/table_extract_davies_di_matteo_2020.py
Issue: https://github.com/owid/owid-issues/issues/1454
> :bar_chart: chartbook: Upload Finland data from Atkinson and Piketty (2010)

- etl/steps/data/garden/demography/2023-10-04/gini_le.py
- etl/steps/data/garden/war/2023-09-27/peace_diehl.py
- lib/catalog/owid/catalog/tables.py
- lib/catalog/tests/test_tables.py
Propagate metadata if the output of `groupby.apply` is Variable or Series.
> :bug: Fix apply for Series and Variables

- dag/chartbook.yml
- etl/steps/data/garden/statfin/2024-08-16/statistics_finland_inequality.meta.yml
- etl/steps/data/garden/statfin/2024-08-16/statistics_finland_inequality.py
- etl/steps/data/meadow/statfin/2024-08-16/statistics_finland_inequality.py
- snapshots/statfin/2024-08-16/gini_coefficient.csv.dvc
- snapshots/statfin/2024-08-16/gini_coefficient.py
- snapshots/statfin/2024-08-16/relative_poverty.csv.dvc
- snapshots/statfin/2024-08-16/relative_poverty.py
Issue: https://github.com/owid/owid-issues/issues/1454
> :bar_chart: chartbook: Upload Finland data from StatFin

- dag/space.yml
- etl/steps/data/garden/space/2024-08-16/exoplanets.meta.yml
- etl/steps/data/garden/space/2024-08-16/exoplanets.py
- etl/steps/data/grapher/space/2024-08-16/exoplanets.py
- etl/steps/data/meadow/space/2024-08-16/exoplanets.py
- snapshots/space/2024-08-16/exoplanets.csv.dvc
- snapshots/space/2024-08-16/exoplanets.py
Closes https://github.com/owid/owid-issues/issues/1568
Closes https://github.com/owid/etl/pull/3138
> 📊 Update exoplanets data

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-16/atkinson_2008_finland.meta.yml
- etl/steps/data/garden/chartbook/2024-08-16/atkinson_2008_finland.py
- etl/steps/data/meadow/chartbook/2024-08-16/atkinson_2008_finland.py
- snapshots/chartbook/2024-08-05/atkinson_2008_australia.xls.dvc
- snapshots/chartbook/2024-08-14/atkinson_2008_canada.xls.dvc
- snapshots/chartbook/2024-08-16/atkinson_2008_finland.py
- snapshots/chartbook/2024-08-16/atkinson_2008_finland.xls.dvc
Issue https://github.com/owid/owid-issues/issues/1454
> :bar_chart: chartbook: Upload Finland data from Atkinson (2008)

- dag/health.yml
- etl/steps/data/meadow/who/2024-07-26/mortality_database.py
- snapshots/who/2024-07-26/mortality_database.feather.dvc
- snapshots/who/2024-07-26/mortality_database.py
Use feather instead of CSV to reduce snapshot size by 20x.
>  :honeybee: Optimize who snapshot

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-19/riihela_et_al_2003_finland.meta.yml
- etl/steps/data/garden/chartbook/2024-08-19/riihela_et_al_2003_finland.py
- etl/steps/data/meadow/chartbook/2024-08-19/riihela_et_al_2003_finland.py
- snapshots/chartbook/2024-08-09/love_1979_canada.py
- snapshots/chartbook/2024-08-09/wolfson_1986_canada.py
- snapshots/chartbook/2024-08-19/riihela_et_al_2003_finland.csv.dvc
- snapshots/chartbook/2024-08-19/riihela_et_al_2003_finland.py
Issue: https://github.com/owid/owid-issues/issues/1454
> :bar_chart: chartbook: Upload Finalnd data from Riihelä et al. (2003)

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-08-19/roine_waldenstrom_2015.countries.json
- etl/steps/data/garden/chartbook/2024-08-19/roine_waldenstrom_2015.meta.yml
- etl/steps/data/garden/chartbook/2024-08-19/roine_waldenstrom_2015.py
- etl/steps/data/meadow/chartbook/2024-08-19/roine_waldenstrom_2015.py
- snapshots/chartbook/2024-08-19/roine_waldenstrom_2015.csv.dvc
- snapshots/chartbook/2024-08-19/roine_waldenstrom_2015.py
Issue: https://github.com/owid/owid-issues/issues/1454
> :bar_chart: chartbook: Upload Finland data from Roine & Waldenström (2015)

- etl/steps/data/garden/who/latest/flunet.py
- etl/steps/data/meadow/who/latest/flunet.py
- snapshots/who/latest/fluid.csv.dvc
- snapshots/who/latest/flunet.csv.dvc
Recent data contains duplicates and unexpected NaN values.
>  :bug: Clean up data from flunet

- snapshots/who/latest/avian_influenza_ah5n1.csv.dvc
- snapshots/who/latest/avian_influenza_ah5n1.py
Fixes https://github.com/owid/owid-issues/issues/1623
I've manually updated the data.
The data is provided, temporary, as a blob file, and can't be accessed from python.
> 📊 h5n1: automate update

- etl/steps/data/explorers/covid/latest/covid.config.yml
- make explorer public
- change download link
> 📊 covid: explorer improvements

- etl/steps/data/garden/covid/latest/cases_deaths.meta.yml
Fix colouring of relative indicators for `confirmed deaths`
> ✨ covid: explorer-color

- etl/steps/data/garden/who/2024-01-03/gho.py
Some indicators like reported cases for cholera are missing values in `numeric` column, but have valid values in `display_value` column. Fill those missing values.
>  :bug: Use display_value if numeric is missing in GHO

- docs/api/covid.md
> 📜 covid: typos

- snapshots/covid/latest/vaccinations_global.py
Automation for vaccinations pipeline depended on a manual input. Not anymore.
> 📊 covid: fix automation for vaccination

- etl/steps/data/grapher/climate/latest/wildfires_by_week_average.meta.yml
> 🐛 wildfires: using projections for max/min is causing weird behaviour

- dag/archive/main.yml
- dag/main.yml
- dag/migrated.yml
From [this discussion](https://owid.slack.com/archives/C03NA1B2P1U/p1725016884323649).
> :honeybee: Archive old versions of GDP in the long run

- etl/steps/data/garden/who/latest/monkeypox/__init__.py
- etl/steps/export/github/who/latest/monkeypox.py
- scripts/update-monkeypox.sh
Update CSV with monkeypox data in the [github repo](https://github.com/owid/monkeypox).
>  :hammer: Update CSV in repo https://github.com/owid/monkeypox

- snapshots/bgs/2024-07-09/world_mineral_statistics.zip.dvc
Update URLs to BGS data (they are migrating their website to a new format).
> 📊 Update BGS data download URL

- etl/steps/data/external/energy_data/latest/owid_energy.py
Add per capita electricity demand to owid_energy dataset.
> 📊 Add per capita electricity demand to owid_energy dataset

- dag/health.yml
- docs/architecture/metadata/structuring-yaml.md
- etl/steps/data/garden/health/2024-09-05/seattle_pathogens.meta.yml
- etl/steps/data/garden/health/2024-09-05/seattle_pathogens.py
- etl/steps/data/grapher/health/2024-09-05/seattle_pathogens.py
- etl/steps/data/meadow/health/2024-09-05/seattle_pathogens.py
- snapshots/health/2024-09-05/seattle_pathogens.csv.dvc
- snapshots/health/2024-09-05/seattle_pathogens.py
[tracking issue](https://github.com/owid/owid-issues/issues/1653)
> 📊 health: pathogens

- etl/steps/data/grapher/climate/2024-07-23/sea_ice_anomalies_by_month.py
Use a baseline period of years instead of an individual year.
> 📊 Change sea ice anomaly baseline year

- etl/steps/data/grapher/climate/2024-07-23/sea_ice_anomalies_by_month.py
Fix bug in sea ice anomalies code.
> 📊 Fix sea ice anomalies

- schemas/dataset-schema.json
* instructions on [this PR](https://github.com/owid/owid-grapher/pull/3792) to keep things consistent were followed
* easy to revert if this is wrong
> fix 1444 removed code exactly as instructed here: /owid-grapher/pull/3792

- etl/steps/export/multidim/energy/latest/energy.py
- etl/steps/export/multidim/energy/latest/energy.yml
- schemas/multidim-schema.json
This PR collects a few tweaks to working with MDims in the ETL
> ✨ Improve MDim support in ETL

- etl/explorer_helpers.py
- etl/steps/export/explorers/minerals/latest/minerals.py
> 📊 Publish minerals explorer

- etl/steps/data/garden/bgs/2024-07-09/world_mineral_statistics.py
Fix issue with chromium mine production data (see [discussion](https://owid.slack.com/archives/C03N1V9KXB9/p1726145261624579)).
> 📊 Fix issue with chromium mine production data

- apps/wizard/app_pages/fasttrack/app.py
- apps/wizard/app_pages/fasttrack/cookiecutter/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- apps/wizard/app_pages/fasttrack/markdown/fasttrack_gsheet_import.md
- apps/wizard/app_pages/fasttrack/process.py
Columns prefixed with `dim_` are now detected as dimensions.
>  :sparkles: Add dimensions to fast-track

- dag/covid.yml
In the covid dag, there was a path with a bad structure.
> 🐛 Fix broken paths, affecting dashboard

- snapshots/who/latest/avian_influenza_ah5n1.csv.dvc
Check if there is available data, and update.
https://github.com/owid/owid-issues/issues/1679
> 📊 h5n1: update

- etl/steps/data/garden/who/2024-08-06/mortality_database_cancer_most_common.meta.yml
change to total deaths from age-standardized ones
> ✨ cancer: WHO mortatlity database - most common cancer

- dag/artificial_intelligence.yml
- etl/steps/data/grapher/artificial_intelligence/2024-10-01/epoch.meta.yml
- etl/steps/data/grapher/artificial_intelligence/2024-10-01/epoch.py
@veronikasamborska1994 some datasets still use `data://meadow/artificial_intelligence/2024-09-09/epoch`, so I had put it back to fix ETL.
>  :bug: Add back old version of epoch dataset

- apps/chart_sync/admin_api.py
- apps/chart_sync/cli.py
- apps/wizard/app_pages/chart_diff/conflict_resolver.py
- apps/wizard/app_pages/indicator_upgrade/charts_update.py
- etl/config.py
- etl/steps/__init__.py
Add localhost support for AdminAPI and clean it up a bit with the help of OWIDEnv.
>  :sparkles: Add localhost support for AdminAPI

- dag/war.yml
- etl/steps/data/garden/war/2024-08-26/ucdp.meta.yml
- etl/steps/data/garden/war/2024-10-02/shared.py
- etl/steps/data/garden/war/2024-10-02/ucdp_monthly.meta.yml
- etl/steps/data/garden/war/2024-10-02/ucdp_monthly.py
- etl/steps/data/grapher/war/2024-10-02/ucdp_monthly.py
- etl/steps/data/meadow/war/2024-10-02/ucdp_ced.py
- snapshots/war/2024-10-02/ucdp_ced.csv.dvc
- snapshots/war/2024-10-02/ucdp_ced.py
- snapshots/war/2024-10-02/ucdp_ced.zip.dvc
Tracking issue: https://github.com/owid/owid-issues/issues/1678
> 📊 conflict: ucdp candidate dataset

- etl/steps/data/garden/oecd/2024-08-21/official_development_assistance.countries.json
Replace "Countries unallocated by income (OECD)" with "Recipients not classified by income group (OECD)"
> :lipstick: oecd: Change name of entity in ODA dataset

- etl/steps/data/garden/wb/2024-10-07/shared.py
- etl/steps/data/garden/wb/2024-10-07/world_bank_pip.meta.yml
Add a bullet point about the prosperity gap and also about nowcasting
> :lipstick: wb: add extra description_key to PIP

- etl/steps/data/garden/oecd/2024-08-21/official_development_assistance.meta.yml
- etl/steps/data/garden/oecd/2024-08-21/official_development_assistance.py
https://github.com/owid/owid-issues/issues/1620
> :lipstick: oecd: Add changes to ODA data after external feedback

- etl/steps/data/garden/oecd/2024-08-21/official_development_assistance.meta.yml
- etl/steps/data/garden/oecd/2024-08-21/official_development_assistance.py
> :lipstick: oecd: Feedback from OECD about ODA data

- etl/helpers.py
Remove unnecessary ipdb instance (I guess you forgot to remove it after testing).
> 💄 Remove unnecessary ipdb instance

- etl/steps/data/garden/andrew/2019-12-03/co2_mitigation_curves.meta.yml
- etl/steps/data/grapher/fasttrack/latest/welfare_broiler_chickens.meta.yml
- etl/steps/data/grapher/fasttrack/latest/welfare_broiler_chickens.py
- snapshots/fasttrack/2023-08-07/animal_lives_per_kilogram.csv.dvc
- snapshots/fasttrack/latest/agricultural_policies_wuepper.csv.dvc
- snapshots/fasttrack/latest/global_precipitation_anomaly_noaa.csv.dvc
- snapshots/fasttrack/latest/heat_deaths_undp_climate_horizons.csv.dvc
- snapshots/fasttrack/latest/hurricane_forecasts_nhc.csv.dvc
- snapshots/fasttrack/latest/north_atlantic_hurricanes_noaa.csv.dvc
- snapshots/fasttrack/latest/rock_metal_ratio_nassar_wang.csv.dvc
- snapshots/fasttrack/latest/transport_co2_emissions_modes.csv.dvc
- snapshots/fasttrack/latest/usa_hurricane_categories_noaa.csv.dvc
- snapshots/fasttrack/latest/usa_weather_climate_noaa.csv.dvc
- snapshots/fasttrack/latest/welfare_broiler_chickens.csv.dvc
Improve multiple metadata files (mostly fasttrack) to allow grapher charts' footer sources to be in sync with ETL.
More details in https://github.com/owid/owid-issues/issues/1630
> 📊 Small improvements on sources and origins for various datasets

- etl/steps/data/garden/oecd/2024-08-21/official_development_assistance.meta.yml
- lib/catalog/owid/catalog/yaml_metadata.py
Following comment https://github.com/owid/owid-issues/issues/1620#issuecomment-2431805867
> :lipstick: oecd: add metadata for private grants

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-10-24/atkinson_2008_germany.meta.yml
- etl/steps/data/garden/chartbook/2024-10-24/atkinson_2008_germany.py
- etl/steps/data/meadow/chartbook/2024-10-24/atkinson_2008_germany.py
- snapshots/chartbook/2024-10-24/atkinson_2008_germany.py
- snapshots/chartbook/2024-10-24/atkinson_2008_germany.xls.dvc
Issue: https://github.com/owid/owid-issues/issues/1456
> :bar_chart: chartbook: Upload Germany data from Atkinson (2008)

- dag/chartbook.yml
- etl/steps/data/garden/chartbook/2024-10-24/becker_1997_germany_relative_poverty.meta.yml
- etl/steps/data/garden/chartbook/2024-10-24/becker_1997_germany_relative_poverty.py
- etl/steps/data/meadow/chartbook/2024-10-24/becker_1997_germany_relative_poverty.py
- snapshots/chartbook/2024-10-24/becker_1997_germany_relative_poverty.csv.dvc
- snapshots/chartbook/2024-10-24/becker_1997_germany_relative_poverty.py
Issue: https://github.com/owid/owid-issues/issues/1456
> :bar_chart: chartbook: Upload Germany relative poverty data from Becker (1997)

- apps/anomalist/anomalist_api.py
- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/utils/cached.py
I forgot to push the latest commit to the previous PR.
> :construction: Hotfix anomalist

- apps/anomalist/anomalist_api.py
- apps/anomalist/detectors.py
- apps/anomalist/gp_detector.py
- apps/wizard/app_pages/anomalist/app.py
- etl/grapher_io.py
- etl/scripts/anomalies/detect_anomalies.py
Some minor improvements and fixes:
* Scale is now strictly positive.
* Anomalist works now on non-yearly data (although we still have a "year" column, that shows the number of days with respect to a certain reference date).
> ✨ anomalist: Minor improvements

- apps/chart_sync/admin_api.py
- etl/multidim.py
Upsert mdims via API instead of upserting them directly to MySQL.
>  :sparkles: Upsert mdims via API

- etl/steps/data/garden/regions/2023-01-01/regions.yml
Hey @pabloarosado an easy PR, but I'm not sure if this will trigger a large rebuild of the ETL, or is that something of the past?
> 🐝  Update regions.yml to shorten Turks and Caicos Islands

- etl/data_helpers/misc.py
- etl/steps/data/garden/covid/latest/vaccinations_age.py
- etl/steps/data/garden/covid/latest/vaccinations_global.py
- etl/steps/data/garden/covid/latest/vaccinations_manufacturer.py
- etl/steps/data/garden/war/2024-08-26/shared.py
- etl/steps/data/garden/war/2024-08-26/ucdp.py
- etl/steps/data/garden/war/2024-10-02/shared.py
- etl/steps/data/garden/war/2024-10-02/ucdp_monthly.py
- etl/steps/data/grapher/countries/2024-08-27/gleditsch.py
Now it works without entity column
> 🔨 expand_time_column: more general function

- snapshots/ember/2024-05-08/yearly_electricity.csv.dvc
- snapshots/ember/2024-05-08/yearly_electricity.py
Fix broken URLs after recent changes in Ember's website.
> ✨ energy: Fix URLs in Ember data that have recently changed

- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_cause.meta.yml
- etl/steps/data/garden/maternal_mortality/2024-07-08/maternal_mortality.meta.yml
- etl/steps/data/garden/un/2024-07-08/maternal_mortality.meta.yml
- etl/steps/data/garden/who/2024-07-26/mortality_database.meta.yml
- etl/steps/data/garden/who/2024-07-30/ghe.meta.yml
- etl/steps/data/grapher/who/2024-01-03/gho.meta.override.yml
Adding an annotation to the United States for the following charts: 
✅ WHO MDB: http://staging-site-mmr-annotation/grapher/maternal-mortality-rate-who-mdb 
✅ Long-run MMR: http://staging-site-mmr-annotation/grapher/maternal-mortality?tab=chart  
✅ WHO GHO: http://staging-site-mmr-annotation/grapher/number-of-maternal-deaths?tab=chart&country=USA 
✅ UN MMEIG dataset: http://staging-site-mmr-annotation/admin/datasets/6642
✅ IHME GBD:  http://staging-site-mmr-annotation/grapher/death-rate-from-maternal-disorders-ihme?tab=chart&country=~USA
> 📊  maternal mortality: Add annotation regarding measurement change issue in the United States

- apps/wizard/app_pages/analytics.py
- apps/wizard/config/config.yml
- apps/wizard/home.py
Link to Analytics dashboard app.
@bnjmacdonald I've tagged you in case you want a high-level view of the project. 
To see the result, there's no need to clone the project, you can see how it'll look in the staging server app: http://staging-site-wizard-dashboard/etl/wizard/
> ✨ wizard: add link to dashboard

- etl/steps/data/garden/ophi/2024-10-28/multidimensional_poverty_index.meta.yml
Issue: https://github.com/owid/owid-issues/issues/1605
> :lipstick: ophi: Improve metadata in MPI dataset

- snapshots/emissions/2023-10-24/emission_factors.xlsx.dvc
Update link to documentation of the IPCC Emissions Factors Database, which was broken.
> 📊 climate: Update link to documentation of the IPCC EFDB, which is broken

- etl/steps/data/garden/ophi/2024-10-28/multidimensional_poverty_index.meta.yml
Main issue https://github.com/owid/owid-issues/issues/1605#issuecomment-2478833397
> :lipstick: ophi: Add FAQs and refine metadata for MPI dataset

- apps/wizard/utils/io.py
- etl/steps/__init__.py
- lib/catalog/owid/catalog/s3_utils.py
Using `PREFER_DOWNLOAD` wasn't cleaning files in dataset directory. If someone renames a table, the old one will still be there and cause problems down the road.
>  :bug: Delete ghost files in dataset directory

- lib/datautils/owid/datautils/dataframes.py
- lib/datautils/tests/test_dataframes.py
- lib/repack/tests/test_repack.py
- pyproject.toml
- tests/data_helpers/test_geo.py
Copy of https://github.com/owid/etl/pull/3516 to make sure CI passes.
>  :hammer: Changes for compatibility with pandas 3.0

- dag/archive/war.yml
- dag/war.yml
- etl/steps/data/garden/war/2024-11-22/ucdp_preview.py
Follow up from https://github.com/owid/etl/pull/3592
- Archive dataset
- Migrate more charts
- Check IDs of conflicts of type 'state-based (unknown)'
> 📊 ucdp: archive

- etl/steps/data/garden/war/2024-08-26/ucdp.py
- etl/steps/data/garden/war/2024-11-22/ucdp_preview.py
> 📊 ucdp: small note

- apps/pr/cli.py
Edit docstring of `etl pr` so that it renders correctly in the documentation
> 📜 fix docstring pr tool

- dag/demography.yml
- etl/steps/data/garden/demography/2024-12-03/birth_rate.meta.yml
- etl/steps/data/garden/demography/2024-12-03/birth_rate.py
- etl/steps/data/garden/demography/2024-12-03/fertility_rate.meta.yml
- etl/steps/data/grapher/demography/2024-12-03/birth_rate.py
Adding new long-run indicator: `Birth rate` by combining UN WPP and HMD
> 📊 add demography long run indicators

- etl/steps/data/garden/demography/2024-11-26/multiple_births.meta.yml
- etl/steps/data/garden/demography/2024-11-26/multiple_births.py
Add indicator measuring number of births per delivery.
> 📊 births per delivery

- dag/demography.yml
- etl/steps/data/garden/un/2024-03-14/un_wpp_most.meta.yml
- etl/steps/data/garden/un/2024-03-14/un_wpp_most.py
- etl/steps/data/grapher/un/2024-03-14/un_wpp_most.py
> 📊 demography: update age-group with largest population chart

- etl/steps/data/garden/urbanization/2024-10-14/ghsl_degree_of_urbanisation.meta.yml
change classification as per source's agreement
> 💄 urbanization: GHSL metatadata changes

- apps/wizard/etl_steps/forms.py
There is an error in the path where to export the generated files in the data step.
> 🐛 wizard export path

- etl/steps/data/garden/hmd/2024-11-19/hfd.py
This PR adds more years to the distribution indicators from HFD.
/schedule
> 📊 add more years for CFR

- apps/wizard/app_pages/expert/app.py
- apps/wizard/etl_steps/snapshot.py
Minor UI changes
- Snapshot: make it more compact
- Expert: move 'clear chat' button all the way down.
> ✨ ui tweaks to wizard

- etl/steps/data/garden/space/2024-08-16/exoplanets.py
- etl/steps/data/garden/space/2024-08-16/space_track.py
- etl/steps/data/garden/un/2024-08-27/un_sdg.py
- etl/steps/data/grapher/space/2024-08-16/exoplanets.py
- etl/steps/data/grapher/space/2024-08-16/space_track.py
- etl/steps/data/meadow/space/2024-08-16/exoplanets.py
- etl/steps/data/meadow/space/2024-08-16/space_track.py
E.g. remove `path.load_dependency` for recent code.
> ✨ correct deprecated code

- dag/archive/artificial_intelligence.yml
- dag/archive/climate.yml
- dag/archive/health.yml
- dag/archive/main.yml
- dag/archive/plastic_use.yml
- dag/artificial_intelligence.yml
- dag/climate.yml
- dag/health.yml
- dag/main.yml
- dag/plastic_use.yml
Archiving unused datasets. See https://github.com/owid/owid-issues/issues/1740
> 🔨 archive steps for datasets with no charts

- etl/steps/data/garden/un/2022-07-11/un_wpp/un_wpp_grapher.meta.yml
- etl/steps/data/garden/un/2024-03-14/un_wpp_most.meta.yml
- etl/steps/data/garden/un/2024-10-01/births_by_age.meta.yml
In admin, we now have multiple datasets named "World Population Prospects". Maybe we could modify some so that it is easier to distinguish them?
> 💄 change dataset title

- .streamlit/config.toml
- Change primary color
- Show only non-archived datasets by default.
> ✨ dataset preview: minor adjustments

- apps/wizard/app_pages/chart_diff/chart_diff_show.py
> 🐛 chart diff query links

- etl/steps/data/garden/wb/2024-12-17/bilateral_remittance.meta.yml
- etl/steps/data/grapher/wb/2024-12-17/bilateral_remittance.py
Cleaning up grapher step of bilateral remittance data by using dimensions. done together with @lucasrodes
> 📊 Remittance dimensions

- etl/steps/data/garden/climate/latest/weekly_wildfires.meta.yml
- etl/steps/data/garden/climate/latest/weekly_wildfires.py
- etl/steps/data/grapher/climate/latest/wildfires_by_week.py
- etl/steps/data/grapher/climate/latest/wildfires_by_week_average.meta.yml
- etl/steps/data/grapher/climate/latest/wildfires_by_week_average.py
- etl/steps/data/grapher/climate/latest/wildfires_by_year.meta.yml
- etl/steps/data/grapher/climate/latest/wildfires_by_year.py
- scripts/update-wildfires.sh
- snapshots/climate/latest/weekly_wildfires.csv.dvc
- snapshots/climate/latest/weekly_wildfires.py
hi @spoonerf! was a slightly annoying bug but I think this solution should be a lot more reliable in the future. I am also adding some code for the 2025 data which should hopefully start running smoothly next week!
> 🐛 wildfires: temporary fix

- apps/wizard/app_pages/dataset_preview/app.py
- apps/wizard/app_pages/dataset_preview/utils.py
- etl/config.py
Make "dataset preview" work for pre-ETL datasets.
/schedule
> ✨ enable dataset preview for archived datasets

- dag/archive/biodiversity.yml
- dag/archive/fasttrack.yml
- dag/archive/health.yml
- dag/archive/main.yml
- dag/biodiversity.yml
- dag/fasttrack.yml
- dag/health.yml
- dag/main.yml
- dag/papers.yml
- scripts/update-wildfires.sh
- snapshots/climate/latest/weekly_wildfires.csv.dvc
- snapshots/who/latest/fluid.csv.dvc
- snapshots/who/latest/flunet.csv.dvc
Archive datasets that are no longer in use in ETL.
> 🐝 archive unused datasets

- apps/housekeeper/cli.py
- apps/housekeeper/utils.py
- etl/grapher/model.py
- scripts/housekeeper.sh
In sync with https://github.com/owid/owid-grapher/pull/4390
> 🎉 demo housekeeper

- snapshots/democracy/2024-05-22/eiu_2023.csv.dvc
- snapshots/democracy/2024-05-22/eiu_dem_index.py
A user reported missing data in our EIU data. There are 19 countries missing, which correspond to the 19 lowest-ranked countries for 2023.
We might have not detected this due to tolerance being enabled, and hiding that the data was missing for 2023. We have removed Tolerance for the [chart](https://ourworldindata.org/grapher/democracy-index-eiu).
/schedule
> 🐛 explore missing countries in EIU data

- apps/housekeeper/cli.py
- scripts/housekeeper.sh
Use correct channel to send chart reviews. Reference: https://github.com/owid/owid-issues/issues/1777
> ✨ correct settings for housekeeper

- etl/steps/data/garden/hmd/2024-11-19/hfd.meta.yml
- etl/steps/data/garden/hmd/2024-11-19/hfd.py
- etl/steps/data/grapher/hmd/2024-11-19/hfd.py
[Tracking issue](https://github.com/owid/owid-issues/issues/1805)
> 📊 add share of women with N children

- apps/housekeeper/charts.py
- apps/housekeeper/cli.py
- apps/housekeeper/utils.py
- etl/grapher/model.py
- etl/slack_helpers.py
(tracking: https://github.com/owid/owid-issues/issues/1777)
Improves housekeeper app by:
- Adding an image preview of the chart
- Adding context to the chart review: Summary of what the chart is about, its edit timeline, general comments.
- Link to a list with similar charts that could replace it.
/schedule
> ✨ provide more context for chart-review by housekeeper

- apps/owidbot/chart_diff.py
- apps/wizard/app_pages/chart_diff/chart_diff.py
- etl/steps/data/garden/biodiversity/2024-01-25/cherry_blossom.py
Add lines
```
Data changes: 1
Metadata changes: 0
```
to owidbot chart-diff
> ✨ Post # of charts with changed data & metadata by owidbot

- apps/chart_sync/admin_api.py
- apps/housekeeper/charts.py
- apps/housekeeper/cli.py
- apps/housekeeper/utils.py
- etl/config.py
- scripts/housekeeper.sh
Housekeeper is not considering charts referenced in Explorers. This info should be shown!
/schedule
> ✨ add chart references from explorers to housekeeper

- dag/families.yml
- etl/steps/data/garden/ons/2025-01-12/divorces.meta.yml
- etl/steps/data/garden/ons/2025-01-12/divorces.py
- etl/steps/data/grapher/ons/2025-01-12/divorces.py
- etl/steps/data/grapher/ons/2025-01-12/divorces_by_year.meta.yml
- etl/steps/data/grapher/ons/2025-01-12/divorces_by_year.py
- etl/steps/data/meadow/ons/2025-01-12/divorces.py
- snapshots/ons/2025-01-12/divorces.py
- snapshots/ons/2025-01-12/divorces.xlsx.dvc
hi @spoonerf! pretty straightforward PR but just wanted to see what you think about this new way of plotting the data on this [chart](http://staging-site-ons-divorces/admin/charts/4347/edit). I think it's a bit easier to read than the old version but wanted to hear a second opinion.
> 📊 marriages and divorces: add ONS divorce data

- etl/grapher/to_db.py
Added a link to the dataset in grapher to the log output when running a grapher step. 
If this is not useful for anybody but me, I am also happy not to merge.
> ✨ link to data set when running grapher step

- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/app_pages/similar_charts/app.py
- apps/wizard/app_pages/similar_charts/scoring.py
- apps/wizard/utils/components.py
Fix https://github.com/owid/etl/issues/3848
> 🐛 url_persist in anomalist

- apps/chart_animation/cli.py
- apps/wizard/app.py
- apps/wizard/app_pages/chart_animation.py
- apps/wizard/app_pages/dataset_preview/app.py
- apps/wizard/app_pages/harmonizer.py
- apps/wizard/app_pages/producer_analytics.py
- apps/wizard/cli.py
- apps/wizard/utils/__init__.py
- tests/apps/wizard/app_pages/test_apps.py
- Add tests to Wizard
- Fix bug in `producer analytics`
- Add warning message if generating GIF animation (MP4 is preferred)
- Add profiler
- Fix bug in Harmonizer (prevented from correct execution in remote)
> ✨ add wizard tests, bug fixes, other minor additions

- etl/steps/data/garden/excess_mortality/latest/excess_mortality/excess_mortality.meta.yml
- etl/steps/data/garden/excess_mortality/latest/excess_mortality/input.py
- etl/steps/data/grapher/excess_mortality/latest/excess_mortality.py
Minor upgrades in xm pipeline
/schedule
> 🐛 fix date processing in grapher

- etl/steps/data/garden/demography/2025-01-20/deaths.meta.yml
Minor typo in metadata. Should cite HMD and not HFD.
/schedule
> 🐛 fix dataset name hfd -> hmd

- docs/guides/sharing-external.md
Added instructions for how to share work with external people. Feel free to update it if you find something unclear.
> 📜 Sharing private work with external people

- etl/steps/data/garden/agriculture/2024-05-23/daily_calories_per_person.meta.yml
Fix typo [pointed out](https://owid.slack.com/archives/C03NV9Z3YSV/p1737483263463419) by Bobbie.
> 📊 agriculture: fix typo in agriculture key description

- etl/steps/data/garden/usgs/2024-07-15/historical_statistics_for_mineral_and_material_commodities.py
Fix USGS data issue with rare earths' unit value.
> 📊 minerals: Fix minerals unit value issues

- etl/steps/data/garden/bgs/2024-07-09/notes_edited.yml
- etl/steps/data/garden/bgs/2024-07-09/notes_original.yml
- etl/steps/data/garden/bgs/2024-07-09/world_mineral_statistics.py
- etl/steps/data/garden/minerals/2024-07-15/minerals.meta.yml
- etl/steps/data/garden/minerals/2024-07-15/minerals.py
- etl/steps/data/garden/usgs/2024-07-15/historical_statistics_for_mineral_and_material_commodities.py
- etl/steps/data/garden/usgs/2024-07-15/mineral_commodity_summaries.py
Fix missing historical unit value USGS data for chromium.
> 📊 minerals: Fix issue with chromium

- dag/animal_welfare.yml
- dag/archive/animal_welfare.yml
Small improvements on fish data as suggested by data providers.
> 📊 animal_welfare: Small improvements to animal welfare data

- etl/steps/data/garden/un/2024-07-25/refugee_data.meta.yml
Editing FASTT of UNHCR indicators to make them clearer - see also [this slack message about user feedback](https://owid.slack.com/archives/C03NV9Z3YSV/p1737745715257679).
> ✨ UNHCR FASTT

- etl/steps/data/garden/ember/2024-11-20/european_wholesale_electricity_prices.meta.yml
- etl/steps/data/garden/eurostat/2024-11-05/gas_and_electricity_prices.meta.yml
- etl/steps/export/multidim/energy/latest/energy_prices.py
- etl/steps/export/multidim/energy/latest/energy_prices.yml
Various improvements and fixes on the energy prices mdim page.
> 📊 energy: Improvements on energy prices

- etl/steps/data/garden/eurostat/2024-11-05/gas_and_electricity_prices.meta.yml
- etl/steps/export/multidim/energy/latest/energy_prices.py
- etl/steps/export/multidim/energy/latest/energy_prices.yml
Improve energy prices mdim page.
> 📊 energy: Improve energy prices mdim

- dag/main.yml
- etl/steps/__init__.py
- etl/steps/data/explorers/faostat/2023-06-12/food_explorer.py
- etl/steps/data/explorers/faostat/latest/food_explorer.py
- etl/steps/data/explorers/poverty_inequality/latest/poverty_inequality.py
- etl/steps/data/explorers/wid/latest/world_inequality_database.py
- etl/steps/data/garden/who/2024-05-20/vehicles.py
- etl/steps/data/grapher/research_development/2024-05-20/patents_wdi_unwpp.py
- etl/steps/data/meadow/lis/2024-06-13/luxembourg_income_study.py
- Fix all cases of setting dataset short name
- Fix a bug with CSV formats from explorers when using PREFER_DOWNLOAD=1
> 🔨 Stop setting dataset short_name

- etl/steps/data/garden/eurostat/2024-11-05/gas_and_electricity_prices.meta.yml
- etl/steps/export/multidim/energy/latest/energy_prices.yml
Minor improvements, as [suggested by Ed](https://owid.slack.com/archives/C0193RW5E2J/p1738153015381259?thread_ts=1738141249.991029&cid=C0193RW5E2J).
> 📊 energy: Energy prices minor tweaks

- docs/architecture/metadata/structuring-yaml.md
- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_cause.meta.yml
- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_child_mortality.meta.yml
- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_drug_risk.meta.yml
- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_prevalence.meta.yml
- etl/steps/data/garden/ihme_gbd/2024-05-20/gbd_risk.meta.yml
- etl/steps/data/garden/who/2024-07-30/ghe.meta.yml
> 🐛 fix hiv/aids lowercase

- etl/steps/data/garden/who/latest/avian_influenza_ah5n1.py
- etl/steps/data/meadow/who/latest/avian_influenza_ah5n1.py
- snapshots/who/latest/avian_influenza_ah5n1.csv.dvc
- snapshots/who/latest/avian_influenza_ah5n1.py
- tests/apps/wizard/app_pages/test_apps.py
Fixes https://github.com/owid/owid-issues/issues/1837
/schedule
> 📊 H5N1 data

- dag/archive/fasttrack.yml
- dag/archive/main.yml
- dag/fasttrack.yml
- dag/main.yml
- dag/technology.yml
> Refactor archive clean datasets

- snapshots/un/2024-07-12/un_wpp.py
- snapshots/un/2024-07-12/un_wpp_deaths_estimates.csv.dvc
- snapshots/un/2024-07-12/un_wpp_deaths_medium.csv.dvc
- snapshots/un/2024-07-12/un_wpp_demographic_indicators.xlsx.dvc
- snapshots/un/2024-07-12/un_wpp_fertility.csv.dvc
- snapshots/un/2024-07-12/un_wpp_fertility_single_age.csv.dvc
- snapshots/un/2024-07-12/un_wpp_population_constant_fertility.csv.dvc
- snapshots/un/2024-07-12/un_wpp_population_estimates.csv.dvc
- snapshots/un/2024-07-12/un_wpp_population_high.csv.dvc
- snapshots/un/2024-07-12/un_wpp_population_low.csv.dvc
- snapshots/un/2024-07-12/un_wpp_population_medium.csv.dvc
* Fixed broken link in WPP description.
* Following Patrick's suggestion, I added useful links in the descriptions of the WPP snapshots.
@lucasrodes do you agree on these changes? This description field is not the most prominent on data pages, but I think creating a key description with those resources would be complicated and maybe not the best option. Please let me know if you think of a better solution.
**WARNING**: Merge at the end of the day (long ETL run).
> 📊 demography: Fix broken link in WPP and add useful links

- etl/steps/data/garden/un/2024-09-16/long_run_child_mortality.py
Removing regional estimates for child mortality before 1950 as a hotfix for this [drop in asia](https://owid.slack.com/archives/C03NV9Z3YSV/p1738774206362549)
> 🐛 Child mortality anomalies

- snapshots/worldbank_wdi/2025-01-24/wdi.py
- snapshots/worldbank_wdi/2025-01-24/wdi.zip.dvc
I was reviewing our WDI pipeline and thought of a few small improvements.
**WARNING**: Merge at the end of the day, since it may trigger a long ETL run.
> 📊 Small improvements to WDI pipeline

- dag/main.yml
- etl/steps/data/garden/language/2024-07-17/ethnologue.meta.yml
- etl/steps/data/garden/language/2024-07-17/ethnologue.py
I made it non-redistributable in a previous PR but it didn't seem to kick in until this one?
> 🐛 make languages non-redistributable

- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.meta.override.yml
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.py
Calculate GDP in constant 2021 US$ to compare it to GDP in int-$ in 2021 prices for this article: https://github.com/owid/owid-issues/issues/1151
> 📊 Create GDP estimates in constant 2021 US$

- schemas/multidim-schema.json
A fix for the issue(s) created in #3932
> Fix mdim grapher schema

- etl/steps/data/garden/eurostat/2025-02-03/gas_and_electricity_prices.py
We are imposing that certain price components need to always be informed. However, this condition was failing in some cases. This lead to Germany having a sudden increase in household electricity price from 2018 to 2019. But in reality, the prices for 2017 and 2018 were simply incomplete (the taxes component was missing), so they should not be there.
This PR fixes that issue, and now those two misleading data points for 2017 and 2018 are removed.
> 📊 energy: Check energy prices issues

- dag/climate.yml
- etl/steps/data/grapher/climate/2025-01-07/surface_global_monthly_anomaly.meta.yml
- etl/steps/data/grapher/climate/2025-01-07/surface_temperature_annual_average.py
- snapshots/climate/2025-02-07/surface_temperature.py
- snapshots/climate/2025-02-07/surface_temperature.zip.dvc
hey @Marigold! we could probably set this code to be automatically updated until next year if that's still something you are keen on doing?
> 📊 climate: monthly era5 surface temperature update

- docs/architecture/metadata/structuring-yaml.md
- etl/helpers.py
- etl/multidim.py
- etl/steps/data/garden/covid/latest/shared.py
- etl/steps/export/multidim/energy/latest/energy_prices.py
- lib/catalog/owid/catalog/utils.py
Fixes https://github.com/owid/etl/issues/3976
- Validate mdim config against JSON schema
- Deprecate `TODAY` parameter in YAML files (it has been causing problems in validation and is no longer needed)
> ✨ Validate mdim config

- apps/wizard/etl_steps/cookiecutter/garden/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.meta.yml
Fix for https://github.com/owid/etl/issues/3989
> ✨ Add non_redistributable: true as defualt to private steps

- etl/steps/data/garden/emissions/2025-02-12/ceds_air_pollutants.py
Minor code improvements, to better handle missing values (should not affect the data).
> 📊 emissions: Minor fixes in air pollution data

- dag/archive/fasttrack.yml
- dag/fasttrack.yml
Archive unused fasttrack CEDS steps.
> 📊 emissions: Archive unused steps

- etl/steps/data/garden/poverty_inequality/2025-01-22/inequality_comparison.meta.yml
- etl/steps/data/garden/poverty_inequality/2025-01-22/inequality_comparison.py
Issue https://github.com/owid/owid-issues/issues/976
> ✨ Add Palma ratio to inequality comparison file

- dag/archive/main.yml
- dag/archive/space.yml
- dag/space.yml
- etl/steps/data/garden/space/2025-03-04/near_earth_asteroids.meta.yml
- etl/steps/data/garden/space/2025-03-04/near_earth_asteroids.py
- etl/steps/data/grapher/space/2025-03-04/near_earth_asteroids.py
- etl/steps/data/meadow/space/2025-03-04/near_earth_asteroids.py
- snapshots/space/2025-03-04/near_earth_asteroids.csv.dvc
- snapshots/space/2025-03-04/near_earth_asteroids.py
Update near-earth asteroids data (1 chart).
> 📊 space: Update Near-Earth Asteroids data

- dag/archive/main.yml
- dag/archive/survey.yml
- dag/survey.yml
- etl/steps/data/garden/survey/2025-03-04/dietary_choices_uk.meta.yml
- etl/steps/data/garden/survey/2025-03-04/dietary_choices_uk.py
- etl/steps/data/grapher/survey/2025-03-04/dietary_choices_uk.py
- etl/steps/data/meadow/survey/2025-03-04/dietary_choices_uk.py
- snapshots/survey/2025-03-04/dietary_choices_uk.py
- snapshots/survey/2025-03-04/dietary_choices_uk.xlsx.dvc
Update YouGov data on the dietary choices of Brits (2 charts).
> 📊 survey: Update dietary choices of Brits data

- dag/archive/fasttrack.yml
- dag/fasttrack.yml
- etl/steps/data/garden/oecd/2025-02-19/official_development_assistance.meta.yml
- etl/steps/data/garden/oecd/2025-02-19/official_development_assistance.py
Main issue https://github.com/owid/owid-issues/issues/1893#issuecomment-2720086923
> ✨ Add total indonor aid in OECD ODA

- dag/archive/climate.yml
- dag/climate.yml
- etl/collections/explorer_migration.py
- etl/helpers.py
- etl/steps/data/garden/climate/2025-01-21/climate_change_impacts.meta.yml
- etl/steps/data/garden/climate/2025-01-21/sea_surface_temperature.meta.yml
- etl/steps/data/garden/met_office_hadley_centre/2025-01-21/near_surface_temperature.meta.yml
- etl/steps/export/explorers/climate/latest/climate_change.config.yml
- etl/steps/export/explorers/climate/latest/climate_change.py
* Transition [climate change impacts](https://ourworldindata.org/explorers/climate-change) csv-based manually created explorer [into an ETL export/explorer](http://staging-site-data-climate-change-explorer/admin/explorers/preview/climate-change).
* Ensure explorer/mdim config cites only steps that are in the DAG as dependencies of the current step.
@lucasrodes there's no need to inspect the metadata changes (this is not a very prominent explorer, and I have basically copied things from the old into the new explorer, adjusting a few minor things, and just changed one missing indicator). But please have a look at the changes in `PathFinder`. I ensured that paths added to config should be in the DAG (but I'm not sure if there is a better way to achieve that). Thanks!
> 📊 climate: Fix climate change explorer

- etl/steps/export/explorers/un/latest/un_wpp.manual.config.yml
Add relative view to "population by broad age group" explorer views. [Reference](https://owid.slack.com/archives/C03NV9Z3YSV/p1741809318519409)
> 🎉 minor tweak to population explorer

- etl/steps/export/explorers/who/latest/monkeypox.config.yml
I forgot to update the config of the Mpox explorer to reflect the changes for `checkbox`.
> 🐛 upgrade missing checkboxes in explorers

- etl/collections/explorer.py
- etl/collections/explorer_migration.py
> 🔨 minor fixes etl collections

- etl/command.py
- etl/scripts/archive/run_all_snapshots/run_all_snapshots.py
- etl/snapshot.py
- snapshots/agriculture/2023-10-04/share_of_agriculture_in_gdp.py
- snapshots/animal_welfare/2023-09-01/chick_culling_laws.py
- snapshots/animal_welfare/2023-09-05/bullfighting_laws.py
- snapshots/animal_welfare/2024-06-04/bullfighting_laws.py
- snapshots/climate/2024-01-31/climate_change_impacts.py
- snapshots/climate/2024-03-11/climate_change_impacts.py
- snapshots/climate/2024-04-17/climate_change_impacts.py
- snapshots/climate/2024-05-20/climate_change_impacts.py
- snapshots/climate/2024-07-23/climate_change_impacts.py
- snapshots/climate/2024-09-30/climate_change_impacts.py
- snapshots/emissions/2024-04-08/national_contributions.py
- snapshots/gcp/2023-09-28/global_carbon_budget.py
- snapshots/gcp/2023-12-05/global_carbon_budget.py
- snapshots/gcp/2023-12-12/global_carbon_budget.py
- snapshots/met_office_hadley_centre/2023-10-18/near_surface_temperature.py
- snapshots/met_office_hadley_centre/2024-03-04/near_surface_temperature.py
- snapshots/met_office_hadley_centre/2024-05-20/near_surface_temperature.py
Based on https://github.com/owid/etl/pull/3352.
Try running all snapshots, upload them to S3 and check how many of them have updated data.
- This runs even outdated snapshots that might already have a newer version available. We should [prune them](https://github.com/owid/etl/issues/3364) and then run this again
>  :broom: Rerun all snapshots

- dag/climate.yml
@veronikasamborska1994 just letting you know that I'm updating one of the dependencies (FAOSTAT, used to get land areas) of the weekly wildfires dataset, in case you notice anything odd. If so, please let me know, thanks!
> 📊 climate: Update weekly fires dependency on FAOSTAT

- apps/wizard/utils/chart_config.py
- etl/config.py
- etl/files.py
- schemas/multidim-schema.json
Updates the Grapher schema version to 007. `map.projection` was renamed to `map.region`.
Waiting for https://github.com/owid/owid-grapher/pull/4707 to be reviewed and merged.
> 🐝 update grapher schema version

- dag/health.yml
- etl/steps/data/garden/ihme_gbd/2025-03-31/gbd_child_mortality_leading_causes.meta.yml
- etl/steps/data/garden/ihme_gbd/2025-03-31/gbd_child_mortality_leading_causes.py
- etl/steps/data/grapher/ihme_gbd/2025-03-31/gbd_child_mortality_leading_causes.py
hi @spoonerf ! what do you think about adding this chart on [leading causes of deaths in children](http://staging-site-child-mort/admin/charts/8579/edit)? I think it tells a pretty interesting story that you can't otherwise see in all our other charts on causes of deaths in children.
> 📊 child mortality: GBD add indicators with the leading causes of death

- etl/steps/data/garden/animal_welfare/2025-03-26/animals_used_for_food.py
Ensure the original descriptions from FAOSTAT are used in the animal welfare explorer.
> 📊 animal_welfare: Improve animal welfare data

- etl/scripts/faostat/update_snapshots_metadata.py
- etl/snapshot.py
- snapshots/animal_welfare/2024-06-04/bullfighting_laws.csv.dvc
- snapshots/animal_welfare/2024-06-04/bullfighting_laws.py
- snapshots/shift/2023-12-12/energy_production_from_fossil_fuels.py
- snapshots/un/2023-08-16/un_sdg.py
- snapshots/un/2024-08-27/un_sdg.py
- snapshots/who/2024-08-06/mortality_database_cancer.py
- snapshots/who/2025-01-17/mortality_database_vaccine_preventable.py
Fixes https://github.com/owid/etl/issues/4165
- Merge `add_snapshot` with `create_snapshot`
- Call `.save` in `create_snapshot`
> :hammer: Refactor snapshot methods

- etl/steps/data/garden/oecd/2025-02-19/official_development_assistance.meta.yml
From discussion here: https://github.com/owid/owid-issues/issues/1620#issuecomment-2760729846
> ✨ OECD ODA: add reference to deflator

- etl/steps/data/garden/lgbt_rights/2025-04-07/equaldex.meta.yml
- etl/steps/data/garden/lgbt_rights/2025-04-07/equaldex.py
One typo and one propagation issue mentioned [here](https://owid.slack.com/archives/C46U9LXRR/p1744109863123159).
> 🐛 fix tiny errors in Equaldex

- apps/wizard/app_pages/explorer_diff/app.py
- apps/wizard/app_pages/explorer_diff/utils.py
- apps/wizard/app_pages/mdim_diff/app.py
- apps/wizard/config/config.yml
- etl/grapher/model.py
Copy Explorer diff and adjust it for MDIM cases. It doesn't show an actual mdim chart, but it'll tell you when configs between staging and production differ.
> 🎉 Add Mdim Diff

- etl/steps/export/multidim/health/latest/causes_of_death.py
Sort choices in dimension `age`.
Context: [slack discussion](https://owid.slack.com/archives/C071F90MD0X/p1743673375315739)
[MDIM demo](http://staging-site-style-mdim-causes-death/admin/grapher/health%2Flatest%2Fcauses_of_death%23causes_of_death)
> 💄 mdim causes of death order

- snapshots/artificial_intelligence/2025-03-12/epoch.csv.dvc
- snapshots/artificial_intelligence/2025-03-12/epoch_compute_intensive.csv.dvc
hey @Marigold ! It's getting a bit tedious to copy the code and update all of these datasets and charts every month so I am using your solution here :) hope that's ok!
> 📊 AI: update Epoch datasets

- dag/archive/main.yml
- dag/artificial_intelligence.yml
- dag/main.yml
- dag/tourism.yml
- etl/steps/data/garden/bls/2025-04-12/us_consumer_prices.meta.yml
- etl/steps/data/garden/bls/2025-04-12/us_consumer_prices.py
- etl/steps/data/grapher/bls/2025-04-12/us_consumer_prices.py
- snapshots/bls/2025-04-12/us_consumer_prices.csv.dvc
- snapshots/bls/2025-04-12/us_consumer_prices.py
hi @edomt! I think you usually update this dataset, but I am working on the AI index report updates where some charts rely on this dataset, so I just wanted to get the latest data. The code is pretty much the same as yours. Garden and grapher steps are the same, and I just removed the meadow step since it didn't really do much. The only thing that's different is that I couldn't run your version of snapshot  - not sure if something about their data access has changed since last year. So the snapshot code is different to your last update.
> 📊 update US CPI

- dag/archive/war.yml
- dag/war.yml
- etl/data_helpers/misc.py
- etl/steps/data/garden/war/2025-04-18/peace_diehl.meta.yml
- etl/steps/data/garden/war/2025-04-18/peace_diehl.py
- etl/steps/data/grapher/war/2025-04-18/peace_diehl.py
- etl/steps/data/meadow/war/2025-04-18/peace_diehl.py
- snapshots/war/2025-04-18/peace_diehl.py
- snapshots/war/2025-04-18/peace_diehl.zip.dvc
Add new version of "Peace data" by Diehl et al.
Tracking issue: https://github.com/owid/owid-issues/issues/1811
> 📊 update peace data by Diehl

- etl/steps/data/garden/war/2025-04-18/peace_diehl.meta.yml
Fix year in dataset title; forgot to change `2023` → `2025`.
/schedule
> 💄 fix dataset title

- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.meta.override.yml
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.meta.yml
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.py
adding custom energy variables to automatically update as a part of WDI as described in the issue [here](https://github.com/owid/owid-issues/issues/1916)
> 📊 energy: adding custom variables to WDI

- etl/steps/data/garden/faostat/2025-03-17/faostat_rl.meta.yml
Improve public title of [this data page](https://ourworldindata.org/grapher/land-area-hectares).
> 📊 Improve title public of land area

- etl/steps/export/multidim/covid/latest/covid.py
- etl/steps/export/multidim/dummy/latest/dummy.py
> 🐛 wrong argument name

- scripts/exclude_archived_steps.py
Improve `make vscode-exclude-archived`
- If a file has been modified recently (1 month), don't exclude it
- Update all relevant files, before this, we left unused ones or those in WIP
- Create backup
> ✨ Improve vscode-exclude-archived

- dag/archive/main.yml
- dag/main.yml
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.meta.override.yml
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.meta.yml
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.py
hi @edomt! the data hasn't been updated but I am adding this code to the wdi script instead so it can be automatically updated whenever we update the wdi. I think it's a simpler way of doing this but let me know if you disagree? don't need to actually review the code as I can ask someone else to do it
> 📊 R&D: update data on patents and articles

- dag/archive/main.yml
- dag/main.yml
- etl/steps/data/garden/itopf/2025-05-05/oil_spills.meta.yml
- etl/steps/data/garden/itopf/2025-05-05/oil_spills.py
- etl/steps/data/grapher/itopf/2025-05-05/oil_spills.py
- etl/steps/data/meadow/itopf/2025-05-05/oil_spills.py
- snapshots/itopf/2025-05-05/oil_spills.pdf.dvc
- snapshots/itopf/2025-05-05/oil_spills.py
pretty much the same code as last year
> 📊 oil spills: update ITOPF dataset

- docs/api/datasette.md
- mkdocs.yml
Add a section about querying ETL catalog with DuckDB and Datasette.
> 📜 How to query ETL catalog with DuckDB

- apps/wizard/app.py
- apps/wizard/app_pages/dashboard/app.py
- apps/wizard/config/config.yml
- Rename "ETL dashboard" to "Step updater"
- Rename sections:
- "ETL steps" → "Create": Apps to create steps (snapshot, data, fast-track)
- "Data curation" → "Update": Apps to update steps (step updater, indicator updater, *diff)
- Move "Anomalist" to next section on "Data tools"
> ✨ clarify some apps in wizard

- etl/steps/data/grapher/fasttrack/latest/war_deaths_by_war_mars.meta.yml
- etl/steps/data/grapher/fasttrack/latest/war_deaths_by_war_mars.py
Work on https://github.com/owid/owid-issues/issues/1990
/schedule
> 💄 edit sino-japanese war name

- apps/wizard/app_pages/chart_diff/app.py
- etl/analytics.py
- etl/config.py
* Minor enhancements related to analytics.
* Fix bug that made chart diff break if no posts references were found.
> 🐛 Minor improvements in analytics and fixed bug

- etl/grapher/to_db.py
- etl/steps/data/garden/wb/2025-04-08/world_bank_pip.py
- lib/catalog/owid/catalog/meta.py
- lib/catalog/owid/catalog/utils.py
@paarriagadap this should fix (some?) of your issues in `data-world-bank-pip`. Merge it to your PR whenever you want. Let me know if you see anything odd.
> :bug: Fix jinja templates

- apps/owidbot/grapher.py
see https://github.com/owid/ops/pull/290
> 🎉 owidbot: include links to archived pages

- etl/collection/core/combine.py
- etl/collection/model/core.py
- etl/collection/model/dimension.py
Support `group` property in Choices. 
/schedule
> ✨ support group in collection dimensions

- dag/war.yml
- etl/collection/model/core.py
- etl/steps/export/multidim/war/latest/mars.config.yml
- etl/steps/export/multidim/war/latest/mars.py
- etl/steps/export/multidim/war/latest/ucdp_prio.config.yml
- etl/steps/export/multidim/war/latest/ucdp_prio.py
- Edits on existing Mars MDIM
- Add new UCDP/PRIO MDIM
/schedule
> 📊 mdims: war and peace

- etl/steps/data/garden/excess_mortality/latest/excess_mortality/__init__.py
- etl/steps/data/garden/excess_mortality/latest/excess_mortality/excess_mortality.meta.yml
- etl/steps/data/garden/excess_mortality/latest/excess_mortality/input.py
- etl/steps/data/garden/excess_mortality/latest/excess_mortality/process.py
- etl/steps/data/garden/excess_mortality/latest/hmd_stmf.py
- etl/steps/data/garden/excess_mortality/latest/wmd.py
- etl/steps/data/grapher/excess_mortality/latest/excess_mortality.py
- snapshots/excess_mortality/latest/hmd_stmf.csv.dvc
- snapshots/excess_mortality/latest/wmd.csv.dvc
Helpful text for future self
/schedule
> 📊 Data: add clarification notes on excess-mortality scripts

- etl/collection/exceptions.py
- etl/collection/model/core.py
- etl/collection/model/view.py
- etl/collection/utils.py
- etl/steps/export/multidim/corruption/latest/corruption_barometer.py
- etl/steps/export/multidim/war/latest/mars.config.yml
- etl/steps/export/multidim/war/latest/mars.py
- etl/steps/export/multidim/war/latest/ucdp.config.yml
- etl/steps/export/multidim/war/latest/ucdp.py
- etl/steps/export/multidim/war/latest/ucdp_prio.config.yml
- etl/steps/export/multidim/war/latest/ucdp_prio.py
- tests/test_collections.py
> ✨ work on war mdims

- snapshots/who/latest/avian_influenza_ah5n1.csv.dvc
Issue: https://github.com/owid/owid-issues/issues/2007
/schedule
> 📊 update h5n1 data

- .github/workflows/publish-owid-catalog.yml
> 🐛 fix publish catalog workflow

- etl/steps/data/garden/democracy/2025-03-17/vdem/vdem.meta.yml
- etl/steps/data/garden/democracy/2025-03-17/vdem/vdem_aggregate.py
- etl/steps/data/garden/democracy/2025-03-17/vdem/vdem_clean.py
- etl/steps/data/garden/democracy/2025-03-17/vdem/vdem_impute.py
Tracking issue: https://github.com/owid/owid-issues/issues/1988
/schedule
> 📊 work on VDEM

- etl/steps/data/garden/democracy/2025-03-05/eiu.meta.yml
- etl/steps/data/garden/democracy/2025-03-05/eiu.py
- etl/steps/data/grapher/democracy/2025-03-05/eiu.py
Tracking issue: https://github.com/owid/owid-issues/issues/1980
> ✨ eiu regional aggregates

- snapshots/who/2024-12-10/vaccination_coverage.xlsx.dvc
Hey @Marigold, thought I would give this cool new feature a try! Is this all I need to do?
> 📊 who vaccine auto update

- snapshots/climate/2025-04-07/sst.csv.dvc
- snapshots/climate/2025-04-07/surface_temperature.zip.dvc
@Marigold probably being v stupid but here I can't see any charts in chart-diff even though they have been updated
> 🤖 Autoupdate: Surface temperature

- dag/education.yml
- etl/steps/data/garden/education/2025-06-09/literacy_1451_1800.countries.json
- etl/steps/data/garden/education/2025-06-09/literacy_1451_1800.meta.yml
- etl/steps/data/garden/education/2025-06-09/literacy_1451_1800.py
- etl/steps/data/grapher/education/2025-06-09/literacy_1451_1800.py
- etl/steps/data/meadow/education/2025-06-09/literacy_1451_1800.py
- snapshots/education/2025-06-09/literacy_1451_1800.pdf.dvc
- snapshots/education/2025-06-09/literacy_1451_1800.py
one of several historic datasets that we'll want to combine with more recent literacy data
> 📊 literacy: add Buringh and van Zanden historical literacy dataset

- apps/wizard/app_pages/chart_diff/chart_diff_show.py
- etl/steps/data/garden/animal_welfare/2024-06-04/bullfighting_laws.meta.yml
Fixes https://github.com/owid/etl/issues/4552
> 🐛 Fix chart diff metadata comparison

- etl/analytics.py
- etl/scripts/create_report_for_data_producer.py
* Fix issue when fetching chart titles in analytics module.
* Improve script to generate data providers reports, following Ed's feedback.
> ✨ Improve data providers report

- apps/wizard/utils/chart_config.py
- docs/architecture/metadata/reference/collections.md
- etl/docs.py
- etl/files.py
- etl/steps/export/multidim/health/latest/vaccination_introductions.py
- lib/catalog/owid/catalog/meta.py
- lib/catalog/tests/test_meta.py
- schemas/explorer-schema.json
- schemas/multidim-schema.json
- scripts/generate_schema_types.py
New grapher schema https://github.com/owid/owid-grapher/pull/5006
> 🐝 Bump default grapher schema to 008

- etl/steps/data/garden/democracy/2025-03-05/eiu.meta.yml
> 💄 eiu key points

- etl/steps/export/multidim/war/latest/mars.py
- etl/steps/export/multidim/war/latest/ucdp.py
- etl/steps/export/multidim/war/latest/ucdp_prio.py
- snapshots/cdc/latest/measles_cases.json.dvc
> 💄 faceting in war mdims

- .claude/settings.json
- .gitignore
- CLAUDE.md
It's [recommended](https://www.anthropic.com/engineering/claude-code-best-practices) to add `CLAUDE.md` and `.claude/settings.json` instructions to have them shared for everyone and use `CLAUDE.local.md` as your personal instructions.
I plan to add more instructions to `CLAUDE.md` soon.
> 🐝 Unignore CLAUDE.md and ignore CLAUDE.local.md

- apps/anomalist/detectors.py
Fix infinite scale score when the new variable becomes a constant (which was making chart diff fail in [this PR](https://github.com/owid/etl/pull/4654)).
> 🐛 Fix anomalist unbound scale score

- etl/steps/__init__.py
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.py
- etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.sources.json
- Fix WDI source
- Don't call sys.exit(1) when a step process fails
> 🐛 Fix WDI source

- apps/housekeeper/utils.py
- apps/utils/gpt.py
Minor tweaks to system prompt
/schedule
> 🐛 housekeeper-debug

- etl/steps/data/garden/democracy/2025-03-17/vdem/vdem.meta.yml
_From https://github.com/owid/owid-issues/issues/1988#issuecomment-3061303749_
-   This index, produced by Varieties of Democracy (V-Dem), is useful if you are interested in big and small differences in democracy, want scores for almost all countries, and prefer a narrow understanding of democracy. For data that focuses on big differences in political systems or has a broad understanding of democracy, other sources will be more useful. You can explore these alternatives in our [Key Democracy Charts](https://ourworldindata.org/democracy#all-charts) and [Democracy Data Explorer](https://ourworldindata.org/explorers/democracy?Dataset=Varieties+of+Democracy&Metric=Electoral+democracy&Sub-metric=Main+index&country=ARG~AUS~BWA~CHN~OWID_WRL).
-   It takes a narrow view of democracy by focusing …
> ✨ Improve the metadata of V-Dem charts/indicators

- etl/steps/data/garden/who/2024-12-10/vaccination_coverage.meta.yml
Improved the wording in the meta descriptions for RCV1 and PCV3 antigens to enhance clarity and accuracy regarding vaccine recommendations and coverage estimates.
> 🐝 Update vaccine coverage meta descriptions for clarity

- etl/steps/data/garden/un/2025-04-25/long_run_child_mortality.py
Hey @pabloarosado, 
Just a quick experiment I did with Claude based on our conversation yesterday. I asked it to come up with some sanity checks based on the information in the .yml file, and I think it came up with some pretty sensible stuff, I thought you'd be interested to see. 
I was quite impressed that it came up with reasonable estimates of what a max and min for each continent would be!
> ✨ Claude suggested sanity checks

- apps/housekeeper/utils.py
- apps/pr/cli.py
- apps/utils/gpt.py
- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/app_pages/chart_diff/chart_diff_show.py
- apps/wizard/app_pages/datainsight_robot.py
- apps/wizard/app_pages/expert/app.py
- apps/wizard/scripts/news.py
GPT-5 was released yesterday, let's set it as our default model across our tooling.
> ✨ add gpt-5

- apps/wizard/app_pages/chart_animation.py
- apps/wizard/app_pages/chart_diff/app.py
- apps/wizard/app_pages/dashboard/operations.py
- apps/wizard/app_pages/explorer_diff/app.py
- apps/wizard/app_pages/fasttrack/app.py
- apps/wizard/app_pages/fasttrack/process.py
- apps/wizard/app_pages/indicator_upgrade/charts_update.py
- apps/wizard/app_pages/indicator_upgrade/dataset_selection.py
- apps/wizard/app_pages/indicator_upgrade/indicator_mapping.py
- apps/wizard/app_pages/insight_search/app.py
- apps/wizard/app_pages/mdim_diff/app.py
- apps/wizard/etl_steps/collection.py
- apps/wizard/etl_steps/data.py
- apps/wizard/etl_steps/snapshot.py
- apps/wizard/home.py
- apps/wizard/utils/components.py
- pyproject.toml
- uv.lock
> 🐝 bump up streamlit

- .claude/commands/check.md
- owid_mcp/data_utils.py
- owid_mcp/indicators.py
- owid_mcp/semantic_search.py
- tests/owid_mcp/test_server.py
Use more efficient data format in `fetch_indicator_data` and split it into `_data` and `_metadata`.
> ✨ Optimize MCP context

- .claude/commands/update-dataset.md
- CLAUDE.md
- etl/datadiff.py
- etl/snapshot_command.py
- More compact datadiff with country flag
- Better instructions for dataset updates
> :sparkles: Better instructions for updating data

- etl/steps/data/grapher/regions/2023-01-01/regions.py
> 📊 tweak un regions indicator

- apps/wizard/app_pages/dashboard/app.py
- apps/wizard/app_pages/dashboard/utils.py
- pyproject.toml
- uv.lock
Fixes https://github.com/owid/etl/issues/4919 by downgrading `streamlit-aggrid` version from `1.1.8` → `1.1.7`.
> 🐛 fix step upgrader

- apps/wizard/app_pages/anomalist/app.py
- apps/wizard/app_pages/chart_diff/chart_diff_show.py
- apps/wizard/app_pages/datainsight_robot.py
- docs/architecture/metadata/reference/collections.md
- docs/guides/schema-management.md
- etl/config.py
- etl/files.py
- etl/steps/data/garden/gcp/2024-06-20/global_carbon_budget.meta.yml
- etl/steps/data/garden/gcp/2024-11-13/global_carbon_budget.meta.yml
- etl/steps/data/garden/gcp/2024-11-21/global_carbon_budget.meta.yml
- etl/steps/data/garden/ggdc/2024-04-26/maddison_project_database.meta.yml
- schemas/dataset-schema.json
- schemas/explorer-schema.json
- schemas/multidim-schema.json
- tests/test_metadata_schemas.py
The schema sections are directly copied over from https://files.ourworldindata.org/schemas/grapher-schema.009.json.
> 🔨 update dataset-schema with new colorScale settings

- etl/steps/data/garden/demography/2024-07-15/population.meta.yml
- etl/steps/data/garden/language/2025-09-03/ethnologue.meta.yml
Adding a display name of 'Population' to Population (historical)
/schedule 2025-09-05
> 🐛  Population (historical) display name

- dag/survey.yml
- etl/steps/data/garden/survey/2025-09-12/acceptability_of_uk_farming_practices.meta.yml
- etl/steps/data/garden/survey/2025-09-12/acceptability_of_uk_farming_practices.py
- etl/steps/data/grapher/survey/2025-09-12/acceptability_of_uk_farming_practices.py
- etl/steps/data/meadow/survey/2025-09-12/acceptability_of_uk_farming_practices.py
- snapshots/survey/2025-09-12/acceptability_of_uk_farming_practices.xlsx.dvc
Create snapshot and data steps for a chart on the opinions of Brits on common farming practices.
For more context, see [this issue](https://github.com/owid/owid-issues/issues/2128).
NOTE: I'm waiting for Max's review, it's still unclear if we may end up using it or not, so there's no need for a thorough review.
> 📊 animal_welfare: Add survey data on animal welfare issues

- etl/steps/data/garden/wb/2025-04-14/world_bank_pip.meta.yml
- etl/steps/data/garden/wb/2025-08-07/world_bank_pip.meta.yml
- etl/steps/export/multidim/wb/latest/world_bank_pip.config.yml
Main issue https://github.com/owid/owid-issues/issues/2116
> 💄 Address feedback on poverty MDim

- dag/energy.yml
- etl/steps/data/garden/energy/2025-09-18/historical_energy_costs.meta.yml
- etl/steps/data/garden/energy/2025-09-18/historical_energy_costs.py
- etl/steps/data/grapher/energy/2025-09-18/historical_energy_costs.py
- etl/steps/data/meadow/energy/2025-09-18/historical_energy_costs.py
- snapshots/energy/2025-09-18/historical_energy_costs.xlsx.dvc
Create a dataset for internal research on the prices of useful energy.
> 📊 energy: Dataset on historical LCOE

- etl/steps/data/garden/wb/2025-04-14/world_bank_pip.meta.yml
- etl/steps/data/garden/wb/2025-08-07/world_bank_pip.meta.yml
- etl/steps/export/multidim/wb/latest/world_bank_pip.config.yml
https://github.com/owid/owid-issues/issues/2116
> 💄 Change description_short for multi-indicator views in Poverty MDim

- apps/wizard/etl_steps/cookiecutter/garden/{{cookiecutter.namespace}}/{{cookiecutter.version}}/{{cookiecutter.short_name}}.py
- docs/data/regions.md
- docs/guides/harmonize-countries.md
- etl/data_helpers/geo.py
- etl/helpers.py
- etl/steps/data/garden/animal_welfare/2025-01-23/number_of_farmed_crustaceans.py
- etl/steps/data/garden/irena/2025-07-18/renewable_energy_statistics.py
- etl/steps/data/garden/worldbank_wdi/2025-09-08/wdi.py
* Change paradigm so that handling region aggregates happens from `paths.regions.add_aggregates()` instead of `paths.region_aggregator().add_aggregates()`, and similar for `add_per_capita`.
* Note that the advanced use of multiple aggregators is still possible, e,g, `tb_agg = region.aggregator()`.
* Update examples using the new `RegionAggregator`.
* Update the wizard garden template.
* Update documentation
> ✨ Improve Regions class, update wizard, improve documentation

- etl/grapher/model.py
Depends on https://github.com/owid/owid-grapher/pull/5378
> Add configMd5 to Explorer model
